#!/bin/bash
# Generated by Claude Fable 5 (Anthropic)
# fishiris container entrypoint: PostgreSQL (timescale image's own entrypoint, in the
# background) → schema + COPY of the exported session tables (first start only) →
# Grafana (provisioned T0 dashboard + PostgreSQL datasource) → FISH viz server.
# PUBLIC_VIZ_URL / PUBLIC_GRAFANA_URL are substituted into the landing page and the
# dashboard so links work from a browser on another machine.
set -u
log(){ echo "[fishiris] $*"; }

# 1. PostgreSQL --------------------------------------------------------------
docker-entrypoint.sh postgres -c shared_buffers=512MB -c work_mem=64MB -c max_wal_size=2GB > /var/log/postgres.log 2>&1 &
for i in $(seq 1 120); do pg_isready -h localhost -U fish -d fish >/dev/null 2>&1 && break; sleep 1; done
export PGPASSWORD=fish
PSQL="psql -h localhost -U fish -d fish -Atq"
if [ "$($PSQL -c "SELECT count(*) FROM information_schema.tables WHERE table_name='graph_nodes'")" != "1" ]; then
  log "creating schema"
  $PSQL -f /opt/fish/init_fish_pg.sql > /var/log/schema.log 2>&1 || log "WARN: schema script reported errors (see /var/log/schema.log)"
fi
for sdir in /opt/fish/data/fish_*; do
  [ -d "$sdir" ] || continue
  SID=$(basename "$sdir")
  if [ "$($PSQL -c "SELECT count(*) FROM sessions WHERE session_id='$SID'")" = "1" ]; then log "$SID already loaded"; continue; fi
  log "loading $SID"
  # sessions/hosts first (foreign keys), then everything else; gantt_* are rebuilt below
  load_tbl() { local T=$1 f="$sdir/$1.csv.gz"; [ -f "$f" ] || return 0; local COLS; COLS=$(cat "$sdir/$T.cols")
    $PSQL -c "\\copy \"$T\"($COLS) FROM PROGRAM 'gunzip -c $f' CSV" 2>&1 | grep -v "^COPY" | sed "s/^/  $T: /" | head -3; }
  load_tbl hosts; load_tbl sessions
  for f in "$sdir"/*.csv.gz; do
    T=$(basename "$f" .csv.gz)
    case "$T" in hosts|sessions|gantt_spans|gantt_meta) continue ;; esac
    load_tbl "$T"
  done
  $PSQL -c "ANALYZE" >/dev/null 2>&1
  log "$SID loaded: $($PSQL -c "SELECT count(*) FROM graph_nodes WHERE session_id='$SID'") graph nodes, $($PSQL -c "SELECT count(*) FROM ros2_trace WHERE session_id='$SID'") trace events"
  # pre-warm the materialised gantt table (the viz server would build it on the first request)
  ( cd /opt/fish/postprocess && python3 - "$SID" <<'PY'
import sys, time, psycopg2, psycopg2.extras, fish_viz_server as v
sid = sys.argv[1]; t = time.time()
conn = psycopg2.connect(v.os.environ.get('FISH_PG_DSN'), cursor_factory=psycopg2.extras.RealDictCursor); conn.autocommit = True
cur = conn.cursor()
for scope in ('__main__',):
    try:
        v._ensure_gantt_spans(cur, sid, scope)
        cur.execute("SELECT count(*) AS n FROM gantt_spans WHERE session_id=%s AND scope=%s", (sid, scope)); n = cur.fetchone()['n']
        print(f"[fishiris]   gantt_spans({sid}, {scope}): {n} spans in {time.time()-t:.0f} s", flush=True)
    except Exception as e:
        print(f"[fishiris]   gantt pre-warm failed: {e}", flush=True)
PY
  )
done

# 2. public URLs into the landing page + dashboard --------------------------
sed -i "s#http://localhost:8783#${PUBLIC_VIZ_URL}#g; s#http://localhost:3000#${PUBLIC_GRAFANA_URL}#g" /opt/fish/site/index.html
sed -i "s#http://localhost:8783#${PUBLIC_VIZ_URL}#g" /opt/grafana/dashboards/T0.json

# 3. Grafana (settings via GF_* env — reliable across versions) ------------------
export GF_PATHS_DATA=/opt/grafana/data GF_PATHS_LOGS=/var/log/grafana GF_PATHS_PLUGINS=/opt/grafana/data/plugins \
       GF_SERVER_HTTP_PORT=3000 GF_SECURITY_ALLOW_EMBEDDING=true \
       GF_AUTH_ANONYMOUS_ENABLED=true GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer GF_AUTH_ANONYMOUS_ORG_NAME="Main Org." \
       GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=gapit-htmlgraphics-panel GF_ANALYTICS_REPORTING_ENABLED=false GF_NEWS_NEWS_FEED_ENABLED=false
mkdir -p /var/log/grafana
( cd /opt/grafana && ./bin/grafana server --homepath /opt/grafana --config /opt/grafana/conf/defaults.ini > /var/log/grafana.log 2>&1 & )

# 4. viz server (foreground) -----------------------------------------------
log "viz server on :8783 (landing page ${PUBLIC_VIZ_URL}/fishiris/), grafana on :3000"
cd /opt/fish/postprocess && exec python3 fish_viz_server.py --port 8783
