#!/usr/bin/env python3
# Generated by Claude Fable 5 (Anthropic)
"""Summarise an Autoware three-mode overhead campaign (run_overhead_modes.sh).

Walks <root>/{baseline,lttng,nsys}_<i>/ and prints per metric: mean ± std over
reps for each mode + deltas vs baseline. Metrics = Autoware's own /diagnostics
measurements (same extraction as analyze_overhead.py) + cpu busiest-60s.

usage: analyze_overhead_modes.py <overhead_aw_dir>
"""
import glob, os, statistics as st, sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from analyze_overhead import analyze_side  # noqa: E402

ROWS = [
    ("CPU cores (busiest 60 s)", "cpu_cores_peak60"),
    ("objects rate [Hz]", "rate_objects"),
    ("obstacle pc rate [Hz]", "rate_obstacle_pc"),
    ("tsm NotReceived (startup)", "tsm_notreceived_startup"),
    ("tsm violations (post-init)", "tsm_violations_postinit"),
    ("concat processing [ms]", "concat_proc_ms"),
    ("concat pipeline lat [ms]", "concat_pipeline_ms"),
    ("centerpoint proc [ms] (GPU)", "centerpoint_proc_ms"),
    ("Total Latency [ms] (tracker reported)", "total_latency_ms"),
    ("tracker first report [ticks]", "latency_tracker_startup_ticks"),
    ("  multi_object_tracker [ms]", "mot_latency_ms"),
]


def main():
    root = sys.argv[1]
    per_mode = {}
    for mode in ("baseline", "lttng", "nsys"):
        sides = []
        for d in sorted(glob.glob(os.path.join(root, f"{mode}_*"))):
            try:
                sides.append(analyze_side(d))
            except Exception as e:
                print(f"[warn] {d}: {e}", file=sys.stderr)
        per_mode[mode] = sides

    def agg(mode, key):
        vals = [s[key] for s in per_mode[mode] if s.get(key) is not None]
        if not vals:
            return None, None
        return st.mean(vals), (st.stdev(vals) if len(vals) > 1 else 0.0)

    def cell(m, s, base=None):
        if m is None:
            return "—"
        t = f"{m:.2f}±{s:.2f}"
        if base:
            t += f" ({(m-base)/base*100:+.1f}%)"
        return t

    n = {m: len(per_mode[m]) for m in per_mode}
    print(f"# Autoware three-mode overhead — {os.path.basename(root.rstrip('/'))} "
          f"(reps: base={n['baseline']}, lttng={n['lttng']}, nsys={n['nsys']})\n")
    print(f"| metric | baseline | lttng-only (Δ) | lttng+nsys (Δ) |")
    print(f"|---|--:|--:|--:|")
    for label, key in ROWS:
        b, bs = agg("baseline", key)
        l, ls = agg("lttng", key)
        x, xs = agg("nsys", key)
        print(f"| {label} | {cell(b, bs)} | {cell(l, ls, b)} | {cell(x, xs, b)} |")


if __name__ == "__main__":
    main()
