#!/usr/bin/env python3
# Generated by Claude Fable 5 (Anthropic)
"""Compare a FISH overhead pair (traced vs baseline) from run_overhead_pair.sh.

Primary metrics come from Autoware's OWN measurements in diag.log:
  - topic_state_monitor: measured_rate per critical topic + WARN/ERROR counts
  - concatenate_data: Processing time (ms), Pipeline latency (ms)
  - lidar_centerpoint processing_time_status: processing_time_ms (GPU node)
  - pipeline_latency_monitor: Total Latency (ms)
Plus the external probes:
  - cpu.log: busiest 60 s window of container CPU (jiffies/s ÷ USER_HZ = cores)
  - hz_*.log (if present, pilot runs): ros2 topic hz cross-check

usage: analyze_overhead.py <overhead_dir>   # containing traced/ + baseline/
"""
import glob, os, re, statistics as st, sys

USER_HZ = 100  # jiffies per second (x86 default)


def cpu_busiest_window(path, win=60.0):
    """Return (cores_avg_in_busiest_window, samples) from cpu.log."""
    pts = []
    for ln in open(path):
        p = ln.split()
        if len(p) >= 2 and p[1].isdigit():
            pts.append((float(p[0]), int(p[1])))
    if len(pts) < 5:
        return None, len(pts)
    best = 0.0
    i = 0
    for j in range(1, len(pts)):
        while pts[j][0] - pts[i][0] > win:
            i += 1
        dt = pts[j][0] - pts[i][0]
        if dt >= win * 0.8:
            rate = (pts[j][1] - pts[i][1]) / dt / USER_HZ
            best = max(best, rate)
    return best, len(pts)


def parse_diag(path):
    """Split diag.log into per-status entries; return dict name -> list of {key: value}.

    Each DiagnosticStatus in `ros2 topic echo` output looks like:
        - level: "\\x02"
          name: 'x: y'
          message: ...
          values:
          - key: k
            value: v
    """
    out = {}
    cur_name, cur = None, None

    def flush():
        nonlocal cur_name, cur
        if cur_name is not None and cur is not None:
            out.setdefault(cur_name, []).append(cur)
        cur_name, cur = None, None

    for ln in open(path, errors="replace"):
        s = ln.strip()
        if s.startswith("- level:"):
            flush()
            lv = s.split(":", 1)[1].strip().strip('"')
            cur = {"_level": {"\\0": 0, "\\x01": 1, "\\x02": 2, "\\x03": 3}.get(lv)}
        elif cur is not None and s.startswith("name: "):
            cur_name = s[6:].strip("'\"")
        elif cur is not None and s.startswith("message: "):
            cur["_msg"] = s[9:]
        elif cur is not None and s.startswith("- key: "):
            cur["_k"] = s[7:]
        elif cur is not None and s.startswith("value: ") and "_k" in cur:
            cur[cur.pop("_k")] = s[7:].strip("'\"")
    flush()
    return out


def fnum(entry, key):
    v = entry.get(key)
    if v is None:
        return None
    m = re.match(r"[-0-9.eE+]+", v)
    try:
        return float(m.group(0)) if m else None
    except ValueError:
        return None


def series(diag, name_sub, key, sane=None):
    vals = []
    for name, entries in diag.items():
        if name_sub in name:
            for e in entries:
                v = fnum(e, key)
                if v is not None and (sane is None or sane(v)):
                    vals.append(v)
    return vals


def med(vals):
    return st.median(vals) if vals else None


def fmt(v, unit=""):
    return f"{v:.2f}{unit}" if v is not None else "—"


def hz_medians(side_dir):
    out = {}
    for f in glob.glob(os.path.join(side_dir, "hz_*.log")):
        rates = [float(m) for m in re.findall(r"average rate: ([0-9.]+)", open(f, errors="replace").read())]
        if len(rates) > 3:
            out[os.path.basename(f)[3:-4]] = st.median(rates[2:])
    return out


def analyze_side(d):
    r = {}
    cpu = os.path.join(d, "cpu.log")
    if os.path.exists(cpu):
        r["cpu_cores_peak60"], r["cpu_samples"] = cpu_busiest_window(cpu)
    diag = parse_diag(os.path.join(d, "diag.log"))
    r["diag_entries"] = sum(len(v) for v in diag.values())
    # topic_state_monitor rates (sane: rate < 1000 Hz filters the uninit 100000 artefact)
    for label, sub in [("rate_objects", "object_recognition_objects"),
                       ("rate_obstacle_pc", "obstacle_segmentation_pointcloud"),
                       ("rate_trajectory", "scenario_planning_trajectory"),
                       ("rate_route", "mission_planning_route")]:
        r[label] = med(series(diag, sub, "measured_rate", sane=lambda v: 0 < v < 1000))
    # violations: Timeout/Error statuses on topic_state_monitors.
    # post-init = the monitor's topic already delivered a message
    # (last_message_time > 0). startup = bad ticks before the first message
    # on monitors whose topic DOES publish later; monitors whose topic never
    # publishes in a goal-less logging_simulator replay (route, trajectory,
    # control_cmd, traffic_signals) tick NotReceived for the whole run and
    # are excluded from both counts.
    viol = startup = 0
    for name, entries in diag.items():
        if "topic_state_monitor" in name:
            got_msg = any((fnum(e, "last_message_time") or 0) > 0
                          for e in entries)
            for e in entries:
                lmt = fnum(e, "last_message_time")
                bad = e.get("status") in ("Timeout", "Error", "NotReceived")
                if lmt and lmt > 0 and bad:
                    viol += 1
                elif bad and got_msg:
                    startup += 1
    r["tsm_violations_postinit"] = viol
    r["tsm_notreceived_startup"] = startup
    r["concat_proc_ms"] = med(series(diag, "concatenate_data", "Processing time (ms)"))
    r["concat_pipeline_ms"] = med(series(diag, "concatenate_data", "Pipeline latency (ms)"))
    r["centerpoint_proc_ms"] = med(series(diag, "processing_time_status", "processing_time_ms",
                                          sane=lambda v: v > 0))
    # pipeline_latency_monitor: Total Latency is a PARTIAL sum whenever a
    # stage has not reported yet ("uninitialized_inputs"); with the tracker
    # missing it sits at a ~257 ms floor. A plain median over all ticks is
    # therefore contaminated (v5 P-core campaign: 49-56% of traced-run ticks
    # at the floor → a fake "improvement"). Use only ticks where the tracker
    # has reported, and expose the fraction of tracker-missing ticks itself
    # as a starvation indicator (post-startup).
    lat_entries = []
    for name, entries in diag.items():
        if "pipeline_latency_monitor" in name:
            lat_entries += entries
    complete = [e for e in lat_entries
                if "multi_object_tracker" not in str(e.get("uninitialized_inputs", ""))]
    tot = [fnum(e, "Total Latency (ms)") for e in complete]
    tot = [v for v in tot if v is not None and v > 0]
    r["total_latency_ms"] = med(tot)
    r["mot_latency_ms"] = med(series(diag, "pipeline_latency_monitor", "multi_object_tracker"))
    # All floor ticks turned out to precede the tracker's FIRST report (no
    # mid-run starvation), so the useful indicator is the startup delay:
    # monitor ticks (~1 Hz) until the tracker first reports.
    first = next((i for i, e in enumerate(lat_entries)
                  if "multi_object_tracker" not in str(e.get("uninitialized_inputs", ""))), None)
    r["latency_tracker_startup_ticks"] = first
    r["hz"] = hz_medians(d)
    return r


def main():
    root = sys.argv[1]
    T = analyze_side(os.path.join(root, "traced"))
    B = analyze_side(os.path.join(root, "baseline"))
    rows = [
        ("CPU cores (busiest 60 s)", "cpu_cores_peak60", ""),
        ("objects rate [Hz]", "rate_objects", ""),
        ("obstacle pc rate [Hz]", "rate_obstacle_pc", ""),
        ("trajectory rate [Hz]", "rate_trajectory", ""),
        ("tsm violations (post-init)", "tsm_violations_postinit", ""),
        ("concat processing [ms]", "concat_proc_ms", ""),
        ("concat pipeline lat [ms]", "concat_pipeline_ms", ""),
        ("centerpoint proc [ms] (GPU)", "centerpoint_proc_ms", ""),
        ("Total Latency [ms]", "total_latency_ms", ""),
        ("  └ multi_object_tracker [ms]", "mot_latency_ms", ""),
    ]
    print(f"{'metric':34s} {'baseline':>12s} {'traced':>12s} {'delta':>10s}")
    for label, key, unit in rows:
        b, t = B.get(key), T.get(key)
        if isinstance(b, (int, float)) and isinstance(t, (int, float)) and b:
            d = f"{(t - b) / b * 100:+.1f}%"
        else:
            d = "—"
        print(f"{label:34s} {fmt(b) if not isinstance(b,int) else b:>12} "
              f"{fmt(t) if not isinstance(t,int) else t:>12} {d:>10s}")
    if B.get("hz") or T.get("hz"):
        print("\nhz probes (pilot cross-check, median of 'average rate'):")
        for k in sorted(set(B.get("hz", {})) | set(T.get("hz", {}))):
            print(f"  {k:50s} base={fmt(B['hz'].get(k))}  traced={fmt(T['hz'].get(k))}")
    print(f"\ndiag entries: baseline={B['diag_entries']}, traced={T['diag_entries']}")


if __name__ == "__main__":
    main()
