#!/usr/bin/env python3
# Generated by Claude Fable 5 (Anthropic)
"""Summarise an Autoware three-mode overhead campaign (run_overhead_modes.sh).

Walks <root>/{baseline,lttng,nsys}_<i>/ and prints per metric: mean ± std over
reps for each mode + deltas vs baseline. Metrics = Autoware's own /diagnostics
measurements (same extraction as analyze_overhead.py) + cpu busiest-60s.

usage: analyze_overhead_modes.py <overhead_aw_dir>
"""
import glob, os, statistics as st, sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from analyze_overhead import analyze_side, window_bounds  # noqa: E402

# Value metrics are medians over each run's execution phase (2→3): (1) first
# /clock = first nonzero stamp, (2) tracker's first report, (3) bag end.
# Warm-up (1→2) is a metric. FISH_AW_WINDOW="lo,hi" forces a common window
# (robustness check). Diagnostic tick counts are NOT reported: the
# ros2-topic-echo probe loses 22-96 % of /diagnostics (analyze_overhead.py).
ROWS = [
    ("CPU cores (busiest 60 s)", "cpu_cores_peak60"),
    ("  app-set cores (split runs)", "cpu_app_peak60"),
    ("  observer-set cores (split runs)", "cpu_obs_peak60"),
    ("objects rate [Hz]", "rate_objects"),
    ("obstacle pc rate [Hz]", "rate_obstacle_pc"),
    ("tsm NotReceived ticks (startup, probe-lossy)", "tsm_notreceived_startup"),
    ("tsm violations (post-init)", "tsm_violations_postinit"),
    ("concat processing [ms]", "concat_proc_ms"),
    ("concat pipeline lat [ms]", "concat_pipeline_ms"),
    ("centerpoint proc [ms] (GPU)", "centerpoint_proc_ms"),
    ("Total Latency [ms] (tracker reported)", "total_latency_ms"),
    ("  chain = Total - 257.4 offsets [ms]", "chain_latency_ms"),
    ("  multi_object_tracker [ms]", "mot_latency_ms"),
    ("NDT activated [sim s]", "ndt_activated_s"),
    ("centerpoint first inference [sim s]", "centerpoint_first_infer_s"),
    ("warm-up (1->2) [sim s]", "warmup_s"),
    ("execution (2->3) [sim s]", "execution_s"),
]


def main():
    root = sys.argv[1]
    per_mode = {}
    for mode in ("baseline", "lttng", "nsys"):
        sides = []
        for d in sorted(glob.glob(os.path.join(root, f"{mode}_*"))):
            try:
                sides.append(analyze_side(d))
            except Exception as e:
                print(f"[warn] {d}: {e}", file=sys.stderr)
        per_mode[mode] = sides

    def agg(mode, key):
        vals = [s[key] for s in per_mode[mode] if s.get(key) is not None]
        if not vals:
            return None, None
        return st.mean(vals), (st.stdev(vals) if len(vals) > 1 else 0.0)

    def cell(m, s, base=None):
        if m is None:
            return "—"
        t = f"{m:.2f}±{s:.2f}"
        if base:
            t += f" ({(m-base)/base*100:+.1f}%)"
        return t

    n = {m: len(per_mode[m]) for m in per_mode}
    ov = window_bounds()
    win = f"common sim window [{ov[0]:g}, {ov[1]:g}) s" if ov else "each run's execution phase (2->3)"
    print(f"# Autoware three-mode overhead — {os.path.basename(root.rstrip('/'))} "
          f"(reps: base={n['baseline']}, lttng={n['lttng']}, nsys={n['nsys']}; "
          f"values = medians over {win})\n")
    print(f"| metric | baseline | lttng-only (Δ) | lttng+nsys (Δ) |")
    print(f"|---|--:|--:|--:|")
    for label, key in ROWS:
        b, bs = agg("baseline", key)
        l, ls = agg("lttng", key)
        x, xs = agg("nsys", key)
        print(f"| {label} | {cell(b, bs)} | {cell(l, ls, b)} | {cell(x, xs, b)} |")


if __name__ == "__main__":
    main()
