#!/usr/bin/env python3
# Generated by Claude Fable 5.1 (Anthropic), 2026-10-03
"""Overlay patch for image fishwait13 (on top of fishwait12): callback_start /
callback_end around GenericSubscription dispatch.

Humble's GenericSubscription::handle_serialized_message calls callback_(message)
with no tracepoint, so every create_generic_subscription callback (Autoware's
topic_state_monitor x14, pipeline_latency_monitor x5, topic_tools relays,
rosbag2 record) is registered (our fishwait hpp hook) but never seen executing:
cb_fire_count 0, no window, and its serialized take (fish_rcl_take) cannot be
paired with a dispatch.  The hook is in the COMPILED rclcpp, so it fires for
Autoware binaries built against stock headers.  tracetools' callback_start also
sets __fish_active_callback, so publishes from inside these callbacks (topic
relays) get a publish_link.  Build: colcon build --packages-select rclcpp."""
W = '/root/trace_overlay_ws/src'
def patch(path, pairs):
    s = open(path).read()
    for old, new in pairs:
        assert s.count(old) == 1, f'{path}: pattern not unique/missing:\n{old[:120]}'
        s = s.replace(old, new)
    open(path, 'w').write(s); print('patched', path)

patch(f'{W}/rclcpp/src/rclcpp/generic_subscription.cpp', [(
'''#include "rclcpp/exceptions.hpp"
''',
'''#include "rclcpp/exceptions.hpp"
#include "tracetools/tracetools.h"  // FISH
'''), (
'''  const rclcpp::MessageInfo &)
{
  callback_(message);
}''',
'''  const rclcpp::MessageInfo &)
{
  // FISH: stock Humble dispatches generic (serialized) subscriptions without
  // callback_start/end; same address as the rclcpp_callback_register in the hpp.
  TRACEPOINT(callback_start, static_cast<const void *>(&callback_), false);
  callback_(message);
  TRACEPOINT(callback_end, static_cast<const void *>(&callback_));
}''')])
print('all patches applied')
