#!/usr/bin/env python3
# Generated by Claude Fable 5.1 (Anthropic), 2026-10-03
"""Overlay patch for image fishwait12: three FISH tracepoints that close the
per-message gaps found in notes/tracepoint_coverage.md.

  fish_rclcpp_intra_publish(publisher_handle, message)   rclcpp intra-process publish (no rcl_publish fires when
                                                         every subscriber is in-process)
  fish_rclcpp_intra_take(waitable, message)              SubscriptionIntraProcess::take_data (the consume from the ring buffer)
  fish_rcl_take(rmw_subscription_handle, kind, source_timestamp, taken)
                                                         rcl_take_serialized_message (kind 1) / rcl_take_loaned_message (kind 2):
                                                         no tracepoint existed anywhere for these takes
plus fish_rclcpp_publish_link in the loaned and serialized publish paths (the
publishing callback was unknown there).  Run inside the container on
/root/trace_overlay_ws/src, then colcon build tracetools rcl rclcpp rclcpp_action."""
import re, sys
W = '/root/trace_overlay_ws/src'
def patch(path, pairs):
    s = open(path).read()
    for old, new in pairs:
        assert s.count(old) == 1, f'{path}: pattern not unique/missing:\n{old[:120]}'
        s = s.replace(old, new)
    open(path, 'w').write(s); print('patched', path)

# ---- tracetools: tp_call.h
patch(f'{W}/tracetools/include/tracetools/tp_call.h', [(
'''TRACEPOINT_EVENT(
  TRACEPOINT_PROVIDER,
  fish_rclcpp_client_link,''',
'''TRACEPOINT_EVENT(
  TRACEPOINT_PROVIDER,
  fish_rclcpp_intra_publish,
  TP_ARGS(
    const void *, publisher_handle_arg,
    const void *, message_arg
  ),
  TP_FIELDS(
    ctf_integer_hex(const void *, publisher_handle, publisher_handle_arg)
    ctf_integer_hex(const void *, message, message_arg)
  )
)

TRACEPOINT_EVENT(
  TRACEPOINT_PROVIDER,
  fish_rclcpp_intra_take,
  TP_ARGS(
    const void *, waitable_arg,
    const void *, message_arg
  ),
  TP_FIELDS(
    ctf_integer_hex(const void *, waitable, waitable_arg)
    ctf_integer_hex(const void *, message, message_arg)
  )
)

TRACEPOINT_EVENT(
  TRACEPOINT_PROVIDER,
  fish_rcl_take,
  TP_ARGS(
    const void *, rmw_subscription_handle_arg,
    const int, kind_arg,
    const int64_t, source_timestamp_arg,
    const bool, taken_arg
  ),
  TP_FIELDS(
    ctf_integer_hex(const void *, rmw_subscription_handle, rmw_subscription_handle_arg)
    ctf_integer(int, kind, kind_arg)
    ctf_integer(int64_t, source_timestamp, source_timestamp_arg)
    ctf_integer(int, taken, (taken_arg ? 1 : 0))
  )
)

TRACEPOINT_EVENT(
  TRACEPOINT_PROVIDER,
  fish_rclcpp_client_link,''')])

# ---- tracetools: tracetools.h declarations
patch(f'{W}/tracetools/include/tracetools/tracetools.h', [(
'''/// `fish_rclcpp_publish_link` — associates publisher_handle to active callback
DECLARE_TRACEPOINT(
  fish_rclcpp_publish_link,
  const void * publisher_handle,
  const void * callback)
''',
'''/// `fish_rclcpp_publish_link` — associates publisher_handle to active callback
DECLARE_TRACEPOINT(
  fish_rclcpp_publish_link,
  const void * publisher_handle,
  const void * callback)

/// `fish_rclcpp_intra_publish` — intra-process publish of one message (per instance)
DECLARE_TRACEPOINT(
  fish_rclcpp_intra_publish,
  const void * publisher_handle,
  const void * message)

/// `fish_rclcpp_intra_take` — SubscriptionIntraProcess consumes one message from its buffer
DECLARE_TRACEPOINT(
  fish_rclcpp_intra_take,
  const void * waitable,
  const void * message)

/// `fish_rcl_take` — rcl take variants without a stock tracepoint: kind 1 serialized, 2 loaned
DECLARE_TRACEPOINT(
  fish_rcl_take,
  const void * rmw_subscription_handle,
  const int kind,
  const int64_t source_timestamp,
  const bool taken)
''')])

# ---- tracetools: tracetools.c implementations (plain CONDITIONAL_TP, no cache: per instance)
patch(f'{W}/tracetools/src/tracetools.c', [(
'''void TRACEPOINT(
  fish_rclcpp_receive_link,''',
'''void TRACEPOINT(
  fish_rclcpp_intra_publish,
  const void * publisher_handle,
  const void * message)
{
  CONDITIONAL_TP(
    fish_rclcpp_intra_publish,
    publisher_handle,
    message);
}

void TRACEPOINT(
  fish_rclcpp_intra_take,
  const void * waitable,
  const void * message)
{
  CONDITIONAL_TP(
    fish_rclcpp_intra_take,
    waitable,
    message);
}

void TRACEPOINT(
  fish_rcl_take,
  const void * rmw_subscription_handle,
  const int kind,
  const int64_t source_timestamp,
  const bool taken)
{
  CONDITIONAL_TP(
    fish_rcl_take,
    rmw_subscription_handle,
    kind,
    source_timestamp,
    taken);
}

void TRACEPOINT(
  fish_rclcpp_receive_link,''')])

# ---- rclcpp publisher.hpp: per-message intra publish + publish_link on loaned/serialized paths
P = f'{W}/rclcpp/include/rclcpp/publisher.hpp'
s = open(P).read()
n = s.count('    TRACEPOINT(fish_rclcpp_publish_link, static_cast<const void *>(publisher_handle_.get()), __fish_active_callback);  // FISH intra\n')
assert n == 3, n
s = s.replace('    TRACEPOINT(fish_rclcpp_publish_link, static_cast<const void *>(publisher_handle_.get()), __fish_active_callback);  // FISH intra\n',
              '    TRACEPOINT(fish_rclcpp_publish_link, static_cast<const void *>(publisher_handle_.get()), __fish_active_callback);  // FISH intra\n'
              '    TRACEPOINT(fish_rclcpp_intra_publish, static_cast<const void *>(publisher_handle_.get()), static_cast<const void *>(msg.get()));  // FISH per-message\n')
old = '''    auto status = rcl_publish_serialized_message(publisher_handle_.get(), serialized_msg, nullptr);'''
assert s.count(old) == 1
s = s.replace(old, '''    TRACEPOINT(fish_rclcpp_publish_link, static_cast<const void *>(publisher_handle_.get()), __fish_active_callback);  // FISH serialized
    auto status = rcl_publish_serialized_message(publisher_handle_.get(), serialized_msg, nullptr);''')
old = '''    auto status = rcl_publish_loaned_message(publisher_handle_.get(), msg.get(), nullptr);'''
assert s.count(old) == 1
s = s.replace(old, '''    TRACEPOINT(fish_rclcpp_publish_link, static_cast<const void *>(publisher_handle_.get()), __fish_active_callback);  // FISH loaned
    auto status = rcl_publish_loaned_message(publisher_handle_.get(), msg.get(), nullptr);''')
open(P, 'w').write(s); print('patched', P)

# ---- rclcpp subscription_intra_process.hpp: the take from the ring buffer
patch(f'{W}/rclcpp/include/rclcpp/experimental/subscription_intra_process.hpp', [(
'''    if (this->buffer_->has_data()) {
      // If there is data still to be processed, indicate to the
      // executor or waitset by triggering the guard condition.
      this->trigger_guard_condition();
    }

    return std::static_pointer_cast<void>(''',
'''    TRACEPOINT(
      fish_rclcpp_intra_take,
      static_cast<const void *>(this),
      static_cast<const void *>(shared_msg ? static_cast<const void *>(shared_msg.get()) : static_cast<const void *>(unique_msg.get())));  // FISH per-message

    if (this->buffer_->has_data()) {
      // If there is data still to be processed, indicate to the
      // executor or waitset by triggering the guard condition.
      this->trigger_guard_condition();
    }

    return std::static_pointer_cast<void>(''')])
# the header must see the tracepoint declarations
H = f'{W}/rclcpp/include/rclcpp/experimental/subscription_intra_process.hpp'
s = open(H).read()
if '#include "tracetools/tracetools.h"' not in s:
    s = s.replace('#include "rclcpp/experimental/subscription_intra_process_buffer.hpp"',
                  '#include "rclcpp/experimental/subscription_intra_process_buffer.hpp"\n#include "tracetools/tracetools.h"', 1)
    assert '#include "tracetools/tracetools.h"' in s
    open(H, 'w').write(s); print('added tracetools include to', H)

# ---- rcl subscription.c: serialized and loaned takes
patch(f'{W}/rcl/src/rcl/subscription.c', [(
'''  RCUTILS_LOG_DEBUG_NAMED(
    ROS_PACKAGE_NAME, "Subscription serialized take succeeded: %s", taken ? "true" : "false");
  if (!taken) {''',
'''  RCUTILS_LOG_DEBUG_NAMED(
    ROS_PACKAGE_NAME, "Subscription serialized take succeeded: %s", taken ? "true" : "false");
  TRACEPOINT(fish_rcl_take, (const void *)subscription->impl->rmw_handle, 1,
    message_info_local->source_timestamp, taken);  // FISH
  if (!taken) {'''), (
'''  RCUTILS_LOG_DEBUG_NAMED(
    ROS_PACKAGE_NAME, "Subscription loaned take succeeded: %s", taken ? "true" : "false");
  if (!taken) {''',
'''  RCUTILS_LOG_DEBUG_NAMED(
    ROS_PACKAGE_NAME, "Subscription loaned take succeeded: %s", taken ? "true" : "false");
  TRACEPOINT(fish_rcl_take, (const void *)subscription->impl->rmw_handle, 2,
    message_info_local->source_timestamp, taken);  // FISH
  if (!taken) {''')])
# ---- rclcpp publisher_base.cpp (COMPILED, ABI-safe): per-publish intra-process event.
# Autoware's binaries were built against the stock headers, so header-level
# tracepoints never fire for them; this getter runs once per publish() of every
# intra-process-capable publisher (see the existing FISH publish_link hook).
patch(f'{W}/rclcpp/src/rclcpp/publisher_base.cpp', [(
'''  TRACEPOINT(
    fish_rclcpp_publish_link,
    static_cast<const void *>(publisher_handle_.get()),
    __fish_active_callback);
  if (!ipm) {''',
'''  TRACEPOINT(
    fish_rclcpp_publish_link,
    static_cast<const void *>(publisher_handle_.get()),
    __fish_active_callback);
  TRACEPOINT(
    fish_rclcpp_intra_publish,
    static_cast<const void *>(publisher_handle_.get()),
    nullptr);  // FISH per-message; the message pointer is only known in the header path
  if (!ipm) {''')])
print('all patches applied')
