#!/usr/bin/env python3
# Generated by Claude Fable 5.1 (Anthropic), 2026-10-03
"""Overlay patch for image fishwait17 (on top of fishwait16) — todo A0.5a/b, "every ROS 2 app":
  fish_rcl_wait_enter(wait_set, timeout_ns)   rcl_wait about to block in rmw_wait (every waiter: rclcpp executors,
  fish_rcl_wait_exit(wait_set, ret)           rclcpp::WaitSet / StaticWaitSet hand-rolled spins, rclpy)
  fish_rcl_take kind 3                        rcl_take_sequence (batch take), with the number taken as 'taken'
Build: colcon build --packages-select tracetools rcl."""
W = '/root/trace_overlay_ws/src'
def patch(path, pairs):
    s = open(path).read()
    for old, new in pairs:
        assert s.count(old) == 1, f'{path}: pattern not unique/missing ({s.count(old)}):\n{old[:160]}'
        s = s.replace(old, new)
    open(path, 'w').write(s); print('patched', path)
patch(f'{W}/tracetools/include/tracetools/tp_call.h', [(
'''TRACEPOINT_EVENT(
  TRACEPOINT_PROVIDER,
  fish_rclcpp_client_link,''',
'''TRACEPOINT_EVENT(
  TRACEPOINT_PROVIDER,
  fish_rcl_wait_enter,
  TP_ARGS(const void *, wait_set_arg, const int64_t, timeout_ns_arg),
  TP_FIELDS(
    ctf_integer_hex(const void *, wait_set, wait_set_arg)
    ctf_integer(int64_t, timeout_ns, timeout_ns_arg)
  )
)

TRACEPOINT_EVENT(
  TRACEPOINT_PROVIDER,
  fish_rcl_wait_exit,
  TP_ARGS(const void *, wait_set_arg, const int, ret_arg),
  TP_FIELDS(
    ctf_integer_hex(const void *, wait_set, wait_set_arg)
    ctf_integer(int, ret, ret_arg)
  )
)

TRACEPOINT_EVENT(
  TRACEPOINT_PROVIDER,
  fish_rclcpp_client_link,''')])
patch(f'{W}/tracetools/include/tracetools/tracetools.h', [(
'''/// `fish_gomp_parallel` — OpenMP parallel region start (GOMP_parallel, master thread; fish_gomp_shim.c)''',
'''/// `fish_rcl_wait_enter` — rcl_wait about to block in rmw_wait (timeout in ns, -1 = infinite)
DECLARE_TRACEPOINT(fish_rcl_wait_enter, const void * wait_set, const int64_t timeout_ns)

/// `fish_rcl_wait_exit` — rmw_wait returned (ret: RMW_RET_OK 0 / RMW_RET_TIMEOUT 2 / error)
DECLARE_TRACEPOINT(fish_rcl_wait_exit, const void * wait_set, const int ret)

/// `fish_gomp_parallel` — OpenMP parallel region start (GOMP_parallel, master thread; fish_gomp_shim.c)''')])
patch(f'{W}/tracetools/src/tracetools.c', [(
'''void TRACEPOINT(fish_gomp_parallel, const void * fn, const int num_threads)
{''',
'''void TRACEPOINT(fish_rcl_wait_enter, const void * wait_set, const int64_t timeout_ns)
{
  CONDITIONAL_TP(fish_rcl_wait_enter, wait_set, timeout_ns);
}

void TRACEPOINT(fish_rcl_wait_exit, const void * wait_set, const int ret)
{
  CONDITIONAL_TP(fish_rcl_wait_exit, wait_set, ret);
}

void TRACEPOINT(fish_gomp_parallel, const void * fn, const int num_threads)
{''')])
# rcl/wait.c: around rmw_wait
patch(f'{W}/rcl/src/rcl/wait.c', [(
'''#include "./context_impl.h"
''',
'''#include "./context_impl.h"
#include "tracetools/tracetools.h"  // FISH
'''), (
'''  // Wait.
  rmw_ret_t ret = rmw_wait(
    &wait_set->impl->rmw_subscriptions,
    &wait_set->impl->rmw_guard_conditions,
    &wait_set->impl->rmw_services,
    &wait_set->impl->rmw_clients,
    &wait_set->impl->rmw_events,
    wait_set->impl->rmw_wait_set,
    timeout_argument);
''',
'''  // Wait.
  TRACEPOINT(fish_rcl_wait_enter, (const void *)wait_set,
    timeout_argument ? (int64_t)(timeout_argument->sec * 1000000000LL + (int64_t)timeout_argument->nsec) : (int64_t)-1);  // FISH
  rmw_ret_t ret = rmw_wait(
    &wait_set->impl->rmw_subscriptions,
    &wait_set->impl->rmw_guard_conditions,
    &wait_set->impl->rmw_services,
    &wait_set->impl->rmw_clients,
    &wait_set->impl->rmw_events,
    wait_set->impl->rmw_wait_set,
    timeout_argument);
  TRACEPOINT(fish_rcl_wait_exit, (const void *)wait_set, (int)ret);  // FISH
''')])
# rcl/subscription.c: take_sequence
patch(f'{W}/rcl/src/rcl/subscription.c', [(
'''  RCUTILS_LOG_DEBUG_NAMED(
    ROS_PACKAGE_NAME, "Subscription took %zu messages", taken);
''',
'''  RCUTILS_LOG_DEBUG_NAMED(
    ROS_PACKAGE_NAME, "Subscription took %zu messages", taken);
  TRACEPOINT(fish_rcl_take, (const void *)subscription->impl->rmw_handle, 3, 0, taken > 0);  // FISH batch take (kind 3)
''')])
print('all patches applied')
