/* Generated by Claude Fable 5.1 (Anthropic), 2026-10-03, fixed 2026-10-04 — FISH OpenMP region shim (todo A0.2).
 * LD_PRELOADed into the traced application: interposes libgomp's GOMP_parallel (the entry point of
 * every `#pragma omp parallel` region in gcc-compiled code), emits ros2:fish_gomp_parallel at region
 * start and ros2:fish_gomp_parallel_end at region end in the master thread's context, forwards to the
 * real libgomp.  Kernel uprobes on libgomp were refused by the lttng ABI on this host (2026-10-03).
 *
 * BUG FIXED 2026-10-04 (fishwait16-18 and the first fishwait19 were affected): dlsym(RTLD_NEXT, ...) only
 * searches the GLOBAL scope. A process that dlopen()s its node library (rclcpp_components node_main
 * executables, component containers: class_loader → dlopen RTLD_LOCAL) has libgomp in that library's
 * LOCAL scope, so the lookup returned NULL and the old code skipped the region body — the application's
 * parallel loops silently did not run (NDT: score 0, no alignment; 0.5 us "regions").  Now: (1) the shim
 * links libgomp itself (DT_NEEDED → global scope, right after the shim), (2) falls back to an explicit
 * dlopen of libgomp.so.1, (3) aborts loudly if the real function cannot be found. A tracer must never
 * change what the application computes.  Regression test: test_gomp_shim.sh.
 * Build: gcc -shared -fPIC -O2 -o libfish_gomp_shim.so fish_gomp_shim.c -I<tracetools include>
 *        -L<tracetools lib> -ltracetools -ldl -Wl,--no-as-needed -l:libgomp.so.1 */
#define _GNU_SOURCE
#include <dlfcn.h>
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include "tracetools/tracetools.h"

typedef void (*gomp_parallel_fn_t)(void (*)(void *), void *, unsigned, unsigned);

static gomp_parallel_fn_t fish_real_gomp_parallel(void)
{
  static gomp_parallel_fn_t real = NULL;
  if (real == NULL) {
    gomp_parallel_fn_t f = (gomp_parallel_fn_t) dlsym(RTLD_NEXT, "GOMP_parallel");
    if (f == NULL) {
      void * h = dlopen("libgomp.so.1", RTLD_LAZY | RTLD_GLOBAL);
      if (h != NULL) {
        f = (gomp_parallel_fn_t) dlsym(h, "GOMP_parallel");
      }
    }
    if (f == NULL) {
      fprintf(stderr, "[fish_gomp_shim] FATAL: cannot resolve the real GOMP_parallel (%s)\n", dlerror());
      abort();
    }
    real = f;
  }
  return real;
}

/* The other entry points that open a parallel region (same team semantics, same two events):
 * combined `parallel for` (GOMP_parallel_loop_*, emitted by gcc when the loop bounds are known before the region)
 * and `parallel sections`.  Autoware imports only GOMP_parallel (18 libraries) and GOMP_parallel_sections (1);
 * the loop variants are here because FISH targets any ROS 2 application.  Resolution is per symbol, same rules. */
static void * fish_real_sym(const char * name)
{
  void * f = dlsym(RTLD_NEXT, name);
  if (f == NULL) {
    void * h = dlopen("libgomp.so.1", RTLD_LAZY | RTLD_GLOBAL);
    if (h != NULL) {
      f = dlsym(h, name);
    }
  }
  if (f == NULL) {
    fprintf(stderr, "[fish_gomp_shim] FATAL: cannot resolve the real %s (%s)\n", name, dlerror());
    abort();
  }
  return f;
}

#define FISH_GOMP_LOOP_CHUNK(NAME) \
  void NAME(void (*fn)(void *), void *data, unsigned num_threads, long start, long end, long incr, long chunk, unsigned flags) \
  { \
    static void (*real)(void (*)(void *), void *, unsigned, long, long, long, long, unsigned) = NULL; \
    if (real == NULL) { real = (void (*)(void (*)(void *), void *, unsigned, long, long, long, long, unsigned)) fish_real_sym(#NAME); } \
    if (num_threads == 1u) { real(fn, data, num_threads, start, end, incr, chunk, flags); return; } \
    TRACEPOINT(fish_gomp_parallel, (const void *) fn, (int) num_threads); \
    real(fn, data, num_threads, start, end, incr, chunk, flags); \
    TRACEPOINT(fish_gomp_parallel_end, (const void *) fn); \
  }
#define FISH_GOMP_LOOP_NOCHUNK(NAME) \
  void NAME(void (*fn)(void *), void *data, unsigned num_threads, long start, long end, long incr, unsigned flags) \
  { \
    static void (*real)(void (*)(void *), void *, unsigned, long, long, long, unsigned) = NULL; \
    if (real == NULL) { real = (void (*)(void (*)(void *), void *, unsigned, long, long, long, unsigned)) fish_real_sym(#NAME); } \
    if (num_threads == 1u) { real(fn, data, num_threads, start, end, incr, flags); return; } \
    TRACEPOINT(fish_gomp_parallel, (const void *) fn, (int) num_threads); \
    real(fn, data, num_threads, start, end, incr, flags); \
    TRACEPOINT(fish_gomp_parallel_end, (const void *) fn); \
  }
FISH_GOMP_LOOP_CHUNK(GOMP_parallel_loop_static)
FISH_GOMP_LOOP_CHUNK(GOMP_parallel_loop_dynamic)
FISH_GOMP_LOOP_CHUNK(GOMP_parallel_loop_guided)
FISH_GOMP_LOOP_CHUNK(GOMP_parallel_loop_nonmonotonic_dynamic)
FISH_GOMP_LOOP_CHUNK(GOMP_parallel_loop_nonmonotonic_guided)
FISH_GOMP_LOOP_NOCHUNK(GOMP_parallel_loop_runtime)
FISH_GOMP_LOOP_NOCHUNK(GOMP_parallel_loop_nonmonotonic_runtime)
FISH_GOMP_LOOP_NOCHUNK(GOMP_parallel_loop_maybe_nonmonotonic_runtime)

void GOMP_parallel_sections(void (*fn)(void *), void *data, unsigned num_threads, unsigned count, unsigned flags)
{
  static void (*real)(void (*)(void *), void *, unsigned, unsigned, unsigned) = NULL;
  if (real == NULL) { real = (void (*)(void (*)(void *), void *, unsigned, unsigned, unsigned)) fish_real_sym("GOMP_parallel_sections"); }
  if (num_threads == 1u) { real(fn, data, num_threads, count, flags); return; }
  TRACEPOINT(fish_gomp_parallel, (const void *) fn, (int) num_threads);
  real(fn, data, num_threads, count, flags);
  TRACEPOINT(fish_gomp_parallel_end, (const void *) fn);
}

void GOMP_parallel(void (*fn)(void *), void *data, unsigned num_threads, unsigned flags)
{
  gomp_parallel_fn_t real = fish_real_gomp_parallel();
  /* num_threads == 1 is a serial "parallel" region (no team, no helpers): nothing to attribute, no events
   * (Autoware's perception container issues ~2 M of them per minute). */
  if (num_threads == 1u) {
    real(fn, data, num_threads, flags);
    return;
  }
  TRACEPOINT(fish_gomp_parallel, (const void *) fn, (int) num_threads);
  real(fn, data, num_threads, flags);
  TRACEPOINT(fish_gomp_parallel_end, (const void *) fn);
}
