#!/usr/bin/env python3
# Generated by Claude Fable 5.1 (Anthropic), 2026-10-05
"""FORK patch `fork-awintra1` (on top of fishwait24) — NOT part of the fishwaitNN line.

The fork exists to try what needs Autoware itself recompiled against the overlay headers: the intra-process path of
rclcpp is template code, so its tracepoints only fire in binaries built against the patched headers.
  - already in the overlay headers, now reaching the rebuilt packages: fish_rclcpp_intra_publish(publisher_handle,
    message) with the real message address (the library-side fallback reports 0x0) and
    fish_rclcpp_intra_take(waitable, message) — the address is the identity of a zero-copy delivery;
  - new here: the retention probe of fishwait24 for intra-process deliveries that hand the callback a shared_ptr
    (SubscriptionIntraProcess::execute_impl): fish_msg_retain / fish_msg_release with handle = the waitable.
Build: build_overlay.sh fork-awintra1 fishwait24 fork_awintra1.py rclcpp  with
       POST_CMD='PKGS="…" bash /fish_scripts/rebuild_header_tracepoint_users.sh' (the Autoware packages to recompile).
Images of a fork carry the label fish.lineage=fork; run_overhead_modes.sh refuses them unless FISH_ALLOW_FORK=1."""
W = '/root/trace_overlay_ws/src'
def patch(path, pairs):
    s = open(path).read()
    for old, new in pairs:
        assert s.count(old) == 1, f'{path}: pattern not unique/missing ({s.count(old)}):\n{old[:160]}'
        s = s.replace(old, new)
    open(path, 'w').write(s); print('patched', path)

patch(f'{W}/rclcpp/include/rclcpp/experimental/subscription_intra_process.hpp', [(
'''    if (any_callback_.use_take_shared_method()) {
      ConstMessageSharedPtr shared_msg = shared_ptr->first;
      any_callback_.dispatch_intra_process(shared_msg, msg_info);
    } else {''',
'''    if (any_callback_.use_take_shared_method()) {
      ConstMessageSharedPtr shared_msg = shared_ptr->first;
      // FISH (fork awintra1): retention probe for intra-process deliveries, as in Executor::execute_subscription —
      // the callback gets an alias of the message (same object, own control block); a kept reference shows as
      // fish_msg_retain(waitable, message, refs), the last release as fish_msg_release in the releasing thread.
      const char * fish_topic = this->get_topic_name();
      if (FISH_TP_ENABLED(0) && !(fish_topic != nullptr && strcmp(fish_topic, "/clock") == 0)) {
        struct FishIntraRelease
        {
          ConstMessageSharedPtr keep;
          const void * sub;
          bool retained;
          void operator()(typename ConstMessageSharedPtr::element_type * p) noexcept
          {
            if (retained) {
              TRACEPOINT(fish_msg_release, sub, static_cast<const void *>(p));
            }
            keep.reset();
          }
        };
        ConstMessageSharedPtr fish_msg(
          shared_msg.get(), FishIntraRelease{shared_msg, static_cast<const void *>(this), false});
        any_callback_.dispatch_intra_process(fish_msg, msg_info);
        const long fish_refs = fish_msg.use_count() - 1;
        if (fish_refs > 0) {
          std::get_deleter<FishIntraRelease>(fish_msg)->retained = true;
          TRACEPOINT(
            fish_msg_retain, static_cast<const void *>(this), static_cast<const void *>(fish_msg.get()),
            static_cast<int>(fish_refs));
        }
      } else {
        any_callback_.dispatch_intra_process(shared_msg, msg_info);
      }
    } else {'''), (
'''#include "tracetools/tracetools.h"
''',
'''#include "tracetools/tracetools.h"
#include <cstring>  // FISH (fork awintra1)
''')])
print('all patches applied')
