#!/bin/bash
# Generated by Claude Fable 5.1 (Anthropic), 2026-10-04
# Regression test for the OpenMP shim, run INSIDE an overlay container: a program that dlopen()s (RTLD_LOCAL) a
# library with a 4-thread parallel region — the rclcpp_components loading pattern — must execute the region
# body with the shim preloaded.  Prints SHIM_TEST_OK or SHIM_TEST_FAIL.  Usage: test_gomp_shim.sh <shim.so>
SHIM=${1:?path to libfish_gomp_shim.so}; D=$(mktemp -d); cd "$D"
cat > lib.c <<'C'
#include <omp.h>
int region(void) { int n = 0;
#pragma omp parallel num_threads(4) reduction(+:n)
  { n += 1; }
  /* combined constructs: GOMP_parallel_loop_* and GOMP_parallel_sections (whatever gcc emits for them) */
  long s = 0;
#pragma omp parallel for schedule(dynamic, 2) num_threads(4) reduction(+:s)
  for (long i = 0; i < 1000; i++) s += i;
  int k = 0;
#pragma omp parallel sections num_threads(2) reduction(+:k)
  {
#pragma omp section
    { k += 1; }
#pragma omp section
    { k += 2; }
  }
  return (n == 4 && s == 499500 && k == 3) ? 4 : -1; }
C
cat > main.c <<'C'
#include <dlfcn.h>
#include <stdio.h>
int main(void) { void *h = dlopen("./libt.so", RTLD_LAZY | RTLD_LOCAL); if (!h) { puts("dlopen failed"); return 2; }
  int (*f)(void) = (int (*)(void)) dlsym(h, "region"); int n = f(); printf("threads_in_region=%d\n", n); return n == 4 ? 0 : 1; }
C
gcc -shared -fPIC -fopenmp -o libt.so lib.c && gcc -o main main.c -ldl || { echo SHIM_TEST_FAIL build; exit 2; }
./main > base.txt 2>&1; B=$?
LD_PRELOAD=$SHIM ./main > shim.txt 2>&1; S=$?
echo "without shim: $(cat base.txt) rc=$B ; with shim: $(cat shim.txt) rc=$S"
[ $B = 0 ] && [ $S = 0 ] && echo SHIM_TEST_OK || echo SHIM_TEST_FAIL
