#!/bin/bash
# Generated by Claude Fable 5.1 (Anthropic), 2026-10-05
# Regression test of the FISH lock shim (fish_lock_shim.c): an "application" library locks a std::mutex 1000 times
# and waits 30 ms on a condition variable inside a callback window (ros_trace_callback_start/end), plus one lock
# outside any callback. The program must print the same result with and without the shim; with
# FISH_LOCK_SHIM_DEBUG=1 the shim must report n=1000 for the first mutex and a hold time for the second one that
# does not contain the 30 ms wait; an untimed wait woken by another thread must return (it hung with the first
# version of the shim, which forwarded to glibc's old pthread_cond_wait).  Needs a running lttng session? No — the debug print does not depend on one,
# but records are only collected when ros2:fish_lock is enabled, so the test forces it with FISH_LOCK_SHIM_FORCE=1.
# Prints LOCKSHIM_TEST_OK or SHIM_TEST_FAIL (the latter blocks the image commit in build_overlay.sh).
# Usage: test_lock_shim.sh <libfish_lock_shim.so>   (overlay environment sourced)
SHIM=${1:?path to libfish_lock_shim.so}; D=$(mktemp -d); cd "$D"
T=/root/trace_overlay_ws/install/tracetools
cat > app.cpp <<'CPP'
#include <chrono>
#include <condition_variable>
#include <mutex>
#include <thread>
extern "C" {
void ros_trace_callback_start(const void *, const bool);
void ros_trace_callback_end(const void *);
}
static std::mutex m1, m2, m3;
static std::condition_variable cv;
static long counter = 0;
extern "C" long app_run(int n)
{
  { std::lock_guard<std::mutex> l(m3); counter += 7; }          // outside a callback: not recorded
  ros_trace_callback_start((const void *) 0x1234, false);
  for (int i = 0; i < n; i++) { std::lock_guard<std::mutex> l(m1); counter += i; }
  { std::unique_lock<std::mutex> l(m2); cv.wait_for(l, std::chrono::milliseconds(30)); counter += 1; }
  ros_trace_callback_end((const void *) 0x1234);
  // an untimed wait that only a notify from another thread ends (hangs if the shim forwards to the wrong
  // pthread_cond_wait), outside and inside a callback window
  for (int k = 0; k < 2; k++) {
    bool ready = false;
    if (k == 1) { ros_trace_callback_start((const void *) 0x5678, false); }
    std::thread t([&] { std::this_thread::sleep_for(std::chrono::milliseconds(20)); { std::lock_guard<std::mutex> l(m3); ready = true; } cv.notify_one(); });
    { std::unique_lock<std::mutex> l(m3); cv.wait(l, [&] { return ready; }); counter += 100; }
    t.join();
    if (k == 1) { ros_trace_callback_end((const void *) 0x5678); }
  }
  return counter;
}
CPP
cat > main.c <<'C'
#include <stdio.h>
long app_run(int n);
int main(void) { printf("result %ld\n", app_run(1000)); return 0; }
C
g++ -O2 -fPIC -shared -o libapp.so app.cpp -L$T/lib -ltracetools -lpthread || { echo "SHIM_TEST_FAIL lock: build app"; exit 1; }
gcc -O2 -o main main.c -L. -lapp -Wl,-rpath,"$D" -L$T/lib -ltracetools || { echo "SHIM_TEST_FAIL lock: build main"; exit 1; }
export LD_LIBRARY_PATH=$T/lib:$LD_LIBRARY_PATH
A=$(timeout 30 ./main 2>/dev/null)
B=$(timeout 30 env LD_PRELOAD=$SHIM FISH_LOCK_SHIM_DEBUG=1 FISH_LOCK_SHIM_FORCE=1 ./main 2> shim.err) || { echo "SHIM_TEST_FAIL lock: the program hangs or fails with the shim (rc=$?)"; cat shim.err; exit 1; }
echo "plain: $A | shim: $B"; cat shim.err
[ "$A" = "$B" ] && [ -n "$A" ] || { echo "SHIM_TEST_FAIL lock: output differs"; exit 1; }
N1=$(grep -c "cb=0x1234 .* n=1000 " shim.err); NREC=$(grep -c "^\[fish_lock\] cb=0x1234" shim.err)
H2=$(grep "cb=0x1234 .* n=1 " shim.err | sed 's/.*hold_sum=\([0-9]*\).*/\1/' | head -1)
H3=$(grep "cb=0x5678 " shim.err | sed 's/.*hold_sum=\([0-9]*\).*/\1/' | head -1)
[ "$N1" = 1 ] && [ "$NREC" = 2 ] && [ -n "$H2" ] && [ "$H2" -lt 5000000 ] && [ -n "$H3" ] && [ "$H3" -lt 5000000 ] || { echo "SHIM_TEST_FAIL lock: records (n1000=$N1 records=$NREC hold2=$H2 hold3=$H3)"; exit 1; }
echo "LOCKSHIM_TEST_OK"
