# Generated by Claude Fable 5.1 (Anthropic), 2026-10-04
"""ROS 2 reference system (ros-realtime/reference-system, commit de8f3bc), `autoware_default_prioritized` — the
configuration LiME-IT evaluates (RTAS'26, Table I): 24 nodes, five single-threaded executors (front / rear / fusion at
SCHED_RR 1, planner at SCHED_RR 30, other best-effort). Built in image autoware-dev-trt-a1000-fishwait19refsys under
/root/refsys_ws. Purpose: compare FISH's task set and periods with LiME-IT's published table."""
import os
import launch
from launch.actions import ExecuteProcess

WS = '/root/refsys_ws/install'


def generate_launch_description():
    libs = ':'.join(f'{WS}/{p}/lib' for p in ('reference_interfaces', 'reference_system', 'autoware_reference_system'))
    env = {'LD_LIBRARY_PATH': libs + ':' + os.environ.get('LD_LIBRARY_PATH', ''),
           'AMENT_PREFIX_PATH': ':'.join(f'{WS}/{p}' for p in ('reference_interfaces', 'reference_system', 'autoware_reference_system'))
           + ':' + os.environ.get('AMENT_PREFIX_PATH', '')}
    exe = os.environ.get('REFSYS_EXE', 'autoware_default_prioritized')
    return launch.LaunchDescription([
        ExecuteProcess(cmd=[f'{WS}/autoware_reference_system/lib/autoware_reference_system/{exe}'],
                       additional_env=env, output='screen'),
    ])
