#!/usr/bin/env python3
# Generated by Claude Opus 5 (Anthropic)
"""check_lifting — does a stored model obey the lifting rule?

The model defines every interaction at the callback layer and every coarser
layer as the union of what is underneath:

    E(u,v) = U_{a in Z*_u, b in Z*_v} E(a,b)

so two properties must hold at every layer boundary:

  * completeness — every pair of vertices with a callback-layer edge between
    their callbacks has an edge at the coarser layer;
  * support — every coarse edge has at least one callback-layer edge under it.

A violation of the first means an interaction stops at the layer it was born
in (join and state edges used to do exactly that); a violation of the second
means a coarse edge claims an interaction that never happened.

usage: check_lifting.py [session_id] [scope]
exit status 0 if the model obeys the rule, 1 otherwise.
"""
import collections
import sys

import psycopg2

DSN = 'host=localhost port=5432 dbname=fish user=fish password=fish'
LAYERS = [('L2', 1, 'entity'), ('L1', 2, 'node'), ('L0', 3, 'executor')]


def load(session_id, scope):
    c = psycopg2.connect(DSN).cursor()
    c.execute("SELECT source, target FROM graph_edges "
              "WHERE session_id=%s AND scope=%s AND rel='contains'",
              (session_id, scope))
    parent = {t: s for s, t in c.fetchall()}
    c.execute("SELECT source, target, level, attrs FROM graph_edges "
              "WHERE session_id=%s AND scope=%s AND rel='comm'",
              (session_id, scope))
    edges = collections.defaultdict(list)
    for s, t, level, attrs in c.fetchall():
        edges[level].append((s, t, attrs or {}))
    if not edges:
        sys.exit(f"no model stored for ({session_id}, {scope})")
    return parent, edges


def ancestor(parent, v, hops):
    for _ in range(hops):
        v = parent.get(v)
        if v is None:
            return None
    return v


def main():
    session_id = sys.argv[1] if len(sys.argv) > 1 else 'fish_20260906_151532'
    scope = sys.argv[2] if len(sys.argv) > 2 else '__main__'
    parent, edges = load(session_id, scope)

    print(f"({session_id}, {scope})")
    print("  callback-layer interactions:",
          dict(collections.Counter(a.get('nature', '?') for _, _, a in edges['L3'])))

    ok = True
    for level, hops, name in LAYERS:
        union = collections.defaultdict(list)
        unattached = contained = 0
        for s, t, a in edges['L3']:
            us, ut = ancestor(parent, s, hops), ancestor(parent, t, hops)
            if us is None or ut is None:
                # an external peer has no node and no executor of its own
                unattached += 1
                continue
            if us == ut:
                # contained by one vertex of this layer, not an edge of it
                contained += 1
                continue
            union[(us, ut)].append(a)
        have = {(s, t) for s, t, _ in edges[level] if s != t}
        missing = set(union) - have
        unsupported = have - set(union)
        print(f"  {level} ({name}): {len(have)} edges, union of the callback "
              f"layer gives {len(union)}"
              + (f", {unattached} interactions have no {name}" if unattached else "")
              + (f", {contained} contained inside one {name}" if contained else ""))
        if missing:
            ok = False
            nat = collections.Counter(a.get('nature', '?')
                                      for p in missing for a in union[p])
            print(f"    MISSING {len(missing)} pair(s) the union requires: {dict(nat)}")
        if unsupported:
            ok = False
            print(f"    UNSUPPORTED {len(unsupported)} edge(s) with no "
                  f"callback-layer interaction under them")

    print("  lifting rule holds" if ok else "  LIFTING RULE VIOLATED")
    return 0 if ok else 1


if __name__ == '__main__':
    sys.exit(main())
