#!/usr/bin/env python3
# Generated by Claude Opus 5 (Anthropic)
"""dag_segment — one *slice* of a typed GPU DAG, in the April style, laid out
for a figure panel.

`dag_signatures.py` draws a whole signature top-to-bottom; a 200-operation
callback is then far too tall for a two-column figure.  This cuts a range of
operations out of one signature and can lay it left-to-right, which is the
shape a wide panel wants.

Usage:
  python3 -m postprocess.dag_segment <session> --anchor 0x796A25ED7560 \
      [--sig 0] [--from 0 --to 30] [--rankdir LR] [-o DIR] [--base NAME]

  --list  prints the operations of the chosen signature with their indices,
          so a meaningful range can be picked before rendering.
"""
from __future__ import annotations
import argparse, collections, html, json, os, subprocess, sys
HERE = os.path.dirname(os.path.abspath(__file__)); sys.path.insert(0, HERE)
import psycopg2, psycopg2.extras
from dag_signatures import FILL, STREAM_FILL, EDGE, _us

DSN = os.environ.get('FISH_PG_DSN', 'host=localhost port=5432 dbname=fish user=fish password=fish')


def render_segment(shape, i0, i1, title, base, rankdir='LR', show_title=True):
    nodes = [n for n in shape['nodes'] if i0 <= n['idx'] < i1]
    keep = {n['idx'] for n in nodes}
    edges = [(u, v, k) for (u, v, k) in shape['edges'] if u in keep and v in keep]
    L = ['digraph seg {', f'  rankdir={rankdir};',
         '  node [shape=box, style="filled,rounded", fontname="Helvetica", fontsize=9, margin="0.05,0.02"];',
         '  edge [fontname="Helvetica", fontsize=7];',
         '  graph [nodesep=0.12, ranksep=0.28];']
    if show_title:
        L.append(f'  label="{title}"; labelloc=t; labeljust=l; fontsize=10;')
    streams = collections.defaultdict(list)
    for n in nodes:
        if n.get('stream') is not None:
            streams[n['stream']].append(n['idx'])
    band = {st: STREAM_FILL[k % len(STREAM_FILL)] for k, st in enumerate(sorted(streams))}
    for st in sorted(streams):
        L.append(f'  subgraph cluster_s{st} {{')
        L.append(f'    label="stream {st}"; labelloc=t; labeljust=l; '
                 f'style="filled,rounded"; fillcolor="{band[st]}"; '
                 f'fontname="Helvetica-Bold"; fontsize=9; color="#bbbbbb";')
        L.append(f'    {" ".join("n%d;" % i for i in streams[st])}')
        L.append('  }')
    for n in nodes:
        pe = n.get('pe', 'CPU'); name = n.get('name') or '?'
        lo, hi = n.get('c_min_ns'), n.get('c_max_ns')
        dur = '' if lo is None else (f'\\n{_us(lo)}' if lo == hi else f'\\n{_us(lo)}\u2013{_us(hi)}')
        extra = ''
        if n.get('stream') is not None:
            extra += f' s{n["stream"]}'
        if n.get('bytes'):
            extra += f' {n["bytes"]}B'
        if n.get('blocks'):
            extra += f' {n["blocks"]}\u00d7{n.get("threads_per_block", "?")}'
        tip = f'{pe}:{name}' + ('' if lo is None else f'\\nduration min={_us(lo)} max={_us(hi)}')
        L.append(f'  n{n["idx"]} [label="{pe}\\n{html.escape(name)}{dur}{extra}", '
                 f'fillcolor="{FILL.get(pe, "#dddddd")}", tooltip="{html.escape(tip)}"];')
    for (u, v, k) in edges:
        L.append(f'  n{u} -> n{v} [{EDGE.get(k, "")}];')
    L.append('}')
    open(base + '.dot', 'w').write('\n'.join(L))
    ok = True
    for fmt in ('svg', 'pdf', 'png'):
        try:
            subprocess.check_call(['dot', f'-T{fmt}'] + (['-Gdpi=150'] if fmt == 'png' else [])
                                  + [base + '.dot', '-o', f'{base}.{fmt}'],
                                  stderr=subprocess.DEVNULL, timeout=600)
        except Exception as e:
            print(f'   dot -T{fmt} failed: {e}'); ok = False
    print(f'[segment] {base}.svg  ops {i0}..{i1-1} ({len(nodes)} nodes, {len(edges)} edges, '
          f'{len(streams)} stream band(s))')
    return ok


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('session'); ap.add_argument('--scope', default='__main__')
    ap.add_argument('--anchor', required=True)
    ap.add_argument('--sig', type=int, default=0, help='signature rank by invocation count')
    ap.add_argument('--from', dest='i0', type=int, default=0)
    ap.add_argument('--to', dest='i1', type=int, default=10**9)
    ap.add_argument('--rankdir', default='LR')
    ap.add_argument('--no-title', action='store_true')
    ap.add_argument('-o', '--outdir', default=os.path.join('paper', 'figures', 'gpu_panel'))
    ap.add_argument('--base', default=None)
    ap.add_argument('--list', action='store_true')
    a = ap.parse_args()
    conn = psycopg2.connect(DSN, cursor_factory=psycopg2.extras.RealDictCursor); conn.autocommit = True
    cur = conn.cursor()
    cur.execute("""SELECT anchor_type, anchor, node, entity, n_invocations, dags FROM gpu_dags
                   WHERE session_id=%s AND scope=%s AND lower(anchor)=lower(%s)""",
                (a.session, a.scope, a.anchor))
    r = cur.fetchone()
    if not r:
        sys.exit(f'no gpu_dags row for anchor {a.anchor} in {a.session}')
    shapes = r['dags'] if isinstance(r['dags'], list) else json.loads(r['dags'])
    shapes = [s for s in shapes if s.get('nodes') and not s.get('truncated')]
    shapes.sort(key=lambda s: -int(s.get('count') or 0))
    sh = shapes[a.sig]
    nick = f"{r['node']} ← {r['entity']}" if r['entity'] else r['node']
    n_all = sum(int(s.get('count') or 0) for s in shapes) or 1
    cnt = int(sh.get('count') or 0)
    if a.list:
        print(f"{nick}: signature {str(sh.get('signature'))[:12]} ×{cnt} of {n_all}, "
              f"{len(sh['nodes'])} ops, phase {sh.get('phase')}")
        for n in sh['nodes']:
            st = f" s{n['stream']}" if n.get('stream') is not None else ''
            print(f"  {n['idx']:>4}  {n['pe']:<3} {(n.get('name') or '?')[:60]:<60}{st}")
        return
    i1 = min(a.i1, len(sh['nodes']))
    os.makedirs(a.outdir, exist_ok=True)
    base = os.path.join(a.outdir, a.base or f"seg_{str(r['anchor']).replace('0x','').lower()}_{a.i0}_{i1}")
    title = (f"{nick} · signature {str(sh.get('signature'))[:12]} ×{cnt} of {n_all} "
             f"({100*cnt/n_all:.1f} %) · operations {a.i0}\u2013{i1-1} of {len(sh['nodes'])}")
    render_segment(sh, a.i0, i1, title, base, a.rankdir, show_title=not a.no_title)


if __name__ == '__main__':
    main()
