#!/usr/bin/env python3
# Generated by Claude Opus 5 (Anthropic)
"""dag_signatures — one full typed DAG per observed signature, for every
GPU-submitting callback of a session (the un-collapsed counterpart of the
conditional graph). Reads gpu_dags from PostgreSQL.

Usage: python3 -m postprocess.dag_signatures <session_id> [-o OUTDIR] [--max-nodes 600]
"""
from __future__ import annotations
import argparse, collections, html, json, os, subprocess, sys
HERE = os.path.dirname(os.path.abspath(__file__)); sys.path.insert(0, HERE)
import psycopg2, psycopg2.extras

DSN = os.environ.get('FISH_PG_DSN', 'host=localhost port=5432 dbname=fish user=fish password=fish')
# April-2026 figure style (gpu_task_graph_viz.py): PE colours, TB layout,
# node label "PE / api / duration [+ bytes, stream]", edges launch solid dark,
# cpu_order dashed grey, stream_fifo thick coloured.
FILL = {'CPU': '#6BAED6', 'SM': '#74C476', 'CE': '#FB6A4A'}
# stream band fills, as in the April figures (one pastel per stream, cycled)
STREAM_FILL = ['#FDE0DD', '#FEF0D9', '#F0F9E8', '#FEE8C8', '#E7E1EF', '#DEEBF7', '#FFF7BC']
EDGE = {'launch': 'color="#333333"',
        'cpu_order': 'style=dashed, color="#999999"',
        'stream_fifo': 'color="#FB6A4A", penwidth=1.2'}


def _us(ns):
    return f'{ns/1e3:.1f}\u00b5s'


def render(shape, title, base):
    """One typed DAG in the April style."""
    L = ['digraph gpudag {', '  rankdir=TB;',
         '  node [shape=box, style="filled,rounded", fontname="Helvetica", fontsize=9, margin="0.05,0.02"];',
         '  edge [fontname="Helvetica", fontsize=7];',
         f'  label="{title}"; labelloc=t; labeljust=l; fontsize=10;',
         '  graph [nodesep=0.10, ranksep=0.25];']
    # stream bands: SM/CE nodes grouped in a coloured cluster per stream,
    # the GPU-side counterpart of the namespace bands in the model figure
    streams = collections.defaultdict(list)
    for n in shape['nodes']:
        if n.get('stream') is not None:
            streams[n['stream']].append(n['idx'])
    stream_of = {i: st for st, idxs in streams.items() for i in idxs}
    band = {st: STREAM_FILL[k % len(STREAM_FILL)] for k, st in enumerate(sorted(streams))}
    for st in sorted(streams):
        L.append(f'  subgraph cluster_s{st} {{')
        L.append(f'    label="stream {st}"; style="filled,rounded"; fillcolor="{band[st]}"; '
                 f'fontname="Helvetica-Bold"; fontsize=9; color="#bbbbbb";')
        L.append(f'    {" ".join("n%d;" % i for i in streams[st])}')
        L.append('  }')
    for n in shape['nodes']:
        pe = n.get('pe', 'CPU')
        name = (n.get('name') or '?')
        lo, hi = n.get('c_min_ns'), n.get('c_max_ns')
        dur = ''
        if lo is not None and hi is not None:
            dur = f'\\n{_us(lo)}' if lo == hi else f'\\n{_us(lo)}\u2013{_us(hi)}'
        extra = ''
        if n.get('stream') is not None:
            extra += f' s{n["stream"]}'
        if n.get('bytes'):
            extra += f' {n["bytes"]}B'
        if n.get('blocks'):
            extra += f' {n["blocks"]}\u00d7{n.get("threads_per_block", "?")}'
        tip = f'{pe}:{name}'
        if lo is not None:
            tip += f'\\nduration min={_us(lo)} max={_us(hi)}'
        if n.get('corr_id') is not None:
            tip += f'\\ncorrelation id {n["corr_id"]}'
        L.append(f'  n{n["idx"]} [label="{pe}\\n{html.escape(name)}{dur}{extra}", '
                 f'fillcolor="{FILL.get(pe, "#dddddd")}", tooltip="{html.escape(tip)}"];')
    for (u, v, k) in shape['edges']:
        L.append(f'  n{u} -> n{v} [{EDGE.get(k, "")}];')
    L.append('}')
    open(base + '.dot', 'w').write('\n'.join(L))
    try:
        subprocess.check_call(['dot', '-Tsvg', base + '.dot', '-o', base + '.svg'],
                              stderr=subprocess.DEVNULL, timeout=900)
        return True
    except Exception as e:
        print(f'   dot failed: {e}')
        return False


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('session'); ap.add_argument('--scope', default='__main__')
    ap.add_argument('-o', '--outdir', default=None); ap.add_argument('--max-nodes', type=int, default=600)
    a = ap.parse_args()
    out = a.outdir or os.path.join('paper', 'dag_gallery', a.session + '_signatures')
    os.makedirs(out, exist_ok=True)
    conn = psycopg2.connect(DSN, cursor_factory=psycopg2.extras.RealDictCursor); conn.autocommit = True
    cur = conn.cursor()
    cur.execute("""SELECT anchor_type, anchor, node, entity, n_invocations, dags FROM gpu_dags
                   WHERE session_id=%s AND scope=%s ORDER BY n_invocations DESC""", (a.session, a.scope))
    rows = cur.fetchall(); blocks = []
    for r in rows:
        shapes = r['dags'] if isinstance(r['dags'], list) else json.loads(r['dags'])
        tag = f"{r['anchor_type']}_{str(r['anchor']).replace('0x','').lower()}"
        total = sum(int(s.get('count') or 0) for s in shapes) or 1
        nick = (f"{r['node']} ← {r['entity']}" if r['entity'] else r['node']) or f"thread {r['anchor']}"
        print(f"{nick}: {len(shapes)} signature(s), {r['n_invocations']} invocations")
        figs = []
        for i, s in enumerate(sorted(shapes, key=lambda x: -int(x.get('count') or 0))):
            cnt = int(s.get('count') or 0); ns = s.get('nodes') or []
            pe = collections.Counter(n['pe'] for n in ns)
            sig = str(s.get('signature') or '')[:12]
            head = (f"{nick} · signature {sig} · ×{cnt} of {total} ({100*cnt/total:.1f} %) · "
                    f"{len(ns)} nodes ({pe.get('CPU',0)} CPU / {pe.get('SM',0)} SM / {pe.get('CE',0)} CE) · "
                    f"phase {s.get('phase','?')}")
            if s.get('truncated') or not ns:
                figs.append(f'<p>{html.escape(head)} — stored as summary, not drawn</p>'); continue
            if len(ns) > a.max_nodes:
                figs.append(f'<p>{html.escape(head)} — too large to draw</p>'); continue
            base = os.path.join(out, f'{tag}_sig{i}_{sig}')
            if render(s, head, base):
                p = os.path.basename(base) + '.svg'
                figs.append(f'<div class="fig"><div class="cap">{html.escape(head)} · <a href="{p}">svg</a></div>'
                            f'<a href="{p}" target="_blank"><img src="{p}" loading="lazy"></a></div>')
        blocks.append(f'<div class="cb"><h2>{html.escape(nick)}</h2>'
                      f'<div class="meta">{r["anchor_type"]} {html.escape(str(r["anchor"]))} · '
                      f'{r["n_invocations"]} invocations · {len(shapes)} signatures</div>' + ''.join(figs) + '</div>')
    css = ("body{font-family:system-ui,sans-serif;max-width:1600px;margin:1em auto;color:#222}"
           "h1{font-size:1.4em}h2{font-size:1.05em;color:#1a5490;margin:.2em 0}"
           ".cb{border:1px solid #ddd;border-radius:6px;padding:.8em 1em;margin-bottom:1em;background:#fafafa}"
           ".meta{color:#666;font-size:.85em;margin-bottom:.6em}"
           ".fig{margin:.6em 0}.fig img{max-width:100%;border:1px solid #ccc;border-radius:4px;background:#fff}"
           ".cap{font-size:.82em;color:#444;margin:.2em 0}a{color:#1a5490}")
    open(os.path.join(out, 'index.html'), 'w').write(
        f'<!DOCTYPE html><html><head><meta charset="utf-8"><title>FISH signatures — {a.session}</title>'
        f'<style>{css}</style></head><body><h1>Typed DAG per signature — {a.session}</h1>'
        f'<p class="meta">One figure per observed signature of every GPU-submitting callback '
        f'(the un-collapsed counterpart of the conditional graph).</p>' + ''.join(blocks) + '</body></html>')
    print(f'[signatures] {os.path.join(out, "index.html")}')


if __name__ == '__main__':
    main()
