#!/usr/bin/env python3
# Generated by Claude Fable 5.1 (Anthropic), 2026-10-03
"""Export a task set for a callback chain from a FISH model (PostgreSQL).

Usage:
  python3 export_taskset.py <session_id> --nodes 'REGEX' [--scope __main__]
         [--ksched analysis/nsys_1.ksched.tsv] [-o taskset.json] [--steady-only]

Per callback (node, entity): instances n, window length mean/p50/p99/max (ns),
arrival period estimate (median gap of starts), executor (type, threads, mode),
callback group, and — with --ksched — on-CPU / preempted / runnable / sleeping
per instance from the sched_switch split (ksched_split.py TSV).
Per edge between those callbacks: kind (sub / srv / join / polled-msg / tf),
flow method and hop or age p50/p90/max (ns).  Output: JSON + a table on stdout.
Timing figures are from the trace, not WCETs: the consumer (an RTA) decides how
to inflate them."""
import argparse, json, re, statistics as st, sys, collections
import psycopg2, psycopg2.extras
sys.path.insert(0, __file__.rsplit('/', 1)[0] if '/' in __file__ else '.')
from topic_class import topic_class

DSN = 'host=localhost port=5432 dbname=fish user=fish password=fish'
INFRA_ENTITIES = ('sub:/clock', 'sub:/parameter_events', 'sub:/tf', 'sub:/tf_static', 'sub:/rosout')

def q(a, p): a = sorted(a); return a[int(p * (len(a) - 1))] if a else None

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('session'); ap.add_argument('--scope', default='__main__')
    ap.add_argument('--nodes', required=True, help='regex on node name')
    ap.add_argument('--ksched', default=None, help='ksched_split TSV for this session')
    ap.add_argument('-o', '--out', default=None)
    ap.add_argument('--steady-only', action='store_true', help='drop the first 10 %% of each callback\'s instances')
    ap.add_argument('--min-n', type=int, default=10, help='drop callbacks with fewer instances (parameter services, init)')
    a = ap.parse_args()
    conn = psycopg2.connect(DSN, cursor_factory=psycopg2.extras.RealDictCursor); conn.autocommit = True; cur = conn.cursor()
    rx = re.compile(a.nodes)
    cur.execute("SELECT count(*) AS n FROM gantt_spans WHERE session_id=%s AND scope=%s", (a.session, a.scope))
    if cur.fetchone()['n'] == 0:
        import fish_viz_server as viz   # builds the per-instance callback windows for this session
        print('gantt_spans empty for this session — building them', file=sys.stderr)
        viz._ensure_gantt_spans(cur, a.session, a.scope)
    cur.execute("SELECT pid, vtid, t0_ns, t1_ns, cb_addr, node, entity, etype, symbol FROM gantt_spans "
                "WHERE session_id=%s AND scope=%s ORDER BY t0_ns", (a.session, a.scope))
    spans = collections.defaultdict(list); meta = {}
    for r in cur:
        if not r['node'] or not rx.search(r['node']): continue
        ent = r['entity'] or ''
        if ent in INFRA_ENTITIES or ent.startswith('sub:') and topic_class(ent[4:]) == 'infra': continue
        k = (r['node'], ent)
        spans[k].append((r['t0_ns'], r['t1_ns']))
        meta.setdefault(k, {'cb_addr': r['cb_addr'], 'pid': r['pid'], 'etype': r['etype'], 'symbol': r['symbol'], 'tids': set()})
        meta[k]['tids'].add(r['vtid'])
    if not spans:
        sys.exit(f'no callbacks match {a.nodes!r}')
    # executors by pid
    cur.execute("SELECT pid, attrs FROM graph_nodes WHERE session_id=%s AND scope=%s AND type='EX'", (a.session, a.scope))
    ex = {}
    for r in cur:
        at = r['attrs'] or {}; et = str(at.get('executor_type') or '')
        ex[r['pid']] = {'type': at.get('executor_type'), 'threads': at.get('num_threads'),
                        'mode': 'MT' if 'Multi' in et else 'ST' if 'Single' in et else at.get('mode')}
    # F vertices: cb_addr → node_id / attrs (callback group, phase, polled, join)
    cur.execute("SELECT node_id, cb_addr, attrs FROM graph_nodes WHERE session_id=%s AND scope=%s AND type='F' AND cb_addr IS NOT NULL",
                (a.session, a.scope))
    f_by_cb = {}; cb_by_f = {}
    for r in cur:
        f_by_cb.setdefault(r['cb_addr'], (r['node_id'], r['attrs'] or {})); cb_by_f[r['node_id']] = r['cb_addr']
    # ksched split
    ks = {}
    if a.ksched:
        with open(a.ksched) as fh:
            hdr = fh.readline().rstrip('\n').split('\t')
            for ln in fh:
                row = dict(zip(hdr, ln.rstrip('\n').split('\t')))
                ks[(row['node'], row['entity'])] = row
    cbs = []; cb_index = {}
    for (node, ent), ws in sorted(spans.items()):
        if len(ws) < a.min_n: continue
        if a.steady_only and len(ws) > 20:
            ws = ws[len(ws) // 10:]
        durs = [t1 - t0 for t0, t1 in ws]
        gaps = [ws[i + 1][0] - ws[i][0] for i in range(len(ws) - 1)]
        m = meta[(node, ent)]; f_id, fattrs = f_by_cb.get(m['cb_addr'], (None, {}))
        c = {'node': node, 'entity': ent, 'etype': m['etype'], 'cb_addr': m['cb_addr'], 'f_id': f_id,
             'pid': m['pid'], 'threads_used': len(m['tids']), 'executor': ex.get(m['pid']),
             'callback_group': fattrs.get('callback_group'), 'polled': fattrs.get('polled'),
             'join_role': fattrs.get('join_role'), 'phase': fattrs.get('phase'),
             'n': len(ws), 'window_ns': {'mean': int(st.mean(durs)), 'p50': q(durs, .5), 'p99': q(durs, .99), 'max': max(durs)},
             'period_ns': {'median_gap': q(gaps, .5), 'p10_gap': q(gaps, .1), 'p90_gap': q(gaps, .9)} if gaps else None}
        k = ks.get((node, ent))
        if k:
            n = int(k['n']) or 1
            c['sched_split_ns_per_instance'] = {f: int(int(k[f]) / n) for f in ('wall', 'on', 'preempted', 'runnable', 'sleeping') if f in k}
            c['sched_split_n'] = int(k['n'])
        cbs.append(c)
        if f_id is not None: cb_index[f_id] = (node, ent)
    # edges among these callbacks
    cur.execute("SELECT source, target, attrs FROM graph_edges WHERE session_id=%s AND scope=%s AND level='L3' AND rel='comm'",
                (a.session, a.scope))
    edges = []
    for r in cur:
        if r['source'] in cb_index and r['target'] in cb_index:
            at = r['attrs'] or {}
            nat = at.get('nature')
            kind = {'msg': 'sub', 'dep': 'srv', 'join': 'join', 'state': ('tf' if at.get('evidence') == 'tf_lookup' else 'polled-msg' if at.get('polled') else 'state-inferred')}.get(nat, nat)
            e = {'src': cb_index[r['source']], 'dst': cb_index[r['target']], 'kind': kind, 'topic': at.get('topic') or at.get('service'),
                 'flow_method': at.get('flow_method'), 'flow_n': at.get('flow_n')}
            for f in ('hop_ns_p50', 'hop_ns_p90', 'hop_ns_max', 'age_ns_p50', 'age_ns_p90', 'age_ns_max'):
                if f in at: e[f] = at[f]
            edges.append(e)
    out = {'session': a.session, 'scope': a.scope, 'node_regex': a.nodes, 'callbacks': cbs, 'edges': edges,
           'executors': {str(p): v for p, v in ex.items() if any(c['pid'] == p for c in cbs)}}
    if a.out:
        json.dump(out, open(a.out, 'w'), indent=1, default=list); print(f'wrote {a.out}')
    # table
    print(f"{'node':34s} {'entity':52s} {'n':>5s} {'win_mean':>9s} {'win_p99':>9s} {'period':>8s} {'onCPU':>8s} {'preempt':>8s} {'runnabl':>8s} {'sleep':>8s} exec")
    for c in cbs:
        s = c.get('sched_split_ns_per_instance') or {}
        ms = lambda v: f"{v/1e6:8.2f}" if v is not None else '       -'
        exs = c['executor'] or {}
        print(f"{c['node'][:34]:34s} {c['entity'][:52]:52s} {c['n']:5d} {ms(c['window_ns']['mean'])} {ms(c['window_ns']['p99'])} "
              f"{ms((c['period_ns'] or {}).get('median_gap'))} {ms(s.get('on'))} {ms(s.get('preempted'))} {ms(s.get('runnable'))} {ms(s.get('sleeping'))} "
              f"{(exs.get('mode') or '?')}/{exs.get('threads') or '?'}")
    print(f"\n{len(edges)} edge(s) among these callbacks:")
    for e in sorted(edges, key=lambda e: (e['src'], e['dst'])):
        hop = e.get('hop_ns_p50') or e.get('age_ns_p50')
        print(f"  {e['src'][0][:28]:28s} → {e['dst'][0][:28]:28s} {e['kind']:10s} {(e['topic'] or '')[:55]:55s} {e['flow_method'] or '-':9s} "
              f"{'' if hop is None else f'{hop/1e6:.3f} ms'}")

if __name__ == '__main__':
    main()
