#!/usr/bin/env python3
# Generated by Claude Fable 5 (Anthropic)
"""GPU Typed-DAG extraction — PostgreSQL port of gpu_dag.py (2026-08-31).

Same Typed DAG per PDF §4.5 (CPU/SM/CE nodes, launch/cpu_order/stream_fifo
edges), same signature aggregation + phase classification (imported from
gpu_dag.py), two anchor modes instead of oort-only:

  * cb  — callback-anchored: every gantt span of a cb_addr that contains CUDA
          runtime calls is ONE invocation (no gap heuristic needed — the
          callback boundaries are the period boundaries).
  * tid — thread-anchored: CUDA activity OUTSIDE any callback span, per thread
          (the NITROS/GXF worker case, and classic oort threads). Periods via
          the original sync+gap detector.

Results land in table gpu_dags (session, scope, anchor_type, anchor) and are
mirrored into graph_nodes.attrs['gpu_dags'] for F vertices that match
(cb anchors via cb_addr; tid anchors via oort F thread_tid).

Usage:
  python3 -m postprocess.gpu_dag_pg <session_id> [--scope __main__]
      [--gap-ms 5] [--min-gpu-ops 2] [--dry-run] [--max-api-rows 2000000]
"""
from __future__ import annotations

import argparse
import json
import os
import sys
import time
from collections import defaultdict

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import numpy as np
import psycopg2
import psycopg2.extras

from gpu_dag import (build_typed_dag, dag_signature, classify_phases,
                     detect_periods, filter_productive)

PG_DSN = os.environ.get(
    "FISH_PG_DSN", "host=localhost port=5432 dbname=fish user=fish password=fish")


def log(msg):
    print(f"[gpu_dag_pg] {msg}", flush=True)


DDL = """
CREATE TABLE IF NOT EXISTS gpu_dags (
  session_id text NOT NULL, scope text NOT NULL,
  anchor_type text NOT NULL,          -- 'cb' | 'tid'
  anchor text NOT NULL,               -- cb_addr | tid number as text
  node text, entity text,             -- context labels (cb anchors)
  n_invocations bigint, n_shapes int,
  dags jsonb NOT NULL,
  updated_at timestamptz DEFAULT now(),
  PRIMARY KEY (session_id, scope, anchor_type, anchor)
);
"""


def _index_gpu_side(cur, sid):
    """correlation → gpu-side row dicts with the key names build_typed_dag
    expects (Influx-era camelCase)."""
    t0 = time.time()
    cur.execute("""
        SELECT correlation_id AS "correlationId", stream_id AS "streamId",
               kernel_name, kernel_short_name,
               grid_x AS "gridX", grid_y AS "gridY", grid_z AS "gridZ",
               block_x AS "blockX", block_y AS "blockY", block_z AS "blockZ",
               duration_ns, source
        FROM gpu_kernels WHERE session_id=%s
    """, (sid,))
    kern = {}
    for r in cur.fetchall():
        kern[(r["source"], r["correlationId"])] = r
    cur.execute("""
        SELECT correlation_id AS "correlationId", stream_id AS "streamId",
               copy_kind AS "copyKind", bytes, duration_ns, source
        FROM gpu_memcpy WHERE session_id=%s
    """, (sid,))
    mcpy = {}
    for r in cur.fetchall():
        mcpy[(r["source"], r["correlationId"])] = r
    mset = {}
    try:
        cur.execute("""
            SELECT correlation_id AS "correlationId", stream_id AS "streamId",
                   bytes, value, duration_ns, source
            FROM gpu_memset WHERE session_id=%s
        """, (sid,))
        for r in cur.fetchall():
            mset[(r["source"], r["correlationId"])] = r
    except Exception:
        pass
    log(f"  gpu-side indexed: kernels={len(kern):,} memcpys={len(mcpy):,} "
        f"memsets={len(mset):,} in {time.time()-t0:.1f}s")
    return kern, mcpy, mset


class _SourceView(dict):
    """kernels_by_corr view for one `source` (nsys report) so the imported
    build_typed_dag can keep using plain correlation keys."""
    def __init__(self, base, source):
        super().__init__()
        self._b, self._s = base, source
    def get(self, corr, default=None):
        return self._b.get((self._s, corr), default)


def _aggregate(periods_rows, api_names_flat, periods_idx, kern, mcpy, mset):
    """periods_rows: list of lists of api-row dicts (one list per invocation,
    each row carries 'source'). Returns the gpu_dags summary list (same shape
    as gpu_dag.extract_for_oort output)."""
    all_dags = []
    for rows in periods_rows:
        if not rows:
            all_dags.append({"nodes": [], "edges": []})
            continue
        src = rows[0]["source"]
        dag = build_typed_dag(rows, _SourceView(kern, src),
                              _SourceView(mcpy, src),
                              memsets_by_corr=_SourceView(mset, src))
        all_dags.append(dag)

    unique = {}
    for dag in all_dags:
        if not dag["nodes"]:
            continue
        sig = dag_signature(dag)
        if sig not in unique:
            durs = [n["duration_ns"] for n in dag["nodes"]]
            unique[sig] = {"count": 0, "template": dag,
                           "c_min": list(durs), "c_max": list(durs)}
        info = unique[sig]
        info["count"] += 1
        for i, node in enumerate(dag["nodes"]):
            d = int(node["duration_ns"])
            info["c_min"][i] = min(info["c_min"][i], d)
            info["c_max"][i] = max(info["c_max"][i], d)

    labels, _, _ = classify_phases(periods_idx, api_names_flat, all_dags)
    sig_to_phases = {}
    for lbl, dag in zip(labels, all_dags):
        if not dag["nodes"]:
            continue
        sg = dag_signature(dag)
        sig_to_phases.setdefault(sg, {}).setdefault(lbl, 0)
        sig_to_phases[sg][lbl] += 1

    out = []
    for sig, info in sorted(unique.items(), key=lambda kv: -kv[1]["count"]):
        tmpl_nodes = []
        for i, node in enumerate(info["template"]["nodes"]):
            tmpl_nodes.append({
                **{k: v for k, v in node.items() if k != "duration_ns"},
                "c_min_ns": info["c_min"][i], "c_max_ns": info["c_max"][i],
            })
        phases = sig_to_phases.get(sig, {})
        out.append({
            "signature": sig, "count": info["count"],
            "phase": max(phases, key=phases.get) if phases else "UNKNOWN",
            "phase_counts": phases,
            "nodes": tmpl_nodes, "edges": info["template"]["edges"],
        })
    return out


MAX_SHAPE_NODES = 800      # larger shapes stored as summaries (jsonb size cap)
MAX_SHAPES_STORED = 12


def _compress(dags):
    """Cap jsonb size: huge shapes → per-stream summary (no node/edge lists);
    at most MAX_SHAPES_STORED shapes stored in full detail order."""
    out = []
    for d in dags[:MAX_SHAPES_STORED]:
        if len(d.get("nodes", [])) <= MAX_SHAPE_NODES:
            out.append(d)
            continue
        streams = {}
        for n in d["nodes"]:
            st = n.get("stream")
            k = str(st) if st is not None else "cpu"
            e = streams.setdefault(k, {"n": 0, "SM": 0, "CE": 0, "CPU": 0})
            e["n"] += 1
            e[n["pe"]] = e.get(n["pe"], 0) + 1
        out.append({
            "signature": d["signature"], "count": d["count"],
            "phase": d.get("phase"), "phase_counts": d.get("phase_counts"),
            "truncated": True,
            "n_nodes": len(d["nodes"]), "n_edges": len(d.get("edges", [])),
            "stream_summary": streams,
        })
    if len(dags) > MAX_SHAPES_STORED:
        out.append({"signature": "…", "truncated": True,
                    "note": f"{len(dags) - MAX_SHAPES_STORED} more shapes not stored",
                    "count": sum(d["count"] for d in dags[MAX_SHAPES_STORED:])})
    return out


def extract(session, scope, gap_ms=5.0, min_gpu_ops=2, dry_run=False,
            max_api_rows=2_000_000):
    conn = psycopg2.connect(PG_DSN, cursor_factory=psycopg2.extras.RealDictCursor)
    conn.autocommit = True
    cur = conn.cursor()
    cur.execute(DDL)
    kern, mcpy, mset = _index_gpu_side(cur, session)

    # ---- callback-anchored --------------------------------------------------
    t0 = time.time()
    cur.execute("""
        SELECT sp.cb_addr, sp.node, sp.entity, sp.t0_ns AS span_t0,
               r.ts_ns, r.api_name, r.correlation_id AS "correlationId",
               r.duration_ns, r.source
        FROM gantt_spans sp
        JOIN cuda_runtime r ON r.session_id=sp.session_id
             AND r.tid=sp.vtid AND r.ts_ns BETWEEN sp.t0_ns AND sp.t1_ns
        WHERE sp.session_id=%s AND sp.scope=%s
        ORDER BY sp.cb_addr, sp.t0_ns, r.ts_ns
    """, (session, scope))
    rows = cur.fetchall()
    log(f"cb-anchored: {len(rows):,} in-span cuda rows in {time.time()-t0:.1f}s")

    by_cb = defaultdict(lambda: defaultdict(list))   # cb → span_t0 → rows
    cb_meta = {}
    for r in rows:
        by_cb[r["cb_addr"]][r["span_t0"]].append(r)
        cb_meta[r["cb_addr"]] = (r["node"], r["entity"])

    n_saved = 0
    for cb, spans in by_cb.items():
        periods_rows = [spans[k] for k in sorted(spans)]
        # flatten for classify_phases (index space = concatenated rows)
        api_names_flat, periods_idx, pos = [], [], 0
        for pr in periods_rows:
            api_names_flat.extend(x["api_name"] for x in pr)
            periods_idx.append((pos, pos + len(pr) - 1))
            pos += len(pr)
        dags = _aggregate(periods_rows, api_names_flat, periods_idx,
                          kern, mcpy, mset)
        if not dags:
            continue
        node, entity = cb_meta.get(cb, (None, None))
        log(f"  cb {cb} ({node} · {entity}): {len(periods_rows)} invocations "
            f"→ {len(dags)} shape(s) "
            + ", ".join(f"{d['phase']}×{d['count']}" for d in dags[:4]))
        if not dry_run:
            cur.execute("""
                INSERT INTO gpu_dags (session_id, scope, anchor_type, anchor,
                                      node, entity, n_invocations, n_shapes, dags)
                VALUES (%s,%s,'cb',%s,%s,%s,%s,%s,%s)
                ON CONFLICT (session_id, scope, anchor_type, anchor)
                DO UPDATE SET node=EXCLUDED.node, entity=EXCLUDED.entity,
                              n_invocations=EXCLUDED.n_invocations,
                              n_shapes=EXCLUDED.n_shapes, dags=EXCLUDED.dags,
                              updated_at=now()
            """, (session, scope, cb, node, entity, len(periods_rows),
                  len(dags), json.dumps(_compress(dags))))
            cur.execute("""
                UPDATE graph_nodes SET attrs = attrs || jsonb_build_object(
                    'gpu_dags_shapes', %s, 'gpu_dags_invocations', %s)
                WHERE session_id=%s AND scope=%s AND type='F' AND cb_addr=%s
            """, (len(dags), len(periods_rows), session, scope, cb))
            n_saved += 1
    log(f"cb-anchored: {n_saved} callbacks saved")

    # ---- thread-anchored (outside any callback span) ------------------------
    t1 = time.time()
    cur.execute("""
        SELECT r.tid, r.ts_ns, r.api_name, r.correlation_id AS "correlationId",
               r.duration_ns, r.source
        FROM cuda_runtime r
        WHERE r.session_id=%s AND NOT EXISTS (
            SELECT 1 FROM gantt_spans sp
            WHERE sp.session_id=r.session_id AND sp.scope=%s
              AND sp.vtid=r.tid AND r.ts_ns BETWEEN sp.t0_ns AND sp.t1_ns)
        ORDER BY r.tid, r.ts_ns
        LIMIT %s
    """, (session, scope, max_api_rows))
    rows = cur.fetchall()
    log(f"tid-anchored: {len(rows):,} out-of-span cuda rows in {time.time()-t1:.1f}s")
    by_tid = defaultdict(list)
    for r in rows:
        by_tid[r["tid"]].append(r)

    gap_ns = int(gap_ms * 1e6)
    n_saved_t = 0
    for tid, trows in sorted(by_tid.items(), key=lambda kv: -len(kv[1])):
        if len(trows) < 10:
            continue
        times = np.array([r["ts_ns"] for r in trows], dtype="int64")
        names = [r["api_name"] for r in trows]
        all_p = detect_periods(times, names, gap_ns)
        prod = filter_productive(all_p, names, min_gpu_ops=min_gpu_ops)
        if not prod:
            continue
        periods_rows = [trows[s:e+1] for (s, e) in prod]
        dags = _aggregate(periods_rows, names, prod, kern, mcpy, mset)
        if not dags:
            continue
        log(f"  tid {tid}: {len(trows):,} rows, {len(prod)} productive periods "
            f"→ {len(dags)} shape(s) "
            + ", ".join(f"{d['phase']}×{d['count']}" for d in dags[:4]))
        if not dry_run:
            cur.execute("""
                INSERT INTO gpu_dags (session_id, scope, anchor_type, anchor,
                                      node, entity, n_invocations, n_shapes, dags)
                VALUES (%s,%s,'tid',%s,NULL,NULL,%s,%s,%s)
                ON CONFLICT (session_id, scope, anchor_type, anchor)
                DO UPDATE SET n_invocations=EXCLUDED.n_invocations,
                              n_shapes=EXCLUDED.n_shapes, dags=EXCLUDED.dags,
                              updated_at=now()
            """, (session, scope, str(tid), len(prod), len(dags),
                  json.dumps(_compress(dags))))
            n_saved_t += 1
            # classic oort F mirror
            cur.execute("""
                UPDATE graph_nodes SET attrs = attrs || jsonb_build_object(
                    'gpu_dags_shapes', %s, 'gpu_dags_invocations', %s)
                WHERE session_id=%s AND scope=%s AND type='F'
                  AND ptype='oort' AND attrs->>'thread_tid'=%s
            """, (len(dags), len(prod), session, scope, str(tid)))
    log(f"tid-anchored: {n_saved_t} threads saved")
    conn.close()


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("session")
    ap.add_argument("--scope", default="__main__")
    ap.add_argument("--gap-ms", type=float, default=5.0)
    ap.add_argument("--min-gpu-ops", type=int, default=2)
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--max-api-rows", type=int, default=2_000_000)
    args = ap.parse_args()
    extract(args.session, args.scope, gap_ms=args.gap_ms,
            min_gpu_ops=args.min_gpu_ops, dry_run=args.dry_run,
            max_api_rows=args.max_api_rows)


if __name__ == "__main__":
    main()
