#!/usr/bin/env python3
# Generated by Claude Opus 5 (Anthropic)
"""ksched_split — where does a callback's wall time go: on the CPU, waiting for
a CPU, or asleep?

Reads the kernel sched_switch session FISH writes to <session_dir>/kernel when
run with FISH_KERNEL_SCHED=1, rebuilds every thread's on-CPU and off-CPU
intervals, and intersects them with the callback spans (gantt_spans) and the
CUDA runtime calls (cuda_runtime) of the same session in PG.

Off-CPU intervals carry the state the thread left the CPU in (lttng-modules,
kernel 6.8):
    256  preempted            runnable, preempted inside the kernel
      0  runnable             runnable, CPU taken in user mode (PREEMPT_VOLUNTARY
                              records a user-mode preemption as state 0; these
                              threads do not call sched_yield)
      1  sleeping (S)         futex / poll / ioctl wait
      2  uninterruptible (D)
Any other state is counted as 'other'; wall time covered by neither an on-CPU
nor an off-CPU interval is printed as 'unaccounted', so each row sums to wall.
For a CUDA call this separates the driver's wait policies: spin (no switch at
all), runnable switches, and blocking sync (state 1).

If the kernel session also carries sched_waking, every wake-up names its
waker (the task running on that cpu) and wakee.  Threads of the callback's
own process that the callback's thread wakes inside its window (OpenMP /
pthread helpers) are charged to it as 'assist' CPU, from the wake-up until
they next sleep, minus their own callback windows (a woken executor thread
running its own callback is a dispatch, not a helper).

Timestamps are converted exactly as ingest_pg does (babeltrace local time of
day + the session date, with the midnight roll), so they share the ros2_trace /
cuda_runtime clock; the fraction of callback starts found on-CPU is printed as
the check.

usage: ksched_split.py <session_dir> [--session-id ID] [--scope __main__] [--tsv FILE]
"""
import argparse
import collections
import os
import re
import subprocess
import sys
import time
from array import array

import numpy as np
import psycopg2

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from ingest_pg import session_start_ts, DEFAULT_TZ  # noqa: E402

DSN = os.environ.get('FISH_PG_DSN', 'host=localhost port=5432 dbname=fish user=fish password=fish')
STR = r'"(?:[^"\\]|\\.)*"'
LINE = re.compile(
    r'^\[(\d\d):(\d\d):(\d\d)\.(\d{9})\] \S+ \S+ sched_switch: '
    r'\{ cpu_id = (\d+) \}, \{ vtid = (\d+), vpid = (\d+), procname = (' + STR + r') \}, '
    r'\{ prev_comm = ' + STR + r', prev_tid = (\d+), prev_prio = -?\d+, prev_state = (-?\d+), '
    r'next_comm = ' + STR + r', next_tid = (\d+), next_prio = -?\d+ \}')
WLINE = re.compile(
    r'^\[(\d\d):(\d\d):(\d\d)\.(\d{9})\] \S+ \S+ sched_waking: '
    r'\{ cpu_id = (\d+) \}, \{ vtid = (\d+), vpid = (\d+), procname = ' + STR + r' \}, '
    r'\{ comm = ' + STR + r', tid = (\d+), prio = -?\d+, target_cpu = \d+ \}')
FLINE = re.compile(
    r'^\[(\d\d):(\d\d):(\d\d)\.(\d{9})\] \S+ \S+ syscall_(entry|exit)_futex: '
    r'\{ cpu_id = (\d+) \}, \{ vtid = (\d+), vpid = (\d+), procname = ' + STR + r' \}, \{ (.*) \}')
FUTEX_WAIT_OPS = {0, 9, 6, 11}          # FUTEX_WAIT, WAIT_BITSET, LOCK_PI, WAIT_REQUEUE_PI (op & 127)
GLINE = re.compile(
    r'^\[(\d\d):(\d\d):(\d\d)\.(\d{9})\] \S+ \S+ gomp_parallel(?:_loop)?: '
    r'\{ cpu_id = (\d+) \}')           # GOMP_parallel uprobe: region start in the master thread's context (A0.2)
STATE = {256: 'preempted', 0: 'runnable', 1: 'sleeping', 2: 'uninterruptible'}


def parse_kernel(session_dir, tz):
    """Stream the kernel CTF once; return on/off interval arrays and the
    host tid -> (vtid, vpid, comm) context map."""
    kdir = os.path.join(session_dir, 'kernel')
    if not os.path.isdir(kdir):
        sys.exit(f'no kernel trace in {kdir} (run with FISH_KERNEL_SCHED=1)')
    base = session_start_ts(session_dir, tz)
    midnight = base.replace(hour=0, minute=0, second=0, microsecond=0).timestamp()
    on_tid, on_t0, on_t1 = array('i'), array('q'), array('q')
    off_tid, off_t0, off_t1, off_st = array('i'), array('q'), array('q'), array('i')
    wk_ts, wk_waker, wk_wakee = array('q'), array('i'), array('i')
    fx_tid, fx_t0, fx_t1, fx_addr = array('i'), array('q'), array('q'), array('q')   # futex WAIT intervals (A0.4)
    pending_fx = {}; nfx = 0
    gp_tid, gp_ts = array('i'), array('q')   # OpenMP parallel region starts per master thread (A0.2)
    ngp = 0
    running, pending, ctx = {}, {}, {}
    last_day, extra = None, 0
    n = bad = nw = nw_unk = 0
    t = time.time()
    proc = subprocess.Popen(['babeltrace2', kdir], stdout=subprocess.PIPE,
                            stderr=subprocess.DEVNULL, text=True, bufsize=1 << 20)
    for line in proc.stdout:
        m = LINE.match(line)
        if not m:
            w = WLINE.match(line)
            if not w:
                fx = FLINE.match(line)
                if not fx:
                    g = GLINE.match(line)
                    if g:
                        hh, mm, ss, ns, cpu = g.groups()
                        day = int(hh) * 3600 + int(mm) * 60 + int(ss)
                        if last_day is not None and day < last_day - 43200:
                            extra += 1
                        last_day = day
                        ts = int((midnight + extra * 86400 + day)) * 1_000_000_000 + int(ns)
                        r = running.get(int(cpu))
                        if r is not None and r[0]:
                            gp_tid.append(r[0]); gp_ts.append(ts); ngp += 1
                        continue
                    bad += 1
                    continue
                # futex entry/exit run in the calling thread's context: the task on that cpu
                hh, mm, ss, ns, kind, cpu, _vt, _vp, rest = fx.groups()
                day = int(hh) * 3600 + int(mm) * 60 + int(ss)
                if last_day is not None and day < last_day - 43200:
                    extra += 1
                last_day = day
                ts = int((midnight + extra * 86400 + day)) * 1_000_000_000 + int(ns)
                r = running.get(int(cpu))
                if r is None or not r[0]:
                    continue
                tid = r[0]
                if kind == 'entry':
                    mo = re.search(r'\bop = (\d+)', rest); ma = re.search(r'\buaddr = (0x[0-9A-Fa-f]+)', rest)
                    if mo and (int(mo.group(1)) & 127) in FUTEX_WAIT_OPS:
                        pending_fx[tid] = (ts, int(ma.group(1), 16) if ma else 0)
                    else:
                        pending_fx.pop(tid, None)
                else:
                    pf = pending_fx.pop(tid, None)
                    if pf is not None and ts > pf[0]:
                        fx_tid.append(tid); fx_t0.append(pf[0]); fx_t1.append(ts); fx_addr.append(pf[1] & 0x7FFFFFFFFFFFFFFF); nfx += 1
                continue
            # sched_waking fires in the waker's context: the task running on
            # that cpu wakes `tid` (host id).  Who is running comes from the
            # switch stream.
            hh, mm, ss, ns, cpu, _vt, _vp, wakee = w.groups()   # STR groups are non-capturing
            day = int(hh) * 3600 + int(mm) * 60 + int(ss)
            if last_day is not None and day < last_day - 43200:
                extra += 1
            last_day = day
            ts = int((midnight + extra * 86400 + day)) * 1_000_000_000 + int(ns)
            r = running.get(int(cpu))
            if r is None or not r[0]:
                nw_unk += 1
                continue
            wk_ts.append(ts); wk_waker.append(r[0]); wk_wakee.append(int(wakee)); nw += 1
            continue
        n += 1
        hh, mm, ss, ns, cpu, vtid, vpid, comm, prev, st, nxt = m.groups()
        day = int(hh) * 3600 + int(mm) * 60 + int(ss)
        if last_day is not None and day < last_day - 43200:
            extra += 1
        last_day = day
        ts = int((midnight + extra * 86400 + day)) * 1_000_000_000 + int(ns)
        cpu, prev, nxt, st = int(cpu), int(prev), int(nxt), int(st)
        if prev and prev not in ctx:
            ctx[prev] = (int(vtid), int(vpid), comm[1:-1])
        r = running.get(cpu)
        if prev:
            if r is not None and r[0] == prev:
                on_tid.append(prev); on_t0.append(r[1]); on_t1.append(ts)
            pending[prev] = (ts, st)
        if nxt:
            p = pending.pop(nxt, None)
            if p is not None:
                off_tid.append(nxt); off_t0.append(p[0]); off_t1.append(ts); off_st.append(p[1])
        running[cpu] = (nxt, ts)
        if n % 5_000_000 == 0:
            print(f'  {n / 1e6:.0f} M switches, {time.time() - t:.0f} s', file=sys.stderr)
    proc.wait()
    print(f'kernel: {n} sched_switch events, {nw} sched_waking events ({nw_unk} with unknown waker, '
          f'{nfx} futex wait intervals, {ngp} OpenMP region starts, {bad} other lines), {len(ctx)} threads, {time.time() - t:.0f} s', file=sys.stderr)
    as_np = lambda a, dt: np.frombuffer(a, dtype=dt)
    return ((as_np(on_tid, np.int32), as_np(on_t0, np.int64), as_np(on_t1, np.int64)),
            (as_np(off_tid, np.int32), as_np(off_t0, np.int64), as_np(off_t1, np.int64),
             as_np(off_st, np.int32)),
            ctx,
            (as_np(wk_ts, np.int64), as_np(wk_waker, np.int32), as_np(wk_wakee, np.int32)),
            (as_np(fx_tid, np.int32), as_np(fx_t0, np.int64), as_np(fx_t1, np.int64), as_np(fx_addr, np.int64)),
            (as_np(gp_tid, np.int32), as_np(gp_ts, np.int64)))


def per_thread(tid, *cols):
    """Split interval columns by thread, each sorted by start."""
    order = np.lexsort((cols[0], tid))
    tid = tid[order]; cols = [c[order] for c in cols]
    cut = np.flatnonzero(np.diff(tid)) + 1
    starts = np.r_[0, cut]; ends = np.r_[cut, len(tid)]
    return {int(tid[s]): [c[s:e] for c in cols] for s, e in zip(starts, ends)}


def overlap(t0, t1, a, b):
    """Total overlap of sorted, non-overlapping [t0,t1) intervals with [a,b)."""
    i = np.searchsorted(t1, a, side='right')
    j = np.searchsorted(t0, b, side='left')
    if j <= i:
        return 0, i, j
    return int(np.sum(np.minimum(t1[i:j], b) - np.maximum(t0[i:j], a))), i, j


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('session_dir')
    ap.add_argument('--session-id', default=None)
    ap.add_argument('--scope', default='__main__')
    ap.add_argument('--tz', default=DEFAULT_TZ)
    ap.add_argument('--tsv', default=None, help='per-callback rows, all callbacks, times in ns')
    ap.add_argument('--steady', default='window', choices=('window', 'legacy'),
                    help="window = fish_window.steady_window (phases + stimulus + warm-up); legacy = centerpoint's last >=900 ms stall")
    ap.add_argument('--no-inst', action='store_true', help='do not write per-instance rows to PG table ksched_inst')
    args = ap.parse_args()
    sid = args.session_id or os.path.basename(args.session_dir.rstrip('/'))

    (on_tid, on_t0, on_t1), (off_tid, off_t0, off_t1, off_st), ctx, (wk_ts, wk_waker, wk_wakee), (fx_tid, fx_t0, fx_t1, fx_addr), (gp_tid, gp_ts) = \
        parse_kernel(args.session_dir, args.tz)
    GP = per_thread(gp_tid, gp_ts) if len(gp_tid) else {}   # master tid -> (region start ts[],)  (A0.2, kernel uprobe — usually empty)
    FX = per_thread(fx_tid, fx_t0, fx_t1, fx_addr) if len(fx_tid) else {}   # tid -> (t0[], t1[], addr[]) futex waits (A0.4)
    LOCKS = collections.defaultdict(set)
    ON = per_thread(on_tid, on_t0, on_t1)
    OFF = per_thread(off_tid, off_t0, off_t1, off_st)
    WK = per_thread(wk_waker, wk_ts, wk_wakee) if len(wk_ts) else {}   # waker -> (ts[], wakee[])
    WKR = per_thread(wk_wakee, wk_ts, wk_waker) if len(wk_ts) else {}  # wakee -> (ts[], waker[])  (A0.1 release)

    conn = psycopg2.connect(DSN); c = conn.cursor()
    c.execute("SELECT pid, vtid, t0_ns, t1_ns, node, entity, cb_addr FROM gantt_spans "
              "WHERE session_id=%s AND scope=%s ORDER BY t0_ns", (sid, args.scope))
    spans = c.fetchall()
    # A0.2 (fishwait16): OpenMP regions from the LD_PRELOAD shim's UST events, per master thread (container ids → host tid)
    GR = {}
    c.execute("SELECT vpid, vtid, ts_ns, event FROM ros2_trace WHERE session_id=%s AND event IN "
              "('ros2:fish_gomp_parallel','ros2:fish_gomp_parallel_end') ORDER BY ts_ns", (sid,))
    _open = {}; _reg = collections.defaultdict(lambda: ([], []))
    for vpid_, vtid_, ts_, ev_ in c.fetchall():
        if ev_.endswith('_end'):
            t0_ = _open.pop((vpid_, vtid_), None)
            if t0_ is not None:
                _reg[(vpid_, vtid_)][0].append(t0_); _reg[(vpid_, vtid_)][1].append(int(ts_))
        else:
            _open[(vpid_, vtid_)] = int(ts_)
    for k_, (a_, b_) in _reg.items():
        GR[k_] = (np.array(a_, dtype=np.int64), np.array(b_, dtype=np.int64))
    if GR:
        print(f"OpenMP regions (shim): {sum(len(v[0]) for v in GR.values())} regions in {len(GR)} master thread(s)")
    if not spans:
        sys.exit(f'no gantt_spans for {sid}/{args.scope}')
    c.execute("SELECT tid, ts_ns, duration_ns, api_name FROM cuda_runtime WHERE session_id=%s ORDER BY ts_ns", (sid,))
    api = collections.defaultdict(list)
    for tid, ts, d, name in c.fetchall():
        api[tid].append((ts, ts + (d or 0), name))

    # container (vpid, vtid) -> host tid, from the context each switch-out carries
    want = {(p, v) for p, v, *_ in spans}
    host_of, clash = {}, collections.Counter()
    for htid, (vtid, vpid, comm) in ctx.items():
        if (vpid, vtid) in want:
            if (vpid, vtid) in host_of:
                clash[(vpid, vtid)] += 1
            host_of[(vpid, vtid)] = htid
    print(f'threads with callbacks: {len(want)}, mapped to a host tid: {len(host_of)}, '
          f'ambiguous: {len(clash)}')

    # steady state: FISH phases + stimulus window + warm-up (fish_window); legacy = after centerpoint's
    # last start-up stall (>= 900 ms), kept for comparison (Autoware-only, needs an initialised localization)
    cp = [(t0, t1) for p, v, t0, t1, node, ent, _cb in spans if node == 'lidar_centerpoint']
    stalls = [t1 for t0, t1 in cp if t1 - t0 >= 900_000_000]
    t_legacy = (max(stalls) + 1_000_000_000) if stalls else (cp[0][0] if cp else spans[0][2])
    t_stop = max(t1 for _p, _v, _t0, t1, *_ in spans)
    if args.steady == 'window':
        from fish_window import steady_window
        W = steady_window(c, sid, args.scope)
        t_ss, t_stop = W['t_ss'], W['t_end']
        print(f"steady state [{W['how']}]: +{(t_ss - spans[0][2]) / 1e9:.1f} s … +{(t_stop - spans[0][2]) / 1e9:.1f} s of the first span "
              f"({(t_stop - t_ss) / 1e9:.1f} s; legacy centerpoint-stall rule would start at +{(t_legacy - spans[0][2]) / 1e9:.1f} s)")
    else:
        t_ss = t_legacy
        print(f'steady state from +{(t_ss - spans[0][2]) / 1e9:.1f} s of the first span (legacy)')

    # callback windows per host thread: a woken thread that runs its OWN
    # callback is a downstream dispatch (e.g. an intra-process delivery), not
    # a helper of the waker; its window time is subtracted from the assist
    SP = collections.defaultdict(list)
    for pid, vtid, t0, t1, node, ent, _cb in spans:
        hh = host_of.get((pid, vtid))
        if hh is not None:
            SP[hh].append((t0, t1))
    SP = {k: (np.array([a for a, _ in v]), np.array([b for _, b in v])) for k, v in SP.items()}

    # helpers = same-process threads that never run a callback and are not middleware threads
    # (OpenMP pool, pthread workers). Executor threads woken by a publish (intra-process delivery)
    # and Cyclone threads (recv*/dq.*/tev/gc) are accounted elsewhere (own windows / middleware table).
    MW_PREFIX_H = ('recv', 'dq.', 'tev', 'gc', 'lease', 'xmit', 'debmon')
    NOT_HELPER = set(host_of.values()) | {h for h, (_vt, _vp, cm) in ctx.items() if cm.startswith(MW_PREFIX_H)}

    def assist_of(h, t0, t1):
        """CPU time of helper threads of h's process that h wakes inside [t0,t1), from
        the wake-up until they next sleep (or the window ends).  Returns (ns, set of helper tids)."""
        if h not in WK:
            return 0, set()
        wts, wkee = WK[h]
        i = np.searchsorted(wts, t0, side='left'); j = np.searchsorted(wts, t1, side='right')
        if j <= i:
            return 0, set()
        my_vpid = ctx[h][1]
        iv = collections.defaultdict(list)
        for k in range(i, j):
            g = int(wkee[k])
            if g == h or g not in ON or ctx.get(g, (0, -1))[1] != my_vpid or g in NOT_HELPER:
                continue
            a = int(wts[k])
            if g in OFF:
                f0, f1, fs = OFF[g]
                q = np.searchsorted(f0, a, side='right')
                while q < len(f0) and fs[q] not in (1, 2):
                    q += 1
                b = min(t1, int(f0[q])) if q < len(f0) else t1
            else:
                b = t1
            if b > a:
                iv[g].append((a, b))
        total = 0
        for g, lst in iv.items():
            lst.sort(); merged = []
            for a, b in lst:
                if merged and a <= merged[-1][1]:
                    merged[-1] = (merged[-1][0], max(merged[-1][1], b))
                else:
                    merged.append((a, b))
            for a, b in merged:
                x = overlap(*ON[g], a, b)[0]
                if g in SP:
                    x -= overlap(SP[g][0], SP[g][1], a, b)[0]
                total += max(0, x)
        return total, set(iv)

    agg = collections.defaultdict(lambda: collections.Counter())
    helpers = collections.defaultdict(set)
    # A0.2: helper POOL per callback thread = same-process threads it ever woke (over the whole trace);
    # a pool thread's on-CPU time inside the window counts as 'assist_pool' whether or not it was woken
    # in that window — this is what the wake-based 'assist' misses when libgomp workers are still
    # spinning from the previous region (GOMP_SPINCOUNT) when the next one starts.
    POOL = {}
    for h, (wts, wkee) in WK.items():
        my = ctx.get(h, (0, -1))[1]
        POOL[h] = {int(g) for g in set(wkee.tolist()) if g != h and ctx.get(int(g), (0, -2))[1] == my and int(g) not in NOT_HELPER}
    def assist_pool_of(h, t0, t1):
        tot = 0; hs = set()
        for g in POOL.get(h, ()):
            if g not in ON: continue
            x = overlap(*ON[g], t0, t1)[0]
            if g in SP:
                x -= overlap(SP[g][0], SP[g][1], t0, t1)[0]
            if x > 0: tot += x; hs.add(g)
        return tot, hs
    REL = collections.defaultdict(list); PREV_END = {}    # A0.1: dispatch delays per callback, last span end per host thread
    on_at_start = checked = 0
    gpu = collections.defaultdict(lambda: collections.Counter())
    INST = []   # per-instance rows → PG ksched_inst (task extraction: C, suspension classes, wake-up per job)
    for pid, vtid, t0, t1, node, ent, cb_addr in spans:
        if t0 < t_ss or t0 > t_stop:
            continue
        h = host_of.get((pid, vtid))
        if h is None or h not in ON:
            continue
        o0, o1 = ON[h]
        checked += 1
        k = np.searchsorted(o0, t0, side='right') - 1
        if k >= 0 and o1[k] >= t0:
            on_at_start += 1
        wall = t1 - t0
        on, _, _ = overlap(o0, o1, t0, t1)
        key = (node or '?', ent or '?')
        a = agg[key]
        a['n'] += 1; a['wall'] += wall; a['on'] += on
        I = collections.Counter()   # this instance
        if WK:
            asst, hs = assist_of(h, t0, t1)
            a['assist'] += asst; helpers[key] |= hs; I['assist'] = asst
            ap_, _ = assist_pool_of(h, t0, t1)
            a['assist_pool'] += ap_
        if h in GP:   # OpenMP regions started by this thread inside the window (kernel uprobe)
            gts = GP[h][0]
            a['omp_regions'] += int(np.searchsorted(gts, t1, side='left') - np.searchsorted(gts, t0, side='left'))
        gr = GR.get((pid, vtid))
        if gr is not None:   # OpenMP regions from the shim: count, span, and pool on-CPU inside the regions only
            r0, r1 = gr
            i0 = int(np.searchsorted(r0, t0, side='left')); i1 = int(np.searchsorted(r0, t1, side='left'))
            if i1 > i0:
                a['omp_regions'] += i1 - i0; I['omp_n'] = i1 - i0
                a['omp_span'] += int(np.sum(np.minimum(r1[i0:i1], t1) - r0[i0:i1]))
                for g in POOL.get(h, ()):
                    if g not in ON: continue
                    x = 0
                    for k in range(i0, i1):
                        x += overlap(*ON[g], int(r0[k]), int(min(r1[k], t1)))[0]
                    a['assist_region'] += x; I['assist_region'] += x
        SEEN_G = set()
        SUSP = []; FCLS = []   # L2: blocked intervals of this instance, and its classified futex waits (start, end, class)
        if h in FX:   # A0.4: futex WAIT inside the window — classified by what the thread was doing
            x0, x1, xa = FX[h]
            lw, i0, i1 = overlap(x0, x1, t0, t1)
            if lw:
                calls_h = api.get(vtid) or []
                cstarts = [cc[0] for cc in calls_h]
                gr_h = GR.get((pid, vtid))
                for k in range(i0, i1):
                    a0 = max(int(x0[k]), t0); a1 = min(int(x1[k]), t1)
                    if a1 <= a0: continue
                    # inside a CUDA runtime call of this thread → the driver's wait (cudaStreamSynchronize & co.)
                    j = np.searchsorted(cstarts, a0, side='right') - 1 if cstarts else -1
                    if j >= 0 and calls_h[j][1] >= a1:
                        a['futex_gpu'] += a1 - a0; I['gpu'] += a1 - a0
                        # L2 cut = the CUDA runtime CALL that blocks (cudaStreamSynchronize, a blocking memcpy …), not each of
                        # the driver's internal futex waits inside it (centerpoint: ~18 waits per invocation, unstable pattern)
                        FCLS.append((a0, a1, 'g', max(int(calls_h[j][0]), t0), min(int(calls_h[j][1]), t1))); continue
                    # inside an OpenMP region started by this thread → team barrier
                    if gr_h is not None:
                        r0, r1 = gr_h
                        jj = int(np.searchsorted(r0, a0, side='right')) - 1
                        if jj >= 0 and r1[jj] >= a1:
                            a['futex_omp'] += a1 - a0; I['omp'] += a1 - a0; FCLS.append((a0, a1, 'o', a0, a1)); continue
                    a['lock_wait'] += a1 - a0; a['lock_n'] += 1; I['lock'] += a1 - a0; FCLS.append((a0, a1, 'l', a0, a1))
                    LOCKS[key].add(int(xa[k]))
        if h in OFF:
            f0, f1, fs = OFF[h]
            i = np.searchsorted(f1, t0, side='right'); j = np.searchsorted(f0, t1, side='left')
            for q in range(i, j):
                _d = int(min(f1[q], t1) - max(f0[q], t0)); _st = STATE.get(int(fs[q]), 'other')
                a[_st] += _d; I[_st] += _d
                if _st in ('sleeping', 'uninterruptible') and _d >= 20_000 and len(SUSP) < 24:
                    _a0 = int(max(f0[q], t0)); _cls = 'd' if _st == 'uninterruptible' else 's'; _s0, _s1 = _a0, _a0 + _d
                    for (_x0, _x1, _c, _u0, _u1) in FCLS:          # futex wait that contains the start of this sleep
                        if _x0 <= _a0 <= _x1:
                            _cls = _c; _s0, _s1 = _u0, _u1; break
                    if _cls == 'g':
                        if _s0 in SEEN_G:                           # same blocking CUDA call: one suspension
                            continue
                        SEEN_G.add(_s0)
                    SUSP.append(f"{_s0 - t0}:{_s1 - _s0}:{_cls}")
            # --- release instant (A0.1): the thread's last sleep (state S/D) that ended
            # before this callback started is the executor blocked in rcl_wait; the
            # wake-up that ended it is the release of what the executor then dispatched.
            # waker 'recv*'  = Cyclone receive thread  → DDS sample arrival
            # waker in my process = publisher thread (intra-process / guard condition)
            # waker swapper/idle or unknown = timer expiry / irq
            # no sleep since the previous callback on this thread = 'busy' (release not observable here)
            rel = relkind = None
            q = np.searchsorted(f1, t0, side='right') - 1   # last off-interval that ended at/before t0
            prev_end = PREV_END.get(h)
            while q >= 0 and f1[q] > (prev_end if prev_end is not None else -1):
                if int(fs[q]) in (1, 2):
                    rel = int(f1[q])                       # switch-in after the sleep (upper bound)
                    relkind = 'timer/irq'
                    if h in WKR:
                        wts2, wkr2 = WKR[h]
                        u = np.searchsorted(wts2, int(f0[q]), side='left'); v = np.searchsorted(wts2, int(f1[q]), side='right')
                        if v > u:
                            rel = int(wts2[v - 1]); w = int(wkr2[v - 1])
                            cm = ctx.get(w, (0, -1, ''))[2]
                            relkind = ('dds' if cm.startswith('recv') else
                                       'intra' if ctx.get(w, (0, -1))[1] == ctx[h][1] else
                                       'timer/irq' if cm.startswith('swapper') or cm.startswith('ksoftirq') else 'other')
                    break
                q -= 1
            if rel is not None and (ent or '').startswith('tmr:'):
                relkind = 'timer/irq'   # hrtimer wakes fire in interrupt context: the 'waker' is whoever ran on that cpu
            if rel is None:
                a['rel_busy'] += 1
            else:
                a['rel_n'] += 1; a['rel_' + relkind] += 1
                REL[key].append(t0 - rel)
            PREV_END[h] = t1
            I['wake'] = rel if rel is not None else 0; I['wake_kind'] = relkind or 'busy'
        INST.append((pid, vtid, int(h), cb_addr, int(t0), int(t1), int(on), I['preempted'], I['runnable'], I['sleeping'],
                     I['uninterruptible'], I['lock'], I['gpu'], I['omp'], I['assist'], I['assist_region'], I['omp_n'],
                     I['wake'], I.get('wake_kind') or 'n/a', ';'.join(SUSP)))
        calls = api.get(vtid)
        if calls:
            ks = [x[0] for x in calls]
            lo = np.searchsorted(ks, t0); hi = np.searchsorted(ks, t1)
            if hi > lo:
                g = gpu[key]; g['n'] += 1
                for ca, cb, name in calls[lo:hi]:
                    cb = min(cb, t1)
                    g['api'] += cb - ca
                    g['api_on'] += overlap(o0, o1, ca, cb)[0]
                    if h in OFF:
                        f0, f1, fs = OFF[h]
                        i = np.searchsorted(f1, ca, side='right'); j = np.searchsorted(f0, cb, side='left')
                        for q in range(i, j):
                            g['api_' + STATE.get(int(fs[q]), 'other')] += int(min(f1[q], cb) - max(f0[q], ca))
                            g['switches'] += 1

    print(f'check: thread on a CPU at the callback start in {100 * on_at_start / max(checked, 1):.1f} % '
          f'of {checked} steady-state spans (clock alignment)')

    if INST and not args.no_inst:
        import io
        c.execute("""CREATE TABLE IF NOT EXISTS ksched_inst (session_id text NOT NULL, scope text NOT NULL, pid int, vtid int, htid int,
                     cb_addr text, t0_ns bigint, t1_ns bigint, on_ns bigint, pre_ns bigint, run_ns bigint, slp_ns bigint, d_ns bigint,
                     lock_ns bigint, gpu_ns bigint, omp_ns bigint, assist_ns bigint, assist_region_ns bigint, omp_n int,
                     wake_ns bigint, wake_kind text)""")
        c.execute("ALTER TABLE ksched_inst ADD COLUMN IF NOT EXISTS susp text")   # L2: 'offset:dur:class;…' blocked intervals ≥ 20 µs
        c.execute("CREATE INDEX IF NOT EXISTS ksched_inst_sid ON ksched_inst (session_id, scope, pid, cb_addr)")
        c.execute("DELETE FROM ksched_inst WHERE session_id=%s AND scope=%s", (sid, args.scope))
        buf = io.StringIO()
        for r in INST:
            buf.write(sid + '\t' + args.scope + '\t' + '\t'.join('\\N' if x is None else str(x) for x in r) + '\n')
        buf.seek(0)
        c.copy_expert("COPY ksched_inst FROM STDIN", buf)
        conn.commit()
        print(f'per-instance rows: {len(INST)} → PG ksched_inst')

    ms = lambda x: x / 1e6
    # wall not covered by on-CPU or a known off-CPU state (includes 'other')
    rest = lambda a: a['wall'] - a['on'] - a['preempted'] - a['runnable'] - a['sleeping'] - a['uninterruptible']
    print('\ncallbacks with the most wall time (steady state), per invocation:')
    print(f"{'node / entity':<60}{'n':>6}{'wall':>8}{'on-CPU':>8}{'preempt':>9}{'runnbl':>7}{'sleep':>7}{'D':>6}{'rest':>6}{'assist':>8}{'hlp':>5}")
    for key, a in sorted(agg.items(), key=lambda kv: -kv[1]['wall'])[:25]:
        n = a['n']
        print(f"{(key[0] + ' / ' + key[1])[:60]:<60}{n:>6}{ms(a['wall'] / n):>8.2f}{ms(a['on'] / n):>8.2f}"
              f"{ms(a['preempted'] / n):>9.2f}{ms(a['runnable'] / n):>7.2f}{ms(a['sleeping'] / n):>7.2f}"
              f"{ms(a['uninterruptible'] / n):>6.2f}{ms(rest(a) / n):>6.2f}{ms(a['assist'] / n):>8.2f}{len(helpers.get(key, ())):>5}")
    tot = collections.Counter()
    if args.tsv:
        with open(args.tsv, 'w') as f:
            cols = ['n', 'wall', 'on', 'preempted', 'runnable', 'sleeping', 'uninterruptible', 'other', 'assist', 'assist_pool', 'assist_region', 'omp_regions', 'omp_span', 'lock_wait', 'lock_n', 'futex_gpu', 'futex_omp']
            f.write('\t'.join(['node', 'entity'] + cols + ['unaccounted', 'gpu_n', 'api', 'api_on', 'api_preempted',
                                                           'api_runnable', 'api_sleeping', 'switches']) + '\n')
            for key, a in sorted(agg.items(), key=lambda kv: -kv[1]['wall']):
                g = gpu.get(key, collections.Counter())
                f.write('\t'.join([key[0], key[1]] + [str(a[c]) for c in cols] + [str(rest(a) - a['other'])] +
                                   [str(g[c]) for c in ('n', 'api', 'api_on', 'api_preempted', 'api_runnable',
                                                        'api_sleeping', 'switches')]) + '\n')
    for a in agg.values():
        tot.update(a)
    print(f"\nall steady-state callback time: {ms(tot['wall']):.0f} ms wall = "
          f"{100 * tot['on'] / tot['wall']:.1f} % on-CPU, {100 * tot['preempted'] / tot['wall']:.1f} % preempted, "
          f"{100 * tot['runnable'] / tot['wall']:.1f} % runnable, {100 * tot['sleeping'] / tot['wall']:.1f} % sleeping, "
          f"{100 * tot['uninterruptible'] / tot['wall']:.1f} % D, {100 * tot['other'] / tot['wall']:.2f} % other state, "
          f"{100 * (rest(tot) - tot['other']) / tot['wall']:.2f} % unaccounted"
          + (f"; assist by woken helper threads {ms(tot['assist']):.0f} ms = {100 * tot['assist'] / tot['wall']:.1f} % of wall" if WK else
             "; no sched_waking in this trace (assist not computed)"))

    if GP or any(a['assist_pool'] for a in agg.values()):
        print('\nOpenMP / helper threads per invocation (steady state): regions started (GOMP_parallel uprobe), wake-based assist, pool co-occurrence assist:')
        print(f"{'node / entity':<60}{'n':>6}{'omp/inv':>8}{'span ms':>8}{'assist ms':>10}{'pool ms':>9}{'in-reg ms':>10}{'pool thr':>9}{'own on-CPU':>11}")
        for key, a in sorted(agg.items(), key=lambda kv: -(kv[1]['assist_pool'] + kv[1]['assist']))[:12]:
            if not (a['assist_pool'] or a['assist'] or a['omp_regions']): break
            print(f"{(key[0] + ' / ' + key[1])[:60]:<60}{a['n']:>6}{a['omp_regions'] / a['n']:>8.2f}{ms(a['omp_span'] / a['n']):>8.2f}{ms(a['assist'] / a['n']):>10.2f}"
                  f"{ms(a['assist_pool'] / a['n']):>9.2f}{ms(a['assist_region'] / a['n']):>10.2f}{len(helpers.get(key, ())):>9}{ms(a['on'] / a['n']):>11.2f}")
    if FX:
        print('\nfutex WAIT inside the callback window, steady state, per invocation: lock = contended mutex/condvar, gpu = inside a CUDA call (driver sync), omp = inside an OpenMP region (barrier):')
        print(f"{'node / entity':<60}{'n':>6}{'lock ms':>9}{'waits':>7}{'locks':>6}{'gpu ms':>8}{'omp ms':>8}{'lock %wall':>11}")
        for key, a in sorted(agg.items(), key=lambda kv: -(kv[1]['lock_wait'] + kv[1]['futex_gpu'] + kv[1]['futex_omp']))[:15]:
            if not (a['lock_wait'] or a['futex_gpu'] or a['futex_omp']): break
            print(f"{(key[0] + ' / ' + key[1])[:60]:<60}{a['n']:>6}{ms(a['lock_wait'] / a['n']):>9.3f}{a['lock_n'] / a['n']:>7.2f}{len(LOCKS[key]):>6}"
                  f"{ms(a['futex_gpu'] / a['n']):>8.2f}{ms(a['futex_omp'] / a['n']):>8.2f}{100 * a['lock_wait'] / max(1, a['wall']):>11.1f}")
        tl = sum(a['lock_wait'] for a in agg.values()); tg = sum(a['futex_gpu'] for a in agg.values()); to = sum(a['futex_omp'] for a in agg.values()); tw = sum(a['wall'] for a in agg.values())
        print(f"all callbacks: futex waits = {ms(tl):.0f} ms on locks ({100 * tl / max(1, tw):.2f} % of wall), {ms(tg):.0f} ms inside CUDA calls, {ms(to):.0f} ms inside OpenMP regions")
    if REL:
        print('\nrelease → callback start (dispatch delay), steady state; release = wake-up of the executor thread that dispatched the callback:')
        print(f"{'node / entity':<60}{'n':>6}{'rel_n':>6}{'busy':>6}{'dds':>6}{'intra':>6}{'timer':>6}{'p50 ms':>8}{'p90 ms':>8}{'max ms':>8}")
        for key, a in sorted(agg.items(), key=lambda kv: -kv[1]['wall'])[:25]:
            d = sorted(REL.get(key, []))
            qq = lambda p: ms(d[int(p * (len(d) - 1))]) if d else float('nan')
            print(f"{(key[0] + ' / ' + key[1])[:60]:<60}{a['n']:>6}{a['rel_n']:>6}{a['rel_busy']:>6}{a['rel_dds']:>6}{a['rel_intra']:>6}"
                  f"{a['rel_timer/irq']:>6}{qq(.5):>8.3f}{qq(.9):>8.3f}{qq(1.0):>8.3f}")
        if args.tsv:
            with open(args.tsv.replace('.tsv', '') + '.release.tsv', 'w') as f:
                f.write('node\tentity\tn\trel_n\trel_busy\trel_dds\trel_intra\trel_timer\trel_other\tdelay_p50_ns\tdelay_p90_ns\tdelay_max_ns\n')
                for key, a in agg.items():
                    d = sorted(REL.get(key, []))
                    qq = lambda p: d[int(p * (len(d) - 1))] if d else ''
                    f.write('\t'.join([key[0], key[1], str(a['n']), str(a['rel_n']), str(a['rel_busy']), str(a['rel_dds']), str(a['rel_intra']),
                                       str(a['rel_timer/irq']), str(a['rel_other']), str(qq(.5)), str(qq(.9)), str(qq(1.0))]) + '\n')

    # --- G.dds.4: middleware threads as tasks. Cyclone's threads (recv*, dq.*, tev, gc, lease, xmit*)
    # share the cores with the callbacks and wake the executor threads; per process: steady-state
    # on-CPU, wake-ups of callback threads. Attached to the EX vertices (graph_nodes attrs) by vpid.
    t_end = t_stop
    cb_threads = set(host_of.values())
    MW_PREFIX = ('recv', 'dq.', 'tev', 'gc', 'lease', 'xmit', 'debmon')
    mw = collections.defaultdict(lambda: collections.Counter()); mw_tids = collections.defaultdict(set)
    for h, (vt, vp, cm) in ctx.items():
        if not cm.startswith(MW_PREFIX) or vp == 0:
            continue
        key = (vp, cm)
        mw_tids[key].add(h)
        if h in ON:
            mw[key]['on'] += overlap(ON[h][0], ON[h][1], t_ss, t_end)[0]
        if h in WK:
            wts, wkee = WK[h]
            i = np.searchsorted(wts, t_ss, side='left')
            wk = wkee[i:]
            mw[key]['wakes'] += len(wk)
            mw[key]['wakes_cb'] += int(np.isin(wk, list(cb_threads)).sum()) if len(wk) else 0
    if mw:
        span_s = (t_end - t_ss) / 1e9
        print(f'\nmiddleware threads per process (steady state, {span_s:.0f} s): on-CPU and wake-ups of callback threads')
        print(f"{'vpid':>7} {'comm':<14}{'thr':>4}{'on-CPU ms':>11}{'CPU %':>7}{'wakes':>8}{'→cb thr':>9}")
        rows = sorted(mw.items(), key=lambda kv: -kv[1]['on'])
        for (vp, cm), a in rows[:25]:
            print(f"{vp:>7} {cm:<14}{len(mw_tids[(vp, cm)]):>4}{ms(a['on']):>11.1f}{100 * a['on'] / max(1, t_end - t_ss):>7.2f}{a['wakes']:>8}{a['wakes_cb']:>9}")
        tot_mw = sum(a['on'] for a in mw.values())
        print(f"all middleware threads: {ms(tot_mw):.0f} ms on-CPU = {100 * tot_mw / max(1, t_end - t_ss):.1f} % of one core over the steady state; "
              f"{sum(a['wakes_cb'] for a in mw.values())} wake-ups of callback threads")
        if args.tsv:
            with open(args.tsv.replace('.tsv', '') + '.middleware.tsv', 'w') as f:
                f.write('vpid\tcomm\tn_threads\ton_ns\twakes\twakes_cb_threads\n')
                for (vp, cm), a in rows:
                    f.write(f"{vp}\t{cm}\t{len(mw_tids[(vp, cm)])}\t{a['on']}\t{a['wakes']}\t{a['wakes_cb']}\n")
        # attach to the executor vertices of this session
        try:
            per_pid = collections.defaultdict(list)
            for (vp, cm), a in rows:
                per_pid[vp].append({'comm': cm, 'n_threads': len(mw_tids[(vp, cm)]), 'on_cpu_ns': int(a['on']),
                                    'wakes': int(a['wakes']), 'wakes_cb_threads': int(a['wakes_cb'])})
            import json as _json
            for vp, lst in per_pid.items():
                c.execute("UPDATE graph_nodes SET attrs = attrs || %s::jsonb WHERE session_id=%s AND scope=%s AND type='EX' AND pid=%s",
                          (_json.dumps({'middleware_threads': lst, 'steady_state_ns': int(t_end - t_ss)}), sid, args.scope, vp))
            conn.commit()
            print(f'middleware threads attached to {len(per_pid)} executor vertex(es) (graph_nodes.attrs.middleware_threads)')
        except Exception as e:  # noqa: BLE001
            print(f'middleware attach skipped: {e}')

    print('\ntime inside CUDA runtime calls, per invocation of the GPU-submitting callbacks:')
    print(f"{'node / entity':<60}{'n':>5}{'in CUDA':>9}{'on-CPU':>8}{'preempt':>9}{'runnbl':>7}{'sleep':>7}{'switches':>9}")
    for key, g in sorted(gpu.items(), key=lambda kv: -kv[1]['api'])[:10]:
        n = g['n']
        print(f"{(key[0] + ' / ' + key[1])[:60]:<60}{n:>5}{ms(g['api'] / n):>9.2f}{ms(g['api_on'] / n):>8.2f}"
              f"{ms(g['api_preempted'] / n):>9.2f}{ms(g['api_runnable'] / n):>7.2f}{ms(g['api_sleeping'] / n):>7.2f}"
              f"{g['switches'] / n:>9.1f}")


if __name__ == '__main__':
    main()
