#!/usr/bin/env python3
# Generated by Claude Fable 5.1 (Anthropic), 2026-10-04
"""LiME-IT-style traditional task models (periodic / sporadic, with names) from a FISH session, next to the
models FISH's own point releases give.  Design: notes/fish_task_extraction.md §5.

  python3 limeit_models.py <session_id> [--releases releases.json] [-o out.json] [--min-n 20] [--top 40]

Observation model of LiME-IT (Ye, Marković, Brandenburg, RTAS'26), reproduced on FISH data:
  per intra-thread task (= callback) start s_i and finish f_i   ← gantt_spans (callback_start / callback_end)
  W(t) = last wake-up of the executor thread before t that is not inside an execution window
                                                                 ← ksched_inst.wake_ns (kernel sched_switch/sched_waking);
                                                                   'busy' instances inherit the thread's previous W
  uncertain release window R_i = [W(s_i), s_i]
Models, with the authors' reference implementation (third_party/rt_model_inference, MIT):
  LiME-IT  possible-fit / certain-fit periodic (T, Φ, J), delta-min under/over approximations (min separation)
  FISH     point releases (arrival of the triggering sample: --releases from extract_fish_tasks.py) →
           periodic (T, Φ, J) and sporadic min separation with LiME's certain-release algorithms;
           timers: configured period from rcl_timer_init (LiME-IT has to infer it)
Also reports which FISH callbacks a LiME-IT run could (not) see: multi-threaded executors, shared entry symbols,
component (dlopen) libraries, expected perf samples.  Time unit inside the inference: microseconds."""
import argparse, collections, json, os, re, sys
import numpy as np
import psycopg2
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE); sys.path.insert(0, os.path.join(HERE, 'third_party'))
import rt_model_inference as rmi
from topic_class import topic_class
from fish_window import steady_window

DSN = 'host=localhost port=5432 dbname=fish user=fish password=fish'
NEGL_US = 1000          # LiME-IT X1: negligible-jitter threshold 1 ms
US = 1000


def model(m):
    return None if m is None else dict(T=int(m.period), phi=int(m.offset), J=int(m.jitter))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('session'); ap.add_argument('--scope', default='__main__')
    ap.add_argument('--releases', default=None); ap.add_argument('-o', '--out', default=None)
    ap.add_argument('--min-n', type=int, default=20); ap.add_argument('--top', type=int, default=40)
    ap.add_argument('--perf-hz', type=float, default=10_000); ap.add_argument('--perf-s', type=float, default=30)
    a = ap.parse_args()
    sid, scope = a.session, a.scope
    conn = psycopg2.connect(DSN); cur = conn.cursor()
    W = steady_window(cur, sid, scope); t_ss, t_end = W['t_ss'], W['t_end']
    dur_s = (t_end - t_ss) / 1e9

    # callbacks: name, executor kind, cb group — from the graph
    cur.execute("SELECT node_id, type, label, children, attrs, pid, full_name, etype, ptype, cb_addr FROM graph_nodes WHERE session_id=%s AND scope=%s", (sid, scope))
    N = {}; parent = {}
    for nid, typ, label, ch, attrs, pid, full, etype, ptype, cb in cur.fetchall():
        N[nid] = dict(id=nid, type=typ, label=label or '', attrs=attrs or {}, pid=pid, full=full, etype=etype, ptype=ptype, cb=cb)
        for c in ch or []:
            parent[c] = nid
    def anc(x, typ):
        while x in parent:
            x = parent[x]
            if N[x]['type'] == typ:
                return N[x]
        return {}
    cb2f = {}
    for n in N.values():
        if n['type'] != 'F':
            continue
        e, nd, ex = anc(n['id'], 'E'), anc(n['id'], 'N'), anc(n['id'], 'EX')
        n.update(etype=e.get('etype') or n['ptype'], ent=e.get('label') or '', node=nd.get('full') or nd.get('label') or '?',
                 vpid=ex.get('pid'), ex_label=ex.get('label'), mode=(ex.get('attrs') or {}).get('mode'),
                 n_thr=(ex.get('attrs') or {}).get('num_threads'))
        for c in [n['cb']] + list(n['attrs'].get('alt_cb_addrs') or []) + [n['attrs'].get('ipc_waitable')]:
            if c and c != 'NA' and n['vpid'] is not None:
                cb2f.setdefault((n['vpid'], c), n['id'])

    # instances with the kernel split: (pid, vtid, cb, t0, t1, on, wake, wake_kind)
    cur.execute("SELECT pid, vtid, cb_addr, t0_ns, t1_ns, on_ns, wake_ns, wake_kind FROM ksched_inst WHERE session_id=%s AND scope=%s ORDER BY pid, vtid, t0_ns", (sid, scope))
    rows = cur.fetchall()
    if not rows:
        sys.exit('no ksched_inst rows for this session — run ksched_split.py first (kernel session needed)')
    inst = collections.defaultdict(list)     # f -> [(Wlo, s, f_end, on)]
    lastW = {}; last_end = {}
    for pid, vtid, cb, t0, t1, on, wake, wk in rows:
        key = (pid, vtid)
        if wake and wk != 'busy':
            lastW[key] = wake
        Wlo = lastW.get(key, t_ss)
        f = cb2f.get((pid, cb))
        if f is None:
            continue
        inst[f].append((min(Wlo, t0), t0, t1, on, vtid))
    for f, lst in inst.items():      # rows arrive in thread order: sort per callback, then drop the nested window
        lst.sort(key=lambda x: x[1]); out_ = []     # of an intra-process delivery (one activation, two windows us apart)
        for x in lst:
            if out_ and x[4] == out_[-1][4] and x[2] <= out_[-1][2]:      # nested on the same thread
                continue
            out_.append(x)
        inst[f] = out_
    REL = json.load(open(a.releases)) if a.releases and os.path.exists(a.releases) else {}

    out = []
    for f, lst in inst.items():
        if len(lst) < a.min_n:
            continue
        n = N[f]
        lst.sort(key=lambda x: x[1])
        rw = [(w // US, s // US) for w, s, *_ in lst]
        starts = [s // US for _, s, *_ in lst]
        on = np.array([x[3] for x in lst], dtype=np.int64)
        row = dict(id=f, node=n['node'], entity=f"{n['etype']}:{n['ent']}", symbol=n['label'][:200], etype=n['etype'], n=len(lst),
                   executor=n['ex_label'], mode=n['mode'], threads=len({x[4] for x in lst}),
                   C_max_us=int(on.max() // US), C_p50_us=int(np.median(on) // US), cpu_total_us=int(on.sum() // US),
                   rate_hz=round(len(lst) / dur_s, 2))
        try:
            row['lime_pf'] = model(rmi.infer_possible_fit_periodic_model(rw, negligible_jitter_threshold=NEGL_US))
            row['lime_cf'] = model(rmi.infer_certain_fit_periodic_model(rw, negligible_jitter_threshold=NEGL_US))
            hi = rmi.infer_delta_min_hi(rw, nmax=8); lo = rmi.infer_delta_min_lo(rw, nmax=8)
            row['lime_minsep_under_us'] = int(hi[2]) if len(hi) > 2 else None    # safe lower bound on the min separation
            row['lime_minsep_over_us'] = int(lo[2]) if len(lo) > 2 else None
            row['start_fit'] = model(rmi.infer_periodic_model(starts, negligible_jitter_threshold=NEGL_US))
        except Exception as ex:      # noqa: BLE001
            row['lime_err'] = repr(ex)[:120]
        row['relwin_us'] = dict(p50=int(np.median([s - w for w, s in rw])), max=int(max(s - w for w, s in rw)))
        r = REL.get(str(f))
        if r and len(r['rel']) >= a.min_n:
            rel = sorted(x // US for x, t0 in zip(r['rel'], r['t0']) if t_ss <= t0 <= t_end)
            rel = [x for i, x in enumerate(rel) if i == 0 or x > rel[i - 1]]
            if len(rel) >= a.min_n:
                row['fish_point'] = model(rmi.infer_periodic_model(rel, negligible_jitter_threshold=NEGL_US))
                row['fish_minsep_us'] = int(rmi.infer_sporadic_model(rel)); row['fish_release'] = r['kind']; row['fish_n'] = len(rel)
        if n['etype'] == 'tmr':
            m = re.search(r'(\d+)ns', n['ent'])
            row['T_cfg_us'] = int(m.group(1)) // US if m else None
        row['infra'] = (n['etype'] == 'sub' and topic_class(n['ent']) == 'infra') or bool(re.search(r'parameter|_container/', n['ent']))
        out.append(row)

    # ---- which FISH callbacks could LiME-IT see?
    by_thread_sym = collections.defaultdict(set)
    for r in out:
        by_thread_sym[(r['executor'], r['symbol'])].add(r['id'])
    for r in out:
        r['lime_scope_st'] = r['mode'] == 'ST' and r['threads'] == 1
        r['shares_symbol_with'] = len(by_thread_sym[(r['executor'], r['symbol'])]) - 1
        r['in_component_lib'] = 'component_conta' in str(r['executor'])
        r['expected_perf_samples'] = round(r['cpu_total_us'] / dur_s * a.perf_s * a.perf_hz / 1e6, 1)
    fit = lambda m: 'n/a' if not m else ('periodic' if m['J'] <= 0.5 * m['T'] else 'loose' if m['J'] < m['T'] else 'sporadic')
    for r in out:
        r['class_lime'] = fit(r.get('lime_pf')); r['class_fish'] = fit(r.get('fish_point') or (r.get('start_fit') if r['etype'] == 'tmr' else None))

    data = [r for r in out if not r['infra']]
    ms = lambda x: '-' if x is None else f"{x / 1000:.2f}"
    mj = lambda m: '-' if not m else f"{m['T'] / 1000:.2f}/{m['J'] / 1000:.2f}"
    print(f"session {sid}: {len(out)} callbacks with >= {a.min_n} activations in {dur_s:.1f} s ({len(data)} on data entities)")
    print(f"\n{'callback':<86}{'ex':>3}{'n':>6}{'T_cfg':>8}{'FISH T/J':>15}{'LiME PF T/J':>15}{'LiME CF T/J':>16}{'minsep F':>9}{'minsep L':>9}{'C max':>8}  class F/L")
    for r in sorted(data, key=lambda r: -r['cpu_total_us'])[:a.top]:
        fp = r.get('fish_point') or (r.get('start_fit') if r['etype'] == 'tmr' else None)
        print(f"{(r['node'] + ' / ' + r['entity'])[-85:]:<86}{r['mode'] or '?':>3}{r['n']:>6}{ms(r.get('T_cfg_us')):>8}{mj(fp):>15}{mj(r.get('lime_pf')):>15}"
              f"{mj(r.get('lime_cf')):>16}{ms(r.get('fish_minsep_us')):>9}{ms(r.get('lime_minsep_under_us')):>9}{ms(r['C_max_us']):>8}  {r['class_fish']}/{r['class_lime']}")

    # ---- agreement and set comparison
    both = [r for r in data if r.get('fish_point') and r.get('lime_pf')]
    same_T = [r for r in both if abs(r['fish_point']['T'] - r['lime_pf']['T']) <= 0.01 * r['fish_point']['T']]
    tm = [r for r in data if r['etype'] == 'tmr' and r.get('T_cfg_us') and r.get('lime_pf')]
    tm_ok = [r for r in tm if abs(r['lime_pf']['T'] - r['T_cfg_us']) <= 0.01 * r['T_cfg_us']]
    tm_half = [r for r in tm if abs(r['lime_pf']['T'] - 2 * r['T_cfg_us']) <= 0.02 * r['T_cfg_us']]
    print(f"\nperiod agreement, data-triggered callbacks with a FISH point release: LiME-PF period = FISH period (±1 %) in {len(same_T)}/{len(both)}")
    if both:
        d_pf = [r['lime_pf']['J'] - r['fish_point']['J'] for r in both]; d_cf = [r['lime_cf']['J'] - r['fish_point']['J'] for r in both if r.get('lime_cf')]
        print(f"  jitter bound minus FISH point-release jitter: PF median {np.median(d_pf) / 1000:+.2f} ms (min {min(d_pf) / 1000:+.2f}, max {max(d_pf) / 1000:+.2f}); "
              f"CF median {np.median(d_cf) / 1000:+.2f} ms (max {max(d_cf) / 1000:+.2f})")
    print(f"timers: LiME-PF period = configured period in {len(tm_ok)}/{len(tm)}; = 2x configured (ROS-time timers at replay rate 0.5) in {len(tm_half)}/{len(tm)}")
    st = [r for r in data if r['lime_scope_st']]
    itt = {(r['executor'], r['symbol']) for r in st}
    print(f"\nwhat a LiME-IT run would see of these {len(data)} FISH data callbacks:")
    print(f"  on multi-threaded executors (outside LiME-IT's scope): {len(data) - len(st)}")
    print(f"  on single-threaded executors: {len(st)} → {len(itt)} distinct entry symbols per executor "
          f"({sum(1 for r in st if r['shares_symbol_with'])} callbacks share a symbol with another callback of the same executor → merged ITTs)")
    print(f"  in component containers (dlopen'ed libraries; LiME-IT Rule 3 must be off): {sum(1 for r in data if r['in_component_lib'])}")
    print(f"  expected perf samples < 10 in {a.perf_s:.0f} s at {a.perf_hz / 1000:.0f} kHz (likely undetected): {sum(1 for r in data if r['expected_perf_samples'] < 10)}")
    cl = collections.Counter((r['class_fish'], r['class_lime']) for r in data)
    print('  class (FISH point | LiME-PF): ' + ', '.join(f"{k[0]}|{k[1]}: {v}" for k, v in sorted(cl.items(), key=lambda kv: -kv[1])))
    if a.out:
        json.dump(dict(session=sid, window=W, callbacks=out), open(a.out, 'w'))
        print(f"\n→ {a.out}")


if __name__ == '__main__':
    main()
