"""
FISH Model Extraction
"""
import os
from pymongo import MongoClient
from influxdb_client_3 import InfluxDBClient3
from dataclasses import dataclass, field
from typing import Any
import networkx as nx
from itertools import count #for unique ids
from utils import pretty_print_executors, confirmed_kills
from utils import entity_fallback_from_trace
from utils import verify_actions
from utils import pretty_print_three_layers
from utils import pretty_print_four_layers
from utils import nsys_profiled_pids
from utils import create_detection_summary
from utils import create_graph_summary
from utils import export_fish_dot, export_fish_overview, export_fish_detail
from utils import export_fish_radial, export_fish_matrix
from utils import export_fish_staircase
from graph_utils import print_graph_metrics

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------

MONGO_URI = "mongodb://localhost:27017"
INFLUX_HOST = "http://127.0.0.1:8181"
INFLUX_TOKEN_FILE = os.path.expanduser("~/inf.tok")

TRACE_SESSION = "fish_20260322_212915"
vertex_counter = count(1)
SKIP_DEBUG = True
SKIP_RVIZ = True
SKIP_PARAMSERVICE = True  # Filter /parameter_events topic and parameter service entities

# ROS 2 parameter service infrastructure: auto-created topics and services
_PARAM_TOPICS = {"/parameter_events"}
_PARAM_SRV_SUFFIXES = (
    "/describe_parameters",
    "/get_parameter_types",
    "/get_parameters",
    "/list_parameters",
    "/set_parameters",
    "/set_parameters_atomically",
)

def _is_param_service(name):
    """Check if a topic or service name belongs to ROS 2 parameter service infrastructure."""
    if name in _PARAM_TOPICS:
        return True
    for suffix in _PARAM_SRV_SUFFIXES:
        if name.endswith(suffix):
            return True
    return False

#Classes
####
@dataclass
class FishVertex:
    t_v: str    #"EX" | "N" | "E" | "F"
    id_v: str   # unique identifier for vertex
    A_v: dict = field(default_factory=dict) #Attributes
    Z_v: list = field(default_factory=list) #membership set (children ids)
    level: int = 0 # l: 0=EX, 1=N, 2=E, 3=F 


@dataclass
class FishEdge:
    src: str
    dst: str
    tau: str # "InterP" | "IntraP"
    msgs: list = field(default_factory=list) 

@dataclass
class FishMessage:
    id: str
    name: str
    data_type: str
    src_exec: str
    src_node: str
    src_entity: str
    dst_exec: str
    dst_node: str
    dst_entity: str

####

def ret_A_dict(t_v, pid= -1, mode= "NA", label= "NA", etype= "NA", cb_addr= "NA", ptype= "NA"):

    if(t_v == "EX"):
        return {"label": label, "pid": pid, "mode": mode}
    if(t_v == "N"):
        return {"label": label, "publishers": {} }##Publishers will later be added as attributes
    if(t_v == "E"):
        return {"label": label, "etype": etype, "cb_addr": cb_addr}
    if(t_v == "F"):
        return {"label": label, "ptype": ptype}
    else:
        print("Unknown vertex type in ret_A_dict():", t_v)
        exit(1)
    

#Function generated by Claude Opus 4.6 (Anthropic)
def load_influx_token():
    with open(INFLUX_TOKEN_FILE) as f:
        for line in f:
            if line.startswith("Token:"):
                return line.split(":", 1)[1].strip()
    raise RuntimeError(f"Could not read token from {INFLUX_TOKEN_FILE}")

#Function generated by Claude Opus 4.6 (Anthropic)
def connect_mongo(session_name):
    """Return a MongoDB database handle for the given session."""
    client = MongoClient(MONGO_URI)
    db = client[session_name]
    print(f"[FISH model] MongoDB connected → {session_name}")
    print(f"  Collections: {db.list_collection_names()}")
    return db

#Function generated by Claude Opus 4.6 (Anthropic)
def connect_influx(session_name):
    """Return an InfluxDB3 client bound to the given session database."""
    token = load_influx_token()
    client = InfluxDBClient3(
        host=INFLUX_HOST, token=token, database=session_name,
    )
    print(f"[FISH model] InfluxDB3 connected → {session_name}")
    return client




def identify_executors(mongo):

    # Find all processes that have at least one rcl_node_init event, which means these are executors running node workloads
    executor_pids = mongo["ros2_trace"].distinct("vpid", {"event": "ros2:rcl_node_init"})
    print("executor_pids: ", executor_pids)

    killed_pids = confirmed_kills(mongo)

    executors = {}
    nodes = {}

    for executor_pid in executor_pids:

        if executor_pid in killed_pids:
            continue

        node_init_events = list(mongo["ros2_trace"].find({"event": "ros2:rcl_node_init", "vpid": executor_pid}))

        # Skip ros2cli tooling processes
        if SKIP_DEBUG and all(nie['payload']['node_name'].startswith("_ros2cli") for nie in node_init_events):
            continue

        # Skip rviz
        if SKIP_RVIZ and any(nie['procname'] == "rviz2" for nie in node_init_events):
            continue
        #print("##########executor_pid:", executor_pid)

        ##Create Executor Object
        ex_A = ret_A_dict("EX", label= "temp", pid=executor_pid)
        ex = FishVertex("EX", next(vertex_counter), ex_A, [], 0)
        
        for nie in node_init_events:
            #print("pid: ", nie['vpid'], 'tid:', nie['vtid'], 'procname:', nie['procname'], 'node name:', nie['payload']['node_name'])
            
            ns = nie['payload'].get('namespace', '/')
            full_name = ns.rstrip('/') + '/' + nie['payload']['node_name']
            n_A = ret_A_dict("N", label=nie['payload']['node_name'])
            n_A['full_name'] = full_name
            n_A['node_handle'] = nie['payload']['node_handle']
            if(ex.A_v['label'] == "temp"):
                ex.A_v['label'] = nie['procname'] ##Give the executor node it's name using one of the queried events
            #n_id = next(vertex_counter) 
            n = FishVertex("N", next(vertex_counter), n_A, level=1)
            ex.Z_v.append(n.id_v)
            nodes[n.id_v] = n
            
        executors[ex.id_v] = ex
                
    return executors, nodes

def identify_entities(mongo, nodes):

    entities = {}
    for node_id in nodes:
        node = nodes[node_id]
        full_name = node.A_v['full_name']
        node_handle = node.A_v['node_handle']

        # Always call fallback (needed for timers, and as backup if node_info is missing, see known_bugs.txt BUG-001)
        fallback = entity_fallback_from_trace(mongo, node_handle)

        # Try node_info first (has msg types)
        info = mongo["node_info"].find_one({"node": full_name})
        if info is None:
            info = fallback

        ##Always get timers from fallback since ros2 node info doesn't provide this information
        info["Timers"] = fallback["Timers"]

        ##Detect actions
        actions, info = verify_actions(info)

        # Publishers → store on node for edge construction, NOT entities
        pubs = info.get("Publishers", {})
        if SKIP_PARAMSERVICE:
            pubs = {t: m for t, m in pubs.items() if not _is_param_service(t)}
        node.A_v['publishers'] = pubs

        # Subscriptions → entity
        for topic, msg_type in info.get("Subscribers", {}).items():
            if SKIP_PARAMSERVICE and _is_param_service(topic):
                continue
            e_A = ret_A_dict("E", label=topic, etype="sub")
            e_A["msg_type"] = msg_type
            e = FishVertex("E", next(vertex_counter), e_A, [], 2)
            node.Z_v.append(e.id_v)
            entities[e.id_v] = e

        # Services → entity
        for srv_name, srv_type in info.get("Service_Servers", {}).items():
            if SKIP_PARAMSERVICE and _is_param_service(srv_name):
                continue
            e_A = ret_A_dict("E", label=srv_name, etype="serv")
            e_A["srv_type"] = srv_type
            e = FishVertex("E", next(vertex_counter), e_A, [], 2)
            node.Z_v.append(e.id_v)
            entities[e.id_v] = e

        # Timers → entity
        for timer_handle, period_ns in info.get("Timers", {}).items():
            e_A = ret_A_dict("E", label=f"timer_{period_ns}ns", etype="tmr")
            e_A["timer_handle"] = timer_handle
            e_A["period_ns"] = period_ns
            e = FishVertex("E", next(vertex_counter), e_A, [], 2)
            node.Z_v.append(e.id_v)
            entities[e.id_v] = e

        # Actions → abstract entity referencing components
        for action_name, action_info in info.get("Action_Servers", {}).items():
            e_A = ret_A_dict("E", label=action_name, etype="act")
            e_A["action_components"] = action_info["components"]
            e = FishVertex("E", next(vertex_counter), e_A, [], 2)
            node.Z_v.append(e.id_v)
            entities[e.id_v] = e

    return entities


def identify_callbacks(mongo, nodes, entities, executors):
    """
    Layer 2→3: Trace callback chains for each entity and create Function vertices.
    Chains (verified in mapping.txt):
      sub:  rcl_subscription_init → rclcpp_subscription_init → rclcpp_subscription_callback_added → rclcpp_callback_register
      serv: rcl_service_init → rclcpp_service_callback_added → rclcpp_callback_register
      tmr:  rclcpp_timer_callback_added → rclcpp_callback_register  (timer_handle from entity A_v)
      act:  abstract entity — component services already get their own callbacks
    Skips nodes belonging to nsys-profiled executors (GPU function layer handled separately).
    Returns dict {id_v: FishVertex} of Function vertices.
    """
    functions = {}
    coll = mongo["ros2_trace"]

    # Identify GPU-profiled PIDs from fishlog — these get functions from nsys, not rclcpp chains
    gpu_pids = nsys_profiled_pids(mongo)

    # Build node_id → executor_pid map
    node_to_pid = {}
    for ex_id, ex in executors.items():
        for n_id in ex.Z_v:
            node_to_pid[n_id] = ex.A_v['pid']

    for node_id, node in nodes.items():
        # Skip nsys-profiled nodes — their functions come from GPU trace
        if node_to_pid.get(node_id) in gpu_pids:
            print(f"  [identify_callbacks] Skipping nsys-profiled node: {node.A_v['label']} (pid={node_to_pid[node_id]})")
            continue

        node_handle = node.A_v['node_handle']

        # --- Build per-node callback lookup maps from trace ---

        # Subscription chain: topic_name → {callback, symbol}
        sub_chain = {}
        for si in coll.find({"event": "ros2:rcl_subscription_init", "payload.node_handle": node_handle}):
            sub_handle = si["payload"]["subscription_handle"]
            topic = si["payload"]["topic_name"]

            csub = coll.find_one({"event": "ros2:rclcpp_subscription_init",
                                  "payload.subscription_handle": sub_handle})
            if not csub:
                continue  # rcl-only (rclpy node), no C++ callback chain
            subscription_obj = csub["payload"]["subscription"]

            cb_added = coll.find_one({"event": "ros2:rclcpp_subscription_callback_added",
                                      "payload.subscription": subscription_obj})
            if not cb_added:
                continue
            callback_ptr = cb_added["payload"]["callback"]

            cb_reg = coll.find_one({"event": "ros2:rclcpp_callback_register",
                                    "payload.callback": callback_ptr})
            if not cb_reg:
                continue

            sub_chain[topic] = {"callback": callback_ptr, "symbol": cb_reg["payload"]["symbol"]}

        # Service chain: service_name → {callback, symbol}
        srv_chain = {}
        for si in coll.find({"event": "ros2:rcl_service_init", "payload.node_handle": node_handle}):
            srv_handle = si["payload"]["service_handle"]
            srv_name = si["payload"]["service_name"]

            srv_cb = coll.find_one({"event": "ros2:rclcpp_service_callback_added",
                                    "payload.service_handle": srv_handle})
            if not srv_cb:
                continue
            callback_ptr = srv_cb["payload"]["callback"]

            cb_reg = coll.find_one({"event": "ros2:rclcpp_callback_register",
                                    "payload.callback": callback_ptr})
            if not cb_reg:
                continue

            srv_chain[srv_name] = {"callback": callback_ptr, "symbol": cb_reg["payload"]["symbol"]}

        # --- Match entities to their callbacks ---

        for e_id in node.Z_v:
            entity = entities.get(e_id)
            if not entity or entity.t_v != "E":
                continue

            etype = entity.A_v["etype"]
            cb_info = None

            if etype == "sub":
                cb_info = sub_chain.get(entity.A_v["label"])

            elif etype == "serv":
                cb_info = srv_chain.get(entity.A_v["label"])

            elif etype == "tmr":
                timer_handle = entity.A_v.get("timer_handle")
                if timer_handle:
                    tmr_cb = coll.find_one({"event": "ros2:rclcpp_timer_callback_added",
                                            "payload.timer_handle": timer_handle})
                    if tmr_cb:
                        callback_ptr = tmr_cb["payload"]["callback"]
                        cb_reg = coll.find_one({"event": "ros2:rclcpp_callback_register",
                                                "payload.callback": callback_ptr})
                        if cb_reg:
                            cb_info = {"callback": callback_ptr, "symbol": cb_reg["payload"]["symbol"]}

            elif etype == "act":
                # Abstract entity — component services have their own callbacks.
                # Action Z_v stays empty at function layer (partition property).
                continue

            if cb_info:
                entity.A_v["cb_addr"] = cb_info["callback"]
                f_A = ret_A_dict("F", label=cb_info["symbol"], ptype="cpu")
                f_A["cb_addr"] = cb_info["callback"]
                f = FishVertex("F", next(vertex_counter), f_A, [], 3)
                entity.Z_v.append(f.id_v)
                functions[f.id_v] = f

    return functions


# ---------------------------------------------------------------------------
# Graph Construction
# ---------------------------------------------------------------------------

def create_graph_add_vertical_relations(executors, nodes, entities, functions):
    """Build nx.DiGraph with all vertices and vertical (hierarchy) edges from Z_v sets.

    Vertical edges represent containment:
      EX → N  (executor contains node)
      N  → E  (node contains entity)
      E  → F  (entity contains function)

    Each nx node stores the FishVertex as attribute 'v'.
    Each vertical edge has attribute rel='contains'.
    """
    G = nx.DiGraph()

    # Add all vertices
    for ex in executors.values():
        G.add_node(ex.id_v, v=ex)
    for n in nodes.values():
        G.add_node(n.id_v, v=n)
    for e in entities.values():
        G.add_node(e.id_v, v=e)
    for f in functions.values():
        G.add_node(f.id_v, v=f)

    # Add vertical edges from Z_v membership sets
    for ex in executors.values():
        for n_id in ex.Z_v:
            G.add_edge(ex.id_v, n_id, rel="contains", level="L0_L1")

    for n in nodes.values():
        for e_id in n.Z_v:
            if e_id in entities:
                G.add_edge(n.id_v, e_id, rel="contains", level="L1_L2")

    for e in entities.values():
        for f_id in e.Z_v:
            if f_id in functions:
                G.add_edge(e.id_v, f_id, rel="contains", level="L2_L3")

    v_count = G.number_of_nodes()
    e_count = G.number_of_edges()
    print(f"[FISH graph] Vertical: {v_count} vertices, {e_count} containment edges")
    return G


def get_node_infos(mongo):
    """Load node_info from MongoDB into a dict keyed by node full_name.

    Returns:
      {"/kiss_icp_node": {"Subscribers": {topic: msg_type, ...},
                          "Publishers": {topic: msg_type, ...},
                          "Service_Servers": {name: type, ...},
                          "Service_Clients": {name: type, ...}},
       ...}
    """
    node_infos = {}
    for doc in mongo["node_info"].find():
        name = doc["node"]
        node_infos[name] = {
            "Subscribers": doc.get("Subscribers", {}),
            "Publishers": doc.get("Publishers", {}),
            "Service_Servers": doc.get("Service_Servers", {}),
            "Service_Clients": doc.get("Service_Clients", {}),
        }
    print(f"[FISH graph] Loaded node_info for {len(node_infos)} nodes")
    return node_infos


def _propagate_l3(G, src_entity_id, dst_entity_id, edge_attrs, entities, functions):
    """Propagate an entity-level edge down to function level.

    If both entities have function children, create edges between them
    carrying the same edge nature (msg/dep).
    """
    src_e = entities.get(src_entity_id)
    dst_e = entities.get(dst_entity_id)
    if not src_e or not dst_e:
        return 0

    src_funcs = [fid for fid in src_e.Z_v if fid in functions]
    dst_funcs = [fid for fid in dst_e.Z_v if fid in functions]

    count = 0
    for sf in src_funcs:
        for df in dst_funcs:
            G.add_edge(sf, df, **edge_attrs, level="L3")
            count += 1
    return count


def _aggregate_l1(G, nodes, entities):
    """Aggregate entity-level horizontal edges up to node level.

    For each pair of nodes that have entity-level edges between them,
    create a single node-level edge carrying the set of topics/services.
    """
    # Build entity_id → node_id reverse map
    entity_to_node = {}
    for n in nodes.values():
        for e_id in n.Z_v:
            if e_id in entities:
                entity_to_node[e_id] = n.id_v

    # Collect entity edges grouped by (src_node, dst_node)
    node_pairs = {}  # (src_node_id, dst_node_id) → list of edge info
    for u, v, data in G.edges(data=True):
        if data.get("level") != "L2":
            continue
        src_node = entity_to_node.get(u)
        dst_node = entity_to_node.get(v)
        if src_node is None or dst_node is None:
            continue
        key = (src_node, dst_node)
        node_pairs.setdefault(key, []).append(data)

    count = 0
    for (src_n, dst_n), edge_list in node_pairs.items():
        topics = [e.get("topic", e.get("service", "?")) for e in edge_list]
        nature_set = {e.get("nature", "?") for e in edge_list}
        G.add_edge(src_n, dst_n, rel="comm", level="L1",
                   comm_count=len(edge_list),
                   topics=topics,
                   natures=nature_set)
        count += 1
    return count


def _aggregate_l0(G, executors, nodes):
    """Aggregate node-level horizontal edges up to executor level.

    For each pair of executors that have node-level edges between them,
    create a single executor-level edge with total comm count.
    """
    # Build node_id → executor_id reverse map
    node_to_exec = {}
    for ex in executors.values():
        for n_id in ex.Z_v:
            node_to_exec[n_id] = ex.id_v

    # Collect node edges grouped by (src_exec, dst_exec)
    exec_pairs = {}  # (src_ex, dst_ex) → list of edge info
    for u, v, data in G.edges(data=True):
        if data.get("level") != "L1":
            continue
        src_ex = node_to_exec.get(u)
        dst_ex = node_to_exec.get(v)
        if src_ex is None or dst_ex is None:
            continue
        key = (src_ex, dst_ex)
        exec_pairs.setdefault(key, []).append(data)

    count = 0
    for (src_ex, dst_ex), edge_list in exec_pairs.items():
        total_comm = sum(e.get("comm_count", 1) for e in edge_list)
        all_topics = []
        all_natures = set()
        for e in edge_list:
            all_topics.extend(e.get("topics", []))
            all_natures.update(e.get("natures", set()))

        tau = "IntraP" if src_ex == dst_ex else "InterP"
        G.add_edge(src_ex, dst_ex, rel="comm", level="L0",
                   tau=tau,
                   comm_count=total_comm,
                   topics=all_topics,
                   natures=all_natures)
        count += 1
    return count


def add_horizontal_relations(G, node_infos, executors, nodes, entities, functions):
    """Add communication edges at entity level, then propagate/aggregate.

    Entity-level edges (L2):
      - topic matching: publisher node → subscriber entity (nature="msg")
      - service matching: client node → server entity (nature="dep")

    Then:
      - propagate_l3: entity edges → function edges
      - aggregate_l1: entity edges → node edges (comm set)
      - aggregate_l0: node edges → executor edges (process comm)
    """
    # Build lookup: node full_name → (node_id, FishVertex)
    name_to_node = {}
    for n in nodes.values():
        name_to_node[n.A_v['full_name']] = n

    # Build lookup: (node_id, topic) → subscriber entity_id
    # A subscriber entity's label is the topic name
    sub_index = {}  # topic → [(node_id, entity_id), ...]
    srv_index = {}  # service_name → [(node_id, entity_id), ...]
    for n in nodes.values():
        for e_id in n.Z_v:
            e = entities.get(e_id)
            if not e:
                continue
            if e.A_v.get("etype") == "sub":
                topic = e.A_v["label"]
                sub_index.setdefault(topic, []).append((n.id_v, e_id))
            elif e.A_v.get("etype") == "serv":
                srv_name = e.A_v["label"]
                srv_index.setdefault(srv_name, []).append((n.id_v, e_id))

    # Build lookup: which nodes publish on which topics (from node_infos + node A_v publishers)
    # Use both node_info (complete) and node.A_v['publishers'] (from model extraction)
    pub_index = {}  # topic → [node_id, ...]
    for n in nodes.values():
        pubs = n.A_v.get("publishers", {})
        for topic in pubs:
            pub_index.setdefault(topic, []).append(n.id_v)

    # Also check node_infos for nodes that might have publishers not yet in node.A_v
    # (e.g., nodes found in node_info but matched to model nodes)
    for full_name, info in node_infos.items():
        n = name_to_node.get(full_name)
        if n is None:
            continue
        for topic in info.get("Publishers", {}):
            if SKIP_PARAMSERVICE and _is_param_service(topic):
                continue
            existing = pub_index.get(topic, [])
            if n.id_v not in existing:
                pub_index.setdefault(topic, []).append(n.id_v)

    # Service client index from node_infos
    client_index = {}  # service_name → [node_id, ...]
    for full_name, info in node_infos.items():
        n = name_to_node.get(full_name)
        if n is None:
            continue
        for srv_name in info.get("Service_Clients", {}):
            if SKIP_PARAMSERVICE and _is_param_service(srv_name):
                continue
            client_index.setdefault(srv_name, []).append(n.id_v)

    # --- L2: Entity-level edges ---
    l2_count = 0

    # Topic matching: publisher_node → subscriber_entity
    for topic, sub_list in sub_index.items():
        pub_nodes = pub_index.get(topic, [])
        for pub_node_id in pub_nodes:
            for sub_node_id, sub_entity_id in sub_list:
                if pub_node_id == sub_node_id:
                    continue  # skip self-loops (same node pub→sub on same topic)
                # Find a "source entity" on the publishing node for this topic.
                # Publisher is not an entity, so we pick the first entity on that node
                # as a proxy source. The edge semantically goes node→entity.
                # We store the publishing node_id on the edge for reference.
                G.add_edge(pub_node_id, sub_entity_id, rel="comm", level="L2",
                           nature="msg", topic=topic)
                l2_count += 1

    # Service matching: client_node → server_entity
    for srv_name, srv_list in srv_index.items():
        client_nodes = client_index.get(srv_name, [])
        for client_node_id in client_nodes:
            for srv_node_id, srv_entity_id in srv_list:
                if client_node_id == srv_node_id:
                    continue
                G.add_edge(client_node_id, srv_entity_id, rel="comm", level="L2",
                           nature="dep", service=srv_name)
                l2_count += 1

    print(f"[FISH graph] L2 horizontal edges: {l2_count}")

    # --- L3: Propagate entity edges to function level ---
    # Note: since publisher side is a node (not entity), L3 propagation
    # only applies when both sides are entities. For topic edges, the
    # source is a node_id so we skip L3 propagation for those.
    # L3 propagation is primarily for service client→server when both are entities.
    # (Currently no service clients in this session.)
    l3_count = 0
    # Future: when rcl_publish_characterization attributes publishes to
    # specific entities, we can add entity→entity edges and propagate to L3.
    print(f"[FISH graph] L3 propagated edges: {l3_count}")

    # --- L1: Aggregate entity edges to node level ---
    # For topic edges, source is already a node_id, dest is entity.
    # We need to resolve dest entity → its parent node for node-level aggregation.
    entity_to_node = {}
    for n in nodes.values():
        for e_id in n.Z_v:
            if e_id in entities:
                entity_to_node[e_id] = n.id_v

    node_pairs = {}
    for u, v, data in G.edges(data=True):
        if data.get("level") != "L2":
            continue
        src_node = u if u in nodes else entity_to_node.get(u)
        dst_node = entity_to_node.get(v, v if v in nodes else None)
        if src_node is None or dst_node is None:
            continue
        key = (src_node, dst_node)
        node_pairs.setdefault(key, []).append(data)

    l1_count = 0
    for (src_n, dst_n), edge_list in node_pairs.items():
        topics = [e.get("topic", e.get("service", "?")) for e in edge_list]
        nature_set = {e.get("nature", "?") for e in edge_list}
        G.add_edge(src_n, dst_n, rel="comm", level="L1",
                   comm_count=len(edge_list),
                   topics=topics,
                   natures=nature_set)
        l1_count += 1
    print(f"[FISH graph] L1 aggregated edges: {l1_count}")

    # --- L0: Aggregate node edges to executor level ---
    l0_count = _aggregate_l0(G, executors, nodes)
    print(f"[FISH graph] L0 aggregated edges: {l0_count}")

    total_h = l2_count + l3_count + l1_count + l0_count
    print(f"[FISH graph] Total horizontal edges: {total_h}")
    return G


if __name__ == "__main__":
    mongo = connect_mongo(TRACE_SESSION)
    influx = connect_influx(TRACE_SESSION)
    session_dir = os.path.expanduser(f"~/fish_traces/{TRACE_SESSION}")

    # Layer extraction
    executors, nodes = identify_executors(mongo)
    entities = identify_entities(mongo, nodes)
    functions = identify_callbacks(mongo, nodes, entities, executors)
    pretty_print_four_layers(executors, nodes, entities, functions)
    create_detection_summary(executors, nodes, entities, functions, mongo)

    # Graph construction
    G = create_graph_add_vertical_relations(executors, nodes, entities, functions)
    node_infos = get_node_infos(mongo)
    G = add_horizontal_relations(G, node_infos, executors, nodes, entities, functions)

    create_graph_summary(G)
    metrics = print_graph_metrics(G)

    # Visualization
    export_fish_overview(G, "fish_overview", fmt="png")
    export_fish_overview(G, "fish_overview", fmt="pdf")
    for ex_id, ex in executors.items():
        label = ex.A_v.get("label", str(ex_id))
        export_fish_detail(G, ex_id, f"fish_detail_{label}", fmt="png")
        export_fish_detail(G, ex_id, f"fish_detail_{label}", fmt="pdf")
    export_fish_radial(G, "fish_radial", fmt="png")
    export_fish_matrix(G, executors, nodes, entities, "fish_matrix", fmt="png")
    export_fish_staircase(G, "fish_staircase", fmt="png")
