"""
FISH Model Extraction
"""
import os
from pymongo import MongoClient
from influxdb_client_3 import InfluxDBClient3
from dataclasses import dataclass, field
from typing import Any
import networkx as nx
from itertools import count #for unique ids
from utils import pretty_print_executors, confirmed_kills
from utils import entity_fallback_from_trace
from utils import verify_actions
from utils import pretty_print_three_layers
from utils import pretty_print_four_layers
from utils import nsys_profiled_pids
from utils import create_detection_summary
from utils import create_graph_summary
from utils import export_fish_dot, export_fish_overview, export_fish_detail
from utils import export_fish_radial, export_fish_matrix
from utils import export_fish_staircase, export_fish_l3_chains
from graph_utils import print_graph_metrics

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------

MONGO_URI = "mongodb://localhost:27017"
INFLUX_HOST = "http://127.0.0.1:8181"
INFLUX_TOKEN_FILE = os.path.expanduser("~/inf.tok")

TRACE_SESSION = "fish_20260330_234647"
vertex_counter = count(1)
SKIP_DEBUG = True
SKIP_RVIZ = True
SKIP_PARAMSERVICE = True  # Filter /parameter_events topic and parameter service entities
INCLUDE_EXTERNAL_ACTIONS = True  # Include short-lived action clients from trace (ros2cli send_goal etc.)

# ROS 2 parameter service infrastructure: auto-created topics and services
_PARAM_TOPICS = {"/parameter_events"}
_PARAM_SRV_SUFFIXES = (
    "/describe_parameters",
    "/get_parameter_types",
    "/get_parameters",
    "/list_parameters",
    "/set_parameters",
    "/set_parameters_atomically",
)

def _is_param_service(name):
    """Check if a topic or service name belongs to ROS 2 parameter service infrastructure."""
    if name in _PARAM_TOPICS:
        return True
    for suffix in _PARAM_SRV_SUFFIXES:
        if name.endswith(suffix):
            return True
    return False

#Classes
####
@dataclass
class FishVertex:
    t_v: str    #"EX" | "N" | "E" | "F"
    id_v: str   # unique identifier for vertex
    A_v: dict = field(default_factory=dict) #Attributes
    Z_v: list = field(default_factory=list) #membership set (children ids)
    level: int = 0 # l: 0=EX, 1=N, 2=E, 3=F 


@dataclass
class FishEdge:
    src: str
    dst: str
    tau: str # "InterP" | "IntraP"
    msgs: list = field(default_factory=list) 

@dataclass
class FishMessage:
    id: str
    name: str
    data_type: str
    src_exec: str
    src_node: str
    src_entity: str
    dst_exec: str
    dst_node: str
    dst_entity: str

####

def ret_A_dict(t_v, pid= -1, mode= "NA", label= "NA", etype= "NA", cb_addr= "NA", ptype= "NA"):

    if(t_v == "EX"):
        return {"label": label, "pid": pid, "mode": mode}
    if(t_v == "N"):
        return {"label": label, "publishers": {} }##Publishers will later be added as attributes
    if(t_v == "E"):
        return {"label": label, "etype": etype, "cb_addr": cb_addr}
    if(t_v == "F"):
        return {"label": label, "ptype": ptype}
    else:
        print("Unknown vertex type in ret_A_dict():", t_v)
        exit(1)
    

#Function generated by Claude Opus 4.6 (Anthropic)
def load_influx_token():
    with open(INFLUX_TOKEN_FILE) as f:
        for line in f:
            if line.startswith("Token:"):
                return line.split(":", 1)[1].strip()
    raise RuntimeError(f"Could not read token from {INFLUX_TOKEN_FILE}")

#Function generated by Claude Opus 4.6 (Anthropic)
def connect_mongo(session_name):
    """Return a MongoDB database handle for the given session."""
    client = MongoClient(MONGO_URI)
    db = client[session_name]
    print(f"[FISH model] MongoDB connected → {session_name}")
    print(f"  Collections: {db.list_collection_names()}")
    return db

#Function generated by Claude Opus 4.6 (Anthropic)
def connect_influx(session_name):
    """Return an InfluxDB3 client bound to the given session database."""
    token = load_influx_token()
    client = InfluxDBClient3(
        host=INFLUX_HOST, token=token, database=session_name,
    )
    print(f"[FISH model] InfluxDB3 connected → {session_name}")
    return client




def identify_executors(mongo):

    # Find all processes that have at least one rcl_node_init event, which means these are executors running node workloads
    executor_pids = mongo["ros2_trace"].distinct("vpid", {"event": "ros2:rcl_node_init"})
    print("executor_pids: ", executor_pids)

    killed_pids = confirmed_kills(mongo)

    executors = {}
    nodes = {}

    for executor_pid in executor_pids:

        if executor_pid in killed_pids:
            continue

        node_init_events = list(mongo["ros2_trace"].find({"event": "ros2:rcl_node_init", "vpid": executor_pid}))

        # Skip ros2cli tooling processes
        if SKIP_DEBUG and all(nie['payload']['node_name'].startswith("_ros2cli") for nie in node_init_events):
            if INCLUDE_EXTERNAL_ACTIONS:
                # Keep action clients (send_goal) — they are real robot commands
                has_action_client = any("send_goal" in nie['payload']['node_name'] for nie in node_init_events)
                if not has_action_client:
                    continue
            else:
                continue

        # Skip rviz
        if SKIP_RVIZ and any(nie['procname'] == "rviz2" for nie in node_init_events):
            continue
        #print("##########executor_pid:", executor_pid)

        ##Create Executor Object
        ex_A = ret_A_dict("EX", label= "temp", pid=executor_pid)
        ex = FishVertex("EX", next(vertex_counter), ex_A, [], 0)
        
        for nie in node_init_events:
            #print("pid: ", nie['vpid'], 'tid:', nie['vtid'], 'procname:', nie['procname'], 'node name:', nie['payload']['node_name'])
            
            ns = nie['payload'].get('namespace', '/')
            full_name = ns.rstrip('/') + '/' + nie['payload']['node_name']
            n_A = ret_A_dict("N", label=nie['payload']['node_name'])
            n_A['full_name'] = full_name
            n_A['node_handle'] = nie['payload']['node_handle']
            if(ex.A_v['label'] == "temp"):
                ex.A_v['label'] = nie['procname'] ##Give the executor node it's name using one of the queried events
            #n_id = next(vertex_counter) 
            n = FishVertex("N", next(vertex_counter), n_A, level=1)
            ex.Z_v.append(n.id_v)
            nodes[n.id_v] = n
            
        executors[ex.id_v] = ex
                
    return executors, nodes

def identify_entities(mongo, nodes):

    entities = {}
    for node_id in nodes:
        node = nodes[node_id]
        full_name = node.A_v['full_name']
        node_handle = node.A_v['node_handle']

        # Always call fallback (needed for timers, and as backup if node_info is missing, see known_bugs.txt BUG-001)
        fallback = entity_fallback_from_trace(mongo, node_handle)

        # Try node_info first (has msg types)
        info = mongo["node_info"].find_one({"node": full_name})
        if info is None:
            info = fallback

        ##Always get timers from fallback since ros2 node info doesn't provide this information
        info["Timers"] = fallback["Timers"]

        ##Detect actions
        actions, info = verify_actions(info)

        # Publishers → store on node for edge construction, NOT entities
        pubs = info.get("Publishers", {})
        if SKIP_PARAMSERVICE:
            pubs = {t: m for t, m in pubs.items() if not _is_param_service(t)}
        node.A_v['publishers'] = pubs

        # Subscriptions → entity with sub aspect
        for topic, msg_type in info.get("Subscribers", {}).items():
            if SKIP_PARAMSERVICE and _is_param_service(topic):
                continue
            e_A = ret_A_dict("E", label=topic, etype="sub")
            e_A["msg_type"] = msg_type
            e_A["aspects"] = [{"aspect": "sub", "topic": topic, "msg_type": msg_type}]
            e = FishVertex("E", next(vertex_counter), e_A, [], 2)
            node.Z_v.append(e.id_v)
            entities[e.id_v] = e

        # Services → entity with req_sub + res_pub aspects
        for srv_name, srv_type in info.get("Service_Servers", {}).items():
            if SKIP_PARAMSERVICE and _is_param_service(srv_name):
                continue
            e_A = ret_A_dict("E", label=srv_name, etype="serv")
            e_A["srv_type"] = srv_type
            e_A["aspects"] = [
                {"aspect": "req_sub", "service": srv_name},
                {"aspect": "res_pub", "service": srv_name},
            ]
            e = FishVertex("E", next(vertex_counter), e_A, [], 2)
            node.Z_v.append(e.id_v)
            entities[e.id_v] = e

        # Timers → entity (aspects added later via runtime attribution)
        for timer_handle, period_ns in info.get("Timers", {}).items():
            e_A = ret_A_dict("E", label=f"timer_{period_ns}ns", etype="tmr")
            e_A["timer_handle"] = timer_handle
            e_A["period_ns"] = period_ns
            e_A["aspects"] = []
            e = FishVertex("E", next(vertex_counter), e_A, [], 2)
            node.Z_v.append(e.id_v)
            entities[e.id_v] = e

        # Node-level unattributed aspects (will be transferred to entities via runtime attribution)
        # Publishers — known from node_info or rcl_publisher_init, entity TBD
        node_pub_aspects = []
        pubs = info.get("Publishers", {})
        if SKIP_PARAMSERVICE:
            pubs = {t: m for t, m in pubs.items() if not _is_param_service(t)}
        for topic, msg_type in pubs.items():
            node_pub_aspects.append({"aspect": "pub", "topic": topic, "msg_type": msg_type})
        node.A_v["pub_aspects"] = node_pub_aspects
        node.A_v["publishers"] = pubs  # keep for backward compat

        # Service clients — known from node_info or rcl_client_init, entity TBD
        node_cli_aspects = []
        for cli_name, cli_type in info.get("Service_Clients", {}).items():
            if SKIP_PARAMSERVICE and _is_param_service(cli_name):
                continue
            node_cli_aspects.append({"aspect": "cli", "service": cli_name})
        node.A_v["cli_aspects"] = node_cli_aspects
        node.A_v["service_clients"] = {a["service"]: "" for a in node_cli_aspects}  # keep for backward compat

        # Actions → abstract entity with 5 component entities (3 services + 2 publishers)
        coll = mongo["ros2_trace"]
        for action_name, action_info in info.get("Action_Servers", {}).items():
            e_A = ret_A_dict("E", label=action_name, etype="act")
            e_A["action_type"] = action_info if isinstance(action_info, str) else action_info.get("type", "")

            short_name = action_name.rsplit('/', 1)[-1]
            act_init = coll.find_one({"event": "ros2:rclcpp_action_server_init",
                                      "payload.action_name": short_name})

            component_ids = {}
            if act_init:
                p = act_init["payload"]
                e_A["action_handle"] = p["action_server_handle"]

                # Create 3 service component entities
                for role, handle_key in [("send_goal", "goal_service_handle"),
                                         ("cancel_goal", "cancel_service_handle"),
                                         ("get_result", "result_service_handle")]:
                    svc_name = f"{action_name}/_action/{role}"
                    ce_A = ret_A_dict("E", label=svc_name, etype="serv")
                    ce_A["service_handle"] = p[handle_key]
                    ce_A["action_role"] = role
                    ce_A["aspects"] = [
                        {"aspect": "req_sub", "service": svc_name},
                        {"aspect": "res_pub", "service": svc_name},
                    ]
                    ce = FishVertex("E", next(vertex_counter), ce_A, [], 2)
                    node.Z_v.append(ce.id_v)
                    entities[ce.id_v] = ce
                    component_ids[role] = ce.id_v

                # Create 2 publisher component entries (look up handles from trace)
                for pub_role in ["feedback", "status"]:
                    pub_topic = f"{action_name}/_action/{pub_role}"
                    pub_init = coll.find_one({"event": "ros2:rcl_publisher_init",
                                              "payload.node_handle": node_handle,
                                              "payload.topic_name": pub_topic})
                    if pub_init:
                        component_ids[pub_role] = pub_init["payload"]["publisher_handle"]

            e_A["action_components"] = component_ids
            e = FishVertex("E", next(vertex_counter), e_A, [], 2)
            node.Z_v.append(e.id_v)
            entities[e.id_v] = e

    return entities


def identify_callbacks(mongo, nodes, entities, executors):
    """
    Layer 2→3: Trace callback chains for each entity and create Function vertices.
    Chains (verified in mapping.txt):
      rclcpp (C++ nodes):
        sub:  rcl_subscription_init → rclcpp_subscription_init → rclcpp_subscription_callback_added → rclcpp_callback_register
        serv: rcl_service_init → rclcpp_service_callback_added → rclcpp_callback_register
        tmr:  rclcpp_timer_callback_added → rclcpp_callback_register
      rclpy (Python nodes, fallback):
        sub:  rcl_subscription_init → rclpy_subscription_callback_added → rclpy_callback_register
        serv: rcl_service_init → rclpy_service_callback_added → rclpy_callback_register
        tmr:  rclpy_timer_callback_added → rclpy_callback_register
      act:  abstract entity — component services already get their own callbacks
    Tries rclcpp path first, falls back to rclpy if not found.
    nsys-profiled nodes are NOT skipped — their CPU-side callbacks (rclpy) are
    extracted and marked with gpu_node=True. GPU function vertices (sm, ce) are
    added separately by the GPU function layer extractor.
    Returns dict {id_v: FishVertex} of Function vertices.
    """
    functions = {}
    coll = mongo["ros2_trace"]

    # Identify GPU-profiled PIDs from fishlog — these get functions from nsys, not rclcpp chains
    gpu_pids = nsys_profiled_pids(mongo)

    # Build node_id → executor_pid map
    node_to_pid = {}
    for ex_id, ex in executors.items():
        for n_id in ex.Z_v:
            node_to_pid[n_id] = ex.A_v['pid']

    for node_id, node in nodes.items():
        is_gpu_node = node_to_pid.get(node_id) in gpu_pids

        node_handle = node.A_v['node_handle']

        # --- Build per-node callback lookup maps from trace ---

        # Subscription chain: topic_name → {callback, symbol}
        sub_chain = {}
        for si in coll.find({"event": "ros2:rcl_subscription_init", "payload.node_handle": node_handle}):
            sub_handle = si["payload"]["subscription_handle"]
            topic = si["payload"]["topic_name"]

            # Try rclcpp path first (C++ nodes)
            csub = coll.find_one({"event": "ros2:rclcpp_subscription_init",
                                  "payload.subscription_handle": sub_handle})
            if csub:
                subscription_obj = csub["payload"]["subscription"]
                cb_added = coll.find_one({"event": "ros2:rclcpp_subscription_callback_added",
                                          "payload.subscription": subscription_obj})
                if cb_added:
                    callback_ptr = cb_added["payload"]["callback"]
                    cb_reg = coll.find_one({"event": "ros2:rclcpp_callback_register",
                                            "payload.callback": callback_ptr})
                    if cb_reg:
                        sub_chain[topic] = {"callback": callback_ptr, "symbol": cb_reg["payload"]["symbol"]}
                        continue

            # Fallback: rclpy path (Python nodes)
            py_cb = coll.find_one({"event": "ros2:rclpy_subscription_callback_added",
                                   "payload.subscription_handle": sub_handle})
            if py_cb:
                callback_ptr = py_cb["payload"]["callback"]
                cb_reg = coll.find_one({"event": "ros2:rclpy_callback_register",
                                        "payload.callback": callback_ptr})
                if cb_reg:
                    sub_chain[topic] = {"callback": callback_ptr, "symbol": cb_reg["payload"]["symbol"]}

        # Service chain: service_name → {callback, symbol}
        srv_chain = {}
        for si in coll.find({"event": "ros2:rcl_service_init", "payload.node_handle": node_handle}):
            srv_handle = si["payload"]["service_handle"]
            srv_name = si["payload"]["service_name"]

            # Try rclcpp path first (C++ nodes)
            srv_cb = coll.find_one({"event": "ros2:rclcpp_service_callback_added",
                                    "payload.service_handle": srv_handle})
            if srv_cb:
                callback_ptr = srv_cb["payload"]["callback"]
                cb_reg = coll.find_one({"event": "ros2:rclcpp_callback_register",
                                        "payload.callback": callback_ptr})
                if cb_reg:
                    srv_chain[srv_name] = {"callback": callback_ptr, "symbol": cb_reg["payload"]["symbol"]}
                    continue

            # Fallback: rclpy path (Python nodes)
            py_cb = coll.find_one({"event": "ros2:rclpy_service_callback_added",
                                   "payload.service_handle": srv_handle})
            if py_cb:
                callback_ptr = py_cb["payload"]["callback"]
                cb_reg = coll.find_one({"event": "ros2:rclpy_callback_register",
                                        "payload.callback": callback_ptr})
                if cb_reg:
                    srv_chain[srv_name] = {"callback": callback_ptr, "symbol": cb_reg["payload"]["symbol"]}

        # --- Match entities to their callbacks ---

        for e_id in node.Z_v:
            entity = entities.get(e_id)
            if not entity or entity.t_v != "E":
                continue

            etype = entity.A_v["etype"]
            cb_info = None

            if etype == "sub":
                cb_info = sub_chain.get(entity.A_v["label"])

            elif etype == "serv":
                cb_info = srv_chain.get(entity.A_v["label"])
                # Action component services: rclcpp_service_callback_added doesn't fire,
                # create function from action role instead
                if not cb_info and entity.A_v.get("action_role"):
                    action_role = entity.A_v["action_role"]
                    action_label = entity.A_v["label"].rsplit("/_action/", 1)[0].rsplit("/", 1)[-1]
                    role_short = {"send_goal": "goal", "cancel_goal": "cancel", "get_result": "result"}[action_role]
                    cb_info = {"callback": None, "symbol": f"{action_label}::{role_short}"}

            elif etype == "tmr":
                timer_handle = entity.A_v.get("timer_handle")
                if timer_handle:
                    # Try rclcpp path first
                    tmr_cb = coll.find_one({"event": "ros2:rclcpp_timer_callback_added",
                                            "payload.timer_handle": timer_handle})
                    if tmr_cb:
                        callback_ptr = tmr_cb["payload"]["callback"]
                        cb_reg = coll.find_one({"event": "ros2:rclcpp_callback_register",
                                                "payload.callback": callback_ptr})
                        if cb_reg:
                            cb_info = {"callback": callback_ptr, "symbol": cb_reg["payload"]["symbol"]}

                    # Fallback: rclpy path
                    if not cb_info:
                        py_cb = coll.find_one({"event": "ros2:rclpy_timer_callback_added",
                                               "payload.timer_handle": timer_handle})
                        if py_cb:
                            callback_ptr = py_cb["payload"]["callback"]
                            cb_reg = coll.find_one({"event": "ros2:rclpy_callback_register",
                                                    "payload.callback": callback_ptr})
                            if cb_reg:
                                cb_info = {"callback": callback_ptr, "symbol": cb_reg["payload"]["symbol"]}

            elif etype == "act":
                # Abstract entity — functions live on component service entities.
                continue

            if cb_info:
                entity.A_v["cb_addr"] = cb_info["callback"]
                f_A = ret_A_dict("F", label=cb_info["symbol"], ptype="cpu")
                f_A["cb_addr"] = cb_info["callback"]
                if is_gpu_node:
                    f_A["gpu_node"] = True
                f = FishVertex("F", next(vertex_counter), f_A, [], 3)
                entity.Z_v.append(f.id_v)
                functions[f.id_v] = f

    return functions


# ---------------------------------------------------------------------------
# Runtime Aspect Attribution
# ---------------------------------------------------------------------------

def attribute_aspects(mongo, executors, nodes, entities):
    """
    Transfer pub/cli aspects from node level to entity level using
    callback window scanning.

    For each node's executor PID:
      1. Load all callback_start/end + rcl_publish + client_request_sent events
      2. For each rcl_publish inside a callback window → attribute pub aspect to entity
      3. For each client_request_sent inside a callback window → attribute cli aspect to entity
      4. Remove attributed aspects from node, warn about unattributed remainder
    """
    coll = mongo["ros2_trace"]

    # Build callback_addr → entity mapping
    cb_to_entity = {}  # callback_addr → (entity_id, entity)
    for e_id, e in entities.items():
        cb = e.A_v.get("cb_addr")
        if cb and cb != "NA":
            cb_to_entity[cb] = (e_id, e)

    # Build node_id → (node, vpid) mapping
    node_to_pid = {}
    for ex_id, ex in executors.items():
        pid = ex.A_v['pid']
        for n_id in ex.Z_v:
            node_to_pid[n_id] = pid

    total_attributed_pub = 0
    total_attributed_cli = 0
    total_unattributed = 0

    for node_id, node in nodes.items():
        pub_aspects = node.A_v.get("pub_aspects", [])
        cli_aspects = node.A_v.get("cli_aspects", [])
        if not pub_aspects and not cli_aspects:
            continue

        pid = node_to_pid.get(node_id)
        if pid is None:
            continue

        # Build publisher_handle → topic map for this pid
        pub_handle_to_topic = {}
        for doc in coll.find({"event": "ros2:rcl_publisher_init", "vpid": pid}):
            pub_handle_to_topic[doc["payload"]["publisher_handle"]] = doc["payload"]["topic_name"]

        # Build client_handle → service_name map for this pid
        cli_handle_to_service = {}
        for doc in coll.find({"event": "ros2:rcl_client_init", "vpid": pid}):
            cli_handle_to_service[doc["payload"]["client_handle"]] = doc["payload"]["service_name"]

        # Load callback_start events for this pid (sorted by time)
        cb_starts = []
        for doc in coll.find({"event": "ros2:callback_start", "vpid": pid}).sort("ts", 1):
            full_ns = int(doc["ts"].timestamp() * 1e9) + doc["ts_nanos"]
            cb_starts.append({
                "ns": full_ns, "vtid": doc["vtid"],
                "cb": doc["payload"]["callback"]
            })

        # Load callback_end events
        cb_ends = []
        for doc in coll.find({"event": "ros2:callback_end", "vpid": pid}).sort("ts", 1):
            full_ns = int(doc["ts"].timestamp() * 1e9) + doc["ts_nanos"]
            cb_ends.append({
                "ns": full_ns, "vtid": doc["vtid"],
                "cb": doc["payload"]["callback"]
            })

        # Load rcl_publish events
        publishes = []
        for doc in coll.find({"event": "ros2:rcl_publish", "vpid": pid}).sort("ts", 1):
            full_ns = int(doc["ts"].timestamp() * 1e9) + doc["ts_nanos"]
            publishes.append({
                "ns": full_ns, "vtid": doc["vtid"],
                "ph": doc["payload"]["publisher_handle"]
            })

        # Load client_request_sent events
        cli_requests = []
        for doc in coll.find({"event": "ros2:rclcpp_client_request_sent", "vpid": pid}).sort("ts", 1):
            full_ns = int(doc["ts"].timestamp() * 1e9) + doc["ts_nanos"]
            cli_requests.append({
                "ns": full_ns, "vtid": doc["vtid"],
                "ch": doc["payload"]["client_handle"]
            })

        # Track active callbacks per thread
        # For each publish/client_request, find enclosing callback_start/end
        active_cbs = {}  # vtid → (cb_addr, start_ns)
        entity_pub_topics = {}  # cb_addr → set of topics
        entity_cli_services = {}  # cb_addr → set of services

        # Merge all events into timeline
        events = []
        for e in cb_starts:
            events.append(("cb_start", e["ns"], e["vtid"], e["cb"], None))
        for e in cb_ends:
            events.append(("cb_end", e["ns"], e["vtid"], e["cb"], None))
        for e in publishes:
            events.append(("publish", e["ns"], e["vtid"], None, e["ph"]))
        for e in cli_requests:
            events.append(("cli_req", e["ns"], e["vtid"], None, e["ch"]))
        events.sort(key=lambda x: x[1])

        for evt_type, ns, vtid, cb, handle in events:
            if evt_type == "cb_start":
                active_cbs[vtid] = cb
            elif evt_type == "cb_end":
                if vtid in active_cbs:
                    del active_cbs[vtid]
            elif evt_type == "publish":
                # Try same thread first, then any active callback in same process
                cb_addr = active_cbs.get(vtid)
                if cb_addr is None and active_cbs:
                    cb_addr = next(iter(active_cbs.values()))
                if cb_addr:
                    topic = pub_handle_to_topic.get(handle)
                    if topic:
                        entity_pub_topics.setdefault(cb_addr, set()).add(topic)
            elif evt_type == "cli_req":
                cb_addr = active_cbs.get(vtid)
                if cb_addr is None and active_cbs:
                    cb_addr = next(iter(active_cbs.values()))
                if cb_addr:
                    service = cli_handle_to_service.get(handle)
                    if service:
                        entity_cli_services.setdefault(cb_addr, set()).add(service)

        # Transfer attributed pub aspects to entities (deduplicated)
        attributed_pub_topics = set()
        for cb_addr, topics in entity_pub_topics.items():
            if cb_addr in cb_to_entity:
                e_id, entity = cb_to_entity[cb_addr]
                existing_pub_topics = {a["topic"] for a in entity.A_v["aspects"]
                                       if a.get("aspect") == "pub"}
                for topic in topics:
                    if topic in existing_pub_topics:
                        continue
                    msg_type = ""
                    for pa in pub_aspects:
                        if pa["topic"] == topic:
                            msg_type = pa.get("msg_type", "")
                            break
                    entity.A_v["aspects"].append({
                        "aspect": "pub", "topic": topic, "msg_type": msg_type
                    })
                    existing_pub_topics.add(topic)
                    attributed_pub_topics.add(topic)
                    total_attributed_pub += 1

        # Transfer attributed cli aspects to entities (deduplicated)
        attributed_cli_services = set()
        for cb_addr, services in entity_cli_services.items():
            if cb_addr in cb_to_entity:
                e_id, entity = cb_to_entity[cb_addr]
                existing_cli_services = {a["service"] for a in entity.A_v["aspects"]
                                          if a.get("aspect") == "cli"}
                for service in services:
                    if service in existing_cli_services:
                        continue
                    entity.A_v["aspects"].append({
                        "aspect": "cli", "service": service
                    })
                    existing_cli_services.add(service)
                    attributed_cli_services.add(service)
                    total_attributed_cli += 1

        # Remove attributed aspects from node, keep unattributed
        remaining_pub = [a for a in pub_aspects
                         if a["topic"] not in attributed_pub_topics]
        remaining_cli = [a for a in cli_aspects
                         if a["service"] not in attributed_cli_services]
        node.A_v["pub_aspects"] = remaining_pub
        node.A_v["cli_aspects"] = remaining_cli

        if remaining_pub or remaining_cli:
            # Filter out /rosout — always unattributed (published from many places)
            real_remaining = [a for a in remaining_pub if a["topic"] != "/rosout"]
            real_remaining += remaining_cli
            if real_remaining:
                total_unattributed += len(real_remaining)
                print(f"  [attribute_aspects] WARNING: {node.A_v['label']} has "
                      f"{len(real_remaining)} unattributed aspects: "
                      f"{[a.get('topic', a.get('service')) for a in real_remaining]}")

    print(f"[attribute_aspects] Attributed: {total_attributed_pub} pub, "
          f"{total_attributed_cli} cli. Unattributed: {total_unattributed}")


# ---------------------------------------------------------------------------
# Graph Construction
# ---------------------------------------------------------------------------

def create_graph_add_vertical_relations(executors, nodes, entities, functions):
    """Build nx.DiGraph with all vertices and vertical (hierarchy) edges from Z_v sets.

    Vertical edges represent containment:
      EX → N  (executor contains node)
      N  → E  (node contains entity)
      E  → F  (entity contains function)

    Each nx node stores the FishVertex as attribute 'v'.
    Each vertical edge has attribute rel='contains'.
    """
    G = nx.DiGraph()

    # Add all vertices
    for ex in executors.values():
        G.add_node(ex.id_v, v=ex)
    for n in nodes.values():
        G.add_node(n.id_v, v=n)
    for e in entities.values():
        G.add_node(e.id_v, v=e)
    for f in functions.values():
        G.add_node(f.id_v, v=f)

    # Add vertical edges from Z_v membership sets
    for ex in executors.values():
        for n_id in ex.Z_v:
            G.add_edge(ex.id_v, n_id, rel="contains", level="L0_L1")

    for n in nodes.values():
        for e_id in n.Z_v:
            if e_id in entities:
                G.add_edge(n.id_v, e_id, rel="contains", level="L1_L2")

    for e in entities.values():
        for f_id in e.Z_v:
            if f_id in functions:
                G.add_edge(e.id_v, f_id, rel="contains", level="L2_L3")

    v_count = G.number_of_nodes()
    e_count = G.number_of_edges()
    print(f"[FISH graph] Vertical: {v_count} vertices, {e_count} containment edges")
    return G


def get_node_infos(mongo):
    """Load node_info from MongoDB into a dict keyed by node full_name.

    Returns:
      {"/kiss_icp_node": {"Subscribers": {topic: msg_type, ...},
                          "Publishers": {topic: msg_type, ...},
                          "Service_Servers": {name: type, ...},
                          "Service_Clients": {name: type, ...}},
       ...}
    """
    node_infos = {}
    for doc in mongo["node_info"].find():
        name = doc["node"]
        node_infos[name] = {
            "Subscribers": doc.get("Subscribers", {}),
            "Publishers": doc.get("Publishers", {}),
            "Service_Servers": doc.get("Service_Servers", {}),
            "Service_Clients": doc.get("Service_Clients", {}),
        }
    print(f"[FISH graph] Loaded node_info for {len(node_infos)} nodes")
    return node_infos


def _propagate_l3(G, src_entity_id, dst_entity_id, edge_attrs, entities, functions):
    """Propagate an entity-level edge down to function level.

    If both entities have function children, create edges between them
    carrying the same edge nature (msg/dep).
    """
    src_e = entities.get(src_entity_id)
    dst_e = entities.get(dst_entity_id)
    if not src_e or not dst_e:
        return 0

    src_funcs = [fid for fid in src_e.Z_v if fid in functions]
    dst_funcs = [fid for fid in dst_e.Z_v if fid in functions]

    count = 0
    for sf in src_funcs:
        for df in dst_funcs:
            G.add_edge(sf, df, **edge_attrs, level="L3")
            count += 1
    return count


def _aggregate_l1(G, nodes, entities):
    """Aggregate entity-level horizontal edges up to node level.

    For each pair of nodes that have entity-level edges between them,
    create a single node-level edge carrying the set of topics/services.
    """
    # Build entity_id → node_id reverse map
    entity_to_node = {}
    for n in nodes.values():
        for e_id in n.Z_v:
            if e_id in entities:
                entity_to_node[e_id] = n.id_v

    # Collect entity edges grouped by (src_node, dst_node)
    node_pairs = {}  # (src_node_id, dst_node_id) → list of edge info
    for u, v, data in G.edges(data=True):
        if data.get("level") != "L2":
            continue
        src_node = entity_to_node.get(u)
        dst_node = entity_to_node.get(v)
        if src_node is None or dst_node is None:
            continue
        key = (src_node, dst_node)
        node_pairs.setdefault(key, []).append(data)

    count = 0
    for (src_n, dst_n), edge_list in node_pairs.items():
        topics = [e.get("topic", e.get("service", "?")) for e in edge_list]
        nature_set = {e.get("nature", "?") for e in edge_list}
        G.add_edge(src_n, dst_n, rel="comm", level="L1",
                   comm_count=len(edge_list),
                   topics=topics,
                   natures=nature_set)
        count += 1
    return count


def _aggregate_l0(G, executors, nodes):
    """Aggregate node-level horizontal edges up to executor level.

    For each pair of executors that have node-level edges between them,
    create a single executor-level edge with total comm count.
    """
    # Build node_id → executor_id reverse map
    node_to_exec = {}
    for ex in executors.values():
        for n_id in ex.Z_v:
            node_to_exec[n_id] = ex.id_v

    # Collect node edges grouped by (src_exec, dst_exec)
    exec_pairs = {}  # (src_ex, dst_ex) → list of edge info
    for u, v, data in G.edges(data=True):
        if data.get("level") != "L1":
            continue
        src_ex = node_to_exec.get(u)
        dst_ex = node_to_exec.get(v)
        if src_ex is None or dst_ex is None:
            continue
        key = (src_ex, dst_ex)
        exec_pairs.setdefault(key, []).append(data)

    count = 0
    for (src_ex, dst_ex), edge_list in exec_pairs.items():
        total_comm = sum(e.get("comm_count", 1) for e in edge_list)
        all_topics = []
        all_natures = set()
        for e in edge_list:
            all_topics.extend(e.get("topics", []))
            all_natures.update(e.get("natures", set()))

        tau = "IntraP" if src_ex == dst_ex else "InterP"
        G.add_edge(src_ex, dst_ex, rel="comm", level="L0",
                   tau=tau,
                   comm_count=total_comm,
                   topics=all_topics,
                   natures=all_natures)
        count += 1
    return count


def add_horizontal_relations(G, node_infos, executors, nodes, entities, functions):
    """Add horizontal edges using entity aspects, then aggregate upward.

    Phase 2 edge construction — all vertices and vertical edges must be complete.

    L2 (entity level):
      - pub aspect on entity A → sub aspect on entity B (nature="msg")
      - cli aspect on entity A → req_sub aspect on entity B (nature="comm", request)
      - res_pub aspect on entity B → entity A (nature="dep", response)
      Fallback: unattributed pub/cli aspects use node-level matching

    L3 (function level): propagate L2 edges down to functions
    L1 (node level): aggregate L2 edges up to nodes
    L0 (executor level): aggregate L1 edges up to executors
    """
    # --- Topic metadata (msg type, hz) for edge attributes ---
    topic_meta = {}  # topic → {type, hz, ...}
    for doc in mongo["topic_info"].find():
        t = doc.get("topic")
        if t:
            topic_meta.setdefault(t, {})["msg_type"] = doc.get("type", "")
            topic_meta[t]["pub_count"] = doc.get("publisher_count", 0)
            topic_meta[t]["sub_count"] = doc.get("subscription_count", 0)
    for doc in mongo["topic_hz"].find():
        t = doc.get("topic")
        if t:
            topic_meta.setdefault(t, {})["avg_rate_hz"] = doc.get("average_rate", 0)
            topic_meta[t]["std_dev"] = doc.get("std_dev", 0)

    # --- Build indexes ---

    # sub aspect index: topic → [(entity_id, node_id), ...]
    sub_index = {}
    # srv (req_sub) aspect index: service_name → [(entity_id, node_id), ...]
    srv_index = {}
    # pub aspect index (entity-level): topic → [(entity_id, node_id), ...]
    pub_entity_index = {}

    # entity → parent node mapping
    entity_to_node = {}

    for n in nodes.values():
        for e_id in n.Z_v:
            e = entities.get(e_id)
            if not e or e.t_v != "E":
                continue
            entity_to_node[e_id] = n.id_v
            for aspect in e.A_v.get("aspects", []):
                if aspect["aspect"] == "sub":
                    topic = aspect["topic"]
                    sub_index.setdefault(topic, []).append((e_id, n.id_v))
                elif aspect["aspect"] == "req_sub":
                    srv = aspect["service"]
                    srv_index.setdefault(srv, []).append((e_id, n.id_v))
                elif aspect["aspect"] == "pub":
                    topic = aspect["topic"]
                    pub_entity_index.setdefault(topic, []).append((e_id, n.id_v))

    # Node-level pub index (for skipped edge counting only)
    pub_node_index = {}  # topic → [node_id, ...]
    for n in nodes.values():
        for pa in n.A_v.get("pub_aspects", []):
            pub_node_index.setdefault(pa["topic"], []).append(n.id_v)

    # cli aspect index: service → [(entity_id, node_id), ...] from attributed entities
    cli_entity_index = {}
    for n in nodes.values():
        for e_id in n.Z_v:
            e = entities.get(e_id)
            if not e or e.t_v != "E":
                continue
            for aspect in e.A_v.get("aspects", []):
                if aspect["aspect"] == "cli":
                    srv = aspect["service"]
                    cli_entity_index.setdefault(srv, []).append((e_id, n.id_v))

    # Node-level cli index (for skipped edge counting only)
    cli_node_index = {}  # service → [node_id, ...]
    for n in nodes.values():
        for ca in n.A_v.get("cli_aspects", []):
            cli_node_index.setdefault(ca["service"], []).append(n.id_v)

    def _topic_edge_attrs(topic, **extra):
        """Build edge attributes for a topic edge, including metadata."""
        attrs = {"rel": "comm", "level": "L2", "nature": "msg", "topic": topic}
        meta = topic_meta.get(topic, {})
        if meta.get("msg_type"):
            attrs["msg_type"] = meta["msg_type"]
        if meta.get("avg_rate_hz"):
            attrs["avg_rate_hz"] = meta["avg_rate_hz"]
        if meta.get("std_dev"):
            attrs["std_dev"] = meta["std_dev"]
        attrs.update(extra)
        return attrs

    # --- L2: Entity-level edges ---
    l2_count = 0

    # 1. Topic edges: pub aspect entity → sub aspect entity (same layer only)
    l2_skipped_pub = 0
    for topic, sub_list in sub_index.items():
        pub_entities = pub_entity_index.get(topic, [])
        if pub_entities:
            for pub_e_id, pub_n_id in pub_entities:
                for sub_e_id, sub_n_id in sub_list:
                    if pub_n_id == sub_n_id:
                        continue
                    G.add_edge(pub_e_id, sub_e_id, **_topic_edge_attrs(topic))
                    l2_count += 1
        else:
            # Unattributed pub — no edge (cross-layer edges not allowed)
            has_node_pub = bool(pub_node_index.get(topic, []))
            if has_node_pub and sub_list:
                l2_skipped_pub += 1

    # 2. Service edges: cli aspect entity → srv entity (same layer only)
    l2_skipped_cli = 0
    for srv_name, srv_list in srv_index.items():
        cli_entities = cli_entity_index.get(srv_name, [])
        if cli_entities:
            for cli_e_id, cli_n_id in cli_entities:
                for srv_e_id, srv_n_id in srv_list:
                    if cli_n_id == srv_n_id:
                        continue
                    G.add_edge(cli_e_id, srv_e_id, rel="comm", level="L2",
                               nature="comm", service=srv_name, direction="request")
                    G.add_edge(srv_e_id, cli_e_id, rel="comm", level="L2",
                               nature="dep", service=srv_name, direction="response")
                    l2_count += 2
        else:
            # Unattributed cli — no edge (cross-layer edges not allowed)
            has_node_cli = bool(cli_node_index.get(srv_name, []))
            if has_node_cli and srv_list:
                l2_skipped_cli += 1

    if l2_skipped_pub or l2_skipped_cli:
        print(f"[FISH graph] L2 skipped (unattributed): {l2_skipped_pub} pub, {l2_skipped_cli} cli")

    # --- External boundary entities ---
    # Detect topics/services with one side inside trace, other side missing.
    # Create EXT placeholder entities + functions for the missing side.
    ext_count = 0

    # All topics that have a subscriber entity but no publisher entity
    all_pub_topics = set(pub_entity_index.keys()) | set(pub_node_index.keys())
    for topic, sub_list in sub_index.items():
        if topic in all_pub_topics:
            continue  # has a publisher (entity or node level)
        # External publisher → create ext entity with pub aspect → edge to sub entity
        ext_e_A = ret_A_dict("E", label=f"ext:{topic}", etype="sub")
        ext_e_A["external"] = True
        ext_e_A["aspects"] = [{"aspect": "pub", "topic": topic}]
        ext_e = FishVertex("E", next(vertex_counter), ext_e_A, [], 2)
        entities[ext_e.id_v] = ext_e
        G.add_node(ext_e.id_v, v=ext_e)
        # Ext function
        ext_f_A = ret_A_dict("F", label=f"ext:{topic}", ptype="ext")
        ext_f = FishVertex("F", next(vertex_counter), ext_f_A, [], 3)
        functions[ext_f.id_v] = ext_f
        ext_e.Z_v.append(ext_f.id_v)
        G.add_node(ext_f.id_v, v=ext_f)
        G.add_edge(ext_e.id_v, ext_f.id_v, rel="contains", level="V")
        # Edges to all subscribers
        for sub_e_id, sub_n_id in sub_list:
            G.add_edge(ext_e.id_v, sub_e_id, **_topic_edge_attrs(topic, external=True))
            l2_count += 1
            ext_count += 1

    # All topics that have a publisher entity but no subscriber entity
    all_sub_topics = set(sub_index.keys())
    for topic, pub_list in pub_entity_index.items():
        if topic in all_sub_topics:
            continue
        # External subscriber → create ext entity with sub aspect
        ext_e_A = ret_A_dict("E", label=f"ext:{topic}", etype="sub")
        ext_e_A["external"] = True
        ext_e_A["aspects"] = [{"aspect": "sub", "topic": topic}]
        ext_e = FishVertex("E", next(vertex_counter), ext_e_A, [], 2)
        entities[ext_e.id_v] = ext_e
        G.add_node(ext_e.id_v, v=ext_e)
        ext_f_A = ret_A_dict("F", label=f"ext:{topic}", ptype="ext")
        ext_f = FishVertex("F", next(vertex_counter), ext_f_A, [], 3)
        functions[ext_f.id_v] = ext_f
        ext_e.Z_v.append(ext_f.id_v)
        G.add_node(ext_f.id_v, v=ext_f)
        G.add_edge(ext_e.id_v, ext_f.id_v, rel="contains", level="V")
        for pub_e_id, pub_n_id in pub_list:
            G.add_edge(pub_e_id, ext_e.id_v, **_topic_edge_attrs(topic, external=True))
            l2_count += 1
            ext_count += 1

    # Services that have a server entity but no client entity
    for srv_name, srv_list in srv_index.items():
        has_cli = bool(cli_entity_index.get(srv_name)) or bool(cli_node_index.get(srv_name))
        if has_cli:
            continue
        # External client → create ext entity with cli aspect
        ext_e_A = ret_A_dict("E", label=f"ext:{srv_name}", etype="sub")
        ext_e_A["external"] = True
        ext_e_A["aspects"] = [{"aspect": "cli", "service": srv_name}]
        ext_e = FishVertex("E", next(vertex_counter), ext_e_A, [], 2)
        entities[ext_e.id_v] = ext_e
        G.add_node(ext_e.id_v, v=ext_e)
        ext_f_A = ret_A_dict("F", label=f"ext:{srv_name}", ptype="ext")
        ext_f = FishVertex("F", next(vertex_counter), ext_f_A, [], 3)
        functions[ext_f.id_v] = ext_f
        ext_e.Z_v.append(ext_f.id_v)
        G.add_node(ext_f.id_v, v=ext_f)
        G.add_edge(ext_e.id_v, ext_f.id_v, rel="contains", level="V")
        for srv_e_id, srv_n_id in srv_list:
            G.add_edge(ext_e.id_v, srv_e_id, rel="comm", level="L2",
                       nature="comm", service=srv_name, direction="request", external=True)
            G.add_edge(srv_e_id, ext_e.id_v, rel="comm", level="L2",
                       nature="dep", service=srv_name, direction="response", external=True)
            l2_count += 2
            ext_count += 2

    if ext_count:
        print(f"[FISH graph] L2 external boundary edges: {ext_count}")

    print(f"[FISH graph] L2 horizontal edges: {l2_count}")

    # --- L3: Propagate entity edges to function level ---
    # When both sides of an L2 edge are entities, propagate to their functions.
    l3_count = 0
    for u, v, data in list(G.edges(data=True)):
        if data.get("level") != "L2":
            continue
        # Both sides must be entities (not nodes)
        if u not in entities or v not in entities:
            continue
        src_funcs = [f_id for f_id in entities[u].Z_v if f_id in functions]
        dst_funcs = [f_id for f_id in entities[v].Z_v if f_id in functions]
        for sf in src_funcs:
            for df in dst_funcs:
                G.add_edge(sf, df, rel="comm", level="L3", **{
                    k: v for k, v in data.items() if k not in ("rel", "level")
                })
                l3_count += 1
    print(f"[FISH graph] L3 propagated edges: {l3_count}")

    # --- L1: Aggregate entity edges to node level ---
    # Resolve both sides of L2 edges to their parent nodes.
    node_pairs = {}
    for u, v, data in G.edges(data=True):
        if data.get("level") != "L2":
            continue
        src_node = u if u in nodes else entity_to_node.get(u)
        dst_node = entity_to_node.get(v, v if v in nodes else None)
        if src_node is None or dst_node is None:
            continue
        key = (src_node, dst_node)
        node_pairs.setdefault(key, []).append(data)

    l1_count = 0
    for (src_n, dst_n), edge_list in node_pairs.items():
        topics = [e.get("topic", e.get("service", "?")) for e in edge_list]
        nature_set = {e.get("nature", "?") for e in edge_list}
        G.add_edge(src_n, dst_n, rel="comm", level="L1",
                   comm_count=len(edge_list),
                   topics=topics,
                   natures=nature_set)
        l1_count += 1
    print(f"[FISH graph] L1 aggregated edges: {l1_count}")

    # --- L0: Aggregate node edges to executor level ---
    l0_count = _aggregate_l0(G, executors, nodes)
    print(f"[FISH graph] L0 aggregated edges: {l0_count}")

    total_h = l2_count + l3_count + l1_count + l0_count
    print(f"[FISH graph] Total horizontal edges: {total_h}")
    return G


if __name__ == "__main__":
    import argparse
    ap = argparse.ArgumentParser(description="FISH model extraction")
    ap.add_argument("--session", default=TRACE_SESSION, help="Session name")
    ap.add_argument("--no-external-actions", action="store_true",
                    help="Exclude short-lived action clients (ros2cli send_goal)")
    args = ap.parse_args()

    if args.no_external_actions:
        INCLUDE_EXTERNAL_ACTIONS = False

    mongo = connect_mongo(args.session)
    influx = connect_influx(args.session)
    session_dir = os.path.expanduser(f"~/fish_traces/{args.session}")

    # Phase 1: Vertex discovery (all vertices + vertical edges)
    executors, nodes = identify_executors(mongo)
    entities = identify_entities(mongo, nodes)
    functions = identify_callbacks(mongo, nodes, entities, executors)
    attribute_aspects(mongo, executors, nodes, entities)
    pretty_print_four_layers(executors, nodes, entities, functions)
    create_detection_summary(executors, nodes, entities, functions, mongo)

    # Phase 2: Edge construction (horizontal edges)
    G = create_graph_add_vertical_relations(executors, nodes, entities, functions)
    node_infos = get_node_infos(mongo)
    G = add_horizontal_relations(G, node_infos, executors, nodes, entities, functions)

    create_graph_summary(G)
    metrics = print_graph_metrics(G)

    # Visualization
    export_fish_overview(G, "fish_overview", fmt="png")
    export_fish_overview(G, "fish_overview", fmt="pdf")
    for ex_id, ex in executors.items():
        label = ex.A_v.get("label", str(ex_id))
        export_fish_detail(G, ex_id, f"fish_detail_{label}", fmt="png")
        export_fish_detail(G, ex_id, f"fish_detail_{label}", fmt="pdf")
    export_fish_radial(G, "fish_radial", fmt="png")
    export_fish_matrix(G, executors, nodes, entities, "fish_matrix", fmt="png")
    export_fish_staircase(G, "fish_staircase", fmt="png")
    export_fish_l3_chains(G, "fish_l3_chains", fmt="png")
    export_fish_l3_chains(G, "fish_l3_chains", fmt="pdf")
