#!/usr/bin/env python3
# Generated by Claude Opus 5 (Anthropic)
"""paper_fig_components — the Layer-B (component) view, drawn for the paper.

Same content as the /components view of fish_viz_server (namespace components,
their callback/GPU counts, and the edges between them classified as trigger /
sampled / infra), but:

  * external sources and sinks merged into one ext:in and one ext:out
    (the view's "merge ext" checkbox),
  * no text on the edges — the edge *kind* is the colour/dash, the width is the
    message volume, and a legend states the encoding,
  * large fonts, so the boxes stay readable at figure size.

Usage:
  python3 -m postprocess.paper_fig_components <session> [--rankdir TB|LR]
      [--infra] [--crosscut] [--depth 1] [-o DIR] [--base NAME]
"""
from __future__ import annotations
import argparse, math, os, subprocess, sys
HERE = os.path.dirname(os.path.abspath(__file__)); sys.path.insert(0, HERE)
import fish_viz_server as viz

KIND = {                       # kind: (colour, extra dot attrs, legend text)
    'data':     ('#222222', 'penwidth=%s',                       'trigger — a message that starts work in the receiver'),
    'sampled':  ('#e07b00', 'penwidth=%s style=dashed arrowhead=onormal',
                                                                 'sampled — the receiver reads the latest value (sample-and-hold)'),
    'state':    ('#9467bd', 'penwidth=%s style=dashed',           'state — deposited by one callback, read by another'),
    'infra':    ('#bbbbbb', 'penwidth=%s style=dotted',           'infrastructure — /diagnostics, /rosout, parameters, TF'),
}
ARCH_ROWS = [['ext:in'], ['/sensing'], ['/localization', '/map'], ['/perception'],
             ['/planning'], ['/control'], ['ext:out']]


def width_scale(flows, lo=1.0, hi=10.0):
    """Edge width from the number of messages, log-normalised over the edges
    actually drawn, so the busiest link is visibly the thickest one."""
    pos = [f for f in flows if f > 0]
    fmin = math.log10(max(min(pos), 1)) if pos else 0.0
    fmax = math.log10(max(pos)) if pos else 1.0
    span = max(fmax - fmin, 1e-9)

    def w(flow):
        if flow <= 0:
            return lo * 0.7                      # link exists, no message seen
        return lo + (hi - lo) * (math.log10(flow) - fmin) / span
    return w


def build(cg, rankdir='TB', show_infra=False, show_crosscut=False, fontsize=22, uniform=True):
    comps = [c for c in cg['components'] if show_crosscut or c['name'] not in viz._CROSSCUT]
    ids = {c['name']: f'c{i}' for i, c in enumerate(comps)}
    links = [l for l in cg['links'] if show_infra or l['kind'] != 'infra']
    if not show_crosscut:
        links = [l for l in links if l['src'] not in viz._CROSSCUT and l['dst'] not in viz._CROSSCUT]
    # merge ext: one ext:in and one ext:out for the whole figure
    for k in ('ext:in', 'ext:out'):
        if any(l['src'] == k or l['dst'] == k for l in links):
            ids[k] = k.replace(':', '_')
    L = ['digraph components {', f'  rankdir={rankdir};', '  newrank=true;',
         f'  graph [fontname="Helvetica" fontsize={fontsize} nodesep=0.55 ranksep=0.85 '
         f'bgcolor="white" splines=spline];',
         f'  node  [shape=box style="filled,rounded" fontname="Helvetica" fontsize={fontsize} '
         f'fillcolor="#3aa6b0" color="#2a7f87" fontcolor="white" penwidth=2 margin="0.28,0.16"];',
         '  edge  [arrowsize=0.9];']
    for c in comps:
        head = c.get('short') or c['name']
        line2 = f"{c['n_nodes']} nodes · {c['n_f']} callbacks"
        extra = []
        if c.get('n_gpu'): extra.append(f"GPU {c['n_gpu']}")
        if c.get('n_internal_edges'): extra.append(f"{c['n_internal_edges']} hops")
        if c.get('n_internal_state'): extra.append(f"{c['n_internal_state']} state reads")
        lbl = '\\n'.join(x for x in (head, line2, ' · '.join(extra)) if x)
        L.append(f'  {ids[c["name"]]} [label="{lbl}"];')
    for k in ('ext:in', 'ext:out'):
        if k in ids:
            L.append(f'  {ids[k]} [label="{k}", shape=ellipse, fillcolor="#e6e6e6", '
                     f'color="#999999", fontcolor="#333333", fontsize={fontsize-2}];')
    # architecture rows, so the figure reads sensing → … → control
    rows = [r for r in ARCH_ROWS if any(n in ids for n in r)]
    for r in rows:
        members = [ids[n] for n in r if n in ids]
        if len(members) > 1:
            L.append('  {rank=same; ' + '; '.join(members) + ';}')
    for r1, r2 in zip(rows, rows[1:]):
        a = next(ids[n] for n in r1 if n in ids); b = next(ids[n] for n in r2 if n in ids)
        L.append(f'  {a} -> {b} [style=invis weight=1000 minlen=1];')
    if uniform:
        # one edge per ordered pair: at this layer the model carries the *set*
        # of messages, so trigger and sampled links between the same two
        # components are one lifted edge (they were four lines before)
        agg = {}
        for l in links:
            k = (l['src'], l['dst'])
            e = agg.setdefault(k, {'src': l['src'], 'dst': l['dst'], 'flow_n': 0,
                                   'n_topics': 0, 'kind': 'data'})
            e['flow_n'] += int(l.get('flow_n') or 0)
            e['n_topics'] += int(l.get('n_topics') or 0)
        links = list(agg.values())
    wof = width_scale([int(l.get('flow_n') or 0) for l in links
                       if ids.get(l['src']) and ids.get(l['dst'])])
    for l in links:
        a, b = ids.get(l['src']), ids.get(l['dst'])
        if not a or not b:
            continue
        # the rows are pinned by the invisible architecture chain; real edges
        # must not fight it (sensing⇄localization is a genuine cycle), so they
        # are routed without ranking constraints
        if uniform:
            # the model lifts a set of message edges into one component edge —
            # the kinds live one layer below, so they are not drawn here
            flow = int(l.get('flow_n') or 0)
            col = '#333333' if flow else '#aaaaaa'
            L.append(f'  {a} -> {b} [color="{col}", penwidth={wof(flow):.2f}, constraint=false];')
        else:
            col, attrs, _ = KIND.get(l['kind'], KIND['data'])
            w = f"{wof(int(l.get('flow_n') or 0)):.2f}"
            L.append(f'  {a} -> {b} [color="{col}", {attrs % w}, constraint=false];')
    L.append('}')
    return '\n'.join(x for x in L if x)


def legend_uniform(fontsize=22):
    """One line: the arrow and what it means."""
    return '\n'.join([
        'digraph legend {', '  rankdir=LR; bgcolor="white";',
        f'  graph [fontname="Helvetica" fontsize={fontsize} nodesep=0.15 ranksep=0.25];',
        f'  node [shape=plaintext fontname="Helvetica" fontsize={fontsize} fontcolor="#222222"];',
        '  a [label=""; shape=point; width=0.02; color="white"];',
        '  b [label=""; shape=point; width=0.02; color="white"];',
        '  t [label="  augmented edge w.r.t. number of elements"];',
        '  a -> b [color="#333333", penwidth=4];',
        '  b -> t [style=invis];',
        '  {rank=same; a; b; t;}', '}'])


def legend_dot(kinds, fontsize=22):
    """The legend as its own little graph — pasted next to the figure."""
    L = ['digraph legend {', '  rankdir=TB; bgcolor="white";',
         f'  graph [fontname="Helvetica" fontsize={fontsize} nodesep=0.18 ranksep=0.30];',
         f'  node [shape=plaintext fontname="Helvetica" fontsize={fontsize} fontcolor="#222222"];',
         '  edge [arrowsize=0.9];']
    prev = None
    for i, k in enumerate(kinds):
        col, attrs, text = KIND[k]
        L += [f'  a{i} [label=""; shape=point; width=0.02; color="white"];',
              f'  b{i} [label=""; shape=point; width=0.02; color="white"];',
              f'  t{i} [label="  {text}"];',
              f'  a{i} -> b{i} [color="{col}", {attrs % "3"}];',
              f'  b{i} -> t{i} [style=invis];',
              f'  {{rank=same; a{i}; b{i}; t{i};}}']
        if prev is not None:
            L.append(f'  t{prev} -> a{i} [style=invis];')
        prev = i
    L += [f'  w [label="  edge width \u221d number of messages"];',
          f'  t{prev} -> w [style=invis];' if prev is not None else '',
          '  boxlabel [label="edges", fontname="Helvetica-Bold"];',
          '  boxlabel -> a0 [style=invis];', '}']
    return '\n'.join(x for x in L if x)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('session'); ap.add_argument('--scope', default='__main__')
    ap.add_argument('--depth', type=int, default=1); ap.add_argument('--axis', default='ros')
    ap.add_argument('--rankdir', default='TB'); ap.add_argument('--infra', action='store_true')
    ap.add_argument('--crosscut', action='store_true'); ap.add_argument('--fontsize', type=int, default=22)
    ap.add_argument('-o', '--outdir', default=os.path.join('paper', 'figures', 'components'))
    ap.add_argument('--base', default=None)
    ap.add_argument('--by-kind', action='store_true',
                    help='colour edges by kind (trigger/sampled) instead of one lifted edge')
    a = ap.parse_args()
    fnodes, edges, _w, _n = viz._fetch_wcc_payload(a.session, a.scope, {'data'}, 'exclude', '', '', 'show')
    cg = viz._component_graph(fnodes, edges, depth=a.depth, axis=a.axis)
    dot = build(cg, a.rankdir, a.infra, a.crosscut, a.fontsize, uniform=not a.by_kind)
    kinds = sorted({l['kind'] for l in cg['links'] if a.infra or l['kind'] != 'infra'},
                   key=lambda k: list(KIND).index(k) if k in KIND else 9)
    os.makedirs(a.outdir, exist_ok=True)
    base = os.path.join(a.outdir, a.base or f'components_{a.session}_{a.rankdir.lower()}')
    open(base + '.dot', 'w').write(dot)
    for fmt in ('svg', 'pdf', 'png'):
        subprocess.run(['dot', f'-T{fmt}'] + (['-Gdpi=150'] if fmt == 'png' else [])
                       + [base + '.dot', '-o', f'{base}.{fmt}'], check=False)
    lb = base + '_legend'
    open(lb + '.dot', 'w').write(legend_dot(kinds, a.fontsize) if a.by_kind
                                 else legend_uniform(a.fontsize))
    for fmt in ('svg', 'pdf', 'png'):
        subprocess.run(['dot', f'-T{fmt}'] + (['-Gdpi=150'] if fmt == 'png' else [])
                       + [lb + '.dot', '-o', f'{lb}.{fmt}'], check=False)
    print(f'[components] {base}.svg  ({len(cg["components"])} components, '
          f'{len([l for l in cg["links"] if a.infra or l["kind"] != "infra"])} edges drawn)')


if __name__ == '__main__':
    main()
