#!/usr/bin/env python3
# Generated by Claude Opus 5 (Anthropic)
"""paper_fig_model.py — the four panels of the FISH model figure, rendered
from a real session in PostgreSQL.

  (a) callback-layer fragment: msg / join / state / polled / dep edges,
      external boundary, GPU submitter marked
  (b) the same fragment lifted: node layer and process layer, each edge a set
  (c) typed DAG of one GPU-submitting callback (CPU / SM / CE nodes;
      launch / cpu_order / stream_fifo edges)
  (d) conditional graph of the same callback: common backbone over all
      observed signatures + branches with their probabilities

Usage:
  python3 -m postprocess.paper_fig_model <session_id> [-o paper/figures/model]
          [--anchor <cb_addr>] [--scope __main__]
"""
from __future__ import annotations
import argparse, collections, json, os, subprocess, sys
HERE = os.path.dirname(os.path.abspath(__file__)); sys.path.insert(0, HERE)
import psycopg2, psycopg2.extras

DSN = os.environ.get('FISH_PG_DSN', 'host=localhost port=5432 dbname=fish user=fish password=fish')

# edge type → (colour, style, label)
NAT = {
    'msg':    ('#1f77b4', 'solid',  'msg'),
    'dep':    ('#9467bd', 'solid',  'dep'),
    'join':   ('#d62728', 'bold',   'join'),
    'state':  ('#ff7f0e', 'dashed', 'state'),
    'polled': ('#2ca02c', 'dashed', 'polled'),
    'gxf':    ('#17becf', 'solid',  'gxf'),
}
FONT = 'Helvetica'


def dot(src, base, fmts=('pdf', 'svg', 'png'), unflatten=None):
    open(base + '.dot', 'w').write(src)
    if unflatten:
        try:
            r = subprocess.run(['unflatten'] + unflatten, input=src, capture_output=True, text=True)
            if r.returncode == 0 and r.stdout.strip():
                open(base + '.dot', 'w').write(r.stdout)
        except FileNotFoundError:
            pass
    for f in fmts:
        try:
            subprocess.check_call(['dot', f'-T{f}'] + (['-Gdpi=200'] if f == 'png' else []) +
                                  [base + '.dot', '-o', f'{base}.{f}'], stderr=subprocess.DEVNULL)
        except Exception as e:
            print(f'  dot -T{f} failed for {base}: {e}')
    try:
        out = subprocess.run(['pdfinfo', base + '.pdf'], capture_output=True, text=True).stdout
        size = [l for l in out.splitlines() if l.startswith('Page size')]
        print(f'  {os.path.basename(base)}: {size[0] if size else "?"}')
    except Exception:
        pass


def fetch_fragment(cur, sid, scope):
    """F vertices + their entity/node/process labels, and the L3 edges."""
    cur.execute("""
      WITH e_n AS (
        SELECT e.node_id e_id, e.label e_label, e.etype, e.attrs->>'external' e_ext,
               n.node_id n_id, n.label n_label, ex.node_id ex_id, ex.label ex_label
        FROM graph_nodes e
        LEFT JOIN graph_edges c1 ON c1.session_id=e.session_id AND c1.scope=e.scope
                                AND c1.target=e.node_id AND c1.rel='contains'
        LEFT JOIN graph_nodes n ON n.session_id=c1.session_id AND n.node_id=c1.source AND n.type='N'
        LEFT JOIN graph_edges c0 ON c0.session_id=n.session_id AND c0.scope=n.scope
                                AND c0.target=n.node_id AND c0.rel='contains'
        LEFT JOIN graph_nodes ex ON ex.session_id=c0.session_id AND ex.node_id=c0.source AND ex.type='EX'
        WHERE e.session_id=%s AND e.scope=%s AND e.type='E')
      SELECT f.node_id fid, f.attrs->>'gpu_node' gpu, f.attrs->>'phase' phase, f.cb_addr,
             en.* FROM graph_nodes f
      JOIN graph_edges c2 ON c2.session_id=f.session_id AND c2.scope=f.scope
                         AND c2.target=f.node_id AND c2.rel='contains'
      JOIN e_n en ON en.e_id=c2.source
      WHERE f.session_id=%s AND f.scope=%s AND f.type='F'
    """, (sid, scope, sid, scope))
    F = {r['fid']: dict(r) for r in cur.fetchall()}
    cur.execute("""SELECT source, target, attrs FROM graph_edges
                   WHERE session_id=%s AND scope=%s AND rel='comm' AND level='L3'""", (sid, scope))
    E = [(r['source'], r['target'], r['attrs'] or {}) for r in cur.fetchall()]
    return F, E


def nat_of(a):
    n = a.get('nature') or 'msg'
    if n == 'state' and a.get('polled'):
        return 'polled'
    if n == 'gxf_internal':
        return 'gxf'
    return n


def short_topic(t):
    if not t:
        return ''
    p = t.strip('/').split('/')
    return p[-1] if len(p) == 1 else '/'.join(p[-2:])


def panel_a(F, E, chain, out, gpu_anchors=frozenset(), clusters=True):
    """chain: list of (node_label_regex, topic_substring) selecting the F vertices."""
    import re
    pick = {}
    for fid, f in F.items():
        for i, (nre, tsub) in enumerate(chain):
            el = f['e_label'] or ''
            hit = (el == tsub[1:]) if tsub.startswith('=') else (tsub in el)
            if f['n_label'] and re.search(nre, f['n_label']) and hit:
                pick.setdefault(i, []).append(fid)
    sel = {}
    for i, fids in pick.items():
        sel[sorted(fids)[0]] = chain[i]
    ids = set(sel)
    L = ['digraph a {', 'rankdir=LR; bgcolor=white; splines=true; nodesep=0.06; ranksep=0.13;',
         f'node [shape=box, style="rounded,filled", fontname="{FONT}", fontsize=7, margin="0.035,0.02", height=0.22, fillcolor="#f4f4f4", color="#888888"];',
         f'edge [fontname="{FONT}", fontsize=7, arrowsize=0.5, penwidth=1.0];']
    # cluster F by ROS node
    byn = collections.defaultdict(list)
    for fid in ids:
        byn[(F[fid]['n_id'], F[fid]['n_label'] or 'external')].append(fid)
    SHORT = {'obstacle_pointcloud_based_validator_node': 'validator',
             'distortion_corrector_node': 'distortion', 'multi_object_tracker': 'tracker',
             'lidar_centerpoint': 'centerpoint', 'concatenate_data': 'concat',
             'ring_outlier_filter': 'ring'}
    dup = collections.Counter(nl for (_nid, nl) in byn)
    def disp(nid, nl0, fids):
        nl = SHORT.get(nl0, nl0)
        if dup[nl0] > 1:   # same node name in several namespaces (per-lidar pipelines)
            ns = sorted({(F[f]['e_label'] or '') for f in fids})
            tag = next((seg for t in ns for seg in t.split('/') if seg in ('top', 'left', 'right', 'rear')), '')
            if tag:
                nl = f'{nl}({tag})'
        return nl
    def box(fid):
        f = F[fid]
        leaf = (f['e_label'] or '').strip('/').split('/')[-1] or f['e_label'] or ''
        for a_, b_ in (('pointcloud_ex', 'pc_ex'), ('pointcloud_before_sync', 'before_sync'),
                       ('pointcloud', 'pc'), ('twist_with_covariance', 'twist'),
                       ('imu_data', 'imu'), ('objects', 'objects')):
            leaf = leaf.replace(a_, b_)
        return leaf if f['etype'] == 'sub' else f"{f['etype']}:{leaf}"
    for i, ((nid, nl0), fids) in enumerate(sorted(byn.items(), key=lambda kv: kv[0][1])):
        nl = disp(nid, nl0, fids)
        if clusters:
            L.append(f'subgraph cluster_n{i} {{ label="{nl}"; fontname="{FONT}-Bold"; fontsize=7; '
                     f'color="#cccccc"; style=rounded; margin=3;')
        for fid in fids:
            f = F[fid]
            lbl = box(fid) if clusters else f'{nl}\\n{box(fid)}'
            attrs = 'penwidth=1.6, color="#d62728"' if (f['cb_addr'] in gpu_anchors) else ''
            L.append(f'  f{fid} [label="{lbl}"{", " + attrs if attrs else ""}];')
        if clusters:
            L.append('}')
    seen = set()
    for u, v, a in E:
        if u not in ids or v not in ids:
            continue
        n = nat_of(a)
        key = (u, v, n)
        if key in seen:
            continue
        seen.add(key)
        col, style, _ = NAT.get(n, ('#999999', 'solid', n))
        L.append(f'f{u} -> f{v} [color="{col}", style={style}];')
    L.append('}')
    dot('\n'.join(L), out)
    return sel


def panel_b(F, E, sel, out, layers=(('L1', 'node layer'), ('L0', 'process layer'))):
    """The fragment of panel (a) lifted: node layer (L1) and process layer (L0),
    each edge the set of callback-layer edges it aggregates."""
    ids = set(sel)
    n_of = {fid: (F[fid]['n_id'], F[fid]['n_label']) for fid in ids}
    ex_of = {fid: (F[fid]['ex_id'], F[fid]['ex_label']) for fid in ids}
    SHORT = {'obstacle_pointcloud_based_validator_node': 'validator',
             'distortion_corrector_node': 'distortion', 'multi_object_tracker': 'tracker',
             'lidar_centerpoint': 'centerpoint', 'ring_outlier_filter': 'ring',
             'concatenate_data': 'concat'}
    def agg(level_of):
        out_e = collections.defaultdict(collections.Counter)
        for u, v, a in E:
            if u not in ids or v not in ids:
                continue
            su, sv = level_of[u][0], level_of[v][0]
            if su is None or sv is None or su == sv:
                continue
            out_e[(su, sv)][nat_of(a)] += 1
        return out_e
    L = ['digraph b {', 'compound=true; rankdir=LR; bgcolor=white; nodesep=0.06; ranksep=0.16;',
         f'node [shape=box, style="rounded,filled", fontname="{FONT}", fontsize=7, margin="0.04,0.02", '
         'height=0.20, fillcolor="#f4f4f4", color="#888888"];',
         f'edge [fontname="{FONT}", fontsize=6, arrowsize=0.5];']
    LV = {'L1': (n_of, '#eef4fb'), 'L0': (ex_of, '#f7f0fb')}
    for tag, title in layers:
        level_of, fill = LV[tag]
        L.append(f'subgraph cluster_{tag} {{ label="{title}"; '
                 f'fontname="{FONT}-Bold"; fontsize=7; style="rounded,filled"; fillcolor="{fill}"; color="#bbbbbb"; margin=4;')
        seen = {}
        for fid in ids:
            k, lab = level_of[fid]
            if k is None or k in seen:
                continue
            seen[k] = True
            lab = SHORT.get(lab, lab or '?')
            if tag == 'L0':
                import re as _re
                m = _re.search(r'PID:(\d+)', lab or '')
                lab = f'process {m.group(1)}' if m else (lab or '?').split(' (')[0]
            L.append(f'  {tag}_{k} [label="{lab}"];')
        for (su, sv), cnt in agg(level_of).items():
            lab = ', '.join(f'{k}×{c}' for k, c in sorted(cnt.items()))
            col = NAT.get(max(cnt, key=cnt.get), ('#555555',))[0]
            L.append(f'  {tag}_{su} -> {tag}_{sv} [label="{lab}", color="{col}", fontcolor="{col}"];')
        L.append('}')
    L.append('}')
    dot('\n'.join(L), out)


ABBR = {'cudaLaunchKernel': 'LK', 'cudaMemcpyAsync': 'MCa', 'cudaMemcpy': 'MC', 'cudaMemsetAsync': 'MSa',
            'cudaMemset': 'MS', 'cudaStreamSynchronize': 'SS', 'cudaEventRecord': 'ER', 'cudaMalloc': 'MAL',
            'cudaMallocAsync': 'MALa', 'cudaFreeAsync': 'FREa', 'cudaFree': 'FRE', 'cudaStreamWaitEvent': 'SWE',
            'cudaDeviceSynchronize': 'DS', 'cudaEventSynchronize': 'ES', 'cudaStreamCreate': 'SCR',
        'cudaEventCreate': 'ECR', 'cudaGetDeviceProperties': 'PROP', 'cudaSetDevice': 'SDEV'}


def ab(nm):
    nm = (nm or '?').split('_v')[0]
    if nm in ABBR:
        return ABBR[nm]
    nm = nm.split('(')[0].split('<')[0]
    return nm[:9]


def panel_c(shape, out, title='', clusters=True):
    PE = {'CPU': ('box', '#e8e8e8'), 'SM': ('ellipse', '#a9dfbf'), 'CE': ('parallelogram', '#f9d5a7')}
    L = ['digraph c {', 'rankdir=LR; bgcolor=white; nodesep=0.04; ranksep=0.08;',
         f'node [fontname="{FONT}", fontsize=7, style=filled, margin="0.025,0.015", height=0.18];',
         'edge [arrowsize=0.4, penwidth=0.8];']
    streams = collections.defaultdict(list)
    for n in shape['nodes']:
        if n['pe'] in ('SM', 'CE'):
            streams[n.get('stream', 0)].append(n)
    for st, ns in sorted(streams.items()):
        if clusters:
            L.append(f'subgraph cluster_s{st} {{ label="stream {st}"; fontsize=7; color="#27ae60"; style=rounded;')
        for n in ns:
            shp, fill = PE[n['pe']]
            lbl = ab(n.get('name')) if clusters else f'{ab(n.get("name"))}\\ns{st}'
            L.append(f'  n{n["idx"]} [shape={shp}, fillcolor="{fill}", label="{lbl}"];')
        if clusters:
            L.append('}')
    for n in shape['nodes']:
        if n['pe'] == 'CPU':
            shp, fill = PE['CPU']
            L.append(f'n{n["idx"]} [shape={shp}, fillcolor="{fill}", label="{ab(n.get("name"))}"];')
    ST = {'launch': 'color="#2c3e50"', 'cpu_order': 'color="#bbbbbb", penwidth=0.5',
          'stream_fifo': 'color="#27ae60", style=dashed'}
    for (u, v, k) in shape['edges']:
        L.append(f'n{u} -> n{v} [{ST.get(k, "")}];')
    L.append('}')
    dot('\n'.join(L), out, unflatten=['-f', '-l', '4', '-c', '6'])


def panel_d(shapes, out, max_branches=3):
    """LCS backbone over the observed signatures + branches with probabilities."""
    seqs = []
    for s in shapes:
        if s.get('truncated') or not s.get('nodes'):
            continue
        seqs.append(([f"{n['pe']}:{ab(n.get('name'))}" for n in s['nodes']],
                     int(s.get('count') or 1)))
    if not seqs:
        return False
    seqs.sort(key=lambda x: -x[1])
    total = sum(c for _, c in seqs)

    def lcs(a, b):
        m = [[0] * (len(b) + 1) for _ in range(len(a) + 1)]
        for i in range(len(a) - 1, -1, -1):
            for j in range(len(b) - 1, -1, -1):
                m[i][j] = m[i + 1][j + 1] + 1 if a[i] == b[j] else max(m[i + 1][j], m[i][j + 1])
        out, i, j = [], 0, 0
        while i < len(a) and j < len(b):
            if a[i] == b[j]:
                out.append(a[i]); i += 1; j += 1
            elif m[i + 1][j] >= m[i][j + 1]:
                i += 1
            else:
                j += 1
        return out
    backbone = seqs[0][0]
    for sq, _ in seqs[1:]:
        backbone = lcs(backbone, sq)
    # run-length compress the backbone for drawing: k consecutive identical ops
    # become one box labelled "op x k" (the sequence itself is unchanged)
    rle = []
    for tok in backbone:
        if rle and rle[-1][0] == tok:
            rle[-1][1] += 1
        else:
            rle.append([tok, 1])
    L = ['digraph d {', 'rankdir=LR; bgcolor=white; nodesep=0.06; ranksep=0.14;',
         f'node [shape=box, style="rounded,filled", fontname="{FONT}", fontsize=7, margin="0.03,0.018", height=0.18];',
         f'edge [fontname="{FONT}", fontsize=6, arrowsize=0.5];']
    L.append('subgraph cluster_bb { label="backbone (common to all invocations)"; fontsize=7; '
             'style="rounded,filled"; fillcolor="#eef4fb"; color="#1a5490";')
    for i, (tok, k) in enumerate(rle):
        lbl = f'{tok}\\u00d7{k}' if k > 1 else tok
        L.append(f'  b{i} [fillcolor="#bbdefb", label="{lbl}"];')
    for i in range(len(rle) - 1):
        L.append(f'  b{i} -> b{i+1} [color="#1976d2"];')
    L.append('}')
    # branches: per shape, the ops inserted w.r.t. the backbone, attached at the
    # backbone position where they occur
    nb = 0
    for sq, cnt in seqs:
        if nb >= max_branches:
            break
        i = j = 0; ins = []
        while i < len(sq):
            if j < len(backbone) and sq[i] == backbone[j]:
                j += 1
            else:
                ins.append((j, sq[i]))
            i += 1
        if not ins:
            continue
        pos = ins[0][0]
        ops = collections.Counter(t for _, t in ins)
        top = ', '.join(f'{t.split(":")[-1]}×{c}' if c > 1 else t.split(':')[-1]
                        for t, c in ops.most_common(2))
        more = '…' if len(ops) > 2 else ''
        pct = 100.0 * cnt / total
        L.append(f'x{nb} [fillcolor="#ffe0b2", color="#e08a1e", label="{top}{more}"];')
        # map the backbone index of the insertion point to its run-length box
        acc = 0; bidx = 0
        for bi, (_t, k) in enumerate(rle):
            if acc + k > pos:
                bidx = bi; break
            acc += k; bidx = bi
        anchor = f'b{bidx}' if rle else 'x0'
        L.append(f'{anchor} -> x{nb} [color="#e08a1e", style=dashed, label="{pct:.0f}%"];')
        nb += 1
    L.append('}')
    dot('\n'.join(L), out, unflatten=['-f', '-l', '3', '-c', '5'])
    return True


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('session'); ap.add_argument('--scope', default='__main__')
    ap.add_argument('-o', '--outdir', default='paper/figures/model')
    ap.add_argument('--anchor', default=None, help='cb_addr for panels c/d (default: busiest with ≥3 shapes)')
    ap.add_argument('--gpu-session', default=None, help='session for panels c/d (default: same session)')
    ap.add_argument('--max-nodes', type=int, default=60, help='largest drawable dominant shape for panel c')
    ap.add_argument('--compact', action='store_true',
                    help='trim every panel so that 7pt text survives a half-column (2x2) placement')
    a = ap.parse_args()
    os.makedirs(a.outdir, exist_ok=True)
    conn = psycopg2.connect(DSN, cursor_factory=psycopg2.extras.RealDictCursor); conn.autocommit = True
    cur = conn.cursor()
    F, E = fetch_fragment(cur, a.session, a.scope)
    print(f'[fig] {len(F)} F vertices, {len(E)} L3 edges')
    # A minimal but complete fragment of the real Autoware graph: it carries
    # msg (inter- and intra-process), join, state, polled and the GPU submitter.
    CHAIN = [
        (r'distortion_corrector_node', '/sensing/lidar/top/mirror_cropped/pointcloud_ex'),
        (r'distortion_corrector_node', '/sensing/imu/imu_data'),
        (r'ring_outlier_filter',       '/sensing/lidar/top/rectified/pointcloud_ex'),
        (r'ring_outlier_filter',       '/sensing/lidar/left/rectified/pointcloud_ex'),
        (r'concatenate_data',          '/sensing/lidar/top/pointcloud_before_sync'),
        (r'concatenate_data',          '/sensing/lidar/left/pointcloud_before_sync'),
        (r'concatenate_data',          'twist_with_covariance'),
        (r'lidar_centerpoint',         '=/sensing/lidar/concatenated/pointcloud'),
        (r'obstacle_pointcloud_based_validator', '/detection/centerpoint/objects'),
    ]
    cur.execute("SELECT DISTINCT anchor FROM gpu_dags WHERE session_id=%s AND scope=%s AND anchor_type='cb'",
                (a.session, a.scope))
    gpu_anchors = {r['anchor'] for r in cur.fetchall()}
    if a.compact:
        CHAIN = [c for c in CHAIN if 'imu' not in c[1] and 'mirror_cropped' not in c[1]
                 and 'validation/objects' not in c[1] and 'centerpoint/objects' not in c[1]]
    sel = panel_a(F, E, CHAIN, os.path.join(a.outdir, 'panel_a'), gpu_anchors=gpu_anchors,
                  clusters=not a.compact)
    panel_b(F, E, sel, os.path.join(a.outdir, 'panel_b'))
    print(f'[fig] panel a/b: {len(sel)} F vertices selected, {len(gpu_anchors)} GPU-submitting callbacks in session')
    gsid = a.gpu_session or a.session
    cur.execute("""SELECT anchor, node, entity, n_invocations, dags FROM gpu_dags
                   WHERE session_id=%s AND scope=%s ORDER BY n_invocations DESC""", (gsid, a.scope))
    rows = cur.fetchall()
    best = None
    for r in rows:
        shapes = r['dags'] if isinstance(r['dags'], list) else json.loads(r['dags'])
        drawable = [s for s in shapes if s.get('nodes') and not s.get('truncated')]
        if not drawable:
            continue
        dom = max((s for s in drawable if s.get('phase') != 'INIT'), key=lambda s: s['count'], default=None)
        if dom is None:
            continue
        if a.anchor and r['anchor'] != a.anchor:
            continue
        if best is None or (len(shapes) >= 3 and 4 <= len(dom['nodes']) <= a.max_nodes and len(dom['nodes']) > len(best[1]['nodes'])):
            best = (r, dom, shapes)
    if best:
        r, dom, shapes = best
        pe = collections.Counter(n['pe'] for n in dom['nodes'])
        print(f"[fig] panels c/d: {r['node']} {r['entity']} — {r['n_invocations']} inv, {len(shapes)} shapes, "
              f"dominant {dom.get('phase')}×{dom['count']} ({len(dom['nodes'])} nodes "
              f"{pe.get('CPU',0)} CPU/{pe.get('SM',0)} SM/{pe.get('CE',0)} CE)")
        panel_c(dom, os.path.join(a.outdir, 'panel_c'), clusters=not a.compact)
        panel_d(shapes, os.path.join(a.outdir, 'panel_d'), max_branches=2 if a.compact else 3)
        json.dump({'session': gsid, 'anchor': r['anchor'], 'node': r['node'], 'entity': r['entity'],
                   'n_invocations': r['n_invocations'], 'n_shapes': len(shapes),
                   'dominant': {'phase': dom.get('phase'), 'count': dom['count'],
                                'nodes': len(dom['nodes']), 'pe': dict(pe)}},
                  open(os.path.join(a.outdir, 'panels_meta.json'), 'w'), indent=1)
    else:
        print('[fig] no drawable GPU anchor')


if __name__ == '__main__':
    main()
