#!/usr/bin/env python3
# Generated by Claude Fable 5.1 (Anthropic), 2026-10-04
"""FISH's version of LiME-IT's Table I (Ye, Marković, Brandenburg, RTAS'26) for the ROS 2 reference system
(autoware_default_prioritized), next to the values LiME-IT published.

  python3 refsys_table.py <limeit.json> <fish_tasks.json>

LiME-IT ran on a Raspberry Pi 5 (PREEMPT_RT 6.12), FISH here on an x86 laptop in a container: PERIODS and the SET of
callbacks / triggers are comparable, jitter values are not (different machine, scheduler and load)."""
import json, sys, collections

# published Table I: abbreviation -> (node, kind, trigger(s), executor, prio, configured ms, inferred ms, J_PF ms, J_CF ms)
PUB = {
    'BP': ('BehaviorPlanner', 'tmr', '', 'planner', 'RR 30', 100, 100, 0.06, 0.11),
    'FLidar': ('FrontLidarDriver', 'tmr', '', 'front', 'RR 1', 100, 100, 0, 0.08),
    'RLidar': ('RearLidarDriver', 'tmr', '', 'rear', 'RR 1', 100, 100, 0, 0.09),
    'PCMap': ('PointCloudMap', 'tmr', '', 'other', 'EEVDF', 120, 120, 0.12, 36.88),
    'Vis': ('Visualizer', 'tmr', '', 'other', 'EEVDF', 60, 60, 0.35, 43.73),
    'L2Map': ('Lanelet2Map', 'tmr', '', 'other', 'EEVDF', 100, 100, 0.50, 40.62),
    'ECSet': ('EuclideanClusterSettings', 'tmr', '', 'other', 'EEVDF', 25, 25, 0.73, 44.29),
    'PTF': ('PointsTransformerFront', 'sub', 'FLidar', 'front', 'RR 1', None, 100, 0, 0.34),
    'PTR': ('PointsTransformerRear', 'sub', 'RLidar', 'rear', 'RR 1', None, 100, 0, 0.42),
    'RGF': ('RayGroundFilter', 'sub', 'PCF', 'fusion', 'RR 1', None, 100, 0, 41.26),
    'OCE': ('ObjectCollisionEstimator', 'sub', 'ECD', 'fusion', 'RR 1', None, 100, 0, 11.24),
    'PCF1': ('PointCloudFusion', 'sub', 'PTR', 'fusion', 'RR 1', None, 100, 0.17, 0.37),
    'PCF2': ('PointCloudFusion', 'sub', 'PTR', 'fusion', 'RR 1', None, 100, 0.52, 0.79),
    'ECD': ('EuclideanClusterDetector', 'sub', 'RGF, ECSet', 'fusion', 'RR 1', None, 20, 15.62, 29.08),
    'VGD': ('VoxelGridDownsampler', 'sub', 'PCF', 'other', 'EEVDF', None, 100, 9.93, 47.71),
    'PCML': ('PointCloudMapLoader', 'sub', 'PCMap', 'other', 'EEVDF', None, 120, 1.10, 44.72),
    'MPC': ('MPCController', 'sub', 'BP', 'other', 'EEVDF', None, 100, 0.68, 43.38),
    'Park': ('ParkingPlanner', 'sub', 'L2ML', 'other', 'EEVDF', None, 120, 0, 69.59),
    'LPlan': ('LanePlanner', 'sub', 'L2ML', 'other', 'EEVDF', None, 120, 0, 66.16),
    'ITO': ('IntersectionOutput', 'sub', 'ECD', 'other', 'EEVDF', None, 25, 7.36, 56.26),
    'NDT1': ('NDTLocalizer', 'sub', 'VGD', 'other', 'EEVDF', None, 100, 0, 53.28),
    'NDT2': ('NDTLocalizer', 'sub', 'PCML', 'other', 'EEVDF', None, 120, 0, 48.57),
    'VI1': ('VehicleInterface', 'sub', 'MPC', 'other', 'EEVDF', None, 100, 0, 47.60),
    'VI2': ('VehicleInterface', 'sub', 'BP', 'other', 'EEVDF', None, 100, 0, 32.60),
    'L2GP1': ('Lanelet2GlobalPlanner', 'sub', 'Vis', 'other', 'EEVDF', None, 60, 0, 72.03),
    'L2GP2': ('Lanelet2GlobalPlanner', 'sub', 'NDT', 'other', 'EEVDF', None, 120, 0, 55.40),
    'L2ML1': ('Lanelet2MapLoader', 'sub', 'L2Map', 'other', 'EEVDF', None, 100, 4.85, 61.93),
    'L2ML2': ('Lanelet2MapLoader', 'sub', 'L2GP', 'other', 'EEVDF', None, 120, 0, 54.94),
    'VDBW': ('VehicleDBWSystem', 'sub', 'VI', 'other', 'EEVDF', None, 100, 0, 62.30),
}
POL = {0: 'OTHER', 1: 'FIFO', 2: 'RR'}

L = json.load(open(sys.argv[1])); T = json.load(open(sys.argv[2]))
V = {v['id']: v for t in T['tasks'] for v in t['vertices']}
trig = collections.defaultdict(set)
for t in T['tasks']:
    for e in t['edges']:
        if e.get('n_pairs') and e['u'] in V:
            trig[e['v']].add(V[e['u']]['node'].strip('/'))
pub_by_node = collections.defaultdict(list)
for ab, r in PUB.items():
    pub_by_node[r[0]].append((ab, r))
rows = [r for r in L['callbacks'] if not r['infra']]
ms = lambda x: '-' if x is None else f"{x / 1000:.2f}"
mj = lambda m: '-' if not m else f"{m['T'] / 1000:.1f}/{m['J'] / 1000:.2f}"
print(f"{'FISH callback (node / entity)':<56}{'thr prio':>9}{'n':>6}{'T_cfg':>7}{'FISH T/J':>13}{'LiME-alg PF':>13}{'CF':>14}  {'FISH trigger(s)':<34}| published LiME-IT rows for this node")
seen = set()
for r in sorted(rows, key=lambda r: (r['node'], r['entity'])):
    node = r['node'].strip('/'); v = V.get(r['id'], {})
    res = v.get('resource') or {}
    pr = '/'.join(f"{POL.get(p, p)}" for p in (res.get('policy') or [])) + ' ' + '/'.join(str(p) for p in (res.get('prio') or []))
    fp = r.get('fish_point') or (r.get('start_fit') if r['etype'] == 'tmr' else None)
    pubs = pub_by_node.get(node, []); seen.add(node)
    ptxt = '; '.join(f"{ab}: {('cfg %d, ' % x[5]) if x[5] else ''}T {x[6]}, J {x[7]}/{x[8]}{', trig ' + x[2] if x[2] else ''}" for ab, x in pubs if x[1] == ('tmr' if r['etype'] == 'tmr' else 'sub'))
    print(f"{(node + ' / ' + r['entity'])[-55:]:<56}{pr[:9]:>9}{r['n']:>6}{ms(r.get('T_cfg_us')):>7}{mj(fp):>13}{mj(r.get('lime_pf')):>13}{mj(r.get('lime_cf')):>14}  "
          f"{', '.join(sorted(trig.get(r['id'], [])))[:33]:<34}| {ptxt}")
fish_nodes = {r['node'].strip('/') for r in rows}
print(f"\nFISH data callbacks: {len(rows)} on {len(fish_nodes)} nodes; published table: {len(PUB)} callbacks on {len({x[0] for x in PUB.values()})} nodes")
print('nodes in the published table without a FISH data callback:', sorted({x[0] for x in PUB.values()} - fish_nodes))
print('FISH nodes not in the published table:', sorted(fish_nodes - {x[0] for x in PUB.values()}))
# period agreement per node: every published inferred period must appear among FISH's periods of that node
ok = bad = 0
for ab, x in PUB.items():
    mine = [(r.get('fish_point') or r.get('start_fit') or {}).get('T') for r in rows if r['node'].strip('/') == x[0] and (r['etype'] == 'tmr') == (x[1] == 'tmr')]
    hit = any(m is not None and abs(m / 1000 - x[6]) <= 0.02 * x[6] for m in mine)
    ok += hit; bad += (not hit)
    if not hit:
        print(f"  period mismatch {ab} ({x[0]}): published {x[6]} ms, FISH {[round(m / 1000, 1) for m in mine if m]}")
print(f"published inferred periods reproduced by FISH: {ok}/{ok + bad}")
