#!/usr/bin/env python3
# Generated by Claude Fable 5.1 (Anthropic), 2026-10-04
"""Readable summary of an extract_fish_tasks.py JSON: inventory, the multi-vertex tasks, and for each source of the
largest tasks the response time of every reached vertex (EDD's R^a: finish − release of the source), i.e. the chain
latencies inside the task.   python3 task_report.py fish_tasks.json [--tasks 3] [--reach 14]"""
import json, sys, collections, argparse
ap = argparse.ArgumentParser(); ap.add_argument('json'); ap.add_argument('--tasks', type=int, default=3); ap.add_argument('--reach', type=int, default=14)
a = ap.parse_args()
d = json.load(open(a.json)); T = d['tasks']; data = [t for t in T if not t['infra']]
ms = lambda x: '-' if x is None else f"{x / 1e6:.2f}"
V = {v['id']: v for t in T for v in t['vertices']}
print(f"session {d['session']}: {len(T)} components, {len(data)} data tasks ({sum(1 for t in data if t['size'] > 1)} multi-vertex, "
      f"{sum(1 for t in data if t['size'] == 1)} single-callback), {sum(len(t['vertices']) for t in data)} data vertices, "
      f"{sum(len([e for e in t['edges'] if e.get('n_pairs')]) for t in data)} trigger edges, {len(d['sampled'])} sampled dependencies")
print('source kinds:', dict(collections.Counter(s['kind'] for t in data for s in t['sources'])),
      '| activation:', dict(collections.Counter(v.get('activation') for t in data for v in t['vertices'])),
      '| timers:', dict(collections.Counter((v.get('arrival') or {}).get('clock') for t in T for v in t['vertices'] if v['etype'] == 'tmr')))
cpu = collections.Counter()
for t in T:
    for v in t['vertices']:
        c = v.get('C') or {}
        cpu['infra' if t['infra'] else 'data'] += (c.get('p50') or 0) * v['n']
tot = sum(cpu.values()) or 1
print(f"callback CPU (n × C p50): data {cpu['data'] / 1e9:.1f} s, infra {cpu['infra'] / 1e9:.1f} s ({100 * cpu['infra'] / tot:.0f} % infra)")
print(f"\n{'task':>4}{'size':>5}{'src':>4}{'exec':>5}  {'gpu':<4}{'join':<5}{'OR':<4} name")
for t in [t for t in data if t['size'] > 1]:
    print(f"{t['id']:>4}{t['size']:>5}{len(t['sources']):>4}{len(t['executors']):>5}  {'y' if t['gpu'] else '':<4}"
          f"{sum(1 for v in t['vertices'] if v.get('join')):<5}{sum(1 for v in t['vertices'] if str(v.get('activation')).startswith('OR')):<4} {t['name'][-100:]}")
for t in data[:a.tasks]:
    for s in t['sources']:
        ia = s.get('inter_arrival') or {}
        print(f"\ntask {t['id']} source [{s['kind']}] {s['name'][-90:]}: {s['n_releases']} releases, inter-arrival {ms(ia.get('min'))}/{ms(ia.get('p50'))}/{ms(ia.get('max'))} ms, "
              f"{s['n_shapes']} job shapes {s['shapes'][:4]}")
        rows = sorted(((r['R']['p50'], f, r) for f, r in s['reach'].items() if r.get('R')), key=lambda x: x[0])
        print(f"  {'reached vertex':<100}{'ratio':>6}{'R p50':>8}{'R p99':>8}{'R max':>8}")
        step = max(1, len(rows) // a.reach)
        for p50, f, r in rows[::step][:a.reach] + rows[-1:]:
            print(f"  {V[int(f)]['name'][-98:]:<100}{r['ratio']:>6.2f}{ms(p50):>8}{ms(r['R']['p99']):>8}{ms(r['R']['max']):>8}")
