#!/usr/bin/env python3
"""Update tests/benchmark_status.json with the result of one benchmark run.

Usage:
    _status_record.py <benchmark> <status> <duration> <image_tag> <tail>

`status` is one of: building / build_failed / build_only / running / run_failed
                    / passed / skipped
"""
import fcntl
import json
import os
import sys
import time
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
STATUS_FILE = REPO_ROOT / "tests" / "benchmark_status.json"
STATUS_MD = REPO_ROOT / "tests" / "benchmark_status.md"
LOCK_FILE = REPO_ROOT / "tests" / ".status.lock"


def load_status():
    if STATUS_FILE.exists():
        with open(STATUS_FILE) as f:
            return json.load(f)
    return {"updated": "", "rows": {}}


def save_status(data):
    data["updated"] = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())
    STATUS_FILE.parent.mkdir(parents=True, exist_ok=True)
    with open(STATUS_FILE, "w") as f:
        json.dump(data, f, indent=2, sort_keys=True)


SYMBOL = {
    "passed":       "✅",
    "build_only":   "🟦",
    "build_failed": "❌",
    "run_failed":   "⚠️",
    "skipped":      "⏭️ ",
    "building":     "🔧",
    "running":      "🔬",
}


def render_md(data):
    inv_file = REPO_ROOT / "tests" / "benchmark_inventory.json"
    with open(inv_file) as f:
        inv = json.load(f)
    rows = data.get("rows", {})

    lines = []
    lines.append("# Isaac ROS benchmark image build + smoke-test status\n")
    lines.append(f"Auto-rendered from `tests/benchmark_status.json` — last updated **{data.get('updated','?')}**\n")
    lines.append("")
    lines.append("Host: `x86_64` + RTX A1000 Laptop (4 GB) + CUDA 12.6 + ROS 2 Humble + FISH.")
    lines.append("Base image: `fish-base:cuda12.6-humble` from `docker/fish-base.Dockerfile`.\n")
    lines.append("Per-benchmark image generated by `scripts/build_benchmark_image.sh <name>`.\n")
    lines.append("")
    lines.append("Status legend:")
    lines.append("- ✅ passed (build + run OK)")
    lines.append("- 🟦 build_only (image built, run not attempted)")
    lines.append("- ⚠️  run_failed (image built, launch_test failed)")
    lines.append("- ❌ build_failed (docker build did not complete)")
    lines.append("- ⏭️  skipped (hardware not available on host)")
    lines.append("- 🔧 building (in progress)")
    lines.append("- 🔬 running (in progress)\n")
    lines.append("")

    lines.append("| ⊕ | Benchmark | Category | Image | Duration | Notes |")
    lines.append("|---|-----------|----------|-------|----------|-------|")
    for b in inv["benchmarks"]:
        name = b["name"]
        row = rows.get(name, {})
        status = row.get("status", "pending")
        sym = SYMBOL.get(status, "·")
        dur = row.get("duration", "")
        img = f"`{row.get('image','')}`" if row.get("image") else ""
        note = row.get("note", b.get("reason", ""))
        # truncate tails
        note_short = (note[:80] + "…") if len(note) > 80 else note
        lines.append(f"| {sym} | `{name}` | {b['category']} | {img} | {dur} | {note_short} |")
    lines.append("")

    counts = {}
    for v in rows.values():
        counts[v["status"]] = counts.get(v["status"], 0) + 1
    if counts:
        lines.append("## Roll-up\n")
        for st in ("passed", "build_only", "run_failed", "build_failed", "skipped"):
            if st in counts:
                lines.append(f"- {SYMBOL.get(st,'?')} `{st}` — {counts[st]}")
        lines.append("")

    STATUS_MD.write_text("\n".join(lines))


def main():
    if len(sys.argv) < 6:
        print("Usage: _status_record.py <bench> <status> <duration> <image> <tail>", file=sys.stderr)
        sys.exit(1)
    name, status, dur, image, tail = sys.argv[1:6]

    # Serialize concurrent writers with a file lock — parallel build workers
    # all call this script when they finish; without flock the JSON race-
    # conditions and rows get lost.
    LOCK_FILE.parent.mkdir(parents=True, exist_ok=True)
    with open(LOCK_FILE, "w") as lk:
        fcntl.flock(lk.fileno(), fcntl.LOCK_EX)
        data = load_status()
        data.setdefault("rows", {})[name] = {
            "status": status,
            "duration": dur,
            "image": image,
            "note": tail.strip(),
            "ts": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        }
        save_status(data)
        render_md(data)
        fcntl.flock(lk.fileno(), fcntl.LOCK_UN)
    print(f"[status] {name} -> {status}")


if __name__ == "__main__":
    main()
