"""IMAGE_PROC-NODE-A2 per-node review data."""

# Source review for RectifyNode (NITROS NEGOTIATED, 2-in/2-out — same template as ResizeNode)
RECTIFY_REVIEW = [
    [1, 'isaac_ros_image_pipeline/isaac_ros_image_proc/src/rectify_node.cpp', '43-58',
     'INPUT_CAM_COMPONENT_KEY="sync/camera_info_in"; INPUT_COMPONENT_KEY="sync/image_in"; OUTPUT_COMPONENT_KEY="image_sink/sink"; OUTPUT_CAM_COMPONENT_KEY="camera_info_sink/sink"',
     '(no VCC — constants only)',
     '—',
     '4 CONFIG_MAP keys: 2 NEGOTIATED inputs (camera_info, image) + 2 NEGOTIATED outputs (rectified image, rectified camera_info)'],
    [2, 'isaac_ros_image_pipeline/isaac_ros_image_proc/src/rectify_node.cpp', '81-116',
     'CONFIG_MAP: 4 entries — INPUT_CAM_*=camera_info, INPUT_*=image, OUTPUT_*=image_rect, OUTPUT_CAM_*=camera_info_rect',
     '(declares the chain VCCI4+VCCI5 instantiate)',
     '—',
     'remappings at launch: image_raw→image (input), image_rect (output) stays as default'],
    [3, 'isaac_ros_image_pipeline/isaac_ros_image_proc/src/rectify_node.cpp', '120-135',
     ': nitros::NitrosNode(options, APP_YAML, CONFIG_MAP, PRESET_EXTENSION_SPEC_NAMES, ..., PACKAGE_NAME)',
     'VCCI1 → VCC1',
     '+1 N + 7 E + 7 F + 2 pub_aspect (via rclcpp::Node base)',
     ''],
    [4, 'isaac_ros_image_pipeline/isaac_ros_image_proc/src/rectify_node.cpp', '156',
     'startNitrosNode()',
     'VCCI2',
     '+1 E + 1 F (negotiation_timer 100ms)',
     ''],
    [5, 'nitros_node.cpp:548 startNitrosNode body',
     'iterates nitros_pub_sub_groups → createNitrosSubscribers + createNitrosPublishers',
     'VCCI4 + VCCI5', '—',
     'For 2-in/2-out: 2× NitrosSubscriber (VCCI6 chain) + 2× NitrosPublisher (VCCI13 chain)'],
    # 2 inputs
    [6, 'nitros_subscriber.cpp:223 + nitros_format_agent.hpp:367',
     'input #0 (camera_info, INPUT_CAM_COMPONENT_KEY) — createCompatibleSubscriberCallback',
     'VCCI8',
     '+1 E + 1 F (compat sub on /camera_info)', ''],
    [7, 'negotiated_subscription.cpp:71-105 ctor',
     'input #0 NegotiatedSubscription on /camera_info/nitros',
     'VCCI9',
     '+1 E + 1 F (NegotiatedTopicsInfo sub) + 1 pub_aspect (_supported_types pub)', ''],
    [8, 'nitros_subscriber.cpp:223 + nitros_format_agent.hpp:367',
     'input #1 (image, INPUT_COMPONENT_KEY) — createCompatibleSubscriberCallback',
     'VCCI8',
     '+1 E + 1 F (compat sub on /image)', ''],
    [9, 'negotiated_subscription.cpp:71-105 ctor',
     'input #1 NegotiatedSubscription on /image/nitros',
     'VCCI9',
     '+1 E + 1 F + 1 pub_aspect', ''],
    # 2 outputs
    [10, 'nitros_publisher.cpp + nitros_format_agent.hpp',
     'output #0 (image_sink/sink) — createCompatiblePublisherCallback',
     'VCCI14',
     '+1 pub_aspect (compat pub on /image_rect)', ''],
    [11, 'negotiated_publisher.cpp:290 ctor + 581 start',
     'output #0 NegotiatedPublisher on /image_rect/nitros',
     'VCCI15',
     '+1 pub_aspect (NegotiatedTopicsInfo pub) + +1 E + 1 F (graph_change_timer 100ms) + +1 E + 1 F (_supported_types sub)', ''],
    [12, 'nitros_publisher.cpp + nitros_format_agent.hpp',
     'output #1 (camera_info_sink/sink) — createCompatiblePublisherCallback',
     'VCCI14',
     '+1 pub_aspect (compat pub on /camera_info_rect)', ''],
    [13, 'negotiated_publisher.cpp:290 ctor + 581 start',
     'output #1 NegotiatedPublisher on /camera_info_rect/nitros',
     'VCCI15',
     '+1 pub_aspect + +1 E + 1 F + +1 E + 1 F', ''],
    [14, 'nitros_node.cpp:721 postNegotiationCallback (RUNTIME)',
     '[runtime] create_wall_timer(gxf_heartbeat_timer)',
     'VCC_GHB',
     '+1 E + 1 F (post-negotiation)',
     'Same gxf_heartbeat as in ResizeNode'],
]

# NitrosMonitorNode for image_proc — uses NITROS NEGOTIATED sub path
NITROSMONITOR_IMAGE_PROC = [
    [1, 'ros2_benchmark/ros2_benchmark/src/monitor_node.cpp', '26',
     ': rclcpp::Node("MonitorNode", options) — invoked via NitrosMonitorNode delegating ctor',
     'VCC1', '+1 N + 7 E + 7 F + 2 pub_aspect', ''],
    [2, 'ros2_benchmark/ros2_benchmark/src/monitor_node.cpp', '30',
     'service_callback_group_{create_callback_group(MutuallyExclusive)}',
     '(no VCC — cbgroup only)', '—', ''],
    [3, 'ros2_benchmark/ros2_benchmark/src/monitor_node.cpp', '32',
     'create_service<StartMonitoring>("monitor_node0_start_monitoring", ...)',
     'VCC4', '+1 E + 1 F', ''],
    [4, 'ros2_benchmark/ros2_benchmark/src/monitor_node.cpp', '42',
     'create_service<StopMonitoring>("monitor_node0_stop_monitoring", ...)',
     'VCC4', '+1 E + 1 F', ''],
    [5, 'isaac_ros_benchmark/isaac_ros_benchmark/src/nitros_monitor_node.cpp', '36',
     ': ros2_benchmark::MonitorNode("NitrosMonitorNode", options) — delegating ctor (skips parent generic sub)',
     '(parent body invoked)', '—', ''],
    [6, 'isaac_ros_benchmark/isaac_ros_benchmark/src/nitros_monitor_node.cpp', '47-58',
     'nitros_type_manager_ + registerSupportedType<...>() × 10',
     '(no vertex)', '—', ''],
    [7, 'isaac_ros_benchmark/isaac_ros_benchmark/src/nitros_monitor_node.cpp', '60',
     'CreateMonitorSubscriber()',
     '(branches)', '—',
     'For image_proc: monitor_data_format="nitros_image_bgr8" (IS in NITROS type registry) + use_nitros_type_monitor_sub=True → CreateNitrosMonitorSubscriber'],
    [8, 'isaac_ros_benchmark/isaac_ros_benchmark/src/nitros_monitor_node.cpp', '128-175',
     'CreateNitrosMonitorSubscriber: builds NitrosSubscriber NEGOTIATED config (compat_data_format=nitros_image_bgr8, topic_name="output"), then nitros_sub_->start()',
     'VCCI6 → VCCI8 + VCCI9', '—',
     'remap: output → image_rect; subs go to /image_rect (compat) and /image_rect/nitros (NEGOTIATED)'],
    [9, 'nitros_subscriber.cpp:223 + nitros_format_agent.hpp:367',
     'compat sub on /image_rect (NitrosImage type)',
     'VCCI8', '+1 E + 1 F', ''],
    [10, 'negotiated_subscription.cpp:71-105 ctor',
     'NegotiatedSubscription on /image_rect/nitros',
     'VCCI9', '+1 E + 1 F + 1 pub_aspect', ''],
]

# Container = rectify_container, same as apriltag container (just different name)
RECTIFY_CONTAINER_REVIEW = [
    [1, 'rclcpp_components/src/component_manager.cpp', '37-50',
     'ComponentManager()',
     'VCC1.cm',
     '+1 N + 1 E + 1 F + 1 pub_aspect (/rosout)', 'NodeOptions override — no params; keeps TimeSource sub'],
    [2, 'rclcpp_components/src/component_manager.cpp', 'service registration',
     'create_service<LoadNode> + UnloadNode + ListNodes',
     'VCC4 ×3', '+3 E + 3 F', ''],
]

# Expected dictionary (composed via a2_lib)
# Imported by sheet builder
