"""STEREO_IMAGE_PROC-NODE-A2 per-node data — only the new DisparityNode review."""

# DisparityNode: NITROS NEGOTIATED, 4 INPUTS + 1 OUTPUT
DISPARITY_REVIEW = [
    [1, 'isaac_ros_image_pipeline/isaac_ros_stereo_image_proc/src/disparity_node.cpp', '43-60',
     'INPUT_LEFT_COMPONENT_KEY="sync/left_image_receiver"; INPUT_RIGHT_COMPONENT_KEY="sync/right_image_receiver"; INPUT_LEFT_CAM_COMPONENT_KEY="sync/left_cam_receiver"; INPUT_RIGHT_CAM_COMPONENT_KEY="sync/right_cam_receiver"; OUTPUT_COMPONENT_KEY="sink/sink"',
     '(no VCC — constants only)',
     '—',
     '5 CONFIG_MAP keys: 4 NEGOTIATED inputs (left/right image + left/right camera_info) + 1 NEGOTIATED output (disparity)'],
    [2, 'isaac_ros_image_pipeline/isaac_ros_stereo_image_proc/src/disparity_node.cpp', '78-120',
     'CONFIG_MAP: 5 NEGOTIATED entries with topic names left/image_rect, right/image_rect, left/camera_info, right/camera_info, disparity',
     '(declares chain)',
     '—', ''],
    [3, 'isaac_ros_image_pipeline/isaac_ros_stereo_image_proc/src/disparity_node.cpp', '124',
     ': nitros::NitrosNode(options, APP_YAML, CONFIG_MAP, PRESET_..., PACKAGE_NAME)',
     'VCCI1 → VCC1',
     '+1 N + 7 E + 7 F + 2 pub_aspect (via rclcpp::Node base)', ''],
    [4, 'isaac_ros_image_pipeline/isaac_ros_stereo_image_proc/src/disparity_node.cpp', '165',
     'startNitrosNode()',
     'VCCI2',
     '+1 E + 1 F (negotiation_timer 100ms)', ''],
    # 4 inputs × (VCCI8 + VCCI9) = 8 E + 8 F + 4 pub_aspect
    [5, 'nitros_subscriber.cpp:223 + nitros_format_agent.hpp:367',
     'input #0 (left image) compat sub on /left/image_rect',
     'VCCI8',
     '+1 E + 1 F', ''],
    [6, 'negotiated_subscription.cpp:71-105 ctor',
     'input #0 NegotiatedSubscription on /left/image_rect/nitros',
     'VCCI9',
     '+1 E + 1 F + 1 pub_aspect', ''],
    [7, 'nitros_subscriber.cpp + nitros_format_agent.hpp',
     'input #1 (right image) compat sub on /right/image_rect',
     'VCCI8',
     '+1 E + 1 F', ''],
    [8, 'negotiated_subscription.cpp ctor',
     'input #1 NegotiatedSubscription on /right/image_rect/nitros',
     'VCCI9',
     '+1 E + 1 F + 1 pub_aspect', ''],
    [9, 'nitros_subscriber.cpp + nitros_format_agent.hpp',
     'input #2 (left camera_info) compat sub on /left/camera_info',
     'VCCI8',
     '+1 E + 1 F', ''],
    [10, 'negotiated_subscription.cpp ctor',
     'input #2 NegotiatedSubscription on /left/camera_info/nitros',
     'VCCI9',
     '+1 E + 1 F + 1 pub_aspect', ''],
    [11, 'nitros_subscriber.cpp + nitros_format_agent.hpp',
     'input #3 (right camera_info) compat sub on /right/camera_info',
     'VCCI8',
     '+1 E + 1 F', ''],
    [12, 'negotiated_subscription.cpp ctor',
     'input #3 NegotiatedSubscription on /right/camera_info/nitros',
     'VCCI9',
     '+1 E + 1 F + 1 pub_aspect', ''],
    # 1 output × (VCCI14 + VCCI15) = 2 E + 2 F + 2 pub_aspect
    [13, 'nitros_publisher.cpp + nitros_format_agent.hpp',
     'output #0 (disparity) — createCompatiblePublisherCallback',
     'VCCI14',
     '+1 pub_aspect (compat pub on /disparity)', ''],
    [14, 'negotiated_publisher.cpp:290 ctor + 581 start',
     'output #0 NegotiatedPublisher on /disparity/nitros',
     'VCCI15',
     '+1 pub_aspect (NegotiatedTopicsInfo pub) + +1 E + 1 F (graph_change_timer 100ms) + +1 E + 1 F (_supported_types sub)', ''],
    [15, 'nitros_node.cpp:721 postNegotiationCallback (RUNTIME)',
     '[runtime] create_wall_timer(gxf_heartbeat_timer)',
     'VCC_GHB',
     '+1 E + 1 F (post-negotiation)', ''],
]
# Total: VCC1 (7) + VCCI2 (1) + 4 in × 2 (8) + 1 out × 2 (2) + runtime (1) = 19 E + 19 F
