#!/usr/bin/env python3
# Generated by Claude Fable 5 (Anthropic)
"""AUTOWARE-<RUN>-NODE-A2 — Google Sheet from scripts/aw_a2_expected.py output.

Same conventions as the Isaac ROS A2 sheets (a2_build.py), scaled to a
250-node stack: instead of one tab per node, the per-node reviews live in ONE
`node_reviews` tab (node full_name in column A) — every row still carries
file:line + the exact code line + VCC code + resulting vertex.

tabs: REFERENCE · bench_node · expected_vertex · actual_vertex · node_reviews ·
      class_map · mismatch_detail · ros2cli_helpers

usage: aw_a2_sheet.py <a2_expected.json> --title AUTOWARE-LOGSIM-R24-NODE-A2 [--image ...] [--session-dir ...]
"""
import argparse, collections, json, os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from pbr1_sheet_writer import make_clients, write_payload   # noqa: E402

REFERENCE = [
    ["Code", "Layer / Class", "Call", "FISH contribution", "pub/cli aspect", "Source / Notes"],
    ["VCC1", "rclcpp::Node ctor", "Node(name[+ns]+opts)", "+1 N + 1 E (/parameter_events sub, TimeSource) + 6 E/F (parameter services)", "+2 pub (/rosout, /parameter_events)",
     "rclcpp/src/rclcpp/parameter_service.cpp:36-145 (6× create_service); node_parameters.cpp:68 (start_parameter_services); time_source.cpp attach"],
    ["VCC1.sim", "rclcpp::TimeSource", "use_sim_time=true (logging_simulator sets it for every node)", "+1 E + 1 F (/clock sub)", "",
     "rclcpp/src/rclcpp/time_source.cpp:257-260 create_clock_sub()"],
    ["VCC1.cm", "rclcpp_components::ComponentManager", "ComponentManager()", "+1 N + 1 E/F (/parameter_events sub only)", "+1 pub (/rosout)",
     "component_manager.cpp: NodeOptions start_parameter_services(false), start_parameter_event_publisher(false)"],
    ["VCC1.cm+", "ComponentManager services", "create_service<LoadNode|UnloadNode|ListNodes>", "+3 E + 3 F", "", "component_manager.cpp:42,46,50"],
    ["VCC1.lc", "rclcpp_lifecycle::LifecycleNode", "LifecycleNode(...)", "+5 E/F (change_state, get_state, get_available_states, get_available_transitions, get_transition_graph)", "+1 pub (/transition_event)", "ROS2 API Investigation - Humble (full)"],
    ["VCC1.rclpy", "rclpy.node.Node", "Node(...)", "+6 E/F (parameter services), no TimeSource sub", "+2 pub", "launch_ros agent"],
    ["VCC2", "rclcpp::Node", "create_subscription<T>(topic, qos, cb)", "+1 E + 1 F", "", "rcl_subscription_init + rclcpp_subscription_callback_added"],
    ["VCC_GS", "rclcpp::Node", "create_generic_subscription", "+1 E + 1 F", "", ""],
    ["VCC3", "rclcpp::Node", "create_publisher<T>", "—", "+1 pub", "publishers are aspects of the F that publishes (fish_rclcpp_publish_link), never E"],
    ["VCC_GP", "rclcpp::Node", "create_generic_publisher", "—", "+1 pub", ""],
    ["VCC4", "rclcpp::Node", "create_service<T>(name, cb)", "+1 E + 1 F", "", ""],
    ["VCC5", "rclcpp::Node", "create_client<T>(name)", "—", "+1 cli", "client requests are aspects (fish_rclcpp_client_request_sent)"],
    ["VCC6", "rclcpp::Node / rclcpp::create_timer", "create_wall_timer / create_timer", "+1 E + 1 F", "", "rcl_timer_init + rclcpp_timer_callback_added"],
    ["VCC_IPC", "rclcpp intra-process", "subscription with use_intra_process_comms → SubscriptionIntraProcess Waitable", "+1 E (waitable) + 1 F — RUNTIME, only when IPC negotiated", "",
     "fish_rclcpp_waitable_init (IntraProcessManager::add_subscription); counted in 'waitable' column, NOT in the static expected"],
    ["VCCA1", "autoware_utils InterProcessPollingSubscriber", "InterProcessPollingSubscriber<T>::create_subscription(node, topic) / ctor", "+1 E + 1 F (subscription with no-op callback; consumer uses take())", "",
     "autoware_utils_rclcpp/polling_subscriber.hpp:216 create_subscription<MessageT>(…, [](…){}) — FISH models the reads as polled_take"],
    ["VCCA2", "autoware_utils LoggerLevelConfigure", "make_unique<LoggerLevelConfigure>(this)", "+1 E + 1 F (service ~/config_logger)", "", "autoware_utils_logging/src/logger_level_configure.cpp:27 create_service<ConfigLogger>"],
    ["VCCA3", "diagnostic_updater::Updater", "Updater(this[, period])", "+1 E + 1 F (update timer)", "+1 pub (/diagnostics)", "diagnostic_updater.hpp:391 create_publisher, :500 rclcpp::create_timer"],
    ["VCCA4", "autoware::rtc_interface::RTCInterface", "RTCInterface(node, name, …)", "+2 E + 2 F (services cooperate_commands, auto_mode); +1 E/F timer counted as VCC6 via rclcpp::create_timer in the same ctor only if the class body is scanned — RTCInterface is external, so timer is included in VCCA4 delta (2,2)+? see notes", "+2 pub",
     "rtc_interface.cpp:130 create_timer, :135,:138 create_publisher, :142,:146 create_service"],
    ["VCCA5", "autoware component_interface_utils", "adaptor.init_sub / init_srv / init_pub / init_cli", "sub +1 E/F · srv +1 E/F", "pub +1 · cli +1", "component_interface_utils/rclcpp.hpp:58-82 → create_*_impl"],
    ["VCCA6", "message_filters::Subscriber", ".subscribe(this, topic, qos) / Subscriber(node, topic)", "+1 E + 1 F", "", "message_filters/subscriber.h:286 create_subscription<M>"],
    ["VCCA7", "image_transport", "image_transport::create_subscription / create_publisher", "sub +1 E/F", "pub +1", "raw transport only (plugins would add per-transport subs)"],
    ["VCCA8", "tf2_ros::TransformListener(buffer, node, spin_thread=false)", "", "+2 E + 2 F on THIS node (/tf, /tf_static)", "", "geometry2/tf2_ros/src/transform_listener.cpp"],
    ["VCCA8h", "tf2_ros::TransformListener(buffer[, node]) spin_thread=true", "", "separate helper N transform_listener_impl_<addr>: 3 E/F (/parameter_events, /tf, /tf_static) [+ /clock]", "+1 pub (/rosout)",
     "transform_listener.cpp:52-56 NodeOptions start_parameter_services(false), start_parameter_event_publisher(false)"],
    ["VCCA8m", "managed_transform_buffer provider", "ManagedTransformBuffer", "per process one helper N managed_tf_listener_impl_*: 3 E/F [+ /clock]", "+1 pub", "managed_transform_buffer_provider.cpp:101-133"],
    ["VCCA9", "rclcpp::(A)SyncParametersClient", "", "—", "+6 cli", ""],
    ["ctx", "review flag", "row found under if/for/while/lambda within the method", "counted ONCE unless resolved (below); otherwise a range bound", "", "static count, no TBD"],
    ["RES-loop", "resolution", "row inside `for (… : X)` / `i < X.size()`", "× N where N = length of the literal list `X` in the sources, of the parameter bound to X (node yaml / package config), or of the helper-function argument bound at the call site", "", "aw_a2_expected.resolve_loop_multiplicity"],
    ["RES-name", "resolution", "deferred / if-guarded row with a literal topic or service name", "created|absent by matching the literal (after the node's launch remappings) against the counted E labels; `absent` only when the remap table is known", "", "aw_a2_expected.resolve_rows_by_names"],
    ["RES-param", "resolution", "`if (flag)` row where flag = declare_parameter<bool>(\"name\"[, default])", "created|absent from the node's parameter yaml, else the code default; the `else` row of the same method takes the opposite", "", "aw_a2_expected.resolve_if_rows_by_params"],
    ["RES-ctor", "resolution", "row in a method that the constructor calls directly", "static (not deferred): the method runs at construction", "", "e.g. autoware::pointcloud_preprocessor::Filter::subscribe()"],
    ["RES-helper", "resolution", "helper class of the same package constructed with the node (make_shared<X>(*this), X m_{this}, opt_.emplace(this,…))", "X's own creation rows count for the node (flagged `via helper class X`), inheriting the guard of the instantiation line", "", "VCCA-listed helpers are skipped (they have exact rules)"],
    ["WAIT-ipc", "tracepoint check", "intra-process SubscriptionIntraProcess Waitable", "no extra E: the sub E carries `ipc_waitable`; trace must show waitable_init(node_handle=0x0) + subscription_init + callback_added for it, and #wrapper dispatches == #inner dispatches", "", "scripts/aw_a2_waitables.py — the executor Waitable-branch callback_start wrap (§5) is the 'unregistered' 0.9 % of r25"],
]


def load(path):
    return json.load(open(path))


BASE_NAMES = {"parameter_events", "get_parameters", "get_parameter_types", "set_parameters", "set_parameters_atomically",
              "describe_parameters", "list_parameters", "clock"}


def phase_columns(d, graph_path):
    """per node: counted E by the phase of its F (data / init / zero_exec) and, for non-OK nodes,
    the counted E that no expected row's literal name explains — by phase."""
    sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
    import aw_a2_expected as m
    g = load(graph_path); by = {n["id"]: n for n in g["nodes"]}
    out = {}
    for n in g["nodes"]:
        if n.get("type") != "N":
            continue
        r = d["nodes"].get(n.get("full_name"))
        if not r or not r.get("expected"):
            continue
        E = []
        for c in n.get("children", []):
            e = by.get(c)
            if not e or e.get("type") != "E" or e.get("etype") == "oore":
                continue
            ph = [by[f].get("phase") for f in e.get("children", []) if by.get(f, {}).get("type") == "F" and by[f].get("split") != "response"]
            E.append((e.get("label", ""), e.get("etype"), ph[0] if ph else "noF"))
        cnt = collections.Counter(ph for _l, _t, ph in E)
        remaps = r.get("launch_remaps") or {}
        claimed = collections.Counter()
        for x in r["rows"]:
            if not x["delta"][0] or x.get("resolved") == "absent":
                continue
            nm = m.literal_name(x["code"])
            if not nm:
                continue
            key = nm[2:] if nm.startswith("~/") else nm
            tgt = remaps.get(key) or remaps.get(nm) or nm
            claimed[tgt.rstrip("/").rsplit("/", 1)[-1]] += (x.get("mult") or 1)
        un = collections.Counter(); un_names = []
        for lab, et, ph in E:
            b = lab.rsplit("/", 1)[-1]
            if b in BASE_NAMES:
                continue
            if claimed.get(b, 0) > 0:
                claimed[b] -= 1; continue
            un[ph] += 1; un_names.append(f"{b}({et},{ph})")
        out[n["full_name"]] = {"data": cnt.get("data", 0), "init": cnt.get("init", 0), "zero": cnt.get("zero_exec", 0), "noF": cnt.get("noF", 0),
                               "un_data": un.get("data", 0), "un_init": un.get("init", 0), "un_zero": un.get("zero_exec", 0),
                               "un_names": ", ".join(un_names)[:1500]}
    return out


def bench_node_tab(d, a):
    s = d["summary"]
    return [["Field", "Value"],
            ["Stack", "Autoware (autowarefoundation/autoware @ 5dfb0900, universe-devel-cuda-20260401 install space)"],
            ["Image", a.image],
            ["Scenario", a.scenario],
            ["Session", d["session"]],
            ["FISH graph JSON", d["graph_json"]],
            ["use_sim_time (VCC1.sim applied)", str(d["use_sim_time"])],
            ["Provenance roots (sources + ctags)", ", ".join(d["roots"])],
            ["Expected model", "VCC1 baseline [+ /clock] + Σ creation calls found in the node class's own method bodies and its base classes (ctags line/end ranges); publishers/clients are aspects"],
            ["Class identification", "launch_components.json plugin → CMake rclcpp_components_register_node → majority of registered callback symbols"],
            ["Nodes modelled", s["modelled"]],
            ["Nodes OK (ΔE=ΔF=0)", s["ok"]],
            ["Expected E/F (sum)", f"{s['expected_E']}/{s['expected_F']}"],
            ["Counted E/F (sum)", f"{s['actual_E']}/{s['actual_F']}"],
            ["Excluded from static model", "/_ros2cli_* helpers (see ros2cli_helpers tab); intra-process Waitables (runtime, 'waitable' column)"],
            ["Generated by", "scripts/aw_a2_expected.py (in fishwait6 container) + scripts/aw_a2_sheet.py — Claude Fable 5"]]


def expected_tab(d, ph=None):
    ph = ph or {}
    rows = [["Node full_name", "kind", "class", "class how", "exp E", "exp F", "exp pub", "exp cli", "act E", "act F", "act pub", "act waitable", "Δ E", "Δ F", "verdict", "range", "resolved (loops/created/absent)",
             "E data", "E init", "E zero_exec", "unexplained data", "unexplained init", "unexplained zero_exec", "unexplained E (name,etype,phase)", "notes"]]
    tE = tF = aE = aF = 0
    for full, r in sorted(d["nodes"].items()):
        if not r.get("expected"):
            continue
        e, ac = r["expected"], r["actual"]
        tE += e["E"]; tF += e["F"]; aE += ac["E"]; aF += ac["F"]
        res = e.get("resolved", {}); p = ph.get(full, {})
        rows.append([full, r["kind"], r.get("class") or "", r.get("class_how") or "", e["E"], e["F"], e["pub"], e["cli"],
                     ac["E"], ac["F"], ac["pub"], len(ac.get("waitable", [])), r["delta"]["E"], r["delta"]["F"], r["verdict"],
                     str(e.get("range", "")), f"{res.get('loops', 0)}/{res.get('created', 0)}/{res.get('absent', 0)}",
                     p.get("data", ""), p.get("init", ""), p.get("zero", ""),
                     "" if r["verdict"] == "OK" else p.get("un_data", ""), "" if r["verdict"] == "OK" else p.get("un_init", ""),
                     "" if r["verdict"] == "OK" else p.get("un_zero", ""), "" if r["verdict"] == "OK" else p.get("un_names", ""),
                     "; ".join(r.get("notes", []))])
    rows += [[], ["TOTAL (modelled)", "", "", "", tE, tF, "", "", aE, aF, "", "", aE - tE, aF - tF, "OK" if (aE == tE and aF == tF) else "mismatch", "", "",
                  sum(p.get("data", 0) for p in ph.values()), sum(p.get("init", 0) for p in ph.values()), sum(p.get("zero", 0) for p in ph.values()),
                  sum(p.get("un_data", 0) for f, p in ph.items() if d["nodes"][f]["verdict"] != "OK"), sum(p.get("un_init", 0) for f, p in ph.items() if d["nodes"][f]["verdict"] != "OK"),
                  sum(p.get("un_zero", 0) for f, p in ph.items() if d["nodes"][f]["verdict"] != "OK"), "", ""]]
    # verdict × phase summary block
    rows += [[], ["verdict × phase", "nodes", "E total", "E data", "E init", "E zero_exec", "unexplained data", "unexplained init", "unexplained zero_exec"]]
    for v in ["OK", "OK:range", "mismatch:ctx", "mismatch:plugins", "mismatch"]:
        fs = [f for f, r in d["nodes"].items() if r.get("expected") and r["verdict"] == v]
        P = [ph.get(f, {}) for f in fs]
        rows.append([v, len(fs), sum(p.get("data", 0) + p.get("init", 0) + p.get("zero", 0) + p.get("noF", 0) for p in P),
                     sum(p.get("data", 0) for p in P), sum(p.get("init", 0) for p in P), sum(p.get("zero", 0) for p in P),
                     "" if v == "OK" else sum(p.get("un_data", 0) for p in P), "" if v == "OK" else sum(p.get("un_init", 0) for p in P), "" if v == "OK" else sum(p.get("un_zero", 0) for p in P)])
    cli = [r for r in d["nodes"].values() if r["kind"] == "ros2cli"]
    rows += [[], [f"+ ros2cli helpers ({len(cli)})", "", "", "", "", "", "", "", sum(r["actual"]["E"] for r in cli), sum(r["actual"]["F"] for r in cli), "", "", "", "", "", "runtime/CLI noise — not in static model"]]
    return rows


def actual_tab(d):
    rows = [["Node full_name", "pid", "E", "F", "sub topics", "srv", "tmr periods (ns)", "waitables", "other E", "pub topics", "cli"]]
    for full, r in sorted(d["nodes"].items()):
        a = r["actual"]
        rows.append([full, r.get("pid"), a["E"], a["F"], ", ".join(a["sub"])[:1500], ", ".join(a["serv"])[:1500], ", ".join(a["tmr"])[:300],
                     ", ".join(a.get("waitable", []))[:500], ", ".join(a.get("other", []))[:300], ", ".join(a.get("pub_topics", []))[:1500], ", ".join(a.get("cli_names", []))[:500]])
    return rows


def reviews_tab(d):
    rows = [["Node full_name", "#", "Class (where the row was found)", "Source file", "Line", "Exact code", "VCC code", "Resulting vertex (E/F/pub/cli)", "Method", "ctx (if/for/lambda)", "Rule"]]
    for full, r in sorted(d["nodes"].items()):
        if not r.get("expected"):
            continue
        e = r["expected"]
        base = e["base"]
        rows.append([full, 0, r.get("class") or "", "(baseline)", "", "rclcpp::Node ctor" + (" + LifecycleNode" if r.get("lifecycle") else "") + (" + /clock (use_sim_time)" if e.get("clock") else ""),
                     "VCC1" + (".lc" if r.get("lifecycle") else "") + (" + VCC1.sim" if e.get("clock") else ""),
                     f"+{base[0] + (1 if e.get('clock') else 0)} E + {base[1] + (1 if e.get('clock') else 0)} F + {base[2]} pub", "", "", r.get("class_how") or ""])
        for i, row in enumerate(r["rows"], 1):
            dE, dF, dP, dC = row["delta"]
            res = " + ".join(x for x in [f"{dE} E" if dE else "", f"{dF} F" if dF else "", f"{dP} pub" if dP else "", f"{dC} cli" if dC else ""] if x) or "—"
            rows.append([full, i, row.get("cls", ""), row["file"], row["line"], row["code"], row["vcc"], "+" + res, row.get("method", ""), row.get("ctx", ""), row.get("desc", "")])
    return rows


def class_map_tab(d):
    rows = [["Node full_name", "kind", "class", "resolved in ctags", "how", "base rclcpp class", "lifecycle", "#rows", "notes"]]
    for full, r in sorted(d["nodes"].items()):
        rows.append([full, r["kind"], r.get("class") or "", r.get("class_resolved") or "", r.get("class_how") or "", r.get("base_rclcpp") or "",
                     str(r.get("lifecycle", "")), len(r.get("rows", [])), "; ".join(r.get("notes", []))])
    return rows


def mismatch_tab(d):
    rows = [["Node full_name", "Δ E", "Δ F", "counted sub topics", "counted services", "counted timers", "counted waitables", "other E", "expected rows (VCC:file:line)", "flagged ctx rows", "notes"]]
    for full, r in sorted(d["nodes"].items(), key=lambda kv: -(abs(kv[1].get("delta", {}).get("E", 0)) + abs(kv[1].get("delta", {}).get("F", 0)))):
        if not r.get("expected") or r["verdict"] == "OK":
            continue
        a = r["actual"]
        rows.append([full, r["delta"]["E"], r["delta"]["F"], ", ".join(a["sub"])[:2000], ", ".join(a["serv"])[:1000], ", ".join(a["tmr"])[:300],
                     ", ".join(a.get("waitable", []))[:500], ", ".join(a.get("other", []))[:300],
                     "; ".join(f"{x['vcc']}:{os.path.basename(x['file'])}:{x['line']}" for x in r["rows"] if x["delta"][0] or x["delta"][1])[:3000],
                     "; ".join(f"{os.path.basename(x['file'])}:{x['line']} [{x['ctx']}]" for x in r["rows"] if x.get("ctx"))[:2000],
                     "; ".join(r.get("notes", []))])
    return rows


def waitables_tab(w):
    s = w["summary"]
    rows = [["IPC Waitable tracepoint check — fish_rclcpp_waitable_init(node_handle=0x0) + executor Waitable-branch callback_start (scripts/aw_a2_waitables.py)"], [],
            ["summary", f"ipc waitables {s['ipc_waitables']} (ok {s['ipc_waitables_ok']}, bad {s['ipc_waitables_bad']})",
             f"unregistered dispatch ids {s['unregistered_dispatch_ids']} of which known waitables {s['unregistered_known_waitables']}, unknown {s['unregistered_unknown_ids']}",
             f"unregistered execs {s['unregistered_execs']} / {s['total_execs']} = {100.0*s['unregistered_execs']/max(1,s['total_execs']):.2f} %"], [],
            ["Node full_name", "pid", "subs", "ipc waitables", "ok", "wrapper dispatches", "inner dispatches", "verdict", "topics (ipc)"]]
    for full, n in sorted(w["nodes"].items()):
        if not n["n_ipc_waitables"]:
            continue
        rows.append([full, n["pid"], n["n_sub"], n["n_ipc_waitables"], n["n_ok"], n["wrapper_dispatches"], n["inner_dispatches"], n["verdict"],
                     ", ".join(str(c.get("topic")) for c in n["checks"])[:800]])
    rows += [[], ["=== processes: unexplained dispatch ids (not registered, not a known waitable) ==="], ["pid", "unregistered ids", "known waitables", "unknown ids", "unreg execs", "total execs"]]
    for pid, p in sorted(w["processes"].items(), key=lambda kv: -kv[1]["unreg_execs"]):
        if p["unregistered_ids"]:
            rows.append([pid, p["unregistered_ids"], p["unregistered_known_waitable"], ", ".join(p["unregistered_unknown"])[:300], p["unreg_execs"], p["total_execs"]])
    return rows


def ros2cli_tab(d):
    rows = [["ros2cli runtime helpers — excluded from the static model (transient CLI nodes spawned by the FISH snapshot and by launch)"], [],
            ["Node full_name", "E", "F", "subs", "srvs", "timers"]]
    for full, r in sorted(d["nodes"].items()):
        if r["kind"] != "ros2cli":
            continue
        a = r["actual"]
        rows.append([full, a["E"], a["F"], ", ".join(a["sub"])[:300], ", ".join(a["serv"])[:300], ", ".join(a["tmr"])[:200]])
    return rows


def sanitize(rows):
    out = []
    for row in rows:
        out.append([("'" + v) if isinstance(v, str) and v[:1] in ("+", "-", "=", "@") else v for v in row])
    return out


def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument("expected_json")
    ap.add_argument("--title", required=True)
    ap.add_argument("--image", default="autoware-dev-trt-a1000-fishwait6:latest")
    ap.add_argument("--scenario", default="logging_simulator.launch.xml + sample rosbag (rviz:=false), scripts/autoware_runs/run_logging_sim_bag_prov.sh")
    ap.add_argument("--waitables", default=None, help="JSON from scripts/aw_a2_waitables.py → extra `waitables` tab")
    ap.add_argument("--graph", default=None, help="fish_graph.json → per-node phase columns (E by data/init/zero_exec, unexplained E by phase)")
    ap.add_argument("--dry-run", action="store_true")
    a = ap.parse_args(argv)
    d = load(a.expected_json)
    payload = {"spreadsheet_title": a.title, "tabs": [
        {"name": "REFERENCE", "rows": sanitize(REFERENCE)},
        {"name": "bench_node", "rows": sanitize(bench_node_tab(d, a))},
        {"name": "expected_vertex", "rows": sanitize(expected_tab(d, phase_columns(d, a.graph) if a.graph else None))},
        {"name": "actual_vertex", "rows": sanitize(actual_tab(d))},
        {"name": "node_reviews", "rows": sanitize(reviews_tab(d))},
        {"name": "class_map", "rows": sanitize(class_map_tab(d))},
        {"name": "mismatch_detail", "rows": sanitize(mismatch_tab(d))},
        {"name": "ros2cli_helpers", "rows": sanitize(ros2cli_tab(d))},
    ]}
    if a.waitables:
        payload["tabs"].insert(7, {"name": "waitables", "rows": sanitize(waitables_tab(load(a.waitables)))})
    for t in payload["tabs"]:
        print(f"  tab {t['name']}: {len(t['rows'])} rows")
    if a.dry_run:
        return 0
    sheets, drive = make_clients()
    sid = write_payload(sheets, drive, payload)
    print(f"→ https://docs.google.com/spreadsheets/d/{sid}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
