#!/bin/bash
# Generated by Claude Fable 5 (Anthropic)
# Bake fish-r2b-<bench>-wip:latest images: the June fish-r2b-<bench>:latest
# base + CURRENT fish_tracepoints overlay (waitable/intra-process included) +
# ros2_benchmark/isaac_ros_benchmark rebuilt against the patched headers.
# Existing images are NEVER touched — new tag only ("wip" per Fatih).
# The FISH python/wrapper are NOT baked; the sweep refreshes them per run.
#
# usage: scripts/build_wip_images.sh [bench ...]   (default: the 17 verified)
set -uo pipefail
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
LOGDIR=${LOGDIR:-$HOME/fish_traces/wip_builds}
PAR=${PAR:-2}
JOBS=${JOBS:-14}
mkdir -p "$LOGDIR"

BENCHES=(${@:-apriltag dnn_image_encoder image_proc stereo_image_proc nvblox \
  visual_slam nitros_bridge detectnet ess segformer unet tensor_rt triton \
  bi3d bi3d_freespace rtdetr dope})

build_one() {
    local B=$1 IMG=fish-r2b-$1:latest WIP=fish-r2b-$1-wip:latest C=wipbuild-$1
    local LOG=$LOGDIR/$B.log
    docker image inspect "$IMG" >/dev/null 2>&1 || { echo "[$B] base image missing"; return 2; }
    docker rm -f "$C" >/dev/null 2>&1 || true
    docker run -d --name "$C" -v "$REPO_ROOT":/host/fish_src:ro \
        "$IMG" bash -c 'sleep 7200' >/dev/null
    timeout 5400 docker exec -e JOBS=$JOBS "$C" bash -c '
        set -e
        export PYTHONUNBUFFERED=1 MAKEFLAGS=-j$JOBS DEBIAN_FRONTEND=noninteractive
        rm -rf /root/fish_interfere
        cp -rT /host/fish_src /root/fish_interfere
        source /opt/ros/humble/setup.bash
        echo "=== [wip] tracepoint overlay update ($(date +%T)) ==="
        FISH_SETUP_PARENT=1 /root/fish_interfere/fish_tracepoints/install_fish_tracepoints --all 2>&1 | tail -25
        echo "=== [wip] rebuild benchmark pkgs against patched headers ==="
        source /root/ros_ws/install/setup.bash 2>/dev/null || true
        source /root/trace_overlay_ws/install/setup.bash
        cd /root/ros_ws
        colcon build --packages-select ros2_benchmark isaac_ros_benchmark \
            --cmake-args -DBUILD_TESTING=OFF -DCMAKE_BUILD_TYPE=Release 2>&1 | tail -6
        for p in ros2_benchmark isaac_ros_benchmark; do
            if grep -q "^rclcpp_DIR:PATH=/root/trace_overlay_ws/install/rclcpp/" \
                 build/$p/CMakeCache.txt 2>/dev/null; then
                echo "[wip] $p: built against overlay rclcpp OK"
            else
                echo "[wip] $p: WARNING overlay rclcpp NOT used"; exit 93
            fi
        done
        grep -rn "fish_rclcpp_waitable_init" /root/trace_overlay_ws/src/rclcpp/src/rclcpp/node_interfaces/node_waitables.cpp \
            >/dev/null && echo "[wip] waitable patch present in overlay source"
    ' > "$LOG" 2>&1
    local rc=$?
    if [ $rc -eq 0 ]; then
        docker commit -m "wip: current fish_tracepoints overlay + bench pkgs rebuilt $(date +%F)" \
            "$C" "$WIP" >/dev/null && echo "[$B] OK → $WIP"
    else
        echo "[$B] FAILED rc=$rc (log: $LOG)"; tail -5 "$LOG" | sed "s/^/[$B]   /"
    fi
    docker rm -f "$C" >/dev/null 2>&1 || true
    return $rc
}

echo "[wip] building ${#BENCHES[@]} images, $PAR in parallel, logs in $LOGDIR"
FAIL=0
i=0
for B in "${BENCHES[@]}"; do
    build_one "$B" &
    i=$((i+1))
    if [ $((i % PAR)) -eq 0 ]; then wait -n || FAIL=$((FAIL+1)); fi
    # keep at most PAR running
    while [ "$(jobs -r | wc -l)" -ge $PAR ]; do sleep 10; done
done
wait
docker images --format '{{.Repository}}:{{.Tag}}' | grep -- "-wip:latest" | sort
echo "[wip] done"
