#!/bin/bash
# Generated by Claude Fable 5 (Anthropic)
# Build autoware-dev-trt-a1000-fishwait8 = fishwait7 + client dispatch spans:
#   - Executor::execute_client wrapped with callback_start/end (cb-id = rcl
#     client handle) → clients become first-class F vertices (5/5 executable
#     kinds traced)
#   - client.hpp legacy per-request &callback inner wraps stripped from the
#     overlay source (NOTE: Autoware app binaries keep the old inlined wraps
#     until the next full Autoware rebuild — affects only the rare
#     callback-variant responses, 2/847 in the r25 session)
#   - fresh container from the UNCHANGED fishwait7 image
#   - committed as a NEW tag; fishwait7 stays as it is
set -euo pipefail
SRC_IMG=${SRC_IMG:-autoware-dev-trt-a1000-fishwait7:latest}
DST_IMG=${DST_IMG:-autoware-dev-trt-a1000-fishwait8:latest}
REPO=${REPO:-/home/tue037807/fish_interfere}
NAME=fishwait8-build
if docker image inspect "$DST_IMG" >/dev/null 2>&1; then
  echo "[build] $DST_IMG already exists — refusing to overwrite (pick another DST_IMG)"; exit 3
fi
echo "[build] $SRC_IMG → $DST_IMG"
docker rm -f $NAME >/dev/null 2>&1 || true
docker run -d --name $NAME --net host "$SRC_IMG" bash -c 'sleep 10800' >/dev/null
trap 'docker rm -f $NAME >/dev/null 2>&1 || true' EXIT
docker exec $NAME rm -rf /root/fish_interfere
docker cp "$REPO" $NAME:/root/fish_interfere
docker exec $NAME bash -lc '
  set -e
  source /opt/ros/humble/setup.bash
  cd /root/fish_interfere
  echo "[build] applying current fish_tracepoints overlay (incl. execute_client wrap)"
  FISH_SETUP_PARENT=1 fish_tracepoints/install_fish_tracepoints --all 2>&1 | tail -30
  echo "[build] verify: execute_client wrap in source + librclcpp rebuilt"
  grep -q "FISH: dispatch a Client" /root/trace_overlay_ws/src/rclcpp/src/rclcpp/executor.cpp \
    && echo "[build] execute_client wrap present"
  test -z "$(grep -l "static_cast<const void \*>(&callback)" /root/trace_overlay_ws/src/rclcpp/include/rclcpp/client.hpp 2>/dev/null)" \
    && echo "[build] legacy inner wraps absent from overlay client.hpp"
  echo "[build] refreshing FISH framework"
  FISH_SETUP_PARENT=1 source scripts/install_fish.sh 2>&1 | tail -3
'
echo "[build] committing $DST_IMG"
docker commit -m "FISH overlay refresh: client dispatch spans (rclcpp+rclpy) + fish_rcl_*_fini lifetime tracepoints; rclcpp Executor::execute_client and rclpy Executor._execute_client wrapped with callback_start/end (cb-id = rcl client handle); legacy &callback inner wraps stripped from overlay client.hpp" $NAME "$DST_IMG"
docker image inspect "$DST_IMG" --format '[build] done: {{.RepoTags}} {{.Size}} bytes'
