#!/bin/bash
# Generated by Claude Fable 5 (Anthropic)
# Build autoware-dev-trt-a1000-fishwait6 = fishwait5 + FISH provenance layer.
#   - fresh container from the UNCHANGED fishwait5 image (never modified)
#   - current fish_interfere copied in, install_fish.sh re-run (new snapshot
#     hooks, fish.provenance CLI); the tracepoint overlay is NOT touched
#   - scripts/install_provenance.sh: sources @ the base image's OCI revision,
#     version check, ctags index, configure-only compile_commands per package
#   - committed as a NEW tag; fishwait5 stays as it is
set -euo pipefail
SRC_IMG=${SRC_IMG:-autoware-dev-trt-a1000-fishwait5:latest}
DST_IMG=${DST_IMG:-autoware-dev-trt-a1000-fishwait6:latest}
BASE_IMG=${BASE_IMG:-ghcr.io/autowarefoundation/autoware:universe-devel-cuda-20260401}
REPO=${REPO:-/home/tue037807/fish_interfere}
NAME=fishwait6-build
if docker image inspect "$DST_IMG" >/dev/null 2>&1; then
  echo "[build] $DST_IMG already exists — refusing to overwrite (pick another DST_IMG)"; exit 3
fi
REV=${AUTOWARE_REVISION:-$(docker inspect "$BASE_IMG" --format '{{index .Config.Labels "org.opencontainers.image.revision"}}' 2>/dev/null || true)}
[ -n "$REV" ] || { echo "[build] cannot determine autoware revision (set AUTOWARE_REVISION)"; exit 2; }
echo "[build] $SRC_IMG → $DST_IMG  (autoware revision $REV)"
docker rm -f $NAME >/dev/null 2>&1 || true
docker run -d --name $NAME --net host "$SRC_IMG" bash -c 'sleep 14400' >/dev/null
trap 'docker rm -f $NAME >/dev/null 2>&1 || true' EXIT
docker exec $NAME rm -rf /root/fish_interfere
docker cp "$REPO" $NAME:/root/fish_interfere
docker exec $NAME bash -lc '
  set -e
  source /opt/ros/humble/setup.bash; source /opt/autoware/setup.bash; source /root/trace_overlay_ws/install/setup.bash
  cd /root/fish_interfere
  echo "[build] refreshing FISH framework (wrapper + python + ini; overlay untouched)"
  FISH_SETUP_PARENT=1 source scripts/install_fish.sh 2>&1 | tail -3
  export AUTOWARE_REVISION='"$REV"'
  bash scripts/install_provenance.sh 2>&1 | tee /root/install_provenance.log | grep -E "^\[provenance\]"
  echo "[build] provenance manifest:"; cat /opt/fish_provenance/manifest.json
  du -sh /opt/fish_provenance /opt/fish_provenance/src /opt/fish_provenance/build 2>/dev/null
'
echo "[build] committing $DST_IMG"
docker commit -m "fishwait5 + FISH provenance layer (sources @ $REV, ctags, configure-only compile_commands)" $NAME "$DST_IMG"
docker image inspect "$DST_IMG" --format '[build] done: {{.RepoTags}} {{.Size}} bytes'
