#!/bin/bash
# Generated by Claude Fable 5.1 (Anthropic)
# Continuation of campaign_pcore_v5.sh after the apt-stall fix (v4 no longer
# installs trtexec/dcgm at run time). Same host config, same DEST dir.
set -u
REPO=/home/tue037807/fish_interfere
LOG=$HOME/fish_traces/campaign_pcore_v5.log
DEST_ISAAC=$HOME/fish_traces/overhead_isaac_v5
cd "$REPO"
stamp() { echo "[campaign $(date +%F' '%T)] $*" | tee -a "$LOG"; }
stat_block() { { echo "=== host_perf_mode status ($1) ==="; scripts/host_perf_mode.sh status; } | tee -a "$LOG"; }
stamp "RESTART (v5c): Isaac from dope (9 benches), trtexec from local apt_cache .deb (offline dpkg), SMOKE_TIMEOUT=1200"
DEST_BASE=$DEST_ISAAC REPS=3 CUDA_EVT=0 SMOKE_TIMEOUT=1200 \
  bash scripts/overhead_sweep_v4.sh dope ess image_proc nvblox segformer \
    stereo_image_proc tensor_rt unet visual_slam 2>&1 | tee -a "$LOG" | grep -E '^\[v4'
stamp "Isaac rc=${PIPESTATUS[0]}"
stat_block "after Isaac"
stamp "AW rate sweep START (0.7 0.8 0.9 1.0 × 3 modes × 3)"
for R in 0.7 0.8 0.9 1.0; do
  stamp "AW rate $R"
  IMG=autoware-dev-trt-a1000-fishwait10:latest REPS=3 RATE=$R \
    bash scripts/autoware_runs/run_overhead_modes.sh 2>&1 | tee -a "$LOG" | grep -E '^\[ovh\] .*(complete|rc=)'
  stamp "AW rate $R rc=${PIPESTATUS[0]}"
done
stat_block "after rate sweep"
stamp "DONE"
