#!/bin/bash
# Generated by Claude Fable 5 (Anthropic)
# Run cb_overhead_extract.py over every traced overhead session (Isaac 13
# bench × {lttng,nsys} × 3 + Autoware 3-mode lttng/nsys ×3), 4-way parallel.
# Output JSONs → $OUT/<platform>__<bench>__<mode>_<rep>.json
set -u
OUT=${OUT:-$HOME/fish_traces/overhead_isaac/cbstats}
mkdir -p "$OUT"
REPO=/home/tue037807/fish_interfere
JOBS=${JOBS:-4}

run_one() {
    local tag=$1 sdir=$2
    [ -f "$OUT/$tag.json" ] && { echo "[skip] $tag"; return; }
    python3 "$REPO/scripts/cb_overhead_extract.py" "$sdir" "$OUT/$tag.json" \
        > "$OUT/$tag.log" 2>&1 && echo "[ok] $tag" || echo "[FAIL] $tag"
}

pids=0
throttle() { while [ "$(jobs -r | wc -l)" -ge $JOBS ]; do sleep 2; done; }

for B in apriltag bi3d bi3d_freespace dnn_image_encoder dope ess image_proc \
         nvblox segformer stereo_image_proc tensor_rt unet visual_slam; do
    for M in lttng nsys; do
        for R in 1 2 3; do
            D=$(ls -d $HOME/fish_traces/overhead_isaac/$B/${M}_${R}/fish_2026* 2>/dev/null | head -1)
            [ -n "$D" ] || { echo "[miss] $B $M $R"; continue; }
            throttle; run_one "isaac__${B}__${M}_${R}" "$D" &
        done
    done
done
AW=$HOME/fish_traces/overhead_aw_20260831_133353
for M in lttng nsys; do
    for R in 1 2 3; do
        SF="$AW/${M}_${R}/session.txt"
        [ -f "$SF" ] || { echo "[miss] aw $M $R"; continue; }
        D=$HOME/fish_traces/$(basename $(cat "$SF"))
        [ -d "$D" ] || { echo "[miss-dir] aw $M $R $D"; continue; }
        throttle; run_one "aw__aw__${M}_${R}" "$D" &
    done
done
wait
echo "[done] $(ls $OUT/*.json 2>/dev/null | wc -l) json"
