#!/usr/bin/env python3
# Generated by Claude Fable 5 (Anthropic)
"""Per-callback overhead charts (Fatih's sketch, 2026-09-01) + the
overhead-vs-event-rate regression + LaTeX tables.

Charts (×4): {autoware, isaac-pooled} × {lttng, lttng+nsys}. Per callback
(key = platform|bench|node|entity, addresses differ across runs):
  mean exec per repetition; overhead per repetition =
    * lttng chart : mean_lttng(rep) − floor, floor = min mean over ALL
      traced reps of that callback (both modes). Documented proxy: the
      untraced baseline has no per-callback times, so the callback's best
      observed mean is the reference ("run-to-run inflation ≥ 0").
    * nsys chart  : mean_nsys(rep) − avg(mean_lttng) — isolates what nsys
      ADDS on top of LTTng (can be negative).
Bar = min–max over the 3 reps (the sketch's interval), marker = mean.
Selection: sort by max desc → top-10, middle-10 (centred), bottom-10.
X label: entity ⟨node tail⟩, ' -GPU' suffix when the callback issues CUDA
calls inside its spans (nsys-session evidence).

usage: cb_overhead_charts.py [--stats-dir ...] [--out-fig paper/figures]
                             [--out-tab paper/tables] [--min-n 50]
"""
import argparse
import glob
import json
import os
import re
from collections import defaultdict

import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt


def load(stats_dir, min_n):
    data = defaultdict(dict)   # key → (mode, rep) → mean_ns
    gpu = defaultdict(bool)
    nsq = defaultdict(int)
    for f in sorted(glob.glob(os.path.join(stats_dir, '*.json'))):
        m = re.match(r'(\w+)__(.+)__(lttng|nsys)_(\d)\.json$', os.path.basename(f))
        if not m:
            continue
        plat, bench, mode, rep = m.groups()
        try:
            d = json.load(open(f))
        except Exception:
            continue
        agg = defaultdict(lambda: [0, 0])
        gflag = {}
        for cb, c in d.get('cbs', {}).items():
            if not c.get('entity'):
                continue
            node = c.get('node') or '?'
            key = (plat, bench, node, c['entity'])
            agg[key][0] += c['sum_ns']
            agg[key][1] += c['n']
            if c.get('gpu'):
                gflag[key] = True
        for key, (sm, n) in agg.items():
            if n < min_n:
                continue
            data[key][(mode, int(rep))] = sm / n
            nsq[key] += n
            if gflag.get(key):
                gpu[key] = True
    return data, gpu


def build_rows(data, gpu, plat, mode):
    rows = []
    for key, reps in data.items():
        if key[0] != plat:
            continue
        l_means = [v for (m, _), v in reps.items() if m == 'lttng']
        m_means = [v for (m, _), v in reps.items() if m == mode]
        if len(m_means) < 2:
            continue
        if mode == 'nsys':
            if len(l_means) < 2:
                continue
            ref = sum(l_means) / len(l_means)
        else:
            allv = l_means + [v for (mm, _), v in reps.items() if mm == 'nsys']
            ref = min(allv)
        ov = [v - ref for v in m_means]
        rows.append({
            'key': key, 'gpu': gpu.get(key, False),
            'min': min(ov), 'max': max(ov), 'mean': sum(ov) / len(ov),
        })
    rows.sort(key=lambda r: -r['max'])
    return rows


def pick_30(rows):
    n = len(rows)
    if n <= 30:
        return rows, [len(rows)]
    top = rows[:10]
    mid_c = n // 2
    mid = rows[mid_c - 5: mid_c + 5]
    bot = rows[-10:]
    return top + mid + bot, [10, 20]


def label_of(r):
    plat, bench, node, ent = r['key']
    node_tail = (node or '?').rsplit('/', 1)[-1]
    ent_s = ent if len(ent) <= 38 else ent[:37] + '…'
    lab = f"{ent_s} ⟨{node_tail}⟩"
    if plat == 'isaac':
        lab = f"[{bench}] " + lab
    if r['gpu']:
        lab += ' -GPU'
    return lab


def chart(rows, seps, title, outbase):
    xs = range(len(rows))
    means = [r['mean'] / 1e3 for r in rows]      # µs
    lo = [max(0.0, (r['mean'] - r['min']) / 1e3) for r in rows]
    hi = [max(0.0, (r['max'] - r['mean']) / 1e3) for r in rows]
    fig, ax = plt.subplots(figsize=(14, 6))
    colors = ['#c0392b' if r['gpu'] else '#2c3e50' for r in rows]
    for x, m, l, h, c in zip(xs, means, lo, hi, colors):
        ax.errorbar([x], [m], yerr=[[l], [h]], fmt='o', ms=4, color=c,
                    ecolor=c, elinewidth=1.6, capsize=4)
    for s in seps:
        ax.axvline(s - 0.5, color='#999', ls='--', lw=0.8)
    if seps:
        grp = ['highest max', 'middle', 'lowest max']
        bounds = [0] + seps + [len(rows)]
        for gi in range(len(bounds) - 1):
            cx = (bounds[gi] + bounds[gi + 1] - 1) / 2
            ax.text(cx, 1.02, grp[gi], transform=ax.get_xaxis_transform(),
                    ha='center', fontsize=9, color='#555')
    ax.set_xticks(list(xs))
    ax.set_xticklabels([label_of(r) for r in rows], rotation=90, fontsize=7)
    ax.set_ylabel('per-execution overhead [µs]')
    span = [abs(v) for v in means if v] or [1]
    if max(span) / max(min(span), 1e-9) > 500:
        ax.set_yscale('symlog', linthresh=1)
    ax.set_title(title, fontsize=11)
    ax.axhline(0, color='#000', lw=0.6)
    ax.grid(axis='y', alpha=0.3)
    fig.tight_layout()
    for ext in ('png', 'pdf'):
        fig.savefig(f'{outbase}.{ext}', dpi=160)
    plt.close(fig)
    print(f'  → {outbase}.png/.pdf ({len(rows)} callbacks)')


def tex_table(rows, seps, caption, label, path):
    L = ['% Generated by Claude Fable 5 (Anthropic)',
         r'\begin{table}[t]\centering\scriptsize',
         rf'\caption{{{caption}}}\label{{{label}}}',
         r'\begin{tabular}{llrrr}', r'\toprule',
         r'callback (entity $\langle$node$\rangle$) & GPU & '
         r'min [$\mu$s] & mean [$\mu$s] & max [$\mu$s] \\', r'\midrule']
    for i, r in enumerate(rows):
        if i in seps:
            L.append(r'\midrule')
        lab = label_of(r).replace('_', r'\_').replace('⟨', r'$\langle$') \
                         .replace('⟩', r'$\rangle$').replace('…', r'\dots') \
                         .replace(' -GPU', '')
        if lab.startswith('['):
            # after \\ a leading [ parses as an optional argument — brace it
            lab = '{[}' + lab[1:]
        gm = r'\checkmark' if r['gpu'] else ''
        L.append(f"{lab} & {gm} & "
                 f"{r['min']/1e3:.1f} & {r['mean']/1e3:.1f} & "
                 f"{r['max']/1e3:.1f}" + r' \\')
    L += [r'\bottomrule', r'\end{tabular}', r'\end{table}']
    open(path, 'w').write('\n'.join(L) + '\n')
    print(f'  → {path}')


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--stats-dir', default=os.path.expanduser(
        '~/fish_traces/overhead_isaac/cbstats'))
    ap.add_argument('--out-fig', default='paper/figures')
    ap.add_argument('--out-tab', default='paper/tables')
    ap.add_argument('--min-n', type=int, default=50)
    a = ap.parse_args()
    os.makedirs(a.out_fig, exist_ok=True)
    os.makedirs(a.out_tab, exist_ok=True)
    data, gpu = load(a.stats_dir, a.min_n)
    print(f'callback keys: {len(data)}')
    NAME = {'aw': 'Autoware', 'isaac': 'Isaac ROS (all benchmarks)'}
    MODE = {'lttng': 'LTTng-only (ref: best observed mean)',
            'nsys': 'LTTng+nsys (ref: LTTng-only mean)'}
    for plat in ('aw', 'isaac'):
        for mode in ('lttng', 'nsys'):
            rows = build_rows(data, gpu, plat, mode)
            if not rows:
                print(f'{plat}/{mode}: no rows'); continue
            sel, seps = pick_30(rows)
            t = f'{NAME[plat]} — per-callback overhead, {MODE[mode]}'
            base = os.path.join(a.out_fig, f'cb_overhead_{plat}_{mode}')
            chart(sel, seps, t, base)
            tex_table(sel, seps,
                      f'Per-callback overhead, {NAME[plat]}, {MODE[mode]}. '
                      f'Bars span min--max over 3 repetitions.',
                      f'tab:cbov-{plat}-{mode}',
                      os.path.join(a.out_tab, f'cb_overhead_{plat}_{mode}.tex'))
            print(f'{plat}/{mode}: {len(rows)} callbacks total')


if __name__ == '__main__':
    main()
