# Generated by Claude Opus 4.6 (Anthropic)
#!/bin/bash
# install_fish.sh — Installs the FISH profiling framework
#
# Components:
#   1. ros2 wrapper (bash — intercepts ros2 run/launch for LTTng tracing)
#   2. Trace session management (bash — LTTng start/stop/counter + daemon)
#   3. Python package (GPU nsys daemon, live collectors, snapshot, logging)
#   4. Settings file (fish_settings.ini)
#
# Output structure per session:
#   ~/fish_traces/<session>/
#     ├── ros2/       — LTTng trace data (callback boundaries, executor, pub/sub)
#     ├── nsys/       — Nsight Systems reports (GPU kernel chains, memory ops)
#     ├── fishlog/    — FISH event logs (kill/resurrect timestamps)
#     └── snapshot/   — System state (process tree, nodes, topics, hz)
#
# Usage: source install_fish.sh

FISH_ROOT=/opt/ros/humble/fish
FISH_BIN=$FISH_ROOT/bin
FISH_SCRIPTS=$FISH_ROOT/scripts
FISH_PYTHON=$FISH_ROOT/python
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
CONFIG_DIR="$REPO_ROOT/config"

mkdir -p $FISH_BIN $FISH_SCRIPTS $FISH_PYTHON/fish

# --- Read events from fish_events.txt ---
if [[ -f "$CONFIG_DIR/fish_events.txt" ]]; then
    EVENTS=$(grep -v '^#' "$CONFIG_DIR/fish_events.txt" | grep -v '^$' | tr '\n' ' ')
else
    echo "[FISH] WARNING: config/fish_events.txt not found, using all events"
    EVENTS=""
fi

# --- Copy Python package ---
if [[ -d "$REPO_ROOT/python/fish" ]]; then
    cp "$REPO_ROOT"/python/fish/*.py $FISH_PYTHON/fish/
else
    echo "[FISH] WARNING: python/fish/ not found, GPU/snapshot features unavailable"
fi

# --- Copy settings file ---
if [[ -f "$CONFIG_DIR/fish_settings.ini" ]]; then
    cp "$CONFIG_DIR/fish_settings.ini" $FISH_ROOT/fish_settings.ini
else
    echo "[FISH] WARNING: config/fish_settings.ini not found, using defaults"
fi

# --- Generate trace session script (bash) ---
cat > $FISH_SCRIPTS/trace_session.sh << TRACE_EOF
#!/bin/bash
# FISH trace session management (LTTng + GPU daemon + snapshot)

FISH_COUNTER=/tmp/fish_session_count
FISH_SESSION_NAME_FILE=/tmp/fish_session_name
FISH_SESSION_DIR_FILE=/tmp/fish_session_dir
FISH_ROOT=/opt/ros/humble/fish
FISH_PYTHON=\$FISH_ROOT/python
REAL_ROS2=\$(which -a ros2 2>/dev/null | grep -v /fish/bin | head -1)
if [[ -z "\$REAL_ROS2" ]]; then
    # Fallback: source ROS setup if not in PATH
    source /opt/ros/humble/setup.bash 2>/dev/null
    REAL_ROS2=\$(which -a ros2 2>/dev/null | grep -v /fish/bin | head -1)
    REAL_ROS2=\${REAL_ROS2:-/opt/ros/humble/bin/ros2}
fi

start_session() {
    SESSION=\$(cat \$FISH_SESSION_NAME_FILE 2>/dev/null)
    if [[ -z "\$SESSION" ]] || ! lttng list "\$SESSION" &>/dev/null; then
        SESSION="fish_\$(date +%Y%m%d_%H%M%S)"
        SESSION_DIR="\$HOME/fish_traces/\$SESSION"
        echo "\$SESSION" > \$FISH_SESSION_NAME_FILE
        echo "\$SESSION_DIR" > \$FISH_SESSION_DIR_FILE

        mkdir -p "\$SESSION_DIR/ros2"
        mkdir -p "\$SESSION_DIR/nsys"
        mkdir -p "\$SESSION_DIR/fishlog"
        mkdir -p "\$SESSION_DIR/snapshot"

        echo "[FISH] Starting trace session: \$SESSION"
        echo "[FISH] Output: \$SESSION_DIR/"
        lttng-sessiond --daemonize 2>/dev/null

        # Spawn the (echo; sleep) | ros2 trace pipeline in its OWN process
        # group via setsid, so stop_session can kill the whole group with a
        # single negative-PID signal. Without this, killing the ros2 trace
        # PID leaves the sibling 'sleep infinity' orphan and the launching
        # container never exits cleanly.
        setsid bash -c "(echo ''; sleep infinity) | \$REAL_ROS2 trace \\
            --session-name \"\$SESSION\" \\
            --path \"\$SESSION_DIR/ros2\" \\
            -u $EVENTS" 2>&1 &
        echo \$! > /tmp/fish_trace_pid
        sleep 2
        echo "[FISH] Trace session started"

        # Auto-start GPU daemon (also starts live collectors)
        PYTHONPATH=\$FISH_PYTHON:\$PYTHONPATH python3 -m fish.cli gpu daemon start 2>/dev/null
    fi
}

stop_session() {
    SESSION_DIR=\$(cat \$FISH_SESSION_DIR_FILE 2>/dev/null)

    # 1. Shutdown snapshot (ps_tree + component_list — needs live processes)
    echo "[FISH] Taking shutdown snapshot..."
    PYTHONPATH=\$FISH_PYTHON:\$PYTHONPATH python3 -m fish.cli snapshot 2>/dev/null

    # 2. Stop daemon (stops live collectors + flushes nsys reports)
    PYTHONPATH=\$FISH_PYTHON:\$PYTHONPATH python3 -m fish.cli gpu daemon stop 2>/dev/null

    # 2b. Belt-and-suspenders: poll fish_events.log for nsys_report_complete
    # entries. Daemon stop already waits for nsys reports, but if it returns
    # early (timeout, race) we don't want to KILL the process group while
    # nsys is still flushing its .nsys-rep file. Wait up to FISH_NSYS_DRAIN
    # seconds (default 60) for the report counter to stabilise.
    if [[ -n "\$SESSION_DIR" ]]; then
        EVT_LOG=\$(ls -t "\$SESSION_DIR/fishlog"/fish_events_*.log 2>/dev/null | head -1)
        if [[ -n "\$EVT_LOG" ]]; then
            DRAIN=\${FISH_NSYS_DRAIN:-60}
            T0=\$(date +%s)
            LAST_N=\$(grep -c "nsys_report_complete" "\$EVT_LOG" 2>/dev/null || echo 0)
            STABLE_FOR=0
            while [[ \$(( \$(date +%s) - T0 )) -lt \$DRAIN ]]; do
                sleep 1
                N=\$(grep -c "nsys_report_complete" "\$EVT_LOG" 2>/dev/null || echo 0)
                if [[ "\$N" == "\$LAST_N" ]]; then
                    STABLE_FOR=\$(( STABLE_FOR + 1 ))
                    # Two consecutive seconds with no new report → done.
                    [[ \$STABLE_FOR -ge 2 ]] && break
                else
                    STABLE_FOR=0
                    LAST_N=\$N
                fi
            done
            echo "[FISH] nsys reports observed: \$LAST_N (waited \$(( \$(date +%s) - T0 ))s)"
        fi
    fi

    # 3. Stop LTTng trace session
    echo "[FISH] Stopping trace session..."
    SESSION=\$(cat \$FISH_SESSION_NAME_FILE 2>/dev/null)
    if [[ -n "\$SESSION" ]]; then
        lttng stop "\$SESSION" 2>/dev/null
        lttng destroy "\$SESSION" 2>/dev/null
    fi
    TPID=\$(cat /tmp/fish_trace_pid 2>/dev/null)
    if [[ -n "\$TPID" ]]; then
        # The pipeline runs in its own process group (setsid in start_session).
        # Kill the whole group so the inner 'sleep infinity' subshell and
        # the ros2 trace process die together. Without this the container
        # never exits cleanly after dec/auto_stop.
        kill -TERM -\$TPID 2>/dev/null
        sleep 0.5
        kill -KILL -\$TPID 2>/dev/null
        # Belt-and-suspenders: also kill by PID in case the group kill missed
        # something (e.g. setsid not available, pre-existing single-PID install).
        kill \$TPID 2>/dev/null
    fi
    rm -f \$FISH_COUNTER \$FISH_SESSION_NAME_FILE \$FISH_SESSION_DIR_FILE /tmp/fish_trace_pid \
         /tmp/fish_launch_output.log /tmp/fish_system_stable \
         /tmp/fish_gpu_handler_complete /tmp/fish_replay_complete
    if [[ -n "\$SESSION_DIR" ]]; then
        chmod -R a+rX "\$SESSION_DIR" 2>/dev/null
        echo "[FISH] Session stopped. Output: \$SESSION_DIR/"
    else
        echo "[FISH] Session stopped."
    fi
}

get_status() {
    COUNT=\$(cat \$FISH_COUNTER 2>/dev/null || echo 0)
    SESSION=\$(cat \$FISH_SESSION_NAME_FILE 2>/dev/null || echo "none")
    SESSION_DIR=\$(cat \$FISH_SESSION_DIR_FILE 2>/dev/null || echo "none")
    if [[ "\$SESSION" != "none" ]] && lttng list "\$SESSION" &>/dev/null; then
        echo "[FISH] Session '\$SESSION' active, \$COUNT node(s) tracked"
        echo "[FISH] Output: \$SESSION_DIR/"
    else
        echo "[FISH] No active session"
    fi
    PYTHONPATH=\$FISH_PYTHON:\$PYTHONPATH python3 -m fish.cli gpu daemon status 2>/dev/null
}

increment_counter() {
    COUNT=\$(cat \$FISH_COUNTER 2>/dev/null || echo 0)
    echo \$((COUNT + 1)) > \$FISH_COUNTER
    echo "[FISH] Node starting (\$((COUNT + 1)) active)"
}

decrement_counter() {
    COUNT=\$(cat \$FISH_COUNTER 2>/dev/null || echo 1)
    echo \$((COUNT - 1)) > \$FISH_COUNTER
    if [[ \$((COUNT - 1)) -le 0 ]]; then
        echo "[FISH] Last node exited, stopping trace session..."
        stop_session
        return 0
    else
        echo "[FISH] Node exited, \$((COUNT - 1)) still active"
        return 1
    fi
}

case "\$1" in
    start)   start_session ;;
    stop)    stop_session ;;
    status)  get_status ;;
    inc)     increment_counter ;;
    dec)     decrement_counter ;;
    *)       echo "Usage: trace_session.sh {start|stop|status|inc|dec}" ;;
esac
TRACE_EOF
chmod +x $FISH_SCRIPTS/trace_session.sh

# --- Generate ros2 wrapper (bash) ---
cat > $FISH_BIN/ros2 << WRAPPER_EOF
#!/bin/bash
# FISH ros2 wrapper (generated by install_fish.sh)

REAL_ROS2=\$(which -a ros2 | grep -v /fish/bin | head -1)
FISH_ROOT=/opt/ros/humble/fish
FISH_SCRIPTS=\$FISH_ROOT/scripts
FISH_PYTHON=\$FISH_ROOT/python

# --- FISH subcommands ---
if [[ "\$1" == "run" && "\$2" == "fish" ]]; then
    case "\$3" in
        stop)
            \$FISH_SCRIPTS/trace_session.sh stop
            exit 0
            ;;
        status)
            \$FISH_SCRIPTS/trace_session.sh status
            exit 0
            ;;
        gpu)
            PYTHONPATH=\$FISH_PYTHON:\$PYTHONPATH python3 -m fish.cli gpu "\${@:4}"
            exit \$?
            ;;
        snapshot)
            PYTHONPATH=\$FISH_PYTHON:\$PYTHONPATH python3 -m fish.cli snapshot "\${@:4}"
            exit \$?
            ;;
        "")
            echo "Lurking in depths..."
            exit 0
            ;;
        *)
            echo "[FISH] Unknown command: \$3"
            echo "Available: stop, status, gpu, snapshot"
            exit 1
            ;;
    esac
fi

# --- Automatic tracing when FISH_ENABLED=1 ---
if [[ "\$FISH_ENABLED" == "1" && ("\$1" == "run" || "\$1" == "launch") ]]; then
    \$FISH_SCRIPTS/trace_session.sh start
    trap "\$FISH_SCRIPTS/trace_session.sh stop; exit 0" SIGTERM SIGINT
    \$FISH_SCRIPTS/trace_session.sh inc

    # Inspect the launch file to extract composable node specs.
    # Only runs for 'ros2 launch' (skip 'ros2 run'). Output goes to
    # \$SESSION_DIR/launch_components.json. Errors are non-fatal —
    # the wrapper continues even if inspection fails.
    if [[ "\$1" == "launch" ]]; then
        SESSION_DIR=\$(cat /tmp/fish_session_dir 2>/dev/null)
        if [[ -n "\$SESSION_DIR" && \$# -ge 3 ]]; then
            LAUNCH_COMPONENTS_JSON="\$SESSION_DIR/launch_components.json"
            echo "[FISH] Inspecting launch file: \$2 \$3"
            PYTHONPATH=\$FISH_PYTHON:\$PYTHONPATH python3 -m fish.launch_inspect \\
                "\$2" "\$3" "\${@:4}" \\
                > "\$LAUNCH_COMPONENTS_JSON" \\
                2> "\$SESSION_DIR/fishlog/launch_inspect.log" || true
            if [[ -s "\$LAUNCH_COMPONENTS_JSON" ]]; then
                N_CONT=\$(python3 -c "import json; d=json.load(open('\$LAUNCH_COMPONENTS_JSON')); print(len(d))" 2>/dev/null || echo "?")
                echo "[FISH] Launch inspector: \$N_CONT containers captured"
            else
                echo "[FISH] Launch inspector produced no output (see fishlog/launch_inspect.log)"
            fi
        fi
    fi

    # Tee launch stdout for executor_started stability monitoring
    FISH_LAUNCH_LOG=/tmp/fish_launch_output.log
    > \$FISH_LAUNCH_LOG

    # For 'ros2 launch' we route through fish.launch_wrap so that
    # composable node containers are started with nsys from the very
    # first moment (no kill/reload needed). For 'ros2 run' we fall back
    # to the real ros2 binary unchanged.
    if [[ "\$1" == "launch" ]]; then
        PYTHONPATH=\$FISH_PYTHON:\$PYTHONPATH python3 -m fish.launch_wrap \\
            "\${@:2}" > >( tee -a \$FISH_LAUNCH_LOG ) 2>&1 &
    else
        \$REAL_ROS2 "\$@" > >( tee -a \$FISH_LAUNCH_LOG ) 2>&1 &
    fi
    NODE_PID=\$!
    wait \$NODE_PID 2>/dev/null
    EXIT_CODE=\$?

    \$FISH_SCRIPTS/trace_session.sh dec
    exit \$EXIT_CODE
fi

exec \$REAL_ROS2 "\$@"
WRAPPER_EOF
chmod +x $FISH_BIN/ros2

# --- Generate launch_test wrapper (bash) ---
# Parallels the ros2 wrapper for the launch_testing entry point used by
# Isaac ROS Benchmark and other pytest-style integration suites.
cat > $FISH_BIN/launch_test << WRAPPER_EOF
#!/bin/bash
# FISH launch_test wrapper (generated by install_fish.sh)

REAL_LT=\$(which -a launch_test 2>/dev/null | grep -v /fish/bin | head -1)
FISH_ROOT=/opt/ros/humble/fish
FISH_SCRIPTS=\$FISH_ROOT/scripts
FISH_PYTHON=\$FISH_ROOT/python

# Locate the first positional argument (the test script path).
# launch_test may receive flags like --xml-output, --launch-arg, etc.
# before the script path; we just grab the first non-flag argument.
TEST_SCRIPT=""
for a in "\$@"; do
    case "\$a" in
        -*) ;;
        *)  TEST_SCRIPT="\$a"; break ;;
    esac
done

# --- Automatic tracing when FISH_ENABLED=1 ---
if [[ "\$FISH_ENABLED" == "1" ]]; then
    \$FISH_SCRIPTS/trace_session.sh start
    trap "\$FISH_SCRIPTS/trace_session.sh stop; exit 0" SIGTERM SIGINT
    \$FISH_SCRIPTS/trace_session.sh inc

    # Inspect the test script's generate_test_description() to extract
    # composable node + standalone node specs. Output goes to
    # \$SESSION_DIR/launch_components.json. Errors are non-fatal.
    SESSION_DIR=\$(cat /tmp/fish_session_dir 2>/dev/null)
    if [[ -n "\$SESSION_DIR" && -n "\$TEST_SCRIPT" ]]; then
        LAUNCH_COMPONENTS_JSON="\$SESSION_DIR/launch_components.json"
        echo "[FISH] Inspecting launch_test: \$TEST_SCRIPT"
        PYTHONPATH=\$FISH_PYTHON:\$PYTHONPATH python3 -m fish.launch_test_inspect \\
            "\$TEST_SCRIPT" \\
            > "\$LAUNCH_COMPONENTS_JSON" \\
            2> "\$SESSION_DIR/fishlog/launch_inspect.log" || true
        if [[ -s "\$LAUNCH_COMPONENTS_JSON" ]]; then
            N_CONT=\$(python3 -c "import json; d=json.load(open('\$LAUNCH_COMPONENTS_JSON')); print(len(d))" 2>/dev/null || echo "?")
            echo "[FISH] launch_test inspector: \$N_CONT containers captured"
        else
            echo "[FISH] launch_test inspector produced no output (see fishlog/launch_inspect.log)"
        fi
    fi

    # Tee launch stdout for executor_started stability monitoring
    FISH_LAUNCH_LOG=/tmp/fish_launch_output.log
    > \$FISH_LAUNCH_LOG

    # Run real launch_test through fish.launch_test_wrap so the
    # Node.execute / ComposableNodeContainer.execute monkey-patches are
    # installed BEFORE launch_testing instantiates LaunchService. Same
    # engine as ros2 launch ⇒ same patches apply, GPU nodes spawn under
    # nsys from t=0.
    PYTHONPATH=\$FISH_PYTHON:\$PYTHONPATH python3 -m fish.launch_test_wrap \\
        "\$@" > >( tee -a \$FISH_LAUNCH_LOG ) 2>&1 &
    NODE_PID=\$!
    wait \$NODE_PID 2>/dev/null
    EXIT_CODE=\$?

    \$FISH_SCRIPTS/trace_session.sh dec
    exit \$EXIT_CODE
fi

exec \$REAL_LT "\$@"
WRAPPER_EOF
chmod +x $FISH_BIN/launch_test

# --- Set up PATH and PYTHONPATH ---
export PATH=$FISH_BIN:$PATH
grep -q "fish/bin" ~/.bashrc || echo "export PATH=$FISH_BIN:\$PATH" >> ~/.bashrc
export PYTHONPATH=$FISH_PYTHON:$PYTHONPATH
grep -q "fish/python" ~/.bashrc || echo "export PYTHONPATH=$FISH_PYTHON:\$PYTHONPATH" >> ~/.bashrc

EVENT_COUNT=$(echo $EVENTS | wc -w)
echo "[FISH] Setup complete ($EVENT_COUNT events, settings loaded)"
echo "ros2 -> $(which ros2)"
echo ""
echo "Commands:"
echo "  export FISH_ENABLED=1         # enable auto-tracing"
echo "  export FISH_ENABLED=0         # disable auto-tracing (ros2 works normally)"
echo "  ros2 run <pkg> <node>         # auto-traced when FISH_ENABLED=1"
echo "  ros2 launch <pkg> <file>      # auto-traced when FISH_ENABLED=1"
echo "  ros2 run fish                 # wrapper test"
echo "  ros2 run fish status          # session + daemon info"
echo "  ros2 run fish stop            # stop (snapshot + flush + save)"
echo "  ros2 run fish snapshot        # manual shutdown snapshot"
echo "  ros2 run fish gpu             # list GPU processes"
echo "  ros2 run fish gpu relaunch    # manual nsys relaunch"
echo "  ros2 run fish gpu daemon fg   # run daemon in foreground"
echo ""
echo "Settings: $FISH_ROOT/fish_settings.ini"
