#!/bin/bash
# Generated by Claude Fable 5 (Anthropic)
# FISH provenance layer — install-time part (runs INSIDE the target container,
# turns a fishwait5-style Autoware image into a fishwait6 one; the image is
# committed by scripts/build_fishwait6.sh, this script never commits).
#
# What it puts under $PROV (default /opt/fish_provenance):
#   src/                 the exact sources the installed binaries were built from
#                        (autoware repo at the base image's OCI revision + vcs import)
#   versions.json        install package.xml version vs source package.xml version
#   tags                 universal-ctags index (qualified C++ names → file:line)
#   build/<pkg>/compile_commands.json   CMake CONFIGURE-ONLY per package (no build)
#   configure.log        per-package configure result
#   manifest.json        revision, dates, counts
#
# Env: AUTOWARE_REVISION (git commit of autowarefoundation/autoware; default
#      taken from the OCI label of the base image, passed by the build script),
#      PROV, INSTALL (/opt/autoware), ROS_SETUP (/opt/ros/humble/setup.bash),
#      JOBS (parallel configures, default 8), CONFIGURE_TIMEOUT (s, default 240)
set -u
PROV=${PROV:-/opt/fish_provenance}
INSTALL=${INSTALL:-/opt/autoware}
ROS_SETUP=${ROS_SETUP:-/opt/ros/humble/setup.bash}
JOBS=${JOBS:-8}
CONFIGURE_TIMEOUT=${CONFIGURE_TIMEOUT:-240}
AUTOWARE_REVISION=${AUTOWARE_REVISION:?set AUTOWARE_REVISION (autoware repo commit the image was built from)}
mkdir -p "$PROV"
log(){ echo "[provenance] $*"; }

# 1. tools -----------------------------------------------------------------
if ! command -v ctags >/dev/null 2>&1 || ! ctags --version 2>/dev/null | grep -qi universal; then
  log "installing universal-ctags"
  apt-get update -qq >/dev/null 2>&1 && apt-get install -y -qq universal-ctags >/dev/null 2>&1 || log "WARN: apt ctags failed"
fi
command -v vcs >/dev/null 2>&1 || pip3 install -q vcstool 2>/dev/null || pip3 install -q vcs2l
command -v git >/dev/null 2>&1 || { log "git missing"; exit 2; }

# 2. sources at the image's revision -----------------------------------------
if [ ! -d "$PROV/autoware/.git" ]; then
  log "cloning autowarefoundation/autoware @ $AUTOWARE_REVISION"
  git clone -q https://github.com/autowarefoundation/autoware.git "$PROV/autoware" || { log "clone failed"; exit 2; }
fi
git -C "$PROV/autoware" fetch -q origin "$AUTOWARE_REVISION" 2>/dev/null || true
git -C "$PROV/autoware" checkout -q "$AUTOWARE_REVISION" || { log "checkout $AUTOWARE_REVISION failed"; exit 2; }
mkdir -p "$PROV/src"
if [ ! -f "$PROV/src/.imported" ]; then
  log "vcs import (shallow) from autoware.repos"
  ( cd "$PROV" && vcs import --shallow --recursive src < autoware/autoware.repos > "$PROV/vcs_import.log" 2>&1 ) \
    && touch "$PROV/src/.imported" || log "WARN: vcs import reported errors (see vcs_import.log)"
fi

# 3. versions: installed package.xml vs source package.xml -------------------
log "comparing installed vs source package versions"
python3 - "$INSTALL" "$PROV" <<'PY'
import sys, os, re, json, glob
install, prov = sys.argv[1], sys.argv[2]
def ver(path):
    try:
        m = re.search(r"<version>\s*([^<\s]+)\s*</version>", open(path).read()); return m.group(1) if m else None
    except Exception: return None
def name(path):
    try:
        m = re.search(r"<name>\s*([^<\s]+)\s*</name>", open(path).read()); return m.group(1) if m else None
    except Exception: return None
src = {}
for p in glob.glob(os.path.join(prov, "src", "**", "package.xml"), recursive=True):
    n = name(p)
    if n: src[n] = {"path": os.path.dirname(p), "version": ver(p)}
out = {"packages": {}, "n_installed": 0, "n_with_source": 0, "n_version_match": 0, "n_version_mismatch": 0, "n_no_source": 0}
for p in glob.glob(os.path.join(install, "share", "*", "package.xml")):
    n = os.path.basename(os.path.dirname(p)); v = ver(p); out["n_installed"] += 1
    s = src.get(n)
    rec = {"installed_version": v, "source_version": s and s["version"], "source_path": s and s["path"]}
    if s:
        out["n_with_source"] += 1
        if s["version"] == v: out["n_version_match"] += 1
        else: out["n_version_mismatch"] += 1
    else:
        out["n_no_source"] += 1
    out["packages"][n] = rec
json.dump(out, open(os.path.join(prov, "versions.json"), "w"), indent=1)
print(f"[provenance] installed {out['n_installed']} packages: source found {out['n_with_source']}, "
      f"version match {out['n_version_match']}, mismatch {out['n_version_mismatch']}, no source {out['n_no_source']}")
PY

# 4. ctags index --------------------------------------------------------------
if command -v ctags >/dev/null 2>&1; then
  log "building ctags index"
  ( cd "$PROV" && ctags -R --languages=C,C++,Python --c++-kinds=+p --fields=+neKSl --extras=+q --tag-relative=yes -f tags src ) \
    2> "$PROV/ctags.log" && log "tags: $(wc -l < "$PROV/tags") entries"
fi

# 5. configure-only per package → compile_commands.json ----------------------
log "cmake configure-only for packages present in install AND source (jobs=$JOBS)"
mkdir -p "$PROV/build"
: > "$PROV/configure.log"
python3 - "$PROV" <<'PY' > "$PROV/configure_list.txt"
import sys, json, os
prov = sys.argv[1]
v = json.load(open(os.path.join(prov, "versions.json")))
for n, r in sorted(v["packages"].items()):
    if r["source_path"] and os.path.exists(os.path.join(r["source_path"], "CMakeLists.txt")):
        print(n, r["source_path"])
PY
configure_one() {
  local pkg="$1" srcdir="$2" b="$PROV/build/$1"
  mkdir -p "$b"
  if [ -f "$b/compile_commands.json" ]; then echo "$pkg SKIP(exists)"; return; fi
  ( source "$ROS_SETUP"; source "$INSTALL/setup.bash" 2>/dev/null
    timeout "$CONFIGURE_TIMEOUT" cmake -S "$srcdir" -B "$b" -G "Unix Makefiles" \
      -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF \
      -DCMAKE_CUDA_ARCHITECTURES=86 > "$b/configure.out" 2>&1 )
  if [ -f "$b/compile_commands.json" ]; then echo "$pkg OK"; else echo "$pkg FAIL rc=$? $(grep -m1 -E 'Error|error:' "$b/configure.out" | cut -c1-120)"; fi
}
export -f configure_one; export PROV ROS_SETUP INSTALL CONFIGURE_TIMEOUT
xargs -P "$JOBS" -L 1 bash -c 'configure_one "$0" "$1"' < "$PROV/configure_list.txt" >> "$PROV/configure.log" 2>&1
log "configure: $(grep -c ' OK' "$PROV/configure.log") OK, $(grep -c ' FAIL' "$PROV/configure.log") FAIL, $(grep -c ' SKIP' "$PROV/configure.log") skipped (of $(wc -l < "$PROV/configure_list.txt"))"
# keep build dirs small: only compile_commands.json + CMakeCache are needed
find "$PROV/build" -mindepth 2 -maxdepth 1 -type d -name CMakeFiles -exec rm -rf {} + 2>/dev/null

# 6. manifest ---------------------------------------------------------------
python3 - "$PROV" "$AUTOWARE_REVISION" <<'PY'
import sys, json, os, time
prov, rev = sys.argv[1], sys.argv[2]
v = json.load(open(os.path.join(prov, "versions.json")))
cfg = open(os.path.join(prov, "configure.log")).read() if os.path.exists(os.path.join(prov, "configure.log")) else ""
json.dump({"autoware_revision": rev, "built_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
           "n_installed": v["n_installed"], "n_with_source": v["n_with_source"],
           "n_version_match": v["n_version_match"], "n_version_mismatch": v["n_version_mismatch"],
           "n_configured": cfg.count(" OK"), "n_configure_failed": cfg.count(" FAIL"),
           "tags": os.path.exists(os.path.join(prov, "tags"))},
          open(os.path.join(prov, "manifest.json"), "w"), indent=1)
print("[provenance] manifest written")
PY
log "done → $PROV"
