#!/bin/bash
# Generated by Claude Fable 5 (Anthropic)
# FISH provenance — ROS 2 core sources as an EXTRA provenance root (host-side,
# no image change): the Autoware images carry only the install space of the
# apt ROS packages (rclcpp, tf2_ros, rclcpp_components, diagnostic_updater,
# rosbag2, …) whose callbacks are the bulk of every session's registered
# symbols. This script clones those repos at the EXACT installed versions
# (package.xml <version> == upstream git tag) into $OUT/src and builds a
# universal-ctags index there, using a fresh throw-away fishwait6 container
# for the version lookup and ctags (host ctags is Emacs ctags).
#   usage: scripts/install_provenance_ros.sh [OUT=~/fish_provenance_ros] [IMG]
#   then:  python3 -m fish.provenance <session> --prov-extra /opt/fish_provenance_ros
#          (mount OUT read-only at that path in the run container)
set -euo pipefail
OUT=${1:-$HOME/fish_provenance_ros}
IMG=${2:-autoware-dev-trt-a1000-fishwait6:latest}
NAME=fish-prov-ros-$$
mkdir -p "$OUT"
cat > "$OUT/.versions.py" <<'PYH'
# installed (/opt/ros/humble) vs cloned source package versions — the honesty check
import re, os, glob, json
def ver(p):
    m = re.search(r"<version>\s*([^<\s]+)\s*</version>", open(p).read()); return m.group(1) if m else None
def name(p):
    m = re.search(r"<name>\s*([^<\s]+)\s*</name>", open(p).read()); return m.group(1) if m else None
out = {"packages": {}, "n_match": 0, "n_mismatch": 0, "n_not_installed": 0}
for p in glob.glob("/prov_ros/src/**/package.xml", recursive=True):
    n = name(p); ip = f"/opt/ros/humble/share/{n}/package.xml"
    iv = ver(ip) if os.path.exists(ip) else None
    rec = {"source_version": ver(p), "installed_version": iv, "source_path": os.path.dirname(p)}
    out["packages"][n] = rec
    if iv is None: out["n_not_installed"] += 1
    elif iv == rec["source_version"]: out["n_match"] += 1
    else: out["n_mismatch"] += 1
json.dump(out, open("/prov_ros/versions.json", "w"), indent=1)
print(f"[prov-ros] source packages {len(out['packages'])}: version match {out['n_match']}, mismatch {out['n_mismatch']}, not installed {out['n_not_installed']}")
PYH
docker rm -f $NAME >/dev/null 2>&1 || true
trap 'docker rm -f $NAME >/dev/null 2>&1 || true' EXIT
docker run -d --name $NAME --net host -v "$OUT:/prov_ros" "$IMG" bash -c 'sleep 7200' >/dev/null
docker exec $NAME bash -c '
set -u
cd /prov_ros; mkdir -p src
log(){ echo "[prov-ros] $*"; }
ver(){ grep -o "<version>[^<]*" /opt/ros/humble/share/$1/package.xml 2>/dev/null | cut -d">" -f2; }
# repo  url  package-for-version   (tag == version for all ros2 core repos)
while read -r repo url pkg; do
  v=$(ver "$pkg"); [ -n "$v" ] || { log "$repo: $pkg not installed, skip"; continue; }
  if [ -d "src/$repo/.git" ]; then log "$repo: exists"; continue; fi
  log "$repo @ $v ($pkg)"
  git clone -q --depth 1 -b "$v" "$url" "src/$repo" 2>/dev/null || log "WARN: $repo tag $v not found"
done <<LIST
rclcpp https://github.com/ros2/rclcpp.git rclcpp
rcl https://github.com/ros2/rcl.git rcl
rmw https://github.com/ros2/rmw.git rmw
geometry2 https://github.com/ros2/geometry2.git tf2_ros
diagnostics https://github.com/ros/diagnostics.git diagnostic_updater
message_filters https://github.com/ros2/message_filters.git message_filters
rosbag2 https://github.com/ros2/rosbag2.git rosbag2_transport
ros2cli https://github.com/ros2/ros2cli.git ros2cli
rclpy https://github.com/ros2/rclpy.git rclpy
robot_state_publisher https://github.com/ros/robot_state_publisher.git robot_state_publisher
topic_tools https://github.com/ros-tooling/topic_tools.git topic_tools
pluginlib https://github.com/ros/pluginlib.git pluginlib
class_loader https://github.com/ros/class_loader.git class_loader
image_transport https://github.com/ros-perception/image_common.git image_transport
LIST
python3 /prov_ros/.versions.py
log "building ctags index"
ctags -R --languages=C,C++,Python --c++-kinds=+p --fields=+neKSl --extras=+q --tag-relative=yes -f tags src 2> ctags.log
log "tags: $(wc -l < tags) entries"
'
echo "[prov-ros] done → $OUT"; du -sh "$OUT"
