#!/bin/bash
# Generated by Claude Fable 5.1 (Anthropic), 2026-10-04
# Timing runs of the night (host must be in split mode; nothing else may run meanwhile):
#   1. tier campaign: baseline + min / default / max, REPS each (scripts/campaign_tiers.sh)
#   2. ROS 2 reference system (LiME-IT's case study) under FISH, tier max, 70 s
# Usage: REPS=2 IMG=autoware-dev-trt-a1000-fishwait20:latest scripts/night_campaign.sh <log_dir>
set -u
cd "$(dirname "$0")/.."
LD=${1:?log dir}; mkdir -p "$LD"
REPS=${REPS:-2} IMG=${IMG:-autoware-dev-trt-a1000-fishwait20:latest} bash scripts/campaign_tiers.sh > "$LD/campaign_tiers.log" 2>&1
echo "campaign_tiers rc=$? $(date +%T)" >> "$LD/night_campaign.txt"
bash scripts/night_runs.sh "$LD" <<'PLAN'
refsys IMG=autoware-dev-trt-a1000-fishwait19refsys:latest FISH_LAUNCH_CMD='ros2 launch /root/fish_interfere/scripts/mini_apps/refsys.launch.py' FISH_APP_SECONDS=70
PLAN
echo "CAMPAIGN DONE $(date +%T)" >> "$LD/night_campaign.txt"
