#!/usr/bin/env python3
# Generated by Claude Fable 5 (Anthropic)
"""Summarise an overhead_sweep_v4 campaign directory.

Walks $DEST/<bench>/<mode>_<i>/ and builds, per bench x mode (mean ± std over reps):
  - r2b 'Mean End-to-End Latency (ms)' / 'Max. ...' / 'Mean Frame Rate (fps)' /
    'Frame-to-Frame Jitter Std. Deviation (ms)'  — ros2_benchmark's OWN report
  - cpu cores over the busiest 60 s window (cpu.log)
Emits: <dest>/summary.csv (long form), <dest>/summary.md (bench x mode table,
with base-relative deltas for lttng and nsys columns). No per-frame e2e
latency in these benches (needs input-timestamp mode): fps = throughput,
jitter = frame-to-frame.

usage: overhead_sweep_report.py <dest_dir> [--md-only]
"""
import csv, glob, json, os, statistics as st, sys

# export_report str()s the Enum KEYS → 'BasicPerformanceMetrics.<NAME>'
KEYS = {
    "fps": "BasicPerformanceMetrics.MEAN_FRAME_RATE",
    "jit_mean": "BasicPerformanceMetrics.MEAN_JITTER",
    "jit_sd": "BasicPerformanceMetrics.STD_DEV_JITTER",
    "missed": "BasicPerformanceMetrics.NUM_MISSED_FRAMES",
}
USER_HZ = 100


def walk_metrics(obj, out):
    """Collect KEYS values anywhere in the report tree (mean over occurrences)."""
    if isinstance(obj, dict):
        for short, key in KEYS.items():
            if key in obj:
                try:
                    out.setdefault(short, []).append(float(obj[key]))
                except (TypeError, ValueError):
                    pass
        for v in obj.values():
            walk_metrics(v, out)
    elif isinstance(obj, list):
        for v in obj:
            walk_metrics(v, out)


def cpu_busiest(path, win=60.0):
    pts = []
    try:
        for ln in open(path):
            p = ln.split()
            if len(p) >= 2 and p[1].isdigit():
                pts.append((float(p[0]), int(p[1])))
    except OSError:
        return None
    best, i = 0.0, 0
    for j in range(1, len(pts)):
        while pts[j][0] - pts[i][0] > win:
            i += 1
        dt = pts[j][0] - pts[i][0]
        if dt >= win * 0.8:
            best = max(best, (pts[j][1] - pts[i][1]) / dt / USER_HZ)
    return best or None


def load_run(d):
    row = {}
    reps = sorted(glob.glob(os.path.join(d, "r2b-log-*.json")))
    if reps:
        try:
            data = json.load(open(reps[-1]))
        except json.JSONDecodeError:
            # export_report APPENDS → concatenated objects possible; take first
            raw = open(reps[-1]).read()
            dec = json.JSONDecoder()
            data, _ = dec.raw_decode(raw)
        acc = {}
        walk_metrics(data, acc)
        for k, vals in acc.items():
            row[k] = st.mean(vals)
    c = cpu_busiest(os.path.join(d, "cpu.log"))
    if c:
        row["cpu"] = c
    return row


def agg(rows, key):
    vals = [r[key] for r in rows if key in r]
    if not vals:
        return None, None
    return st.mean(vals), (st.stdev(vals) if len(vals) > 1 else 0.0)


def main():
    dest = sys.argv[1]
    data = {}   # bench -> mode -> list of run rows
    for bdir in sorted(glob.glob(os.path.join(dest, "*", ""))):
        bench = os.path.basename(bdir.rstrip("/"))
        for rdir in sorted(glob.glob(os.path.join(bdir, "*_*", ""))):
            mode = os.path.basename(rdir.rstrip("/")).rsplit("_", 1)[0]
            if mode == "warmup":
                continue
            row = load_run(rdir)
            if row:
                data.setdefault(bench, {}).setdefault(mode, []).append(row)

    with open(os.path.join(dest, "summary.csv"), "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["bench", "mode", "n"] +
                   [f"{k}_{s}" for k in list(KEYS) + ["cpu"] for s in ("mean", "std")])
        for bench in sorted(data):
            for mode in ("base", "lttng", "nsys"):
                rows = data[bench].get(mode, [])
                out = [bench, mode, len(rows)]
                for k in list(KEYS) + ["cpu"]:
                    m, s = agg(rows, k)
                    out += [f"{m:.3f}" if m is not None else "",
                            f"{s:.3f}" if s is not None else ""]
                w.writerow(out)

    md = [f"# Isaac ROS FISH overhead campaign — {os.path.basename(dest.rstrip('/'))}",
          "", "mode deltas are vs base. "
          "fps = 'Mean Frame Rate', cpu = busiest-60s cores.", "",
          "| bench | base fps | lttng fps (Δ) | nsys fps (Δ) | base jitter [ms] | "
          "lttng jit (Δ) | nsys jit (Δ) | base cpu | lttng cpu | nsys cpu |",
          "|---|--:|--:|--:|--:|--:|--:|--:|--:|--:|"]
    for bench in sorted(data):
        fps = {m: agg(data[bench].get(m, []), "fps") for m in ("base", "lttng", "nsys")}
        jit = {m: agg(data[bench].get(m, []), "jit_mean") for m in ("base", "lttng", "nsys")}
        cpu = {m: agg(data[bench].get(m, []), "cpu") for m in ("base", "lttng", "nsys")}

        def cell(pair, base=None, unit=""):
            m, s = pair
            if m is None:
                return "—"
            txt = f"{m:.1f}±{s:.1f}"
            if base and base[0]:
                txt += f" ({(m-base[0])/base[0]*100:+.1f}%)"
            return txt

        md.append("| " + " | ".join([
            bench, cell(fps["base"]), cell(fps["lttng"], fps["base"]), cell(fps["nsys"], fps["base"]),
            cell(jit["base"]), cell(jit["lttng"], jit["base"]), cell(jit["nsys"], jit["base"]),
            cell(cpu["base"]), cell(cpu["lttng"]), cell(cpu["nsys"]),
        ]) + " |")
    open(os.path.join(dest, "summary.md"), "w").write("\n".join(md) + "\n")
    print("\n".join(md))
    print(f"\nwrote {dest}/summary.csv + summary.md")


if __name__ == "__main__":
    main()
