#!/usr/bin/env python3
# Generated by Claude Fable 5 (Anthropic)
"""Benchmark × ros2_benchmark-metric matrices: cell = (mean(mode) − mean(base))
/ mean(base) ×100 over the peak-throughput test, 3 runs per mode.
Two matrices: lttng-only and lttng+nsys. Markdown to stdout."""
import glob
import json
import os

ROOT = os.path.expanduser('~/fish_traces/overhead_isaac')
BENCHES = ['apriltag', 'bi3d', 'bi3d_freespace', 'dnn_image_encoder', 'dope',
           'ess', 'image_proc', 'nvblox', 'segformer', 'stereo_image_proc',
           'tensor_rt', 'unet', 'visual_slam']
B = 'BasicPerformanceMetrics.'
R = 'ResourceMetrics.'


def ev_rate(bench, mode):
    """Mean LTTng event rate [ev/s] over the mode's traced runs
    ('[FISH] LTTng events: N' in launch.log ÷ run duration)."""
    import re
    rates = []
    for rep in (1, 2, 3):
        d = f'{ROOT}/{bench}/{mode}_{rep}'
        try:
            m = re.search(r'LTTng events: ([\d,]+)',
                          open(f'{d}/launch.log', errors='replace').read())
            t0 = float(open(f'{d}/t_start.txt').read())
            t1 = float(open(f'{d}/t_end.txt').read())
            if m and t1 > t0:
                rates.append(int(m.group(1).replace(',', '')) / (t1 - t0))
        except OSError:
            continue
    return sum(rates) / len(rates) if rates else None


COLS = [
    ('fps [fps]', B + 'MEAN_FRAME_RATE'),
    ('play fps [fps]', B + 'MEAN_PLAYBACK_FRAME_RATE'),
    ('sent [frame]', B + 'NUM_FRAMES_SENT'),
    ('missed [frame]', B + 'NUM_MISSED_FRAMES'),
    ('recv dur [ms]', B + 'RECEIVED_DURATION'),
    ('first e2e [ms]', B + 'FIRST_SENT_RECEIVED_LATENCY'),
    ('last e2e [ms]', B + 'LAST_SENT_RECEIVED_LATENCY'),
    ('jit mean [ms]', B + 'MEAN_JITTER'),
    ('jit sd [ms]', B + 'STD_DEV_JITTER'),
    ('jit max [ms]', B + 'MAX_JITTER'),
    ('cpu mean [%]', R + 'MEAN_OVERALL_CPU_UTILIZATION'),
    ('cpu max [%]', R + 'MAX_OVERALL_CPU_UTILIZATION'),
]


def peak_metrics(d):
    """Top-level = peak-throughput test. nvblox has no top-level basics:
    its outputs sit in per-topic dicts (mesh, static_map_slice) — average
    those. Fixed-rate subtests ('10.0fps'…) and metadata are excluded."""
    if any(k.startswith(B) for k in d):
        return d
    subs = [v for k, v in d.items()
            if isinstance(v, dict) and k not in ('metadata', 'custom')
            and not k.endswith('fps') and any(s.startswith(B) for s in v)]
    if not subs:
        return {k: v for k, v in d.items() if not isinstance(v, dict)}
    out = {}
    for _, key in COLS:
        vs = [s[key] for s in subs if isinstance(s.get(key), (int, float))]
        if vs:
            out[key] = sum(vs) / len(vs)
    for k, v in d.items():          # keep top-level ResourceMetrics
        if not isinstance(v, dict):
            out.setdefault(k, v)
    return out


def means(bench, mode):
    acc = {}
    n = 0
    for rep in (1, 2, 3):
        js = glob.glob(f'{ROOT}/{bench}/{mode}_{rep}/r2b-log-*.json')
        if not js:
            continue
        d = peak_metrics(json.load(open(js[0])))
        n += 1
        for _, key in COLS:
            v = d.get(key)
            if isinstance(v, (int, float)):
                acc[key] = acc.get(key, 0.0) + float(v)
    return ({k: v / n for k, v in acc.items()}, n) if n else ({}, 0)


def fmt_abs(v):
    if v is None:
        return '--'
    if abs(v) >= 1000:
        return f'{v:.0f}'
    if abs(v) >= 10:
        return f'{v:.1f}'
    return f'{v:.2f}'


def sorted_benches(mode):
    """Benches with data, ascending by the mode's mean event rate."""
    out = []
    for b in BENCHES:
        r = ev_rate(b, mode)
        if r is not None:
            out.append((r, b))
    out.sort()
    return out


def tex_matrix(mode, title, path):
    hdr = ' & '.join(
        r'\makecell{' + c.split(' [')[0] + r'\\{}['
        + c.split(' [')[1].replace('%', r'\%') + '}'
        for c, _ in COLS)
    L = ['% Generated by Claude Fable 5 (Anthropic)',
         r'\begin{table*}[t]\centering\scriptsize',
         r'\setlength{\tabcolsep}{3pt}',
         rf'\caption{{Isaac ROS, {title} vs.\ untraced baseline over the '
         r'peak-throughput test (3-run means, all metrics reported by '
         r'\texttt{ros2\_benchmark} itself), sorted by LTTng event rate. '
         r'Cell: baseline value over $\Delta$\%.}'
         rf'\label{{tab:matrix-{mode}}}',
         r'\resizebox{\textwidth}{!}{%',
         r'\begin{tabular}{lr' + 'r' * len(COLS) + '}', r'\toprule',
         r'benchmark & \makecell{events\\{}[kev/s]} & ' + hdr + r' \\',
         r'\midrule']
    for rate, b in sorted_benches(mode):
        mb, _ = means(b, 'base')
        mm, _ = means(b, mode)
        if not mb or not mm:
            continue
        cells = [f'{rate / 1e3:.1f}']
        for _, key in COLS:
            vb, vm = mb.get(key), mm.get(key)
            if vb is None or vm is None:
                cells.append('--')
            elif abs(vb) < 1e-9:
                d = r'$\pm$0.0\%' if abs(vm) < 1e-9 \
                    else rf'$\rightarrow${vm:.1f}'
                cells.append(r'\makecell[r]{' + fmt_abs(vb) + r'\\' + d + '}')
            else:
                d = f'{(vm - vb) / vb * 100:+.1f}'.replace('-', '--') + r'\%'
                cells.append(r'\makecell[r]{' + fmt_abs(vb) + r'\\' + d + '}')
        L.append(b.replace('_', r'\_') + ' & ' + ' & '.join(cells) + r' \\')
        L.append(r'\midrule')
    if L[-1] == r'\midrule':
        L.pop()
    L += [r'\bottomrule', r'\end{tabular}}', r'\end{table*}']
    open(path, 'w').write('\n'.join(L) + '\n')
    print(f'→ {path}')


def main():
    for mode, title in (('lttng', 'LTTng-only'), ('nsys', 'LTTng+nsys')):
        print(f'\n### {title} vs baseline — cell: baseline / Δ% '
              f'(peak-throughput test, 3-run means; sorted by event rate)\n')
        print('| benchmark | events [kev/s] | '
              + ' | '.join(c for c, _ in COLS) + ' |')
        print('|---' * (len(COLS) + 2) + '|')
        for rate, b in sorted_benches(mode):
            mb, nb = means(b, 'base')
            mm, nm = means(b, mode)
            if not mb or not mm:
                continue
            cells = [f'{rate / 1e3:.1f}']
            for _, key in COLS:
                vb, vm = mb.get(key), mm.get(key)
                if vb is None or vm is None:
                    cells.append('--')
                elif abs(vb) < 1e-9:
                    d = '±0.0%' if abs(vm) < 1e-9 else f'→{vm:.1f}'
                    cells.append(f'{fmt_abs(vb)} / {d}')
                else:
                    cells.append(f'{fmt_abs(vb)} / {(vm - vb) / vb * 100:+.1f}%')
            print(f'| {b} ({nb}v{nm}) | ' + ' | '.join(cells) + ' |')

    os.makedirs('paper/tables', exist_ok=True)
    for mode, title in (('lttng', 'LTTng-only'), ('nsys', 'LTTng+nsys')):
        tex_matrix(mode, title, f'paper/tables/metric_matrix_{mode}.tex')


if __name__ == '__main__':
    main()
