#!/bin/bash
# Generated by Claude Fable 5.1 (Anthropic), 2026-10-04
# Post-run pipeline for one traced Autoware run (replaces the ad-hoc post_validate*.sh of 2026-10-03):
#   health → ingest (PG) → model → gantt spans → thread attrs → ksched split (+ per-instance rows) →
#   FISH tasks (typed-EDD) → LiME-IT-style models.
# Usage: scripts/post_run_pipeline.sh <run_dir (…/overhead_aw_*/nsys_1) | session_id> [out_dir] [--no-ingest]
# Run it with the host in `off` mode (split confines this shell to 2 E-cores).
set -u
cd "$(dirname "$0")/.."
ARG=${1:?run dir or session id}; OUT=${2:-}; NOINGEST=${3:-}
if [ -d "$ARG" ] && [ -f "$ARG/session.txt" ]; then S=$(basename "$(cat "$ARG/session.txt")"); RUN=$ARG; else S=$ARG; RUN=""; fi
SD=$HOME/fish_traces/$S
[ -z "$OUT" ] && OUT=$HOME/fish_traces/analysis_$S
mkdir -p "$OUT"; SUM=$OUT/summary.txt; : > "$SUM"
say() { echo "[$(date +%T)] $*" | tee -a "$SUM"; }
export PGPASSWORD=fish; Q="psql -h localhost -U fish -d fish -At"
say "session $S (dir $SD) → $OUT"
if [ -n "$RUN" ]; then
  L=$RUN/launch.log
  say "health: nullptr=$(grep -c 'is nullptr' "$L") NoInputSource=$(grep -c 'No InputSource' "$L") activation=$(grep -ci 'activat' "$L") died=$(grep -c 'process has died' "$L")"
  for f in net_stable.txt net_shutdown.txt; do [ -f "$SD/snapshot/$f" ] && say "  $f: $(grep -m1 -o 'RcvbufErrors[^,]*' "$SD/snapshot/$f" | head -1)"; done
  [ -f "$SD/fishlog/tier.txt" ] && say "  tier: $(cat "$SD/fishlog/tier.txt" | tr '\n' ' ')"
fi
cd postprocess
if [ "$NOINGEST" != "--no-ingest" ]; then
  say "ingest"; python3 ingest_pg.py "$SD" --force > "$OUT/ingest.log" 2>&1 || say "INGEST FAILED"
  tail -2 "$OUT/ingest.log" | cut -c1-200 >> "$SUM"
  say "model"; python3 model_improved_pg.py --session "$S" > "$OUT/model.log" 2>&1 || say "MODEL FAILED"
  grep -E "measure_flows:|provenance of derived|publisher thread|untraced|tf read|detect_joins|Executors:" "$OUT/model.log" | cut -c1-400 >> "$SUM"
  say "gantt spans"
  python3 - "$S" > "$OUT/gantt.log" 2>&1 <<'EOF'
import sys, psycopg2, psycopg2.extras
import fish_viz_server as viz
conn = psycopg2.connect('host=localhost port=5432 dbname=fish user=fish password=fish', cursor_factory=psycopg2.extras.RealDictCursor)
conn.autocommit = True; cur = conn.cursor()
print({k: v for k, v in viz._ensure_gantt_spans(cur, sys.argv[1], '__main__').items() if k != 'gpu_submitter_cbs'})
EOF
  tail -1 "$OUT/gantt.log" | cut -c1-200 >> "$SUM"
  say "thread attrs"; python3 attach_thread_attrs.py "$S" > "$OUT/threads.log" 2>&1; head -3 "$OUT/threads.log" | cut -c1-200 >> "$SUM"
fi
say "ksched split"; python3 ksched_split.py "$SD" --session-id "$S" --tsv "$OUT/ksched.tsv" > "$OUT/ksched.txt" 2> "$OUT/ksched.err" || say "KSCHED FAILED ($(tail -1 "$OUT/ksched.err" | cut -c1-150))"
grep -E "^steady state|^check:|^all steady-state|^all callbacks: futex|^all middleware|per-instance rows|OpenMP regions" "$OUT/ksched.txt" | cut -c1-400 >> "$SUM"
if [ -f extract_fish_tasks.py ]; then
  say "FISH tasks"; python3 extract_fish_tasks.py "$S" -o "$OUT/fish_tasks.json" --releases "$OUT/releases.json" --show 6 > "$OUT/fish_tasks.txt" 2> "$OUT/fish_tasks.err" || say "TASKS FAILED ($(tail -1 "$OUT/fish_tasks.err" | cut -c1-150))"
  head -30 "$OUT/fish_tasks.txt" | cut -c1-220 >> "$SUM"
fi
if [ -f limeit_models.py ]; then
  say "LiME-IT-style models"; python3 limeit_models.py "$S" --releases "$OUT/releases.json" -o "$OUT/limeit.json" > "$OUT/limeit.txt" 2> "$OUT/limeit.err" || say "LIMEIT FAILED ($(tail -1 "$OUT/limeit.err" | cut -c1-150))"
  head -30 "$OUT/limeit.txt" | cut -c1-220 >> "$SUM"
fi
say "event counts (FISH TPs)"
$Q -F' | ' -c "select event, count(*), count(distinct vpid) from ros2_trace where session_id='$S' and event like 'ros2:fish_%' group by 1 order by 1" >> "$SUM"
say "PIPELINE DONE"
