#!/bin/bash
# Generated by Claude Opus 5 (Anthropic)
#
# sched_switch capture for the on-CPU / off-CPU split of FISH callbacks.
#
#   sudo bash scripts/sched_capture.sh            # starts capturing
#   touch <out>/STOP                              # stops it (the run script does this)
#
# What it does, and nothing else:
#   * a private ftrace instance (instances/fish_sched), so the global trace
#     buffer and any other tracing on the host are untouched;
#   * sched:sched_switch only, only on the application P-cores 0,2,4,6,8,10,
#     timestamped on CLOCK_MONOTONIC (the clock LTTng records);
#   * two trace_marker lines carrying CLOCK_REALTIME, to align with the ingest;
#   * every 5 s, the host-tid <-> container-tid map of containerised threads
#     (kernel events carry host tids, LTTng carries container tids);
#   * the script itself stays where the user slice puts it (18-19 under split).
# On exit it disables and removes the instance and hands the files to $SUDO_USER.
set -eu
OUT=${1:-/home/tue037807/fish_traces/sched_$(date +%Y%m%d_%H%M%S)}
CPUMASK=555                       # bits 0,2,4,6,8,10
MAX_S=1800                        # safety stop after 30 min
T=/sys/kernel/tracing
I=$T/instances/fish_sched

# No pinning: under host_perf_mode.sh split the desktop user slice (and so this
# sudo shell) is already confined to CPUs 18-19, outside both the application
# and the observer sets.  Just report where we are.
echo "[sched_capture] running on cpus $(grep Cpus_allowed_list /proc/self/status | cut -f2)"
mkdir -p "$OUT"
mountpoint -q $T || mount -t tracefs nodev $T
[ -d $I ] && rmdir $I
mkdir $I

CAT=""
cleanup() {
    echo "FISH_SYNC end realtime_ns=$(date +%s%N)" > $I/trace_marker 2>/dev/null || true
    sleep 1
    echo 0 > $I/tracing_on 2>/dev/null || true
    [ -n "$CAT" ] && kill $CAT 2>/dev/null || true
    sleep 1
    rmdir $I 2>/dev/null || true
    sort -u -o "$OUT/tidmap.txt" "$OUT/tidmap.txt" 2>/dev/null || true
    chown -R "${SUDO_USER:-root}:" "$OUT"
    echo "[sched_capture] stopped; $(wc -l < "$OUT/sched.trace") lines in $OUT/sched.trace"
}
trap cleanup EXIT

echo mono      > $I/trace_clock
echo 131072    > $I/buffer_size_kb
echo $CPUMASK  > $I/tracing_cpumask
echo 1         > $I/events/sched/sched_switch/enable
cat $I/trace_pipe > "$OUT/sched.trace" &
CAT=$!
echo 1 > $I/tracing_on
echo "FISH_SYNC start realtime_ns=$(date +%s%N)" > $I/trace_marker
echo "[sched_capture] capturing -> $OUT   (touch $OUT/STOP to finish)"
echo "$OUT" > /tmp/fish_sched_capture_dir

end=$((SECONDS + MAX_S))
while [ ! -e "$OUT/STOP" ] && [ $SECONDS -lt $end ]; do
    # host_tid ns_tid host_tgid comm cpuset  (containerised threads only: NSpid has 2 ids)
    awk '
      /^Name:/  { name = $2 }
      /^NSpid:/ && NF == 3 {
          split(FILENAME, p, "/"); tgid = p[3]
          cg = ""; f = "/proc/" tgid "/cpuset"
          if ((getline cg < f) > 0) close(f)
          print $2, $3, tgid, name, cg
      }' /proc/[0-9]*/task/[0-9]*/status 2>/dev/null >> "$OUT/tidmap.txt" || true
    sleep 5
done
