# Generated by Claude Opus 4.6 (Anthropic)
"""
FISH snapshot module.

Two-phase system state capture:

Phase 1 — Live collection (background, during runtime):
  Started by daemon after GPU kill-resurrect completes.
  Runs as background threads collecting data while system is live:
    - ros2 node info: publishers, subscribers, services per node
    - ros2 topic info: message types, pub/sub counts
    - ros2 topic hz: continuous rate sampling until stop signal

Phase 2 — Shutdown snapshot (instant, at stop time):
  Called during 'ros2 run fish stop' before anything is killed:
    - ps_tree: full process/thread listing (needs final state)
    - component_list: MT executor compositions

Output: <session>/snapshot/
"""

import json
import os
import queue
import signal
import subprocess
import threading
import time
from pathlib import Path
from typing import Optional

FISH_SESSION_DIR_FILE = "/tmp/fish_session_dir"
FISH_COLLECTOR_PID_FILE = "/tmp/fish_collector_active"

# Topic hz sampling: window size for rate calculation
TOPIC_HZ_WINDOW_SIZE = 50
# Topic hz: seconds per topic sample
TOPIC_HZ_SAMPLE_SECONDS = 10


def get_session_dir() -> str:
    try:
        return Path(FISH_SESSION_DIR_FILE).read_text().strip()
    except FileNotFoundError:
        return os.path.expanduser("~/fish_traces/unsorted")


def get_snapshot_dir() -> str:
    d = os.path.join(get_session_dir(), "snapshot")
    os.makedirs(d, exist_ok=True)
    return d


def _find_real_ros2() -> str:
    """Find the real ros2 binary, skipping the FISH wrapper."""
    try:
        result = subprocess.run(
            "which -a ros2 | grep -v /fish/bin | head -1",
            shell=True, text=True, capture_output=True
        )
        path = result.stdout.strip()
        if path:
            return path
    except Exception:
        pass
    return "/opt/ros/humble/bin/ros2"


def _run_cmd(cmd: str, timeout: float = 30.0) -> str:
    """Run a shell command and return stdout."""
    try:
        result = subprocess.run(
            cmd, shell=True, text=True, capture_output=True, timeout=timeout
        )
        return result.stdout.strip()
    except (subprocess.TimeoutExpired, subprocess.CalledProcessError, Exception) as e:
        print(f"[FISH] WARNING: Command failed: {cmd} ({e})")
        return ""


def _ros2_cmd(cmd: str, timeout: float = 30.0) -> str:
    """Run a ros2 CLI command using the real ros2 binary."""
    real_ros2 = _find_real_ros2()
    full_cmd = cmd.replace("ros2 ", f"{real_ros2} ", 1)
    return _run_cmd(full_cmd, timeout=timeout)


# ===================================================================
# Phase 2 — Shutdown snapshot (instant captures)
# ===================================================================

def capture_process_tree(snapshot_dir: str) -> str:
    """
    Capture full process tree with thread info (instant).

    Columns: PID, PPID, LWP (thread ID), UID, USER, CMD
    Must be captured at shutdown when all processes are still alive,
    including nsys-relaunched GPU nodes.
    """
    output_path = os.path.join(snapshot_dir, "ps_tree.txt")
    print("[FISH] Capturing process tree...")

    data = _run_cmd("ps -eL -o pid,ppid,lwp,uid,user,cmd")
    if data:
        with open(output_path, "w") as f:
            f.write(data + "\n")
        print(f"[FISH]   → {output_path}")
    return output_path


def capture_component_list(snapshot_dir: str) -> str:
    """
    Capture ROS 2 component list (near-instant).

    Components share an executor — critical for identifying
    intra-process scheduling dependencies.
    """
    output_path = os.path.join(snapshot_dir, "component_list.txt")
    print("[FISH] Capturing component list...")

    data = _ros2_cmd("ros2 component list")
    if data:
        with open(output_path, "w") as f:
            f.write(data + "\n")
    else:
        with open(output_path, "w") as f:
            f.write("# No components found\n")
    print(f"[FISH]   → {output_path}")
    return output_path


def _refresh_node_info(snapshot_dir: str) -> None:
    """
    Re-capture node_list and node_info at shutdown, merge with Phase 1 data.

    Phase 1 (live) may have missed nodes that weren't ready yet.
    Phase 2 (shutdown) may miss nodes that already exited.
    Merging both gives the most complete picture.
    """
    print("[FISH] Refreshing node info...")

    # Get current node list
    data = _ros2_cmd("ros2 node list")
    if not data:
        print("[FISH]   No nodes found at shutdown, keeping Phase 1 data")
        return

    shutdown_nodes = set(n.strip() for n in data.splitlines() if n.strip())

    # Load Phase 1 node list (if exists)
    node_list_path = os.path.join(snapshot_dir, "node_list.txt")
    phase1_nodes = set()
    try:
        with open(node_list_path) as f:
            phase1_nodes = set(n.strip() for n in f if n.strip())
    except FileNotFoundError:
        pass

    # Union of both
    all_nodes = phase1_nodes | shutdown_nodes
    with open(node_list_path, "w") as f:
        f.write("\n".join(sorted(all_nodes)) + "\n")

    # Collect info for any nodes missing from Phase 1
    node_dir = os.path.join(snapshot_dir, "node_info")
    os.makedirs(node_dir, exist_ok=True)

    json_path = os.path.join(snapshot_dir, "node_info_all.json")
    all_info = {}
    try:
        with open(json_path) as f:
            all_info = json.load(f)
    except (FileNotFoundError, json.JSONDecodeError):
        pass

    new_count = 0
    for node in shutdown_nodes:
        if node not in all_info:
            info = _ros2_cmd(f"ros2 node info {node}")
            if info:
                safe_name = node.strip("/").replace("/", "_")
                output_path = os.path.join(node_dir, f"{safe_name}_info.txt")
                with open(output_path, "w") as f:
                    f.write(info + "\n")
                all_info[node] = info
                new_count += 1

    if new_count > 0:
        with open(json_path, "w") as f:
            json.dump(all_info, f, indent=2)

    print(f"[FISH]   Node list: {len(all_nodes)} total ({len(phase1_nodes)} phase1 + {len(shutdown_nodes)} shutdown, {new_count} new)")


def shutdown_snapshot() -> str:
    """
    Phase 2: Capture instant system state at shutdown time.

    Called by trace_session.sh stop BEFORE daemon/LTTng shutdown.
    Only captures data that needs the final process state.
    """
    snapshot_dir = get_snapshot_dir()
    print(f"\n[FISH] Shutdown snapshot → {snapshot_dir}/")

    capture_process_tree(snapshot_dir)
    capture_component_list(snapshot_dir)
    _refresh_node_info(snapshot_dir)

    print("[FISH] Shutdown snapshot complete")
    return snapshot_dir


# ===================================================================
# Phase 1 — Live collection (background, during runtime)
# ===================================================================

class LiveCollector:
    """
    Background collector that gathers ROS 2 system info while
    the system is running. Started by the daemon after GPU
    kill-resurrect completes.

    Collects:
      - Node list + node info (one-shot)
      - Topic list + topic info (one-shot)
      - Topic hz (continuous until stopped)
    """

    def __init__(self):
        self.snapshot_dir = get_snapshot_dir()
        self._stop_event = threading.Event()
        self._threads: list[threading.Thread] = []
        self._hz_data: dict = {}
        self._hz_lock = threading.Lock()

    def start(self) -> None:
        """Start all background collection threads."""
        print("[FISH] Starting live collectors...")

        # Mark as active
        Path(FISH_COLLECTOR_PID_FILE).write_text(str(os.getpid()))

        # One-shot collectors
        t_nodes = threading.Thread(
            target=self._collect_node_info, name="fish-node-info", daemon=True
        )
        t_topics = threading.Thread(
            target=self._collect_topic_info, name="fish-topic-info", daemon=True
        )
        # Continuous collector
        t_hz = threading.Thread(
            target=self._collect_topic_hz, name="fish-topic-hz", daemon=True
        )

        self._threads = [t_nodes, t_topics, t_hz]
        for t in self._threads:
            t.start()

    def stop(self) -> None:
        """Stop all collectors and save final hz data."""
        print("[FISH] Stopping live collectors...")
        self._stop_event.set()

        # Wait for threads to finish (short timeout for one-shots,
        # hz thread checks stop_event frequently)
        for t in self._threads:
            t.join(timeout=15)

        # Save accumulated hz data
        self._save_hz_data()

        # Cleanup
        try:
            os.remove(FISH_COLLECTOR_PID_FILE)
        except FileNotFoundError:
            pass

        print("[FISH] Live collectors stopped")

    def _collect_node_info(self) -> None:
        """
        Periodic node list polling + parallel node info collection.

        - Polls ros2 node list every 10s, union into cumulative set
        - After 2nd poll (t≈20s), starts 4 worker threads to collect
          ros2 node info in parallel for all discovered nodes
        - If session ends before all node info is collected, logs a
          warning to fishlog
        """
        print("[FISH] Collecting node info (periodic, background)...")

        node_list_path = os.path.join(self.snapshot_dir, "node_list.txt")
        node_dir = os.path.join(self.snapshot_dir, "node_info")
        json_path = os.path.join(self.snapshot_dir, "node_info_all.json")
        os.makedirs(node_dir, exist_ok=True)

        all_nodes: set = set()
        all_info: dict = {}
        info_lock = threading.Lock()
        poll_count = 0

        # ── Periodic node list polling ──
        while not self._stop_event.is_set():
            data = _ros2_cmd("ros2 node list")
            if data:
                new_nodes = set(n.strip() for n in data.splitlines() if n.strip())
                added = new_nodes - all_nodes
                all_nodes |= new_nodes

                # Save cumulative node list
                with open(node_list_path, "w") as f:
                    f.write("\n".join(sorted(all_nodes)) + "\n")

                if added:
                    print(f"[FISH]   Node list poll #{poll_count + 1}: {len(all_nodes)} total (+{len(added)} new)")

            poll_count += 1

            # After 2nd poll, start collecting node info
            if poll_count == 2:
                self._collect_all_node_info(all_nodes, all_info, info_lock,
                                            node_dir, json_path)

            # Wait 10s between polls
            if self._stop_event.wait(timeout=10):
                break

        # ── Final info collection for any nodes discovered after initial batch ──
        with info_lock:
            missing = all_nodes - set(all_info.keys())
        if missing:
            self._collect_all_node_info(all_nodes, all_info, info_lock,
                                        node_dir, json_path)

        # ── Check for incomplete collection ──
        with info_lock:
            still_missing = all_nodes - set(all_info.keys())
        if still_missing:
            # Filter out ros2cli nodes — those are expected to be transient
            real_missing = {n for n in still_missing if "_ros2cli" not in n}
            if real_missing:
                print(f"[FISH]   WARNING: {len(real_missing)} nodes missing info: {real_missing}")
                self._log_warning(f"node_info incomplete: {sorted(real_missing)}")

        print(f"[FISH]   Node info final: {len(all_info)}/{len(all_nodes)} nodes")

    def _collect_all_node_info(self, all_nodes, all_info, info_lock,
                               node_dir, json_path, num_workers=4):
        """Collect ros2 node info in parallel using worker threads."""
        # Build work queue: nodes that don't have info yet
        with info_lock:
            work = [n for n in all_nodes if n not in all_info]
        if not work:
            return

        work_queue = queue.Queue()
        for node in work:
            work_queue.put(node)

        def worker():
            while True:
                try:
                    node = work_queue.get_nowait()
                except queue.Empty:
                    break
                if self._stop_event.is_set():
                    break

                info = _ros2_cmd(f"ros2 node info {node}")
                if info:
                    safe_name = node.strip("/").replace("/", "_")
                    output_path = os.path.join(node_dir, f"{safe_name}_info.txt")
                    with open(output_path, "w") as f:
                        f.write(info + "\n")
                    with info_lock:
                        all_info[node] = info

                work_queue.task_done()

        threads = []
        for _ in range(min(num_workers, len(work))):
            t = threading.Thread(target=worker, daemon=True)
            t.start()
            threads.append(t)

        for t in threads:
            t.join(timeout=30)

        # Save JSON
        with info_lock:
            with open(json_path, "w") as f:
                json.dump(all_info, f, indent=2)

        print(f"[FISH]   Node info batch: {len(all_info)} nodes collected")

    def _log_warning(self, message):
        """Write a warning to fishlog."""
        session_dir = get_session_dir()
        fishlog_dir = os.path.join(session_dir, "fishlog")
        os.makedirs(fishlog_dir, exist_ok=True)
        log_path = os.path.join(fishlog_dir, "snapshot_warnings.log")
        ts = time.strftime("%Y-%m-%dT%H:%M:%S", time.gmtime())
        with open(log_path, "a") as f:
            f.write(f"{ts}  WARNING  {message}\n")

    def _collect_topic_info(self) -> None:
        """Collect topic list, types, and pub/sub counts (one-shot)."""
        print("[FISH] Collecting topic info (background)...")

        data = _ros2_cmd("ros2 topic list")
        if not data:
            print("[FISH]   No topics found")
            return

        topics = [t.strip() for t in data.splitlines() if t.strip()]

        # Save topic list
        topic_list_path = os.path.join(self.snapshot_dir, "topic_list.txt")
        with open(topic_list_path, "w") as f:
            f.write("\n".join(topics) + "\n")

        topic_data = {}
        for topic in topics:
            if self._stop_event.is_set():
                break

            info = _ros2_cmd(f"ros2 topic info {topic}")
            if not info:
                continue

            entry = {"type": "", "publisher_count": 0, "subscription_count": 0}
            for line in info.splitlines():
                line = line.strip()
                if line.startswith("Type:"):
                    entry["type"] = line.split(":", 1)[1].strip()
                elif line.startswith("Publisher count:"):
                    try:
                        entry["publisher_count"] = int(line.split(":", 1)[1].strip())
                    except ValueError:
                        pass
                elif line.startswith("Subscription count:"):
                    try:
                        entry["subscription_count"] = int(line.split(":", 1)[1].strip())
                    except ValueError:
                        pass

            topic_data[topic] = entry

        output_path = os.path.join(self.snapshot_dir, "topic_info.json")
        with open(output_path, "w") as f:
            json.dump(topic_data, f, indent=2)

        print(f"[FISH]   Topic info collected: {len(topic_data)} topics")

    def _collect_topic_hz(self) -> None:
        """
        Continuously sample topic publication rates until stopped.

        Cycles through all topics, sampling each for TOPIC_HZ_SAMPLE_SECONDS.
        Results accumulate — longer runtime = more accurate arrival curves.
        """
        print("[FISH] Collecting topic hz (continuous, background)...")

        # Wait a moment for topic info to populate the list
        time.sleep(3)

        topic_list_path = os.path.join(self.snapshot_dir, "topic_list.txt")
        try:
            topics = Path(topic_list_path).read_text().strip().splitlines()
        except FileNotFoundError:
            # Fallback: query directly
            data = _ros2_cmd("ros2 topic list")
            topics = [t.strip() for t in data.splitlines() if t.strip()] if data else []

        if not topics:
            print("[FISH]   No topics for hz sampling")
            return

        real_ros2 = _find_real_ros2()
        cycle = 0

        while not self._stop_event.is_set():
            cycle += 1
            for topic in topics:
                if self._stop_event.is_set():
                    break

                try:
                    result = subprocess.run(
                        f"{real_ros2} topic hz {topic} --window {TOPIC_HZ_WINDOW_SIZE}",
                        shell=True, text=True, capture_output=True,
                        timeout=TOPIC_HZ_SAMPLE_SECONDS
                    )
                    output = result.stdout
                except subprocess.TimeoutExpired as e:
                    output = e.stdout if e.stdout else ""
                    if isinstance(output, bytes):
                        output = output.decode("utf-8", errors="replace")

                if not output:
                    continue

                entry = self._parse_hz_output(output)
                if entry and entry["average_rate"] is not None:
                    with self._hz_lock:
                        self._hz_data[topic] = entry

            if cycle == 1:
                active = sum(1 for v in self._hz_data.values() if v["average_rate"] is not None)
                print(f"[FISH]   Hz cycle 1 complete: {active}/{len(topics)} active topics")

    def _parse_hz_output(self, output: str) -> Optional[dict]:
        """Parse ros2 topic hz output into structured data."""
        entry = {
            "average_rate": None,
            "min_period": None,
            "max_period": None,
            "std_dev": None,
            "window_size": TOPIC_HZ_WINDOW_SIZE,
        }

        for line in reversed(output.splitlines()):
            line = line.strip()
            if line.startswith("average rate:"):
                try:
                    entry["average_rate"] = float(line.split(":")[1].strip())
                except (ValueError, IndexError):
                    pass
            elif "min:" in line and "max:" in line:
                parts = line.split()
                for i, part in enumerate(parts):
                    if part == "min:" and i + 1 < len(parts):
                        try:
                            entry["min_period"] = float(parts[i + 1].rstrip("s"))
                        except ValueError:
                            pass
                    elif part == "max:" and i + 1 < len(parts):
                        try:
                            entry["max_period"] = float(parts[i + 1].rstrip("s"))
                        except ValueError:
                            pass
                    elif part == "dev:" and i + 1 < len(parts):
                        try:
                            entry["std_dev"] = float(parts[i + 1].rstrip("s"))
                        except ValueError:
                            pass

                if entry["average_rate"] is not None:
                    break

        return entry if entry["average_rate"] is not None else None

    def _save_hz_data(self) -> None:
        """Save accumulated hz data to JSON."""
        with self._hz_lock:
            data = dict(self._hz_data)

        if data:
            output_path = os.path.join(self.snapshot_dir, "topic_hz.json")
            with open(output_path, "w") as f:
                json.dump(data, f, indent=2)
            print(f"[FISH]   Hz data saved: {len(data)} topics → {output_path}")
        else:
            print("[FISH]   No hz data collected")
