#!/usr/bin/env python3
# Generated by Claude Fable 5.1 (Anthropic), 2026-09-15 — Fig. 3b, folded LR layout (~2:1) with a large legend
import sys
OUT = sys.argv[1] if len(sys.argv) > 1 else 'fig3b_fold'
NOLEGEND = len(sys.argv) > 2 and sys.argv[2] == 'nolegend'
SUB, TMR = '#F9E79F', '#AED6F1'; GPU = 'color="#d62728" penwidth=2.4'
FS_N, FS_E, FS_C, FS_L = 16, 13, 14, 18
L = ['digraph fig3b {', '  rankdir=LR; newrank=true; nodesep=0.6; ranksep=0.7; splines=true;',
     '  graph [fontname="Helvetica" fontsize=%d bgcolor="white"];' % FS_C,
     '  node  [shape=box style="filled,rounded" fontname="Helvetica" fontsize=%d color="#555555" penwidth=1 margin="0.10,0.05"];' % FS_N,
     '  edge  [fontname="Helvetica" fontsize=%d color="#222222" penwidth=1.3 arrowsize=0.8];' % FS_E]
def cluster(cid, label, other, body):
    style = 'style="rounded,dashed" color="#999999" fontcolor="#666666"' if other else 'style="rounded" color="#444444"'
    L.append(f'  subgraph cluster_{cid} {{ label="{label}"; {style};'); L.extend('    ' + b for b in body); L.append('  }')
def ent(id_, label, kind, gpu=False):
    return f'{id_} [label="{label}" fillcolor="{SUB if kind == "sub" else TMR}"{" " + GPU if gpu else ""}];'
JOIN = 'style=dotted color="#1f77b4" dir=none penwidth=1.8'
cluster('concat', 'concatenate_data\\n(/sensing/lidar)', True, [
    ent('c_top', 'sub top cloud', 'sub'), ent('c_left', 'sub left cloud', 'sub'), ent('c_right', 'sub right cloud', 'sub'), ent('c_tmr', 'tmr 200 ms (x3)', 'tmr'),
    f'c_left -> c_top [{JOIN} label="join"];', f'c_right -> c_top [{JOIN}];', f'c_tmr -> c_top [{JOIN}];'])
cluster('crop', 'crop_box_filter', False, [ent('crop', 'sub concatenated cloud', 'sub')])
cluster('ground', 'common_ground_filter', False, [ent('ground', 'sub range_cropped cloud', 'sub')])
cluster('ogm', 'occupancy_grid_map_node\\n(/perception/occupancy_grid_map)', True, [
    ent('ogm_pc', 'sub concatenated cloud', 'sub', gpu=True), ent('ogm_sf', 'sub single_frame cloud', 'sub', gpu=True),
    f'ogm_pc -> ogm_sf [{JOIN} label="join" constraint=false];'])
cluster('outlier', 'occupancy_grid_based_outlier_filter', False, [ent('out_sf', 'sub single_frame cloud', 'sub'), ent('out_map', 'sub occupancy map', 'sub')])
cluster('aeb', 'autonomous_emergency_braking\\n(/control)', True, [
    ent('aeb_sub', 'sub obstacle cloud (polled)', 'sub'), ent('aeb_tmr', 'tmr 100 ms', 'tmr'),
    'aeb_sub -> aeb_tmr [style=dashed color="#e07b00" penwidth=1.8 arrowhead=onormal label="polled-msg\\nage 108 ms"];'])
L += ['  c_top -> crop [label="concatenated cloud"];', '  c_left -> crop;', '  c_tmr -> crop;', '  c_top -> ogm_pc;', '  c_left -> ogm_pc;', '  c_tmr -> ogm_pc;',
      '  crop -> ground [label="range_cropped cloud" constraint=false];', '  ground -> out_sf [label="single_frame cloud"];', '  ground -> ogm_sf [constraint=false];',
      '  ogm_pc -> out_map [label="occupancy map\\nhop 0.7 ms"];', '  ogm_sf -> out_map;',
      '  out_map -> aeb_sub [headlabel="obstacle cloud\\nhop 0.2 ms" labeldistance=3.2 labelangle=-35 constraint=false];', '  ground -> ogm_pc [style=invis constraint=false];',
      '  {rank=same; out_sf; out_map; aeb_sub; aeb_tmr;}', '  {rank=same; crop; ground; ogm_pc; ogm_sf;}']
LEGEND = f'''  legend [shape=box style="filled" fillcolor="white" color="#999999" margin=0.05 label=<
<TABLE BORDER="0" CELLBORDER="0" CELLSPACING="2" CELLPADDING="3">
<TR><TD COLSPAN="4" ALIGN="LEFT"><B>Legend</B></TD></TR>
<TR><TD BGCOLOR="#F9E79F" WIDTH="34" HEIGHT="20"></TD><TD ALIGN="LEFT">sub</TD>
    <TD><FONT COLOR="#222222" POINT-SIZE="{FS_L+2}">&#9472;&#9472;&#9654;</FONT></TD><TD ALIGN="LEFT">sub</TD></TR>
<TR><TD BGCOLOR="#AED6F1" WIDTH="34" HEIGHT="20"></TD><TD ALIGN="LEFT">tmr</TD>
    <TD><FONT COLOR="#1f77b4" POINT-SIZE="{FS_L+2}">&#8230;&#8230;&#8230;</FONT></TD><TD ALIGN="LEFT">join</TD></TR>
<TR><TD BORDER="3" COLOR="#d62728" WIDTH="34" HEIGHT="20"></TD><TD ALIGN="LEFT">submits GPU work</TD>
    <TD><FONT COLOR="#e07b00" POINT-SIZE="{FS_L+2}">&#8211; &#8211; &#9655;</FONT></TD><TD ALIGN="LEFT">polled-msg</TD></TR>
<TR><TD BORDER="1" COLOR="#999999" STYLE="dashed" WIDTH="34" HEIGHT="20"></TD><TD ALIGN="LEFT">other namespace</TD>
    <TD></TD><TD ALIGN="LEFT">hop / age: measured p50</TD></TR>
</TABLE>> fontsize={FS_L}];'''
if not NOLEGEND: L.append(LEGEND)
open(OUT + '.legend.dot','w').write('digraph legend {\n  graph [bgcolor="white"];\n' + LEGEND + '\n}\n')
L.append('  {rank=min; c_left; c_right; c_tmr;}' if NOLEGEND else '  {rank=min; legend; c_left; c_right; c_tmr;}')
L.append('}')
open(OUT + '.dot', 'w').write('\n'.join(L))
